### ISSUE TITLE
release history

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#100]
can we combine the release history in aer and terra and have it after the roadmap

**Comment by derivation** [comment]
Yes, I think it's a good idea to have all of the element/component release notes under one heading off the global ToC, instead of inside each element/component section.

You asked about Aer and Terra. I think we should do this with Aqua et al. too. Thoughts?

**Comment by jaygambetta** [comment]
Aqua I would leave until it is part of the mega.
