### ISSUE TITLE
Capitalization error

### ISSUE THREAD

**Issue by MuhammadMiqdadKhan** [Qiskit/qiskit-metapackage#1000]
## Did you find a doc bug or broken link that needs to be fixed?
Yes
- What is the file name(s) where you found the bug?
install.rst
- What is the current text that needs to be fixed or removed? (You can copy and paste)
These commands can be run in Anaconda prompt irrespective of Windows or linux machine.
- What should the documentation say instead?
These commands can be run in Anaconda prompt irrespective of Windows or Linux machine.
- Are there other related issues or pull requests about this bug?
No
## Does existing documentation need to be updated with new content?
Yes
- Which files need to be updated?
install.rst
- What content needs to be updated or replaced? (You can copy and paste)
These commands can be run in Anaconda prompt irrespective of Windows or linux machine.
- What new content needs to be added?
These commands can be run in Anaconda prompt irrespective of Windows or Linux machine.

**Comment by SooluThomas** [comment]
Fixed in https://github.com/Qiskit/qiskit/pull/1002
