### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by MuhammadMiqdadKhan** [Qiskit/qiskit-metapackage#1001]
## Did you find a doc bug or broken link that needs to be fixed?
Yes
- What is the file name(s) where you found the bug?
install.rst
- What is the current text that needs to be fixed or removed? (You can copy and paste)
To configure your account, you create a local configuration file which includes an API key
- What should the documentation say instead?
To configure your account, you will create a local configuration file which includes an API key
- Are there other related issues or pull requests about this bug?
No
## Does existing documentation need to be updated with new content?
Yes
- Which files need to be updated?
install.rst
- What content needs to be updated or replaced? (You can copy and paste)
With the release of Qiskit 0.11, if you had previously saved your IBM Quantum credentials locally, you might need to update your IBM Quantum Experience credentials so that you can use the new IBM Quantum Experience V2. See Updating your IBM Quantum Experience Credentials.
- What new content needs to be added?
With the release of Qiskit 0.11, if you had previously saved your IBM Quantum Experience credentials locally, you might need to update your IBM Quantum Experience credentials so that you can use the new IBM Quantum Experience V2. See Updating your IBM Quantum Experience Credentials.

**Comment by 3yakuya** [comment]
This is in fact fixed in https://github.com/Qiskit/qiskit/pull/1002 and can be closed as resolved.
