### ISSUE TITLE
QiskitError: 'Label contains invalid characters.'

### ISSUE THREAD

**Issue by praveentn** [Qiskit/qiskit-metapackage#1003]
### Informations

- **Qiskit version**: 0.14.2
- **Python version**: 3.7.8
- **Operating system**: posix

### What is the current behavior?

I'm trying to run a the below piece of code and it throws error stating "Label contains invalid characters"

Running on IBM Quantum (https://quantum-computing.ibm.com/)

`---------------------------------------------------------------------------`
`QiskitError                               Traceback (most recent call last)`
`<ipython-input-101-db751b675485> in <module>`
`----> 1 qi.Operator.from_label('CX')`

`/opt/conda/lib/python3.7/site-packages/qiskit/quantum_info/operators/operator.py in from_label(cls, label)`
`    176         }`
`    177         if re.match(r'^[IXYZHST01rl\-+]+$', label) is None:`
`--> 178             raise QiskitError('Label contains invalid characters.')`
`    179         # Initialize an identity matrix and apply each gate`
`    180         num_qubits = len(label)`

`QiskitError: 'Label contains invalid characters.'`

### Steps to reproduce the problem
`from qiskit.extensions import HGate, CXGate`
`import qiskit.quantum_info as qi`
`qc = QuantumCircuit(2)`
`qc.h(0)`
`qc.cx(0,1)`

`qc.draw('mpl')`

`# no issues with the below line`
`qi.Operator.from_label('HI')`

`# error at this line`
`qi.Operator.from_label('CX')`

### What is the expected behavior?

return the result as Operator object

**Comment by NimishMishra** [comment]
From the documentation https://qiskit.org/documentation/stubs/qiskit.quantum_info.Operator.from_label.html, it seems like this `from_label` takes in single-qubit operators on N qubits as an N length string and returns a tensor product. `CX` doesn't satisfy that, yielding the error.

**Comment by d4rkc0nd0r** [comment]
Import it as header `%matplotlib inline` 
Then try correcting  `qc.draw('mpl')` to `qc.draw(output='mpl')`.
It works.

**Comment by alanspace** [comment]
When I change it to 
`qi.Operator.from_label('H') + qi.Operator.from_label('X')`

I got result

```
Operator([[ 0.70710678+0.j,  1.70710678+0.j],
          [ 1.70710678+0.j, -0.70710678+0.j]],
         input_dims=(2,), output_dims=(2,))
```

But when I only change it to 

`qi.Operator.from_label('HI')`

I still got the result 

```
Operator([[ 0.70710678+0.j,  0.        +0.j,  0.70710678+0.j,
            0.        +0.j],
          [ 0.        +0.j,  0.70710678+0.j,  0.        +0.j,
            0.70710678+0.j],
          [ 0.70710678+0.j,  0.        +0.j, -0.70710678+0.j,
            0.        +0.j],
          [ 0.        +0.j,  0.70710678+0.j,  0.        +0.j,
           -0.70710678+0.j]],
         input_dims=(2, 2), output_dims=(2, 2))
```

The problem is with the ` qi.Operator.from_label('CX')`

**Comment by NimishMishra** [comment]
> When I change it to
> `qi.Operator.from_label('H') + qi.Operator.from_label('X')`
> 
> I got result
> 
> ```
> Operator([[ 0.70710678+0.j,  1.70710678+0.j],
>           [ 1.70710678+0.j, -0.70710678+0.j]],
>          input_dims=(2,), output_dims=(2,))
> ```
> 
> But when I only change it to
> 
> `qi.Operator.from_label('HI')`
> 
> I still got the result
> 
> ```
> Operator([[ 0.70710678+0.j,  0.        +0.j,  0.70710678+0.j,
>             0.        +0.j],
>           [ 0.        +0.j,  0.70710678+0.j,  0.        +0.j,
>             0.70710678+0.j],
>           [ 0.70710678+0.j,  0.        +0.j, -0.70710678+0.j,
>             0.        +0.j],
>           [ 0.        +0.j,  0.70710678+0.j,  0.        +0.j,
>            -0.70710678+0.j]],
>          input_dims=(2, 2), output_dims=(2, 2))
> ```
> 
> The problem is with the ` qi.Operator.from_label('CX')`
 

It's because `from_label` takes in single-qubit operator labels only. `CX` does not satisfy that. For further discussion, refer to https://qiskit.slack.com/archives/CMXDMFNN5/p1595336109201500
