### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by d4rkc0nd0r** [Qiskit/qiskit-metapackage#1005]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
 README.md
- What is the current text that needs to be fixed or removed? (You can copy and paste)
 Broken link of [IBM Q Provider](qiskit.org) & [Slack](https://join.slack.com/t/qiskit/shared_invite/enQtODQ2NTIyOTgwMTQ3LTI0NzM2NzkzZjJhNDgzZjY5MTQzNDY3MGNiZGQzNTNkZTE4Nzg1MjMwMmFjY2UwZTgyNDlmYWQwYmZjMjE1ZTM)
- What should the documentation say instead?
It has to redirect to [Qiskit](qiskit.org) & Slack has to make invitation
- Are there other related issues or pull requests about this bug?
Yes #976

**Comment by SooluThomas** [comment]
There's an open pull request #978 to fix the slack broken link

**Comment by d4rkc0nd0r** [comment]
Thank You @SooluThomas

**Comment by d4rkc0nd0r** [comment]
It's working now.
