### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by TanveshT** [Qiskit/qiskit-metapackage#1010]
### Informations

- **Qiskit version**: 0.20.0
- **Python version**: 3.7.8
- **Operating system**: Windows 10

### What is the current behavior?
Currently, I switched from a Linux based system to windows based.  
I am getting this error whenver I try to import qiskit.

```python
from qiskit import *
from qiskit import QuantumCircuit
```
**Both doesn't work**

### What is the expected behavior?

The expected behavior should that the qiskit should get imported without any errors.

**Comment by deeplokhande** [comment]
It should work, unless there is a path mismatch or something else. If you receive 'importerror', saying 'qiskit not found', then in this case your qiskit installation is faulty. If you receive some other error, Can you share a screen shot of the error you receive.
Best I would recommend a creating a clean environment and trying. Follow the installation instructions on Qiskit.

**Comment by TanveshT** [comment]
@deeplokhande The problem got resolved after reinstalling python. Python from the default Windows Store is giving errors similar errors to many. So installed it from the original website. Therefore closing the Issue

**Comment by deeplokhande** [comment]
Cool!!
