### ISSUE TITLE
Holography development

### ISSUE THREAD

**Issue by preciousmetalsirarollover** [Qiskit/qiskit-metapackage#1011]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Based on the release dates of Quantum Computing libraries, I think it is evident that either Qiskit or Forest might have been used to create a biological holographic neural network that I am thinking about. If not, it could be coded from scratch (or is HNeT). 

### Steps to reproduce the problem

I have had to reverse engineer the problem starting from knowing that my NLP centers were firing more data than normal, and that somehow old friends that I have suddenly have “information” based on old memories that I have. This must be derived from my hippocampus and related areas of the brain. 

### What is the expected behavior?

I should be able to sleep when I decide to. Also, my memories should be private. 

### Suggested solutions

I would like to get in touch with a knowledgeable and professional quantum computing expert.

**Comment by deeplokhande** [comment]
Wow!! This discussion looks Something!!

**Comment by preciousmetalsirarollover** [comment]
Do you know how to do quantum superposition with holography? @deeplokhande

**Comment by deeplokhande** [comment]
Nope. Sorry. I was just interested to read about the topic in discussion here. Why don't you post this question on qiskit-slack. I think there'll be someone who can help you find this.

**Comment by mtreinish** [comment]
It doesn't look like this is a bug with qiskit so I'm going to close this.
