### ISSUE TITLE
AttributeError: module 'qiskit.pulse' has no attribute 'build'

### ISSUE THREAD

**Issue by praveentn** [Qiskit/qiskit-metapackage#1012]
### Informations

- **Qiskit version**: 0.14.2
- **Python version**: 3.7.8
- **Operating system**: posix

### What is the current behavior?
`---------------------------------------------------------------------------`
`AttributeError                            Traceback (most recent call last)`
`<ipython-input-5-7c1e5c48f6d8> in <module>`
`      4 backend = FakeArmonk()`
`      5 `
`----> 6 with pulse.build(backend) as drive_sched:`
`      7     d0 = pulse.drive_channel(0)`
`      8     print(d0)`

``

`AttributeError: module 'qiskit.pulse' has no attribute 'build'`

### Steps to reproduce the problem

Execute the code mentioned in this section (https://qiskit.org/documentation/apidoc/pulse.html?highlight=pulse#pulse-builder-builder)

`from qiskit import pulse`
`from qiskit.test.mock import FakeArmonk`

`backend = FakeArmonk()`

`with pulse.build(backend) as drive_sched:`
`    d0 = pulse.drive_channel(0)`
`    print(d0)`

P.S - indentation is not showing up in the above code

### What is the expected behavior?

No exception

**Comment by taalexander** [comment]
This feature is only available in Qiskit v0.15+. Please try upgrading your Qiskit installation.

**Comment by praveentn** [comment]
> This feature is only available in Qiskit v0.15+. Please try upgrading your Qiskit installation.

@taalexander tried with version `0.19.6`, same error.

**Comment by taalexander** [comment]
I see you closed and then reopened? Has this been resolved?

**Comment by praveentn** [comment]
@taalexander  I upgraded qiskit. These are the versions 

`qiskit-0.20.0 qiskit-aer-0.6.1 qiskit-aqua-0.7.5 qiskit-ibmq-provider-0.8.0 qiskit-ignis-0.4.0 qiskit-terra-0.15.1`

Still getting the error.

**Comment by Hirmay** [comment]
@praveentn I ran it on the latest version of qiskit(0.20.0 same as yours) and didn't get any attribute error. So please try reinstalling qiskit if you still face that error.

![image](https://user-images.githubusercontent.com/56473003/91935320-1a4e8c80-ed0b-11ea-84e9-ee95095eefd2.png)

**Comment by taalexander** [comment]
@praveentn is it possible your Jupyter notebook is running a different kernel than your standard interpreter? Could you please try what @Hirmay showed to get the versions?

**Comment by praveentn** [comment]
{'qiskit-terra': '0.15.2',
 'qiskit-aer': '0.6.1',
 'qiskit-ignis': '0.4.0',
 'qiskit-ibmq-provider': '0.8.0',
 'qiskit-aqua': '0.7.5',
 'qiskit': '0.20.1'}

Worked for the above config. Closing the issue. Thanks!

**Comment by Hirmay** [comment]
Glad to know that it got worked out for you :)
