### ISSUE TITLE
Add "New in version x.y.z" indicator to documents

### ISSUE THREAD

**Issue by 3yakuya** [Qiskit/qiskit-metapackage#1024]
### What is the expected behavior?
Add a note for every function/property/class etc. stating the version in which given API element was introduced or updated. For example, near the top of a documentation page for a function, we could include a note saying "New in version x.y.z" indicating x.y.z version where given function was introduced or updated.

#### What is the sample use case?
This is inspired by a possibly common experience: yesterday I was trying to get `plot_state_city` to work using [documentation](https://qiskit.org/documentation/stubs/qiskit.visualization.plot_state_city.html?highlight=plot_state_city#qiskit.visualization.plot_state_city) but sadly the provided snippet did not work. I created an [issue for the problem](https://github.com/Qiskit/qiskit/issues/1021) only to find soon afterwards that the function started taking arguments like in the Snippet only in `0.20.0`, while I was running `0.19.6`. Having this information in the docs page would save me a lot of time.

There are some other great projects that include such information in the docs, for ex. [Pyspark](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html).

**Comment by nonhermitian** [comment]
In SciPy this is done in the docstrings:

```
    Notes
    -----
    .. versionadded:: 0.15.0
```

We can of course do the same, but it requires the devs to add such comments into the docstrings.

**Comment by nonhermitian** [comment]
Closing as I am not sure this can be addressed here.  Namely, unless the developers as a whole decide to enforce this for all new functions, it can not maintained.
