### ISSUE TITLE
Pulse benchmarks are not actually constructing schedules

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-metapackage#1031]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The current `pulse.Schedule` behavior is to build an immutable Schedule, all operations build a new Schedule. This new Schedule should be assigned after generation. The current pulse benchmarks such as:
https://github.com/Qiskit/qiskit/blob/a1bb148a5fb9e10279de8ed167660375ccffad64/test/benchmarks/pulse/schedule_construction.py#L37

do not assign the constructed schedule and are therefore dishonest as these operations are expected to not be constant time. 

### Suggested solutions

To fix
`schedule.append(...)` should become `schedule = schedule.append(...)`.

**Comment by 3yakuya** [comment]
Good catch, in fact any immutable object generated _must_ be assigned to be meaningful, by definition or canoe modify some state internally...

**Comment by lcapelluto** [comment]
While this is getting touched, `SamplePulse` needs to become `Waveform`. I know it should be a separate issue 😬

**Comment by nonhermitian** [comment]
What is the status of this? Can it be closed?

**Comment by taalexander** [comment]
This has been fixed in #1155.
