### ISSUE TITLE
command errored out with exit status 1 with qiskit terra editable mode in virtualenv

### ISSUE THREAD

**Issue by tgag17** [Qiskit/qiskit-metapackage#1032]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior
ERROR: Command errored out with exit status 1: command: 'C:\Users\Tanya Garg\Anaconda3\envs\fixissueenv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Tanya Garg\qiskit-terra\setup.py'"'"'; file='"'"'C:\Users\Tanya Garg\qiskit-terra\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps cwd: C:\Users\Tanya Garg\qiskit-terra
Complete output (13 lines): running develop running egg_info writing qiskit_terra.egg-info\PKG-INFO writing dependency_links to qiskit_terra.egg-info\dependency_links.txt writing requirements to qiskit_terra.egg-info\requires.txt writing top-level names to qiskit_terra.egg-info\top_level.txt reading manifest file 'qiskit_terra.egg-info\SOURCES.txt' reading manifest template 'MANIFEST.in' warning: no files found matching 'test\python\pickles*.pickle' writing manifest file 'qiskit_terra.egg-info\SOURCES.txt' running build_ext building 'qiskit.transpiler.passes.routing.cython.stochastic_swap.utils' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ ---------------------------------------- ERROR: Command errored out with exit status 1: 'C:\Users\Tanya Garg\Anaconda3\envs\fixissueenv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Tanya Garg\qiskit-terra\setup.py'"'"'; file='"'"'C:\Users\Tanya Garg\qiskit-terra\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

This is the error while installing the editable version of qiskit terra in an env. Help please

### Steps to reproduce the problem
Error occurs after pip install -e.

**Comment by tgag17** [comment]
Is the error there due to lack of visual studio?

**Comment by 3yakuya** [comment]
Hi, thanks for filing! Could you provide the following to help get answers faster:
- what OS and version do you use?
- what Python version?
- what Anaconda version?
- what exactly are the steps that led you to this error?
Thanks!

**Comment by tgag17** [comment]
Hi. I tried again by downloading visual studio and it worked. Thank you for the help. I would be closing the issue.

**Comment by 3yakuya** [comment]
Glad it works now, it does seem like some setup problem rather than Qiskit specific. Enjoy!
