### ISSUE TITLE
Broken link in qiskit textbook

### ISSUE THREAD

**Issue by AstroSkape** [Qiskit/qiskit-metapackage#1035]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
Link to "The Atoms Of Computation" page under section 3.1 of the textbook chapter 2.2 : "Multiple Qubits and Entangled States"
(Link to the page : https://qiskit.org/textbook/ch-gates/multiple-qubits-entangled-states.html )
- What is the current text that needs to be fixed or removed? (You can copy and paste)
https://qiskit.org/textbook/ch-states/atoms-computation.ipynb

- What should the documentation say instead?
https://qiskit.org/textbook/ch-states/atoms-computation.html

- Are there other related issues or pull requests about this bug?
No.

**Comment by namasyh** [comment]
yeah, seems like there's an error. Can I edit it?

**Comment by AstroSkape** [comment]
Sure, go ahead.
