### ISSUE TITLE
Is C_{X} a common notation for controlled-Not operation?

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1039]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

https://qiskit.org/documentation/getting_started.html#step-3-add-gates

- What is the current text that needs to be fixed or removed? (You can copy and paste)

<img width="614" alt="Screen Shot 2020-09-14 at 3 18 32 PM" src="https://user-images.githubusercontent.com/766693/93128700-e590ec80-f69d-11ea-8f59-f1e48d175ebd.png">

- What should the documentation say instead?

Not an expert here, but this notation in the documentation is new to me. It is there since "[the beginning](https://github.com/Qiskit/qiskit/pull/35/files#diff-85245c59bbc7f378cc2ad4fd800f0782R73)" and I could not find any other place where this notation for CX is used. Wikipedia uses [cX](https://en.wikipedia.org/wiki/Quantum_logic_gate#Controlled_(cX_cY_cZ)_gates), [C-NOT, or CNOT](https://en.wikipedia.org/wiki/Controlled_NOT_gate). The closer notation Im aware of is in [this paper ](https://arxiv.org/pdf/1810.00375.pdf): something like X<sup>c</sup>. 

Even if the notation exists, it can be argued that is not the most common notation. Probably CNOT is the best way to go here, an introduction to quantum computing.

**Comment by g-ebbs** [comment]
@1ucian0 Is it alright if I fix this issue? (If it has not already been fixed of course)

**Comment by 1ucian0** [comment]
Sure!

**Comment by g-ebbs** [comment]
Quick fix, the pull request mentioned above should do the trick!

**Comment by nonhermitian** [comment]
Closing as done.
