### ISSUE TITLE
Printing # of logical CPU in the output of %qiskit_version_table

### ISSUE THREAD

**Issue by omarshehab** [Qiskit/qiskit-metapackage#1045]
### Print the number of logical CPUs in the output of `%qiskit_version_table`. Currently, only the number of physical CPUs is printed. Following code could help.
```

import psutil
psutil.cpu_count()
```

**Comment by nonhermitian** [comment]
It is like this because logical cores (hyperthreads) do not add much in terms of performance if any. Indeed, when spawning processes, the memory overhead vs performance gain calculation is not good.

**Comment by nonhermitian** [comment]
Closing. Feel free to reopen if anything else is needed.
