### ISSUE TITLE
Spelling Issue

### ISSUE THREAD

**Issue by camitava0321** [Qiskit/qiskit-metapackage#1048]
## Spelling 

'Note that we cut off the part after the **decimla** point in the converted formulation...'
modify to 
'Note that we cut off the part after the decimal point in the converted formulation...'

- https://qiskit.org/documentation/tutorials/optimization/2_converters_for_quadratic_programs.html

**Comment by wmurphy-collabstar** [comment]
Hi, I'm interested in contributing to the documentation. Can I work on this issue?

**Comment by SooluThomas** [comment]
The tutorials source files are here: https://github.com/Qiskit/qiskit-tutorials. Feel free to open a PR in that repository.

**Comment by wmurphy-collabstar** [comment]
Okay, will do, thank you!

**Comment by wmurphy-collabstar** [comment]
Nevermind, someone else already made a pull request for the issue: https://github.com/Qiskit/qiskit-tutorials/pull/1044 , but it hasn't closed yet.

**Comment by nonhermitian** [comment]
Closing as done
