### ISSUE TITLE
Operator equation for Toffoli gate is incorrect 

### ISSUE THREAD

**Issue by ReubenDemirdjian** [Qiskit/qiskit-metapackage#1050]
The qiskit documentation for the Toffoli gate (https://qiskit.org/documentation/stubs/qiskit.circuit.library.CCXGate.html#qiskit.circuit.library.CCXGate) is incorrect. 

The Toffoli matrix representation for qiskit is stated in the doc as "|0⟩⟨0|⊗I⊗I+|1⟩⟨1|⊗CX" when in fact it should be "I⊗I⊗|0⟩⟨0|+CX⊗|1⟩⟨1|." 

Similarly, the note within the doc provides the form given in many textbooks as "I⊗I⊗|0⟩⟨0|+CX⊗|1⟩⟨1|" when in fact it should be "|0⟩⟨0|⊗I⊗I+|1⟩⟨1|⊗CX."

In both cases, the full matrices given on the right hand side are correct, but the equations are wrong.

**Comment by kdk** [comment]
Closing as resolved by https://github.com/Qiskit/qiskit-terra/pull/5256 .
