### ISSUE TITLE
Dead link in "Getting Started with Qiskit"

### ISSUE THREAD

**Issue by daniel-miller-quantum** [Qiskit/qiskit-metapackage#1052]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
A link is not working.

### Steps to reproduce the problem
- Go on https://qiskit.org/documentation/getting_started.html
- Search for "various forms"
- click on the link

### What is the expected behavior?
- You will be directed to a page saying "Page Not Found - Sorry, but the page you were trying to view does not exist."

### Suggested solutions
- Update/Remove the hyperlink

**Comment by daniel-miller-quantum** [comment]
Sorry, this is not a bug but a documentation issue.

**Comment by wmurphy-collabstar** [comment]
Hello, I'm interested in this issue. Is it okay if I work on it? Also, do you know where I can look to figure out what the link should be?

**Comment by shaashwat** [comment]
Hey, I didn't see this fixed and it has been 20 days so can I go ahead and fix it?
