### ISSUE TITLE
In U3, the gates RX and RY are mixed up

### ISSUE THREAD

**Issue by daniel-miller-quantum** [Qiskit/qiskit-metapackage#1055]
## Did you find a doc bug or broken link that needs to be fixed?

https://qiskit.org/documentation/stubs/qiskit.circuit.library.U3Gate.html
 
![image](https://user-images.githubusercontent.com/72351187/95088433-40f54e00-0723-11eb-9c3e-7d0bc675208b.png)

## Does existing documentation need to be updated with new content?
 
I believe that RX and RY should be swapped; also there is a typo as pi/2 is not displayed correctly.

**Comment by g-ebbs** [comment]
I am going to take a look at this issue if that is ok. I will make another issue post for it on the qiskit-terra page with a link to this post.

**Comment by kdk** [comment]
The current docs have
![image](https://user-images.githubusercontent.com/2241698/95794772-b4183a80-0cb6-11eb-8657-ab9f30aa3c37.png)
![image](https://user-images.githubusercontent.com/2241698/95794784-bc707580-0cb6-11eb-8e9e-3ecddf98e129.png)
![image](https://user-images.githubusercontent.com/2241698/95794799-c5f9dd80-0cb6-11eb-834b-a3b809baa55f.png)
which look consistent with the examples above to me (other than the pi rendering). Is there something I'm missing?

**Comment by g-ebbs** [comment]
> The current docs have
> ![image](https://user-images.githubusercontent.com/2241698/95794772-b4183a80-0cb6-11eb-8657-ab9f30aa3c37.png)
> ![image](https://user-images.githubusercontent.com/2241698/95794784-bc707580-0cb6-11eb-8e9e-3ecddf98e129.png)
> ![image](https://user-images.githubusercontent.com/2241698/95794799-c5f9dd80-0cb6-11eb-834b-a3b809baa55f.png)
> which look consistent with the examples above to me (other than the pi rendering). Is there something I'm missing?

I checked to see if the RX and RY gates were swapped by creating circuits for each case on IBMQ and they seemed consistent with the docs to me as well.

**Comment by daniel-miller-quantum** [comment]
Oh sorry, I just realized that I mixed up the matrix representations of RX and RY. Sorry about that.

So, the only thing to be done is the rendering of pi.

**Comment by kdk** [comment]
:+1: Closing as resolved by https://github.com/Qiskit/qiskit-terra/pull/5211 .
