### ISSUE TITLE
Update Qiskit Code of Conduct

### ISSUE THREAD

**Issue by ryanfmandelbaum** [Qiskit/qiskit-metapackage#1057]
## Does existing documentation need to be updated with new content?

- Which files need to be updated?
https://github.com/Qiskit/qiskit/blob/master/CODE_OF_CONDUCT.md
https://github.com/Qiskit/qiskit-terra/blob/master/CODE_OF_CONDUCT.md
https://github.com/Qiskit/qiskit-aer/blob/master/CODE_OF_CONDUCT.md
https://github.com/Qiskit/qiskit-ignis/blob/master/CODE_OF_CONDUCT.md
https://github.com/Qiskit/qiskit-aqua/blob/master/CODE_OF_CONDUCT.md
https://github.com/Qiskit/retworkx/blob/master/CODE_OF_CONDUCT.md
https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/CODE_OF_CONDUCT.md
https://github.com/Qiskit/qiskit-aqua-interfaces/blob/master/CODE_OF_CONDUCT.md
https://github.com/Qiskit/qiskit.org/blob/master/CODE_OF_CONDUCT.md

- What content needs to be updated or replaced? (You can copy and paste)
The IBM Quantum and Qiskit team re-wrote the CoC to put a stronger enforcement process in place and tighten language. This has been reviewed by the IBM Quantum Legal team. 

- What new content needs to be added?
Code of Conduct in Qiskit Tutorials folder

**Comment by nonhermitian** [comment]
Closing as done.
