### ISSUE TITLE
ModuleNotFoundError: No module named 'qiskit.circuit.library'

### ISSUE THREAD

**Issue by tycooperaow** [Qiskit/qiskit-metapackage#1074]
### Informations

- **Qiskit version**: qiskit==0.16.1
- **Python version**: python3.8
- **Operating system**: MacOS Catalina 10.15.5

### What is the current behavior?
ModuleNotFoundError: No module named 'qiskit.circuit.library'

### Steps to reproduce the problem
`
from qiskit.circuit.library import FourierChecking
`

### What is the expected behavior?
To Run the library

### Suggested solutions
I typed in 
`dir(qiskit.circuit)`
The following popped up
`
'ClassicalRegister',
 'Clbit',
 'ControlledGate',
 'Gate',
 'Instruction',
 'InstructionSet',
 'Measure',
 'Parameter',
 'ParameterExpression',
 'ParameterVector',
 'QuantumCircuit',
 'QuantumRegister',
 'Qubit',
 'Reset',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'bit',
 'classicalregister',
 'controlledgate',
 'exceptions',
 'gate',
 'instruction',
 'instructionset',
 'measure',
 'parameter',
 'parameterexpression',
 'parametertable',
 'parametervector',
 'quantumcircuit',
 'quantumcircuitdata',
 'quantumregister',
 'register',
 'reset'
`

**Comment by kdk** [comment]
The circuit library was introduced in Qiskit 0.18. Feel free to re-open if upgrading to Qiskit 0.18+ doesn't resolve this issue.
