### ISSUE TITLE
Qiskit transpile different basis gate set

### ISSUE THREAD

**Issue by maxkeller321** [Qiskit/qiskit-metapackage#1075]
### Informations
- **Qiskit version**:  
{'qiskit-terra': '0.16.0', 
'qiskit-aer': '0.7.0', 
'qiskit-ignis': '0.5.0',
 'qiskit-ibmq-provider': '0.11.0',
 'qiskit-aqua': '0.8.0', 
'qiskit': '0.23.0'}
- **Python version**: Python 3.8.1
- **Operating system**: macOs

### What is the current behavior?

Currently, the output from the qiskit transpile function for my random gate set (random gates) with the basis gate set 'rx', 'ry' and 'cx' is this circuit: 

<img width="1191" alt="Bildschirmfoto 2020-10-24 um 12 39 51" src="https://user-images.githubusercontent.com/60929371/97079637-04b45f80-15f6-11eb-8b50-1af0a37dc755.png">

I'm not sure, why the transpile function gives sometimes three single qubit rotations (Is it not possible to decompose every  single qubit rotation into one  rx( -pi <= theta<= pi)  and one ry( -pi <= theta <= pi) rotation ?).

The second minor issue is that sometimes a rotation with an angle of 0 degree is still in the circuit and not removed (see image).  

### Steps to reproduce the problem

The following code produces the circuit of the provided image. 
`
qc = QuantumCircuit(3)

qc.h(0)
qc.h(1)
qc.x(0)
qc.h(0)
qc.ry(np.pi/4, 0)
qc.rx(np.pi/10, 0)
qc.y(1)
qc.rx(np.pi/10, 0)
qc.rx(np.pi/10, 0)
qc.h(2)
qc.cx(2, 1)
qc.x(0)
qc.cx(0, 1)
qc.y(2)
qc.rx(np.pi/10, 0)
qc.rx(np.pi/10, 0)
qc.y(0)
qc.x(2)
qc.rx(np.pi/10, 0)
qc.ry(np.pi/4, 2)
qc.cx(0, 2)
qc.h(2)
qc.cx(2, 1)
qc.x(0)
qc.cx(0, 1)
qc.rx(np.pi/10, 0)
qc.rx(np.pi/10, 0)

qc.x(2)
qc.ry(np.pi/4, 2)
qc.ry(np.pi/4, 2)
qc.ry(np.pi/4, 2)
qc.cx(0, 2)
qc.h(2)
qc.cx(2, 1)
qc.measure_all()

coupling_string = [[0, 1], [1, 0], [2, 0], [0,2], [1,2], [2, 1]]
CM = CouplingMap(coupling_string)
basis_gates = ['id', 'ry', 'rx', 'cx']
transpiled_qc = transpile(qc, coupling_map=CM, basis_gates=basis_gates, optimization_level=3, seed_transpiler=1)

### What is the expected behavior?

Normally I would expect that the transpile function with the passed basis gate set would give me in my circuit only two consecutive applied single qubit roations and not three and that rotations with an angle of 0 would be removed.  

Am I wrong with my expectations ?

### Suggested solutions
...

**Comment by taalexander** [comment]
This is due to Terra's transpiler gate equivalencies. Can you please post this as a Qiskit terra issue?
