### ISSUE TITLE
Unable to use the unitary_simulator

### ISSUE THREAD

**Issue by ayushdeolasee** [Qiskit/qiskit-metapackage#1076]
##Error: 
IndexError: list index out of range

###I have a circuit that has one x gate and I want to use the unitary simulator on that circuit.

##Code

circuit0 = QuantumCircuit(1,1)
circuit0.x(0)
circuit0.measure(0, 1)
simulator0 = Aer.get_backend('unitary_simulator')
resul0t = execute(circuit0, backend=simulator0).result()
unitary = result.get_unitary()
print(unitary)

**Comment by yaelbh** [comment]
The line
```
circuit0 = QuantumCircuit(1,1)
```
says that there is one classical bit, but in the line
```
circuit0.measure(0, 1)
```
you refer to classical bit no. 1, where the numbering begins with 0.
Change to
```
circuit0.measure(0, 0)
```

**Comment by ayushdeolasee** [comment]
I made the changes and I have the error:
QiskitError: 'No unitary for experiment "None"'

**Comment by yaelbh** [comment]
When calling `get_unitary`, you need to enter a circuit name or index. Change to:
```
unitary = result.get_unitary(0)
```

**Comment by nonhermitian** [comment]
Well I would remove the measurements as well.

**Comment by ayushdeolasee** [comment]
Okay thank you!
