### ISSUE TITLE
No viable alternative at input `gate disentangler q0 { ... }`

### ISSUE THREAD

**Issue by praveentn** [Qiskit/qiskit-metapackage#1077]
### Informations

- **Qiskit version**: 0.23
- **Python version**: 3.8
- **Operating system**: Win

### What is the current behavior?

No viable alternative at input `gate disentangler q0 { ... }`

### Steps to reproduce the problem
Place the following code in QASM editor.

```
OPENQASM 2.0;
include "qelib1.inc";
gate disentangler q0 {multiplex1 q0; multiplex1_reverse q0; }
gate initialize q0 {reset q0; disentangler_dg q0; }
qreg q[3];
creg crz[1];
creg crx[1];
creg c0[1];
initialize(0.18398168+0.70228441j,0.60962324+0.31828738j) q[0];
barrier q[0],q[1],q[2];
h q[1];
cx q[1],q[2];
barrier q[0],q[1],q[2];
cx q[0],q[1];
h q[0];
barrier q[0],q[1],q[2];
measure q[0] -> crz[0];
measure q[1] -> crx[0];
if(crx==1) x q[2];
if(crz==1) z q[2];
disentangler q[2];
measure q[2] -> c0[0];
```

### What is the expected behavior?

Create the circuit for teleportation

**Comment by kdk** [comment]
Running this, I get
```
qiskit.qasm.exceptions.QasmError: "Cannot find gate definition for 'multiplex1', line 4 file "
```
since `multiplex1` isn't defined in your qasm string or in `qelib1.inc`. Did you generate this QASM from qiskit?

**Comment by praveentn** [comment]
> Running this, I get
> 
> ```
> qiskit.qasm.exceptions.QasmError: "Cannot find gate definition for 'multiplex1', line 4 file "
> ```
> 
> since `multiplex1` isn't defined in your qasm string or in `qelib1.inc`. Did you generate this QASM from qiskit?

yes, generated this `QASM` from `qiskit`

**Comment by kdk** [comment]
Can you share the code you used to build this qasm?

**Comment by praveentn** [comment]
> 
> 
> Can you share the code you used to build this qasm?

I took the `qasm` of the `teleportation_circuit` in this [notebook ](https://quantum-computing.ibm.com/jupyter/user/qiskit-textbook/content/ch-algorithms/teleportation.ipynb) after cell 10.

```
print(teleportation_circuit.qasm())
```

**Comment by sajidanis** [comment]
If you don't mind, can I have a look at which code creates this qasm. I am not able to create an identical qasm from that notebook.

**Comment by praveentn** [comment]
I took the `qasm` of the final circuit which gave this. The one of the teleportation circuit worked fine. Closing the issue.
