### ISSUE TITLE
Symbol name already exists at `creg ...`

### ISSUE THREAD

**Issue by praveentn** [Qiskit/qiskit-metapackage#1078]
### Informations

- **Qiskit version**: 0.23
- **Python version**: 3.8
- **Operating system**: Win

### What is the current behavior?

Symbol name already exists at `creg crz[1]; creg crx[1];`

### Steps to reproduce the problem

```
OPENQASM 2.0;
include "qelib1.inc";

qreg q[3];
creg crz[1]; //error here
creg crx[1]; //error here
creg c0[1];
```

### What is the expected behavior?

No errors

**Comment by nonhermitian** [comment]
Crz and crx are gate names in qasm

**Comment by kdk** [comment]
Running this I get
```
qiskit.qasm.exceptions.QasmError: "Duplicate declaration for creg 'crz' at line 6, file .
Previous occurrence at line 106, file /Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/qasm/libs/qelib1.inc"
```
Is this the error message you see?

**Comment by praveentn** [comment]
The error is this

```
Symbol name already exists at creg ...
```

changing the names (`crx` and `crz`) resolves the error
