### ISSUE TITLE
Inline figures does not work on Jupyter Notebook & VScode

### ISSUE THREAD

**Issue by deep-introspection** [Qiskit/qiskit-metapackage#1085]
### Informations

- **Qiskit version**: '0.16.0'
- **Python version**: 3.7
- **Operating system**: OSX Catalina 10.15.7

### What is the current behavior?

```qc.draw("mpl")``` provides a fig handle instead of showing a figure after using ```%matplotlib inline```

### Steps to reproduce the problem

```
from qiskit import QuantumCircuit, execute, Aer
from qiskit.visualization import plot_histogram
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
qc = QuantumCircuit(1,1)
initial_state = [np.sqrt(1/2), np.sqrt(1/2)]
qc.initialize(initial_state, 0)
qc.measure(0, 0)
qc.draw("mpl")
```

Output: ```<Figure size 253.926x144.48 with 1 Axes>```

### Screenshot showing matplotlib works independently of Qiskit

![Screen Shot 2020-11-04 at 11 01 57 AM](https://user-images.githubusercontent.com/208779/98135600-03085880-1e8e-11eb-8262-a2e9fce4ab63.jpg)

**Comment by nonhermitian** [comment]
Can you say more how your running this?  Note that `@matplotlib inline` has not been required for sometime now, and is automatically applied in notebooks.

**Comment by deep-introspection** [comment]
@nonhermitian Thanks! Actually, the issue is solved in the last version!

![Screen Shot 2021-03-26 at 3 12 19 PM](https://user-images.githubusercontent.com/208779/112681907-b675e780-8e45-11eb-8172-636261c9228f.jpg)
