### ISSUE TITLE
ERROR: Failed building wheel for retworkx' in Qiskit/qiskit'

### ISSUE THREAD

**Issue by kusalAbeywickrama** [Qiskit/qiskit-metapackage#1087]
### Informations

- **Qiskit version**: None
- **Python version**: Python 3.9.0
- **pip version**: pip 20.2.4
- **Anaconda version**: conda 4.8.5
- **Operating system**: Ubuntu 20.04.1 LTS

### What is the current behavior?

During the qiskit installation process, when run pip install qiskit command and, it returns this error.

Processing ./.cache/pip/wheels/44/6a/b8/70d530095a4fd93199b06fd7c4b94b36fd2845f9ec6156e250/qiskit-0.23.0-py3-none-any.whl
Collecting qiskit-ibmq-provider==0.11.0
  Using cached qiskit_ibmq_provider-0.11.0-py3-none-any.whl (194 kB)
Collecting qiskit-aqua==0.8.0
  Using cached qiskit_aqua-0.8.0-py3-none-any.whl (2.1 MB)
Processing ./.cache/pip/wheels/14/05/e2/3e1b4acf4941bfe27ef9dc54e85cb2a461480f284fe3f2ff15/qiskit_terra-0.16.0-cp39-cp39-linux_x86_64.whl
Collecting qiskit-ignis==0.5.0
  Using cached qiskit_ignis-0.5.0-py3-none-any.whl (203 kB)
Processing ./.cache/pip/wheels/77/c8/be/c84ddde57a938168f3e44a64c4dd314f9a9e38e37cadfde59a/qiskit_aer-0.7.0-cp39-cp39-linux_x86_64.whl
Collecting nest-asyncio!=1.1.0,>=1.0.0
  Using cached nest_asyncio-1.4.2-py3-none-any.whl (5.3 kB)
Collecting requests-ntlm>=1.1.0
  Using cached requests_ntlm-1.1.0-py2.py3-none-any.whl (5.7 kB)
Collecting urllib3>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting requests>=2.19
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting numpy>=1.13
  Using cached numpy-1.19.4-cp39-cp39-manylinux2010_x86_64.whl (14.5 MB)
Processing ./.cache/pip/wheels/d8/b9/a0/b97b211aeda2ebd6ac2e43fc300d308dbf1f9df520ed390cae/websockets-8.1-cp39-cp39-linux_x86_64.whl
Collecting python-dateutil>=2.8.0
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Processing ./.cache/pip/wheels/5e/74/24/7e235ccf01765c0daa089c98cc823e9dc1383da5fe0ed7e224/scikit_learn-0.23.2-cp39-cp39-linux_x86_64.whl
Collecting scipy>=1.4
  Using cached scipy-1.5.4-cp39-cp39-manylinux1_x86_64.whl (25.8 MB)
Processing ./.cache/pip/wheels/76/43/53/a0fed7ed0582fd7b0b3032a6703bd498bc6397d4217e88a9ce/psutil-5.7.3-cp39-cp39-linux_x86_64.whl
Collecting quandl
  Using cached Quandl-3.5.3-py2.py3-none-any.whl (25 kB)
Collecting h5py
  Using cached h5py-3.0.0-cp39-cp39-manylinux1_x86_64.whl (4.4 MB)
Collecting retworkx>=0.5.0
  Using cached retworkx-0.5.0.tar.gz (45 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing ./.cache/pip/wheels/59/50/ec/66f77a4e69f1e456dd1d88eec793730387f80b9de8056b8306/docplex-2.15.194-py3-none-any.whl
Collecting pandas
  Using cached pandas-1.1.4-cp39-cp39-manylinux1_x86_64.whl (9.3 MB)
Collecting sympy>=1.3
  Using cached sympy-1.6.2-py3-none-any.whl (5.8 MB)
Requirement already satisfied: setuptools>=40.1.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aqua==0.8.0->qiskit) (50.3.0.post20201103)
Processing ./.cache/pip/wheels/75/6f/b1/2a6be95ab6a39ae5e82cef79a5bed8b5b841ee1322fecf3dee/yfinance-0.1.55-py2.py3-none-any.whl
Processing ./.cache/pip/wheels/1f/a1/63/bfd0fddb5bf0b59f564872e29272cee8a2de0cd745d88fede5/fastdtw-0.3.4-cp39-cp39-linux_x86_64.whl
Processing ./.cache/pip/wheels/81/bd/ba/2896ffc1856e28914fcbf4d0ded1bfbb5924dad98c80ba2d5c/dlx-1.0.4-py3-none-any.whl
Collecting dill>=0.3
  Using cached dill-0.3.3-py2.py3-none-any.whl (81 kB)
Collecting ply>=3.10
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Collecting networkx>=2.2
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting fastjsonschema>=2.10
  Using cached fastjsonschema-2.14.5-py3-none-any.whl (21 kB)
Processing ./.cache/pip/wheels/51/36/1f/c2ccb8dc4eba38c5215636d4ae2c480b32069cab0376bcc1a4/python_constraint-1.4.0-py2.py3-none-any.whl
Collecting jsonschema>=2.6
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting pybind11>=2.4
  Using cached pybind11-2.6.0-py2.py3-none-any.whl (187 kB)
Collecting cython>=0.27.1
  Using cached Cython-0.29.21-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
Collecting ntlm-auth>=1.0.2
  Using cached ntlm_auth-1.5.0-py2.py3-none-any.whl (29 kB)
Collecting cryptography>=1.3
  Using cached cryptography-3.2.1-cp35-abi3-manylinux2010_x86_64.whl (2.6 MB)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from requests>=2.19->qiskit-ibmq-provider==0.11.0->qiskit) (2020.6.20)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting joblib>=0.11
  Using cached joblib-0.17.0-py3-none-any.whl (301 kB)
Collecting inflection>=0.3.1
  Using cached inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting more-itertools
  Using cached more_itertools-8.6.0-py3-none-any.whl (45 kB)
Collecting cached-property
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting pytz>=2017.2
  Using cached pytz-2020.4-py2.py3-none-any.whl (509 kB)
Processing ./.cache/pip/wheels/95/ce/4d/8d9590361a444e9d675579e0ead7a43932654456fef0d5258a/mpmath-1.1.0-py3-none-any.whl
Collecting lxml>=4.5.1
  Using cached lxml-4.6.1-cp39-cp39-manylinux1_x86_64.whl (5.4 MB)
Processing ./.cache/pip/wheels/1d/13/0b/0c32509050dcd9264e9a90b1d9d2dc9c6db9538db151ea7d26/multitasking-0.0.9-py3-none-any.whl
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting attrs>=17.4.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Processing ./.cache/pip/wheels/00/cc/12/e712d3979a4aeee423b34a832d97c803e1a67659060315a7e0/pyrsistent-0.17.3-cp39-cp39-linux_x86_64.whl
Collecting cffi!=1.11.3,>=1.8
  Using cached cffi-1.14.3-cp39-cp39-manylinux1_x86_64.whl (405 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: retworkx
  Building wheel for retworkx (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/kusal/anaconda3/envs/conda/bin/python /home/kusal/anaconda3/envs/conda/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpna05q14i
       cwd: /tmp/pip-install-wt2iojos/retworkx
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/retworkx
  copying retworkx/__init__.py -> build/lib/retworkx
  running egg_info
  writing retworkx.egg-info/PKG-INFO
  writing dependency_links to retworkx.egg-info/dependency_links.txt
  writing requirements to retworkx.egg-info/requires.txt
  writing top-level names to retworkx.egg-info/top_level.txt
  reading manifest file 'retworkx.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'retworkx.egg-info/SOURCES.txt'
  running build_ext
  running build_rust
  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for retworkx
Failed to build retworkx
ERROR: Could not build wheels for retworkx which use PEP 517 and cannot be installed directly

### Steps to reproduce the problem

- download and install anaconda
- conda create -n name_of_my_env python=3
- conda activate name_of_my_env
- pip install qiskit

### What is the expected behavior?

Complete the installation without any errors

Requirement already satisfied: qiskit in ./anaconda3/envs/conda/lib/python3.9/site-packages (0.23.0)
Requirement already satisfied: qiskit-ignis==0.5.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit) (0.5.0)
Requirement already satisfied: qiskit-aer==0.7.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit) (0.7.0)
Requirement already satisfied: qiskit-ibmq-provider==0.11.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit) (0.11.0)
Requirement already satisfied: qiskit-terra==0.16.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit) (0.16.0)
Requirement already satisfied: qiskit-aqua==0.8.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit) (0.8.0)
Requirement already satisfied: scikit-learn>=0.17 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ignis==0.5.0->qiskit) (0.23.2)
Requirement already satisfied: scipy!=0.19.1,>=0.19 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ignis==0.5.0->qiskit) (1.5.4)
Requirement already satisfied: setuptools>=40.1.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ignis==0.5.0->qiskit) (50.3.0.post20201103)
Requirement already satisfied: numpy>=1.13 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ignis==0.5.0->qiskit) (1.19.4)
Requirement already satisfied: cython>=0.27.1 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aer==0.7.0->qiskit) (0.29.21)
Requirement already satisfied: pybind11>=2.4 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aer==0.7.0->qiskit) (2.6.0)
Requirement already satisfied: requests>=2.19 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ibmq-provider==0.11.0->qiskit) (2.24.0)
Requirement already satisfied: websockets>=8 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ibmq-provider==0.11.0->qiskit) (8.1)
Requirement already satisfied: python-dateutil>=2.8.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ibmq-provider==0.11.0->qiskit) (2.8.1)
Requirement already satisfied: urllib3>=1.21.1 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ibmq-provider==0.11.0->qiskit) (1.25.11)
Requirement already satisfied: nest-asyncio!=1.1.0,>=1.0.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ibmq-provider==0.11.0->qiskit) (1.4.2)
Requirement already satisfied: requests-ntlm>=1.1.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-ibmq-provider==0.11.0->qiskit) (1.1.0)
Requirement already satisfied: networkx>=2.2 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (2.5)
Requirement already satisfied: sympy>=1.3 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (1.6.2)
Requirement already satisfied: psutil>=5 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (5.7.3)
Requirement already satisfied: ply>=3.10 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (3.11)
Requirement already satisfied: fastjsonschema>=2.10 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (2.14.5)
Requirement already satisfied: dill>=0.3 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (0.3.3)
Requirement already satisfied: jsonschema>=2.6 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (3.2.0)
Requirement already satisfied: python-constraint>=1.4 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (1.4.0)
Requirement already satisfied: retworkx>=0.5.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-terra==0.16.0->qiskit) (0.5.0)
Requirement already satisfied: dlx in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aqua==0.8.0->qiskit) (1.0.4)
Requirement already satisfied: pandas in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aqua==0.8.0->qiskit) (1.1.4)
Requirement already satisfied: docplex in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aqua==0.8.0->qiskit) (2.15.194)
Requirement already satisfied: h5py in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aqua==0.8.0->qiskit) (3.0.0)
Requirement already satisfied: quandl in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aqua==0.8.0->qiskit) (3.5.3)
Requirement already satisfied: fastdtw in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aqua==0.8.0->qiskit) (0.3.4)
Requirement already satisfied: yfinance in ./anaconda3/envs/conda/lib/python3.9/site-packages (from qiskit-aqua==0.8.0->qiskit) (0.1.55)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from scikit-learn>=0.17->qiskit-ignis==0.5.0->qiskit) (2.1.0)
Requirement already satisfied: joblib>=0.11 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from scikit-learn>=0.17->qiskit-ignis==0.5.0->qiskit) (0.17.0)
Requirement already satisfied: chardet<4,>=3.0.2 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from requests>=2.19->qiskit-ibmq-provider==0.11.0->qiskit) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from requests>=2.19->qiskit-ibmq-provider==0.11.0->qiskit) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from requests>=2.19->qiskit-ibmq-provider==0.11.0->qiskit) (2.10)
Requirement already satisfied: six>=1.5 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from python-dateutil>=2.8.0->qiskit-ibmq-provider==0.11.0->qiskit) (1.15.0)
Requirement already satisfied: ntlm-auth>=1.0.2 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.11.0->qiskit) (1.5.0)
Requirement already satisfied: cryptography>=1.3 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.11.0->qiskit) (3.2.1)
Requirement already satisfied: decorator>=4.3.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from networkx>=2.2->qiskit-terra==0.16.0->qiskit) (4.4.2)
Requirement already satisfied: mpmath>=0.19 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from sympy>=1.3->qiskit-terra==0.16.0->qiskit) (1.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from jsonschema>=2.6->qiskit-terra==0.16.0->qiskit) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from jsonschema>=2.6->qiskit-terra==0.16.0->qiskit) (20.3.0)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from pandas->qiskit-aqua==0.8.0->qiskit) (2020.4)
Requirement already satisfied: cached-property in ./anaconda3/envs/conda/lib/python3.9/site-packages (from h5py->qiskit-aqua==0.8.0->qiskit) (1.5.2)
Requirement already satisfied: more-itertools in ./anaconda3/envs/conda/lib/python3.9/site-packages (from quandl->qiskit-aqua==0.8.0->qiskit) (8.6.0)
Requirement already satisfied: inflection>=0.3.1 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from quandl->qiskit-aqua==0.8.0->qiskit) (0.5.1)
Requirement already satisfied: lxml>=4.5.1 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from yfinance->qiskit-aqua==0.8.0->qiskit) (4.6.1)
Requirement already satisfied: multitasking>=0.0.7 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from yfinance->qiskit-aqua==0.8.0->qiskit) (0.0.9)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./anaconda3/envs/conda/lib/python3.9/site-packages (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.11.0->qiskit) (1.14.3)
Requirement already satisfied: pycparser in ./anaconda3/envs/conda/lib/python3.9/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.11.0->qiskit) (2.20)

### Suggested solutions

We have to installe Rust toolchain installer, then we can easily install retworkx into our python environment using pip command. In this case, we do not need to install it separately. Execute pip install qiskit command after curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh command (rust installation).

- download and install anaconda
- conda create -n name_of_my_env python=3
- conda activate name_of_my_env
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  
- pip install qiskit

**Comment by mtreinish** [comment]
The issue here is that qiskit does not support python 3.9 yet. It was only released about a month ago and many of the upstream dependencies do not fully support python 3.9 yet (or haven't published python 3.9 wheels yet). This is just a matter of time as we wait for those packages to release and then push a qiskit version that supports 3.9. The process for this has started here: https://github.com/Qiskit/qiskit-terra/pull/5189 Until Python 3.9 is supported in qiskit I'd recommend you downgrade to python 3.8 where everything is supported already.

If you can't wait you'll have to build many of the dependencies from source (which if things are setup properly in your environment pip should be able to handle for you). In this specific case the retworkx library has merged support for python 3.9 (in https://github.com/Qiskit/retworkx/pull/168 ) and in its next release it will publish precompiled wheel for python 3.9.
