### ISSUE TITLE
Update langauges to new theme

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#1091]
Not sure how this works, but the translations need to be updated to the new theme.

**Comment by mtreinish** [comment]
This will happen automatically when the translations repo merges updated translations triggering a build and publishes it in the ci job.

**Comment by SooluThomas** [comment]
I just triggered the build for updated the theme for the translated docs. 

The translated docs toggle button is not easily found though. 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/11485594/98315038-3db0e480-1fa5-11eb-83ba-725057325482.png">


Edit: This issue should be fixed once the build is complete.

**Comment by nonhermitian** [comment]
Yes, that will need some tweaking. I did not know that was there because of my js blocker
