### ISSUE TITLE
Improving Installing Qiskit section

### ISSUE THREAD

**Issue by divya-mohan0209** [Qiskit/qiskit-metapackage#1092]
[Installing Qiskit](https://qiskit.org/documentation/install.html) documentation for Windows, specifically, could be made better. 

Here are a few suggestions that, I think, would be helpful for the very first installations of Qiskit on Windows:

- In the pre-requisites, it would be best if we mentioned that Conda installed using pip runs into errors. Directly downloading  the executable from the website would help them not run into these issues.
- Also, after it is installed on Windows the conda package often requires an update. This can be done using the command: conda update conda.

**Comment by nonhermitian** [comment]
I do not thing that installing conda via pip is a common usage pattern.  Typically one downloads Anaconda or miniconda to get it.  Updates are also good, but typically not required if one downloads a reasonably new version.
