### ISSUE TITLE
get qubits from statevector

### ISSUE THREAD

**Issue by missingpuzzle233** [Qiskit/qiskit-metapackage#1093]
How do I get the amplitude of each qubit, like plot_bloch_multivector(), but not output the tensor product of all qubits.

**Comment by nonhermitian** [comment]
In general the state of a qubit is a density matrix that is found by doing a partial trace over all other qubits. See https://qiskit.org/documentation/stubs/qiskit.quantum_info.partial_trace.html#qiskit.quantum_info.partial_trace

**Comment by nonhermitian** [comment]
Closing as answered.
