### ISSUE TITLE
Localization page does not show properly

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-metapackage#1094]
### Informations

- **Qiskit version**: NA
- **Python version**: NA
- **Operating system**: macOS 10.15.7

### What is the current behavior?

Qiskit documentation page in Japanese does not show properly.

### Steps to reproduce the problem

Choose Japanese at https://qiskit.org/documentation/
Then, it goes to https://qiskit.org/documentation/locale/ja_JP/index.html
The page looks as follows.
![image](https://user-images.githubusercontent.com/31178928/98320014-5cef5680-2025-11eb-93e8-82bcbfa238c8.png)

It reproduces on both Firefox 82.0.1 and MS Edge 86.0.622.63

### What is the expected behavior?

Localization page syncs with English page as follows.
![image](https://user-images.githubusercontent.com/31178928/98319983-4cd77700-2025-11eb-9e36-c903ffec3806.png)

**Comment by t-imamichi** [comment]
It looks fixed now.

**Comment by mtreinish** [comment]
FWIW, I expect this was a stale cache issue, either in the cloudflare CDN or in your local browser. We had a similar issue when we adopted the new theme and had to manually purge the CDN cache to fix it.

**Comment by t-imamichi** [comment]
Thanks. I tried cache clear, so it might be CDN issue (time lag).
