### ISSUE TITLE
Bullet points don't show up with new docs theme

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-metapackage#1097]
Bullet points on the docs page don't show up in the rendered output. For example, the terra 0.16.0 prelude on https://qiskit.org/documentation/release_notes.html#notable-changes has 4 bullets in the source (https://github.com/Qiskit/qiskit/blob/master/docs/release_notes.rst#prelude ) but it doesn't render bullet points in the built document:

![Screenshot_2020-11-07_08-31-47](https://user-images.githubusercontent.com/2447371/98442661-e65d6200-20d3-11eb-84b6-9b00b313df2f.png)

**Comment by nonhermitian** [comment]
This is why I hesitated to update the docs. Now I get assigned more css digging 😔

**Comment by nonhermitian** [comment]
Note that I am working on a generic doc in the theme repo to quickly diagnose these. Will add a section about bullets
