### ISSUE TITLE
Minimum tested version of OS

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-metapackage#1101]
### What is the expected behavior?

The installing documentation says that
> Qiskit is tested and supported on the following 64-bit systems:
> - Ubuntu 16.04 or later
> - macOS 10.12.6 or later
> - Windows 7 or later

https://qiskit.org/documentation/install.html

~I see the Travis of Qiskit terra runs on Ubuntu Bionic. https://travis-ci.com/github/Qiskit/qiskit-terra
So, is the tested minimum version of Ubuntu is 18.04? The default Python3 package of Ubuntu 16.04 is Python 3.5. So, it gets more difficult to setup qiskit on Ubuntu 16.04.~

~How about other OS? Is Windows 7 tested now?~

I notice that Ubuntu 16.04 is tested according to https://github.com/Qiskit/qiskit-terra/blob/master/azure-pipelines.yml
Windows uses 'vs2017-win2016', Ubuntu uses 'ubuntu-16.04' and 'ubuntu-latest', and macOS uses 'macOS-10.15'.
Does install.rst need to reflect the versions?

**Comment by mtreinish** [comment]
I don't think we necessarily need to document the versions we test with and probably should just remove that block from the install guide. 

As a general statement we're limited by the platform support for things with compiled extensions (aer and terra) the other platforms are pure python and should work anywhere python is installable. For linux packages we build against python specs. The minimum spec for linux is manylinux2010 https://www.python.org/dev/peps/pep-0571/ (terra is manylinux1 compatible but aer is not). For macOS we build with the deployment target of ISX 10.9. Windows abi compatibility is a bit different, I know it should work on any windows 10 system, I'm not sure if windows 7 will work or not (don't have a system to test that).

We also fully support 32bit systems now, both i686 and win32 are binaries are built at release time, and we have testing for that in aer.

**Comment by t-imamichi** [comment]
Thank you. It makes sense to remove versions. When we wrote about Windows 7, some people tested qiskit on our own Windows 7 PC.

How about writing about Python 3.9? You commented that Qiskit does not support Python 3.9 yet.
https://github.com/Qiskit/qiskit/issues/1087#issuecomment-722431527

**Comment by mtreinish** [comment]
The current releases do no support python 3.9. But I'm optimistic the next metapackage release that includes everything will. Right now terra is blocked on a retworkx release (which is almost ready https://github.com/Qiskit/retworkx/milestone/2). Once retworkx releases it will include precompiled binaries for python 3.9 that will mean all of terra's dependencies have python 3.9 wheels (or are pure python and there isn't anything to change). Once terra merges https://github.com/Qiskit/qiskit-terra/pull/5189 we can  push similar commits to ignis, aer, and aqua saying they support 3.9 and adding CI.

How we document this came up last year with the 3.8 release in: https://github.com/Qiskit/qiskit/issues/660 we decided there to leave it a bit open ended and point people to the package metadata for the specific supported versions (see: https://github.com/Qiskit/qiskit/pull/708 ). The thought back then was we wanted to avoid updating a list of hard coded versions in the docs on every python release. But, we can revisit this if you have some ideas on how to improve this. I do agree I find it quite annoying every python release we get a bunch of bugs and pings from people while we wait for upstream dependencies to add support. One thought I just had is we could write a sphinx extension that parses the setup.py to get the versions from the trove classifiers and just build a table or something in the docs from that.

**Comment by t-imamichi** [comment]
I see. Let's leave the description of Python version.
It's complicated to deal with every python release... I have no idea now.
Anyway, thank for your information about my questions. I close this.

**Comment by t-imamichi** [comment]
Sorry. I re-open it and leave it until we remove the OS versions in install.rst as you mentioned:
> I don't think we necessarily need to document the versions we test with and probably should just remove that block from the install guide.

**Comment by t-imamichi** [comment]
How about simplifying it as follows.
> Qiskit is supported on Linux, macOS, and Windows.

**Comment by t-imamichi** [comment]
I think the current documentation is enough for the new Python releases
> However, both Python and Qiskit are evolving ecosystems, and sometimes when new releases occur in one or the other, there can be problems with compatibility.

**Comment by nonhermitian** [comment]
Is there anything to do here?

**Comment by t-imamichi** [comment]
No. I close this.
