### ISSUE TITLE
Search in Qiskit Documentation does not work

### ISSUE THREAD

**Issue by veenaiyuri** [Qiskit/qiskit-metapackage#1106]
# Information
    Qiskit version: NA
    Python version: NA
    Operating system: macOS 10.15.7

# What is the current behavior?

The Search in Qiskit documentation does not work properly.

# Steps to reproduce the problem

Choose  https://qiskit.org/documentation/
Then, go to Search Docs window, type an arbitrary qiskit related keyword and enter.
The page keeps showing Searching... and never shows actual results. Please see image below.
![image](https://user-images.githubusercontent.com/24409087/98643354-42451680-2372-11eb-8281-9ca64f5817c6.png)

**Comment by veenaiyuri** [comment]
Thanks for looking into this. However. the issue seems to persist. Should I open a new issue?

**Comment by nonhermitian** [comment]
The docs take 1+ hours to generate, so it is still in progress.
