### ISSUE TITLE
Search Function Not working 

### ISSUE THREAD

**Issue by divshacker** [Qiskit/qiskit-metapackage#1108]
### Informations

- **Latest version**:
- **Latest Version**:
- **Latest Updated Windows**:

### What is the current behavior?
The Search Function is not working still . It is keep going loading .

### Steps to reproduce the problem
Just type any word and try to search it .

### What is the expected behavior?
It will load the search but will not show any result . 

### Suggested solutions
Previously the qiskit documentation was working fine but this theme have some problems I think . 
If we can fix those bugs then there might be no problem.

**Comment by nonhermitian** [comment]
This has already been solved in #1107 and is being uploaded as we speak.

**Comment by divshacker** [comment]
It is not working still

**Comment by nonhermitian** [comment]
It takes over an hour to generate all the documentation.
