### ISSUE TITLE
IBM tutorial optimization, 5_admm_optimizer has attribute error

### ISSUE THREAD

**Issue by feifeng1993** [Qiskit/qiskit-metapackage#1109]
### Informations

- **Operating system**:

### What is the current behavior?
In IBM toturial optimization demo, when running the demo, it has attribute error, binary_vartype does not have attribute 'one_letter_symbol'. Does any one know how to solve it?
https://qiskit.org/documentation/tutorials/optimization/5_admm_optimizer.html
![addmm](https://user-images.githubusercontent.com/59180238/98697725-38f08580-2343-11eb-8156-18607f7095d0.png)

**Comment by mtreinish** [comment]
This was a bug in aqua that was introduced with the release yesterday of docplex 2.16.196. Aqua pushed out a 0.8.1 that includes a fix so it's compatible with the new docplex version. A qiskit 0.23.1 release is pending with that new aqua release (https://github.com/Qiskit/qiskit/pull/1105 ) but is waiting on bugfix releases for terra, aer, and ignis. In the meantime you can either manually upgrade aqua to 0.8.1 or downgrade docplex to the previous release 2.15.194 and either will workaround this issue.

**Comment by feifeng1993** [comment]
> This was a bug in aqua that was introduced with the release yesterday of docplex 2.16.196. Aqua pushed out a 0.8.1 that includes a fix so it's compatible with the new docplex version. A qiskit 0.23.1 release is pending with that new aqua release (#1105 ) but is waiting on bugfix releases for terra, aer, and ignis. In the meantime you can either manually upgrade aqua to 0.8.1 or downgrade docplex to the previous release 2.15.194 and either will workaround this issue.

Hi , I install docplex by pip install docplex==2.15.194
and upgrade aqua by pip install qiskit-aqua==0.8.1 on IBM simulator, 
unfortunately, it still reports the same error.

**Comment by t-imamichi** [comment]
We don't use `one_letter_symbol` in aqua 0.8.1. See https://github.com/Qiskit/qiskit-aqua/blob/0.8.1/qiskit/optimization/problems/quadratic_program.py#L564

**Comment by feifeng1993** [comment]
Thanks, it can run now

**Comment by feifeng1993** [comment]
> We don't use `one_letter_symbol` in aqua 0.8.1. See https://github.com/Qiskit/qiskit-aqua/blob/0.8.1/qiskit/optimization/problems/quadratic_program.py#L564

Thanks for your reply. When I solve a simple obj using admm_optimizer, it can not output right result. the constrain and obj are similar to the demo. normally, the result should be v=0,w=1,u=5. obj=1
![image](https://user-images.githubusercontent.com/59180238/99703388-0d694b80-2a65-11eb-89b8-b19dd1734ec1.png)
![image](https://user-images.githubusercontent.com/59180238/99703840-9a140980-2a65-11eb-93a4-aeea8533cb38.png)

**Comment by t-imamichi** [comment]
Your model is not equivalent to that of the textbook.
![image](https://user-images.githubusercontent.com/31178928/99780273-98c40900-2b59-11eb-84a0-d11944e81378.png)

**Comment by t-imamichi** [comment]
By the way, you need to fill the following information. It is essential to investigate the details. Please do not ignore our issue template.

```
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:
```

**Comment by nonhermitian** [comment]
I believe this can be closed, so doing so.
