### ISSUE TITLE
A program is working well on IBM Q. But kernel dead on jupyter notebook

### ISSUE THREAD

**Issue by zhouyf-10** [Qiskit/qiskit-metapackage#1110]
I am running HHL to solve a 4*4 linear problem. It works well in IBM Q. But when I am trying in in local environment using jupyter notebook, always met with kernel dead. Any suggestions to solve this issue? 

Thank you so much!

**Comment by matrixbot123** [comment]
Did you download the jupyter notebook with code to use? Then you might have issues of the dead kernel, Try to make a new notebook and run your program there

**Comment by taalexander** [comment]
What qiskit version, python version, operating system, etc. Any information will help. What is emitted in the terminal window you launched the Jupyter notebook from with `jupyter notebook`?

**Comment by nonhermitian** [comment]
Closing as stale since OP has not responded.
