### ISSUE TITLE
Unable to load images on "more circuit identities" page

### ISSUE THREAD

**Issue by jiteshlalwani** [Qiskit/qiskit-metapackage#1114]
### Found broken image links

**Name of the page:**
more circuit identities

**Link of the page:**
https://qiskit.org/textbook/ch-gates/more-circuit-identities.html

**Current links that need to be changed:**
A doubly controlled version of a gate V:
https://s3.us-south.cloud-object-storage.appdomain.cloud/strapi/693974b222d24dba9111e02ae25e9151iden2.png

A Toffoli:
https://s3.us-south.cloud-object-storage.appdomain.cloud/strapi/b3cbeb9b7d674d60a75bed351e4f2bcbiden3.png

**Comment by SooluThomas** [comment]
Looks like this is an issue in the textbook. Please open this issue in the repository for qiskit-textbook - https://github.com/qiskit-community/qiskit-textbook/issues

**Comment by nonhermitian** [comment]
Closing as the remedy was posted.
