### ISSUE TITLE
"if operator" in Circuit Composer gives wrong measurement state ! 

### ISSUE THREAD

**Issue by patdenim** [Qiskit/qiskit-metapackage#1117]
### Informations

- **Qiskit version**:  0.23.1
- **Python version**:  3.8 
- **Operating system**:  Windows

### What is the current behavior?
The  if operator in the Circuit Composer whose application depends on the value contained in the classical register does not work properly. 

### Steps to reproduce the problem

Using this simple circuit, it seems that the classical register is not updated after the measure of a qubit0. As a result, the conditional operation will never be applied if the condition value is ==1 (and will always be applied for the condition ==0).
If you execute the qasm code in qiskit the result is correct. (state 0), but state 1 is given in IQX 
![image](https://user-images.githubusercontent.com/22474500/99536398-996a6d00-29aa-11eb-98fe-acc96af690cd.png)
the measurement state is 1  
![image](https://user-images.githubusercontent.com/22474500/99537687-485b7880-29ac-11eb-99b3-80c7c4b90624.png)

If you inspect the circuit the measurement probability state is correct. 

![image](https://user-images.githubusercontent.com/22474500/99538908-e69c0e00-29ad-11eb-9011-236db7cf5ef6.png)

 

### What is the expected behavior?
would expect measurement state == 0

**Comment by nonhermitian** [comment]
This is not a Qiskit issue so closing here.  I have reported it to the compser team.

**Comment by nonhermitian** [comment]
As a general rule there is no single statevector as output from a probabilistic measurement so having a single statevector histogram does not make a lot of sense.  That being said, how to best handle this when there are measurement, resets, and conditionals is currently being worked on.
