### ISSUE TITLE
Basis gates in _parse_transpile_args() function in the transpile.py file are not iterable as required by `zip`

### ISSUE THREAD

**Issue by ntwalibas** [Qiskit/qiskit-metapackage#1119]
### Informations

- **Qiskit version**: `{'qiskit-terra': '0.16.1', 'qiskit-aer': '0.7.1', 'qiskit-ignis': '0.5.1', 'qiskit-ibmq-provider': '0.11.1', 'qiskit-aqua': '0.8.1', 'qiskit': '0.23.1'}`
- **Python version**: `3.7.9`
- **Operating system**: `MacOS Catalina 10.15.7`

### What is the current behavior?
Running a simple circuit using, say the state vector simulator, results in an exception stating: `zip argument #1 must support iteration`.

The traceback is:
```
Traceback (most recent call last):
  File "simulator.py", line 114, in <module>
    result = execute(qc, backend, 100).result()
  File "/Users/ntwalibas/miniconda3/envs/tests/lib/python3.7/site-packages/qiskit/execute.py", line 259, in execute
    backend=backend)
  File "/Users/ntwalibas/miniconda3/envs/tests/lib/python3.7/site-packages/qiskit/compiler/transpile.py", line 238, in transpile
    callback, output_name)
  File "/Users/ntwalibas/miniconda3/envs/tests/lib/python3.7/site-packages/qiskit/compiler/transpile.py", line 436, in _parse_transpile_args
    output_name, callback, backend_num_qubits, faulty_qubits_map):
TypeError: zip argument #1 must support iteration
```

### Steps to reproduce the problem

Just run the following program:
```
from qiskit import *

if __name__ == "__main__":
    backend = Aer.get_backend('statevector_simulator')
    qc = QuantumCircuit(2, 2)
    qc = QuantumCircuit(2, 2)
    qc.h(0)
    qc.cx(0, 1)
    qc.measure([0,1], [0,1])
    result = execute(qc, backend, 100).result()
    print(result.get_counts(qc))
```

### What is the expected behavior?

The program should not produce any exception and should execute the corresponding quantum program.

### Suggested solutions

Can't think of one at the moment.

**Comment by mtreinish** [comment]
I think this is an issue in your code snippet. The signature for `execute()` https://qiskit.org/documentation/apidoc/execute.html shows the 3 arg is `coupling_map` which expects a list for basis gates. `100` is not a list. I assume that is meant to be a different field like `seed_simulator` or `shots` that takes an `int`. When you set a keyword for the 100 to `shots` or `seed_simulator` for example: `execute(qc, backend, shots=100)` it works as expected.

**Comment by ntwalibas** [comment]
@mtreinish You're right! Looks like the signature changed and I didn't notice that. Thank you!
