### ISSUE TITLE
Add Zenodo for a better way to cite Qiskit  

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1121]
The current way to cite Qiskit is explained [here](https://qiskit.org/documentation/faq.html):

> **Q: How should I cite Qiskit in my research?**
> A: Please cite Qiskit by using the included [BibTeX file](https://raw.githubusercontent.com/Qiskit/qiskit/master/Qiskit.bib).

That means that we need to keep https://github.com/Qiskit/qiskit/blob/master/Qiskit.bib up to date (judging from the `year`, we don't). The bibtex entry points to https://doi.org/10.5281/zenodo.2562110, which is the DOI for the current "last version". Because Zenodo was removed, currently points to Qiskit 0.7.2 (Jan 2019).

I suggest to:
 - Update the FAQ:
   -  Point to the "last version" DOI in Zenodo
   - Explain how to export the Zenodo entry into a BibTeX
   - Suggest to add your related code to the [Qiskit community in Zenodo](https://zenodo.org/communities/qiskit/ ) currently curated by @cbjuan under `qiskit@qiskit.org`
 - Allow Zenodo to track the Qiskit releases. This was possible but, at some point in 2019, Zenodo permission got dropped.
 - Remove  https://github.com/Qiskit/qiskit/blob/master/Qiskit.bib
 - Add the Zenodo badge in the [Release Notes](https://qiskit.org/documentation/release_notes.html) (probably, it can be automatized) for each new version.
 - Add the Zenodo badge to "last version" in [Qiskit REAME.md](https://github.com/Qiskit/qiskit/blob/master/README.md)

**Comment by cbjuan** [comment]
After some research, I found the following:

- The item we created as the basis citation to ack every author is under this Zenodo record https://doi.org/10.5281/zenodo.2562110 (which is the one you pointed, Luciano)
- Apart from it, another Zenodo record https://doi.org/10.5281/zenodo.2573505 is the one that is tracking every Qiskit new version (and it's not under Qiskit Community in Zenodo). This one is tracking automatically the authors who contributed code to the last (or X last) version(s), and not those who contributed _at any time_.

So, probably, the fairest way of citing the software would be to cite the version used for the research. That would introduce a big change in terms of:
- Authors will change depending on the version used (not sure how it affects our already messed records in G Scholar and other databases).
- The title of the software package is not the same as the people are using right now. It can be changed to match the current one that everyone is using. Yet, I'm not sure whether we will need to change it manually for every new release.

We need to address those changes and decide how to proceed. Thoughts?


Extra ball: It seems that Zenodo is also tracking code from [Qiskit/openqasm](https://doi.org/10.5281/zenodo.4266607) and [Qiskit/qiskit-terra](https://doi.org/10.5281/zenodo.2583252) repos. Again, those records are not under the Qiskit community in Zenodo.

**Comment by 1ucian0** [comment]
The full authorship list is probably fixable via https://developers.zenodo.org/ REST API as part of the release workflow.

**Comment by prasanthcakewalk** [comment]
Many journals don't allow a long list of authors. Is there a recommended way to cite qiskit in these situations? Maybe acknowledge "The Qiskit Community" as the author of the package?

**Comment by marcolincs** [comment]
We need help setting up Zenodo/DOI for the new repo qiskit-metal. Who would be the right person?

I do not seem to be able to do it as a qiskit-metal admin, because it appears I would need to be qiskit github org admin to authorize third-party OAuth.

Also I am not familiar with how and if to make qiskit-metal appear as part of the Qiskit community in Zenodo. So it would be great to understand how/if to do that.
(Note: would need help this week if possible)

**Comment by cbjuan** [comment]
@marcolincs Probably I'm the right one to help here. I configured the Zenodo record for Qiskit in the past. We can work together in setting it up and review the different options.

**Comment by jakelishman** [comment]
The Zenodo link the BibTeX file and the README are both up-to-date and point to either the DOI doi.org/10.5281/zenodo.2573505, or the track-latest Zenodo link that resolves to, so I'll mark this as completed.  The other parts of the issue are more related to #934 and #1693.
