### ISSUE TITLE
Translations for Qiskit Docs are not viewable

### ISSUE THREAD

**Issue by veenaiyuri** [Qiskit/qiskit-metapackage#1124]
# Information
    Qiskit 0.23.1 documentation
    Python version: NA
    Web Browser: Firefox 83.0(64-bit)

# What is the current behavior?

The language does not switch from English to another language that is currently available such as German, Korean and Japanese.

# Steps to reproduce the problem

Choose  https://qiskit.org/documentation/
Then, go to the lower right corner where the language choices are and click you are viewing lang: English
The choice for other languages (German, Japanese and Korean) does not appear.
![image](https://user-images.githubusercontent.com/24409087/100213854-83cce880-2f52-11eb-8e83-f04ff247e0dd.png)

**Comment by SooluThomas** [comment]
This should be fixed by #1127 and https://github.com/Qiskit/qiskit_sphinx_theme/pull/17
