### ISSUE TITLE
Add an example of extracting circuit for the Grover class.

### ISSUE THREAD

**Issue by wmurphy-collabstar** [Qiskit/qiskit-metapackage#1130]
I would like to add content to the page describing the [Grover class](https://qiskit.org/documentation/stubs/qiskit.aqua.algorithms.Grover.html?highlight=grover#qiskit.aqua.algorithms.Grover) in the Qiskit documentation. Specifically I'd like to add code examples, specifically of extracting the Grover search algorithm as a Quantum circuit. I think other code examples showing how to use the Grover class in Qiskit Aqua would be helpful. I'm very open to other ideas or criticisms also.

**Comment by woodsp-ibm** [comment]
The page, in the API documentation you refer to, is automatically generated from the docstring content in the Python source code of the class. Hence any change to that page means a change to the source code.

Now there have been a couple of tutorials here on Grover that were recently added - have you seen these? https://qiskit.org/documentation/tutorials/algorithms/07_grover.html and https://qiskit.org/documentation/tutorials/algorithms/08_grover_examples.html

**Comment by wmurphy-collabstar** [comment]
Hello, I'm sorry I didn't respond earlier! These look like good tutorials, thank you for the reference! I guess my question is, why are there code snippets for the Grover operator class and not for the Grover class, and is it purposefully that way?

**Comment by woodsp-ibm** [comment]
For the algorithms the tendency has been to keep examples as part of tutorials. Often the examples, for the complete algorithm (i.e. Grover class), are more extensive to setup and take time to run. Having them in the code as docstrings, and not being able to quickly run them to verify them can lead to them becoming invalid if care is not taken.

**Comment by nonhermitian** [comment]
Closing as answered.
