### ISSUE TITLE
Broken Link in 05_getting_started_with_pulse.ipynb

### ISSUE THREAD

**Issue by AlexMiessen** [Qiskit/qiskit-metapackage#1133]
Hi, there is a broken link in the tutorial `05_getting_started_with_pulse.ipynb`
https://qiskit.org/documentation/tutorials/circuits_advanced/05_getting_started_with_pulse.html?highlight=openpulse

The last word of the section "Build Instructions" links to a tutorial `5_gathering_system_information.ipynb` and gives "404 page not found".
https://qiskit.org/documentation/tutorials/circuits_advanced/5_gathering_system_information.ipynb

**Comment by divshacker** [comment]
Not only that is not working but last line  in the section "Execute" that is " Next, we will cover in detail the **different instructions which can be used in Pulse programs.**" is not working, showing same error.
https://qiskit.org/documentation/tutorials/circuits_advanced/2_building_pulse_instructions.ipynb

**Comment by taalexander** [comment]
This is likely a result of tutorials being moved around and references not being properly updated. Please see all tutorials here https://github.com/Qiskit/qiskit-tutorials/tree/master/tutorials/circuits_advanced.

**Comment by divshacker** [comment]
Yup that's true  . I have updated some links and created a pr in qiskit-tutorials

**Comment by SooluThomas** [comment]
The PR https://github.com/Qiskit/qiskit-tutorials/pull/1102 should probably have fixed this issue. Please reopen if the issue still persists.
