### ISSUE TITLE
Most of tutorial/algorithms .ipynb files are not found on IBM Quantum Experience (404 : Not Found)

### ISSUE THREAD

**Issue by ibmamnt** [Qiskit/qiskit-metapackage#1134]
## Most of tutorial/algorithms .ipynb files are not found (404 : Not Found)

For example, the following file is not found.
https://quantum-computing.ibm.com/jupyter/tutorial/algorithms/02_vqe_convergence.ipynb

**Comment by divshacker** [comment]
I think this is because  .ipynb files which are not found are not there in IBM quantum Experience and it will be uploaded . In mean time one can use github for accessing the files as they are all available on github. 
https://github.com/Qiskit/qiskit-tutorials/tree/master/tutorials

**Comment by nonhermitian** [comment]
The example the OP highlighted is working for me, so closing as fixed. Feel free to reopen if this is not the case.
