### ISSUE TITLE
ModuleNotFoundError: No module named 'qiskit.extensions.standard'

### ISSUE THREAD

**Issue by sassan72** [Qiskit/qiskit-metapackage#1135]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

- What is the current text that needs to be fixed or removed? (You can copy and paste)

- What should the documentation say instead?

- Are there other related issues or pull requests about this bug?

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

- What content needs to be updated or replaced? (You can copy and paste)

- What new content needs to be added?

**Comment by sassan72** [comment]
i encountered this issue:
ModuleNotFoundError: No module named 'qiskit.extensions.standard'

**Comment by divshacker** [comment]
What is the problem can you please link the file.

**Comment by sassan72** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-ea56af52fe80> in <module>
      8 
      9 from dc_qiskit_qml.feature_maps import NormedAmplitudeEncoding
---> 10 from dc_qiskit_qml.distance_based.hadamard import QmlHadamardNeighborClassifier
     11 from dc_qiskit_qml.distance_based.hadamard.state import QmlGenericStateCircuitBuilder
     12 from dc_qiskit_qml.distance_based.hadamard.state.sparsevector import MöttönenStatePreparation

~/anaconda3/lib/python3.7/site-packages/dc_qiskit_qml/distance_based/hadamard/__init__.py in <module>
     15 # limitations under the License.
     16 
---> 17 from ._QmlHadamardNeighborClassifier import QmlHadamardNeighborClassifier
     18 

~/anaconda3/lib/python3.7/site-packages/dc_qiskit_qml/distance_based/hadamard/_QmlHadamardNeighborClassifier.py in <module>
     60 from sklearn.neighbors.base import SupervisedIntegerMixin
     61 
---> 62 from .state import QmlStateCircuitBuilder
     63 from ...feature_maps import FeatureMap
     64 

~/anaconda3/lib/python3.7/site-packages/dc_qiskit_qml/distance_based/hadamard/state/__init__.py in <module>
     17 from ._QmlGenericStateCircuitBuilder import QmlGenericStateCircuitBuilder
     18 from ._QmlStateCircuitBuilder import QmlStateCircuitBuilder
---> 19 from ._QmlBinaryDataStateCircuitBuilder import QmlBinaryDataStateCircuitBuilder

~/anaconda3/lib/python3.7/site-packages/dc_qiskit_qml/distance_based/hadamard/state/_QmlBinaryDataStateCircuitBuilder.py in <module>
     41 from qiskit.converters import circuit_to_dag, dag_to_circuit
     42 from qiskit.dagcircuit import DAGNode
---> 43 from qiskit.extensions.standard.h import h
     44 from scipy import sparse
     45 

ModuleNotFoundError: No module named 'qiskit.extensions.standard'

**Comment by sassan72** [comment]
here is the problem 
from qiskit.extensions.standard.h import h

**Comment by kdk** [comment]
`qiskit.extensions.standard` was deprecated in Qiskit 0.19.0 and recently removed in Qiskit 0.23.0 in favor of `qiskit.circuit.library.standard_gates` ( see https://qiskit.org/documentation/release_notes.html ). You can either use a qiskit version <0.23.0 or update the import locations in dc_qiskit_qml.
