### ISSUE TITLE
Update the documentation about the supported python versions

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-metapackage#1142]
## Does existing documentation need to be updated with new content?

Some people are having trouble installing qiskit after following the recommended default installation at https://github.com/Qiskit/qiskit/blob/master/docs/install.rst. I am aware that it is due to the command: `conda create -n name_of_my_env python=3` which installs the latest version of python 3.9 not yet supported by qiskit, but many issues have been reported on slack, stack... even if the documentation mentions to check the metapackage. I think it is better to specify directly which python versions are supported by qiskit on the documentation page and also add a comment saying that the conda command installs the latest version of python.
- Which files need to be updated?

https://github.com/Qiskit/qiskit/blob/master/docs/install.rst

- What content needs to be updated or replaced? (You can copy and paste)
   - Qiskit supports Python 3.6 or later replaced by Qiskit supports Python 3.6, 3.7, 3.8
   - Create a minimal environment with only Python installed in it replaced by Create a minimal environment with only the latest Python 3 version installed

**Comment by vishwas1234567** [comment]
It supports the version of python above Version 3.6
