### ISSUE TITLE
Circuit code gets stripped when running on Qiskit Pulse enabled backend

### ISSUE THREAD

**Issue by ntwalibas** [Qiskit/qiskit-metapackage#1143]
### Informations

- **Qiskit version**: 0.23.1
- **Python version**: 3.7.9
- **Operating system**: MacOS Catalina 10.15.7

### What is the current behavior?
Sending a quantum object that executes on pulse-enabled hardware gets all the relevant information stripped.

Here is the circuit one would prepare:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
creg c[1];
creg meas[1];
x q[0];
barrier q[0];
measure q[0] -> meas[0];
```

Here is the corresponding QObj after assembling the circuit (and before running):
```
Pulse Qobj: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx:
Config: {'init_qubits': True,
 'meas_level': 2,
 'meas_lo_freq': [7.284054663,
                  7.385438514,
                  7.32318003,
                  7.230756417,
                  7.280310863,
                  7.146993373,
                  7.400652534],
 'meas_return': 'avg',
 'memory': False,
 'memory_slot_size': 100,
 'memory_slots': 7,
 'parametric_pulses': ['gaussian', 'gaussian_square', 'drag', 'constant'],
 'pulse_library': [],
 'qubit_lo_freq': [4.8220691969340805,
                   4.75994700374019,
                   4.907311555951348,
                   4.878962331604751,
                   4.870904757614711,
                   4.963969787916278,
                   5.177005068926206],
 'rep_delay': 250.0,
 'rep_time': 1000,
 'shots': 1024}
Header: {'backend_name': 'ibmq_casablanca', 'backend_version': '1.1.5'}
Experiments:
Pulse Experiment:
Header:
{'memory_slots': 7, 'name': 'circuit7'}
Config:
{}
        Instruction: parametric_pulse
                t0: 0
                ch: d0
                pulse_shape: drag
                parameters: {'duration': 160, 'amp': (0.1343577470984396+0j), 'sigma': 40, 'beta': -0.33448266317555875}
        Instruction: parametric_pulse
                t0: 160
                ch: m0
                pulse_shape: gaussian_square
                parameters: {'duration': 22400, 'amp': (0.09236770009241822-0.004945500949053017j), 'sigma': 64, 'width': 22144}
        Instruction: acquire
                t0: 160
                duration: 24080
                qubits: [0, 1, 2, 3, 4, 5, 6]
                memory_slot: [0, 1, 2, 3, 4, 5, 6]
```

But here is the actual circuit that gets executed on the hardware:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
creg c0[7];
barrier q[0], q[1], q[2], q[3], q[4], q[5], q[6];
measure q[0] -> c0[0];
measure q[1] -> c0[1];
measure q[2] -> c0[2];
measure q[3] -> c0[3];
measure q[4] -> c0[4];
measure q[5] -> c0[5];
measure q[6] -> c0[6];
```

As one can see above, the <strike>CNOT</strike> NOT instruction got stripped and all qubits got measured.

### Steps to reproduce the problem

1. Prepare the circuit:

```Python
from qiskit import *

qc = QuantumCircuit(1)
qc.x(0)
qc.measure_all()

IBMQ.delete_account()
IBMQ.save_account("API-KEY-HERE", overwrite = True)
IBMQ.load_account()

provider = IBMQ.get_provider(
    hub = "ibm-q-xxxxx",
    group = "xxxxxx",
    project = "openpulse",
)
backend = provider.get_backend(device_name)
instance_map = backend.defaults().instruction_schedule_map
basis_gates =  backend.configuration().basis_gates
measurement_map = backend.configuration().meas_map
measurement_level = 2
optimization_level = 0
n_samples = 1024

circuits = [qc]
transpiled_circuits = transpile(
    circuits,
    backend = backend,
    basis_gates = basis_gates,
    optimization_level = optimization_level
)

schedules = schedule(
    transpiled_circuits,
    backend = backend,
    inst_map = instance_map,
    meas_map = measurement_map
)

qobjects = assemble(
    schedules,
    backend = backend,
    meas_level = measurement_level,
    shots = n_samples
)

if not isinstance(qobjects, list):
    qobjects = [qobjects]

jobs = []
for qobject in qobjects:
    job = backend.run(qobject)
    jobs.append(job)

# Get results from jobs
counts = []
for job in jobs:
    result = job.result(timeout = 3600)
    counts.append(result.get_counts())

return counts
```

2. Run the code above then look into the IBMQ interface for the particular job being run.
Then look at the circuit that's actually being executed.

### What is the expected behavior?
The circuit that was sent is the one that gets executed.
Not one where all the relevant info is stripped.

### Suggested solutions
None.

**Comment by taalexander** [comment]
Circuit calibrations resolve, are available in Qiskit and will be released on backends soon https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit.add_calibration.

**Comment by ntwalibas** [comment]
@taalexander I'm not sure I follow. In the example above, I'm not trying to add a new gate definition given a custom schedule. But I may be missing something. Can you elaborate on your reply?

**Comment by taalexander** [comment]
The circuit information is not available as you are sending a lower-level "pulse" representation to the backend, the notion of circuits has disappeared. It is now possible to represent circuits with calibrations for gates, as demonstrated by `add_calibration`. In this format, the circuit will be communicated to the backend along with the tied gate calibrations.

**Comment by taalexander** [comment]
If you don't want any pulse at all don't use the scheduler, as demonstrated below:
```python
from qiskit import *

qc = QuantumCircuit(1)
qc.x(0)
qc.measure_all()

IBMQ.delete_account()
IBMQ.save_account("API-KEY-HERE", overwrite = True)
IBMQ.load_account()

provider = IBMQ.get_provider(
    hub = "ibm-q-xxxxx",
    group = "xxxxxx",
    project = "openpulse",
)
backend = provider.get_backend(device_name)
instance_map = backend.defaults().instruction_schedule_map
basis_gates =  backend.configuration().basis_gates
measurement_map = backend.configuration().meas_map
measurement_level = 2
optimization_level = 0
n_samples = 1024

circuits = [qc]
transpiled_circuits = transpile(
    circuits,
    backend = backend,
    basis_gates = basis_gates,
    optimization_level = optimization_level
)

qobjects = assemble(
    transpiled_circuits,
    backend = backend,
    meas_level = measurement_level,
    shots = n_samples
)

if not isinstance(qobjects, list):
    qobjects = [qobjects]

jobs = []
for qobject in qobjects:
    job = backend.run(qobject)
    jobs.append(job)

# Get results from jobs
counts = []
for job in jobs:
    result = job.result(timeout = 3600)
    counts.append(result.get_counts())

return counts
```

**Comment by ntwalibas** [comment]
@taalexander Ohhh, now I have an idea about what you meant with `add_calibration`, thank you!
So if I understand correctly, in order to get accurate results, we need to add these calibrations manually even for predefined gates?

Because essentially, even after the pulses are sent to the device, all one gets is essentially a more or less measurement of all qubits in their ground state (corresponding exactly to the circuit that shows that no useful computation got done).

**Comment by taalexander** [comment]
It is not necessary to add them if the defaults are fine. They are only useful if you are designing your own custom gates with pulses. Otherwise, you can just use bare circuits and not worry about pulses at all.

**Comment by ntwalibas** [comment]
@taalexander Yeah, that's the problem though: I'm working directly with pulses and the basic test (before sending my own custom pulses) was to run a simple NOT gate on a single qubit and make sure it works (after getting the NOT gate scheduled at the pulse level). Unfortunately, it doesn't!
I expected that, even if working with pulses, predefined gates should work right out of the box but I'm not getting the expected result.

Either I'm doing something wrong or there might be a bug in Qiskit/IBMQ integration.
What do you think?

**Comment by taalexander** [comment]
I now understand the problem. All qubits must be measured with pulse due to the current `meas_map` reported. Please trace over the unused qubits with `https://qiskit.org/documentation/stubs/qiskit.ignis.verification.marginal_counts.html`. See this tutorial for more information https://qiskit.org/documentation/tutorials/circuits_advanced/08_adding_measurements.html. In your initial qasm file there is not a `cx` gate.

**Comment by ntwalibas** [comment]
@taalexander Many thanks, that did the trick! And I appreciate the additional info as well.
