### ISSUE TITLE
Incompatibility with Numpy 1.20.0

### ISSUE THREAD

**Issue by weiT1993** [Qiskit/qiskit-metapackage#1158]
### Informations

- **Qiskit version**: 0.23.4
- **Python version**: 3.8.5
- **Operating system**: MacOS 11.2

### What is the current behavior?
Deprecation warnings for `np.int` and `np.bool`.

### Steps to reproduce the problem
I believe this problem should be fairly easy to reproduce when using Qiskit to simulate circuits. E.g. 
```
qiskit/circuit/register.py:119: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

### Suggested solutions
Update Qiskit backend for Numpy 1.20

**Comment by mtreinish** [comment]
This has already been fixed on the qiskit master branch with https://github.com/Qiskit/qiskit-terra/commit/5f9da19d455306140d91bd42f0c2a1a9ea31a091 which will be included in the next qiskit-terra release. But, until there is a new release the warnings will still be raised. We're not able to do anything with the released versions. You might be able to setup a filter with the `warnings` module to try and suppress the deprecation warnings when you're running with numpy 1.20.0.

**Comment by mtreinish** [comment]
Qiskit 0.23.5 was just released that includes the fix for this. Marking this issue as closed now
