### ISSUE TITLE
Integration with Quirk

### ISSUE THREAD

**Issue by ShreyBiswas** [Qiskit/qiskit-metapackage#1160]
### Suggestion
Is it feasible to integrate Qiskit with [Quirk](https://algassert.com/quirk)? It's used often enough that I feel it could be beneficial. Perhaps someway to import or export circuits?

**Comment by navaneethsdk** [comment]
I am not quite familiar with Quirk but judging by its features I believe IBM Quantum Experience also gives the provision to generate circuits using the "drag and drop" functionality and generate the corresponding code. But if Quirk gives enhanced options to play with the Quantum circuits, it is certainly worth a try.

**Comment by divshacker** [comment]
I agree with @navaneethsdk about the circuit simulator, I think IBM Quantum have a better UI but the Quirk is way more better in terms of no. of gates and features. I think Quirk Features can be brought to IBM Quantum Simulators. That would be better.

**Comment by nonhermitian** [comment]
IBM Quantum already offers the circuit composer online and as a Jupyter widget that can generate Qiskit code. I am not sure what functionality is not covered by this?

**Comment by divshacker** [comment]
> IBM Quantum already offers the circuit composer online and as a Jupyter widget that can generate Qiskit code. I am not sure what functionality is not covered by this?

In Quirk one can directly use many predefined functions like QFT and QFT inverse. There are certainly more number of Gates which are predefined in Quirk than IBM circuit composer. One can get some predefined circuits (which works as a tutorial) for different topics.Of course that can be done with IBM Circuit composer but we don't have any Circuit specific code files for tutorial purposes. I am not here to compare the features between two (Just saying).

**Comment by nonhermitian** [comment]
Well then it seems like there are two possible routes to take. 1) try to integrate Quirk with Qiskit, as the composer already does or 2) add the ability to use a catalog of gates / circuits (like the Qiskit circuit library) into the current composer widget. Regardless of the choice, they are both outside of the core Qiskit mission, but would make for an interesting add-on project.

**Comment by nonhermitian** [comment]
Closing as out of scope for Qiskit proper.  Looking forward to seeing this pop up as an add-on in the future.
