### ISSUE TITLE
Unable to install qiskit in python 3.9.1

### ISSUE THREAD

**Issue by insominiac21** [Qiskit/qiskit-metapackage#1166]
When I wrote 'pip install qiskit' in my visual studio code's terminal; the error popped , "Command errored out with exit status 1"... Which had 70 values:
running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.9
  creating build\lib.win32-3.9\h5py
  copying h5py\h5py_warnings.py -> build\lib.win32-3.9\h5py
  copying h5py\ipy_completer.py -> build\lib.win32-3.9\h5py
  copying h5py\version.py -> build\lib.win32-3.9\h5py
  copying h5py\__init__.py -> build\lib.win32-3.9\h5py
  creating build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\attrs.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\base.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\compat.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\dataset.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\datatype.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\dims.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\files.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\filters.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\group.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\selections.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\selections2.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\vds.py -> build\lib.win32-3.9\h5py\_hl
  copying h5py\_hl\__init__.py -> build\lib.win32-3.9\h5py\_hl
  creating build\lib.win32-3.9\h5py\tests
  copying h5py\tests\common.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\conftest.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_attribute_create.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_attrs.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_attrs_data.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_base.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_big_endian_file.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_completions.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_dataset.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_dataset_getitem.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_dataset_swmr.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_datatype.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_dimension_scales.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_dims_dimensionproxy.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_dtype.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_errors.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_file.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_file2.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_file_image.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_filters.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_group.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_h5.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_h5d_direct_chunk.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_h5f.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_h5p.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_h5pl.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_h5t.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_objects.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_selections.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\test_slicing.py -> build\lib.win32-3.9\h5py\tests
  copying h5py\tests\__init__.py -> build\lib.win32-3.9\h5py\tests
  creating build\lib.win32-3.9\h5py\tests\data_files
  copying h5py\tests\data_files\__init__.py -> build\lib.win32-3.9\h5py\tests\data_files
  creating build\lib.win32-3.9\h5py\tests\test_vds
  copying h5py\tests\test_vds\test_highlevel_vds.py -> build\lib.win32-3.9\h5py\tests\test_vds
  copying h5py\tests\test_vds\test_lowlevel_vds.py -> build\lib.win32-3.9\h5py\tests\test_vds
  copying h5py\tests\test_vds\test_virtual_source.py -> build\lib.win32-3.9\h5py\tests\test_vds
  copying h5py\tests\test_vds\__init__.py -> build\lib.win32-3.9\h5py\tests\test_vds
  copying h5py\tests\data_files\vlen_string_dset.h5 -> build\lib.win32-3.9\h5py\tests\data_files
  copying h5py\tests\data_files\vlen_string_dset_utc.h5 -> build\lib.win32-3.9\h5py\tests\data_files
  copying h5py\tests\data_files\vlen_string_s390x.h5 -> build\lib.win32-3.9\h5py\tests\data_files
  running build_ext
  Loading library to get version: hdf5.dll
  error: Unable to load dependency HDF5, make sure HDF5 is installed properly
  error: Could not find module 'hdf5.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  ----------------------------------------
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py which use PEP 517 and cannot be installed directly

How to resolve this?

**Comment by mtreinish** [comment]
The issue you're facing here is that the h5py dependency doesn't ship precompiled binaries for win32, just 64bit windows: https://pypi.org/project/h5py/#files and h5py is a dependency of qiskit-aqua. What is happening is pip is going to install h5py sees that there are no precompiled binaries available and tries to build it from source, which is failing because you don't have hdf5 installed.

You have 3 options to workaround this:

1. Use a 64bit version of python (which may not be an option if you're running a 32bit version of windows) if you run `pip install qiskit` on a 64bit python version there are precompiled binaries available for h5py and you should have no trouble installing anything.
2. Install hdf5 which will involve building it from source since it doesn't appear that hdf5 ships precompiled win32 binarie (It may not be compatible with 32bit windows). Once you have hdf5 libraries installed in your system you can hopefully build h5py from source.
3. Don't install qiskit-aqua. If you're usage doesn't need qiskit-aqua you can just run `pip install -U qiskit-terra qiskit-aer qiskit-ibmq-provider qiskit-ignis` which will install everything that `pip install -U qiskit` does except for qiskit-aqua which will avoid the h5py dependency.

**Comment by insominiac21** [comment]
I use 32 bit windows, so I will try 3rd option... Thanks for answering

**Comment by insominiac21** [comment]
It worked! thank you for guiding
