### ISSUE TITLE
Difference in the Q Sphere representation of a circuit

### ISSUE THREAD

**Issue by praveentn** [Qiskit/qiskit-metapackage#1188]
## Did you find a doc bug or broken link that needs to be fixed?
Yes

- What is the file name(s) where you found the bug?
https://quantum-computing.ibm.com/composer/docs/iqx/visualizations#q-sphere-view

In this section, there's an image of the q sphere representation of the circuit. If you run the circuit in the Qiskit Composer you get a different q sphere than the one shown in the documentation.

- What is the current text that needs to be fixed or removed? (You can copy and paste)
https://iqx-docs.quantum-computing.ibm.com/_images/q-sphere.png

- What should the documentation say instead?
https://raw.githubusercontent.com/praveentn/ml-repos/master/qsphere.png

- Are there other related issues or pull requests about this bug?

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

- What content needs to be updated or replaced? (You can copy and paste)

- What new content needs to be added?

**Comment by lebinyu** [comment]
I think the current [q-sphere image](https://iqx-docs.quantum-computing.ibm.com/_images/q-sphere.png) in the text is correct. The control-Z gate introduced a phase of pi to state |11>. I guess you mixed the control-Z gate up with the CNOT gate.

**Comment by praveentn** [comment]
> I think the current [q-sphere image](https://iqx-docs.quantum-computing.ibm.com/_images/q-sphere.png) in the text is correct. The control-Z gate introduced a phase of pi to state |11>. I guess you mixed the control-Z gate up with the CNOT gate.

Yes, I thought the gate in the documentation was a Swap gate. It's indeed a CZ gate as you pointed out. Thanks!
