### ISSUE TITLE
Question about making changes to file of Release Notes

### ISSUE THREAD

**Issue by purva-thakre** [Qiskit/qiskit-metapackage#1190]
## Did you find a doc bug or broken link that needs to be fixed?

Yes. 

- What is the file name(s) where you found the bug?
`release_notes.rst` in `docs` folder

- What is the current text that needs to be fixed or removed? (You can copy and paste)
All the column labels of tables need to be edited - either the background color or font color. For example,[ here's a link](https://qiskit.org/documentation/release_notes.html#version-history) to the `Version History Table`. None of the column titles on this page are visible due to incompatible background and font color. 

- What should the documentation say instead?
See above. 

- Are there other related issues or pull requests about this bug?
Not that I know of. I checked for any issues related to `release notes`. 

## Does existing documentation need to be updated with new content?

- Which files need to be updated?
`release_notes.rst` in `docs` folder and `versionutils.py`
- What content needs to be updated or replaced? (You can copy and paste)
Either change font color or make the background lighter for table column labels. 
- What new content needs to be added?
See above. 

I can fix this after I get feedback about which of the above changes is preferred.

**Comment by nonhermitian** [comment]
Thank you for reporting this issue.  This was solved here: https://github.com/Qiskit/qiskit-terra/pull/5865  but since it is in the source code, does not get pushed out until the next release. As such closing this as completed.  Feel free to reopen if it is still an issue in the next Qiskit release.
