### ISSUE TITLE
Broken link in documentation: "several backends"

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit-metapackage#1194]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

As reported in https://github.com/Qiskit/qiskit.org/issues/1575 by https://github.com/MannimMond86, a link in https://qiskit.org/documentation/getting_started.html in the **Step 5: Simulate the Experiment** section is broken.

### Steps to reproduce the problem

1. Go to https://qiskit.org/documentation/getting_started.html 
2. Scroll to the **Step 5: Simulate the Experiment** section
3. Click on the "several backends" link
4. The link is broken

![Screenshot 2021-03-22 at 12 52 35](https://user-images.githubusercontent.com/22047320/111985884-7fce6300-8b0d-11eb-912c-3b3976ebbfc6.png)

### What is the expected behavior?

The link should point to a valid URL.

### Suggested solutions

Adjust or remove the linked URL.

**Comment by divshacker** [comment]
Hey @eddybrando I have tried to fix that problem. Please let me know if any further changes required

**Comment by bopardikarsoham** [comment]
I would like to work on this issue.

**Comment by bopardikarsoham** [comment]
Can I work on it or are you done with it @divshacker

**Comment by divshacker** [comment]
I actually tried to fix that link and I think I fixed it AFAIK. If you want to add something then you are welcome. @bopardikarsoham

**Comment by HuangJunye** [comment]
Close by #1195
