### ISSUE TITLE
make the visualization install option work in the readme update the readme as needed

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#12]
Install with visualization dependencies

There are optional dependencies that are required to use all the visualization functions included in Qiskit. You can install these at the same time by running:

pip install qiskit[visualization]

which will install qiskit and all the visualization dependencies.

see the install https://github.com/Qiskit/qiskit/blob/master/docs/install.rst

**Comment by jaygambetta** [comment]
@mtreinish did you get a chance to look at this.

**Comment by mtreinish** [comment]
Oops, sorry I did mean to leave a comment in here a while ago but forgot. The way I wanted to do this (putting `qiskit-terra['visualization']` in the extras list here to avoid duplicating the list and getting things out of sync) didn't seem to work as I intended. So I'm thinking the only option is to just copy the list from qiskit-terra's setup.py and updating both if we ever need to add a requirement or bump a minimum version.

**Comment by pistoia** [comment]
@mtreinish @manoelmarques, Jay and I discussed the fact that, since the visualization capabilities in Qiskit come with a special installation option, that installation option should also bring the Aqua and Chemistry GUI wizards.  So when installing Qiskit, the Aqua and Chemistry GUI wizards will only be installed if the visualization option is on.

**Comment by derivation** [comment]
@mtreinish I noticed that for qiskit 0.8.0, 

`pip install qiskit[visualization]`

throws the warning message

`qiskit 0.8.0 does not provide the extra 'visualization'`

and installs successfully.

Should the [install doc](https://qiskit.org/documentation/install.html#install) no longer recommend running `pip install qiskit[visualization]` to get the visualization tools?

**Comment by mtreinish** [comment]
Yeah, this is still an open issue. I have been meaning to circle back to this to come up with a fix (I keep getting side tracked on other issues). Until this issue is fixed we should probably update the docs to say `pip install qiskit-terra[visualization]` to install the visualization dependencies.

**Comment by devlwkyan** [comment]
When I run 

```pip install qiskit-terra[visualization]```

 I get the error: 

```no matches found: qiskit-terra[visualization]```

What command should I run, ```pip install qiskit[visualization]``` as it used to be previously?

**Comment by jaygambetta** [comment]
@mtreinish and @nonhermitian can you check on this. I think we close this if it all works.

**Comment by mtreinish** [comment]
`qiskit-terra[visualization]` definitely works fine when I test it locally. Running it in a clean env results in: 
```
MarkupSafe-1.1.1 Send2Trash-1.5.0 backcall-0.1.0 bleach-3.1.0 cycler-0.10.0 decorator-4.4.0 defusedxml-0.6.0 entrypoints-0.3 ipykernel-5.1.2 ipython-7.7.0 ipython-genutils-0.2.0 ipywidgets-7.5.1 jedi-0.15.1 jinja2-2.10.1 jsonschema-2.6.0 jupyter-client-5.3.1 jupyter-core-4.5.0 kiwisolver-1.1.0 marshmallow-2.20.1 marshmallow-polyfield-3.2 matplotlib-3.1.1 mistune-0.8.4 mpmath-1.1.0 nbconvert-5.6.0 nbformat-4.4.0 networkx-2.3 notebook-6.0.0 numpy-1.17.0 nxpd-0.2.0 pandocfilters-1.4.2 parso-0.5.1 pexpect-4.7.0 pickleshare-0.7.5 pillow-6.1.0 ply-3.11 prometheus-client-0.7.1 prompt-toolkit-2.0.9 psutil-5.6.3 ptyprocess-0.6.0 pydot-1.4.1 pygments-2.4.2 pylatexenc-1.5 pyparsing-2.4.2 python-dateutil-2.8.0 pyzmq-18.1.0 qiskit-terra-0.8.2 scipy-1.3.1 six-1.12.0 sympy-1.4 terminado-0.8.2 testpath-0.4.2 tornado-6.0.3 traitlets-4.3.2 wcwidth-0.1.7 webencodings-0.5.1 widgetsnbextension-3.5.1
```
being installed. Which includes terra, all dependencies, and all the visualization dependencies. The issue being reported by @devlwkyan looks like an issue with their local shell. Some shells (mostly zsh in my experience) treats `[ ]` as a regex by default. So when you type `qiskit-terra[visualization]` it tries to regex match and there isn't anything so it errors. You can normally fix this by escaping or quoting the square brackets so your shell doesn't interpret the square brackets as a regex.

That being said I'm not sure I want to close this. I'd like to add a visualization extras option to the meta package. That way people don't need to run 2 commands to get qiskit and visualization dependencies. When I've looked at it before there were issues with my approach to trying to just reuse terra's extras directly. I'll play with it some more this afternoon and come up with something (in the worst case I'll just duplicate the list from terra).

**Comment by mtreinish** [comment]
So this took me way longer to circle back to than I had originally intended. I can't find a way to add a visualization target on the metapackage that just pulls in `qiskit-terra[visualzation]`. The only option would be to copy https://github.com/Qiskit/qiskit-terra/blob/master/setup.py#L112-L115 into the meta package's `setup.py`.
