### ISSUE TITLE
Docs jobs failing due to tweedledum

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#1202]
Build shows version 1.0.0 installed but raises exception in docs:
 
Cell raised uncaught exception:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-66ca9dc5364d> in <module>
      2 
      3 @classical_function
----> 4 def grover_oracle(a: Int1, b: Int1, c: Int1, d: Int1) -> Int1:
      5     return (not a and b and not c and d)
      6 

~/work/qiskit/qiskit/.tox/docs/lib/python3.7/site-packages/qiskit/circuit/classicalfunction/__init__.py in classical_function(func)
    115 
    116     source = inspect.getsource(func).strip()
--> 117     return ClassicalFunction(source, name=func.__name__)

~/work/qiskit/qiskit/.tox/docs/lib/python3.7/site-packages/qiskit/circuit/classicalfunction/classicalfunction.py in __init__(self, source, name)
     44             raise QiskitError('ClassicalFunction needs a source code as a string.')
     45         if not HAS_TWEEDLEDUM:
---> 46             raise ImportError("To use the classicalfunction compiler, tweedledum "
     47                               "must be installed. To install tweedledum run "
     48                               '"pip install tweedledum".')

ImportError: To use the classicalfunction compiler, tweedledum must be installed. To install tweedledum run "pip install tweedledum".

**Comment by mtreinish** [comment]
I believe this is caused by a recent release of tweedledum (1.0.0) which is incompatible with the classical function compiler in terra 0.16.x. The next terra release should fix compatibility (and bump the minimum requirement version to 1.0.0). In the meantime we can should cap the tweedledum requirement to `< 1.0.0` until terra is released.
