### ISSUE TITLE
Broken link in qiskit.org

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-metapackage#1206]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

#1200 removes install.html and `Get Started` in the [qiskit.org](https://qiskit.org/) does not work.

**Comment by divshacker** [comment]
Hey @nonhermitian  @mtreinish @ikkoham  I have tried to fix that. Let me know if any mistake is there

**Comment by nonhermitian** [comment]
Works fine for me:

<img width="942" alt="Screen Shot 2021-04-02 at 02 10 04" src="https://user-images.githubusercontent.com/1249193/113386567-8c965680-9358-11eb-93c3-9d091466aa30.png">

**Comment by nonhermitian** [comment]
When we change things substantially, sometimes it is good to clear the cached version.

**Comment by divshacker** [comment]
![Screenshot from 2021-04-02 11-46-59](https://user-images.githubusercontent.com/55018955/113387136-53d29d80-93a9-11eb-9dfd-47bf70904317.png)
The "get started" link is not working in qiskit.org
@nonhermitian

**Comment by nonhermitian** [comment]
Ahh, that is not us.  That should go here: https://github.com/Qiskit/qiskit.org

**Comment by divshacker** [comment]
Yup that's what I have done above.

**Comment by nonhermitian** [comment]
Closing here as there is a PR in the right location to fix this: https://github.com/Qiskit/qiskit.org/pull/1639
