### ISSUE TITLE
Include small example codes for various functions and classes

### ISSUE THREAD

**Issue by paniash** [Qiskit/qiskit-metapackage#1214]
Hi!

I was wondering if it might be a good idea to include minor example codes for various classes and functions in terra (and other elements). For example, in the [schedule_circuit](https://qiskit.org/documentation/stubs/qiskit.scheduler.schedule_circuit.html#module-qiskit.scheduler.schedule_circuit) docs, it is not immediately apparent to me what `schedule_config` is. Including an example code would help the user get a fair idea of the usage of the function.

I feel this would make the docs more accessible to the general audience as someone who doesn't have much familiarity with programming.

**Comment by nonhermitian** [comment]
In general we do like to have such examples.  e.g. see:

https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit
https://qiskit.org/documentation/stubs/qiskit.visualization.plot_histogram.html#qiskit.visualization.plot_histogram

however it is up to the author of the code in question to add them as it is not a strict requirement for accepting a PR.

**Comment by paniash** [comment]
@nonhermitian Thanks a lot! Is it alright to make PRs to include examples for such functions as I described in the OP?

**Comment by nonhermitian** [comment]
Sure, go for it!
