### ISSUE TITLE
Can't navigate linked tutorials in IBM quantum lab

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/qiskit-metapackage#1218]
### What is the current behavior?
Following what has been reported on slack and in #1215 , documentation seems a bit broken right now.
A work around to access the notebooks is to navigate in ibmqx to the tic-tac-toe menu > quantum lab.
There are folders for the tutorials and textbook (thanks!). But it seems that any links these might have will not be able to reach its destination. Example: [qiskit-tutorials/start_here.ipynb](https://quantum-computing.ibm.com/lab/files/qiskit-tutorials/start_here.ipynb)

**Comment by nonhermitian** [comment]
This is now resolved.  Thanks for reporting.

**Comment by omarcostahamido** [comment]
thank you, for fixing it 😄
