### ISSUE TITLE
GitHub inside Quantum Lab

### ISSUE THREAD

**Issue by pawmasz** [Qiskit/qiskit-metapackage#1231]
### What is the expected behavior?
It would be nice to have GitHub directly inside Quantum Lab. With version control, the Quantum Lab would be easiest way to setup, write code, and share work. Right now the last thing missing from that list is the **share** functionality.

If this is not the place for this request, please refer me to correct one.

**Comment by kdk** [comment]
Hi @pawmasz , I believe the best place to request features for the Quantum Lab is under the "Support -> Feedback -> Missing Features" form directly from the support icon in the quantum lab.

**Comment by pawmasz** [comment]
@kdk thanks! I've sent it. I'll close this issue 😉
