### ISSUE TITLE
Shor's algorithm => is there an error in def c_mod15(a, power) ?

### ISSUE THREAD

**Issue by CRWie** [Qiskit/qiskit-metapackage#1233]
## Did you find a doc bug or broken link that needs to be fixed?  

- What is the file name(s) where you found the bug?
https://qiskit.org/textbook/ch-algorithms/shor.html
- What is the current text that needs to be fixed or removed? (You can copy and paste)
if a not in [2,7,8,11,13]:
raise ValueError("'a' must be 2,7,8,11 or 13")
U = QuantumCircuit(4)
for iteration in range(power):
if a in [2,13]:
U.swap(0,1)
U.swap(1,2)
U.swap(2,3)
if a in [7,8]:
U.swap(2,3)
U.swap(1,2)
U.swap(0,1)
if a == 11:
U.swap(1,3)
U.swap(0,2)
if a in [7,11,13]:
for q in range(4):
U.x(q)
U = U.to_gate()
U.name = "%i^%i mod 15" % (a, power)
c_U = U.control()
return c_U
- What should the documentation say instead?
if a not in [2,7,8,11,13]:
raise ValueError("'a' must be 2,7,8,11 or 13")
U = QuantumCircuit(4)
for iteration in range(power):
if a in [2,13]: # for y0=LSB and y3=MSB in the input, y3y2y1y0 => y2y1y0y3
U.swap(2,3)
U.swap(1,2)
U.swap(0,1)
if a in [7,8]: # y3y2y1y0 => y0y3y2y1
U.swap(0,1)
U.swap(1,2)
U.swap(2,3)
if a == 11:
U.swap(1,3)
U.swap(0,2)
if a in [7,11,13]:
for q in range(4):
U.x(q)
U = U.to_gate()
U.name = "%i^%i mod 15" % (a, power)
c_U = U.control()
return c_U
- Are there other related issues or pull requests about this bug?

## Does existing documentation need to be updated with new content?
Yes, but after making sure that the suggested correction is correct first.
- Which files need to be updated?
https://qiskit.org/textbook/ch-algorithms/shor.html
- What content needs to be updated or replaced? (You can copy and paste)
def c_amod15(a, power):
    """Controlled multiplication by a mod 15"""
    if a not in [2,7,8,11,13]:
        raise ValueError("'a' must be 2,7,8,11 or 13")
    U = QuantumCircuit(4)        
    for iteration in range(power):
        if a in [2,13]:
            U.swap(0,1)
            U.swap(1,2)
            U.swap(2,3)
        if a in [7,8]:
            U.swap(2,3)
            U.swap(1,2)
            U.swap(0,1)
        if a == 11:
            U.swap(1,3)
            U.swap(0,2)
        if a in [7,11,13]:
            for q in range(4):
                U.x(q)
    U = U.to_gate()
    U.name = "%i^%i mod 15" % (a, power)
    c_U = U.control()
    return c_U
- What new content needs to be added?

**Comment by kdk** [comment]
Hi @CRWie , thanks for reporting this. Can you re-open this under https://github.com/qiskit-community/qiskit-textbook ?

**Comment by jakelishman** [comment]
Closing now as stale - if the problem still exists, please feel free to re-open under the relevant textbook repository.
