### ISSUE TITLE
Creating and managing credentials section is missing from the Installation guide

### ISSUE THREAD

**Issue by veenaiyuri** [Qiskit/qiskit-metapackage#1237]
Source file:
https://github.com/Qiskit/qiskit/blob/master/docs/getting_started.rst

Issue:
The section titled 'Access IBM Quantum Systems', which used to outline steps for creating your IBM Quantum account and how to manage multiple IBM Quantum credentials seems to be missing.

Proposed solution:
Reinstate some of the [description](https://github.com/Qiskit/qiskit/commit/568c237847c559f7e93d786abdca58b785d10cf7#diff-379774f5c6e537f2001c951863c6ac577b56eb5c6e61cc581dce95143760ff36) from the old install.rst to the 'Start locally' section in getting_started.rst

**Comment by nonhermitian** [comment]
Yes, that info was removed, and was destined to be in the new provider docs. However, that got blocked on other work.

**Comment by veenaiyuri** [comment]
Thanks @nonhermitian for the clarification. Do you know when this info will be in the new provider docs?

**Comment by jakelishman** [comment]
The new provider is called IBM Provider, and its tutorial about account management is now here: https://qiskit.org/documentation/partners/qiskit_ibm_provider/tutorials/1_the_ibm_quantum_account.html.  I'll close this issue now, but if there are further problems, please feel free to re-open on https://github.com/Qiskit/qiskit-ibm-provider.
