### ISSUE TITLE
Does the class InnerProduct actually calculates the inner product between general quantum states?

### ISSUE THREAD

**Issue by cwhsing** [Qiskit/qiskit-metapackage#1242]
I've been searching for quantum algorithms for calculating the inner product between two multiple-qubit general quantum states (which are already processed by preceding quantum gates and have superposition and entanglement) and found this function:

https://qiskit.org/documentation/stubs/qiskit.circuit.library.InnerProduct.html

To my understanding, the circuit used seems to only work for quantum states as simple as computational basis product states, but not general quantum states. Is it really the case?

If I'd like to use a quantum circuit to calculate the inner product of two multiple-qubit general quantum states, how would you suggest to design the circuit?

**Comment by MR-Asif12116135** [comment]
.....

**Comment by ajavadia** [comment]
Yes you are right. This is a phase oracle, it is intended to work on computational states (well +1/-1 superpositions of them as well). See my answer in https://github.com/Qiskit/qiskit-terra/issues/5649.

I think what you are looking for is the SWAP test https://en.wikipedia.org/wiki/Swap_test
