### ISSUE TITLE
Minor typo in qc_intro.rst

### ISSUE THREAD

**Issue by td2014** [Qiskit/qiskit-metapackage#1254]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

qc_intro.rst 

(As rendered on page/section https://qiskit.org/documentation/qc_intro.html#quantum-circuits).
Typo located in fourth paragraph. Please see below for specific location.

- What is the current text that needs to be fixed or removed? (You can copy and paste)

The word "to" is reversed ("ot") in the last sentence of the paragraph below. I have indicated the location in bold below. Please check the second word from the end of the paragraph.

> Quantum gates form the primitive operations on quantum data. Quantum gates represent information preserving, reversible transformations on the quantum data stored in qubits. These “unitary” transformations represent the quantum mechanical core of a quantum circuit. Some gates such as 𝑋 (also written as ⊕) and 𝐶𝑋 have classical analogs such as bit-flip and 𝑋𝑂𝑅 operations, respectively, while others do not. The Hadamand (𝐻) gate, along with the parameterized rotates 𝑟𝑋(𝜃) and 𝑟𝑌(𝜃), generate superposition states, while gates such as 𝑍, 𝑟𝑍(𝜃), 𝑆, and 𝑇 impart phases that can be used for interference. Two-qubit gates like the 𝐶𝑋 gate are used to generate entanglement between pairs of qubits, or to “kick” the phase from one qubit **ot** another.

- What should the documentation say instead?

> ...the phase from one qubit to another.

- Are there other related issues or pull requests about this bug?

I don't believe so.

**Comment by divshacker** [comment]
Hey @td2014 I have fixed the issue and made a PR. Please check that and let me know. 
Thank you 
@mtreinish

**Comment by td2014** [comment]
@divshacker The changes made for PR #1255 look good to me.  Thank you.
