### ISSUE TITLE
Subprojects referring main/Qiskit.bib

### ISSUE THREAD

**Issue by horvatha** [Qiskit/qiskit-metapackage#1264]
### What is the current behavior?

The  qiskit-machine-learning, qiskit-nature, qiskit-finance and qiskit-optimization repos refer to the file https://github.com/Qiskit/qiskit/blob/main/Qiskit.bib in their `README.md` but there is no main branch (yet?).

### Suggested solutions

Create that branch/file or change the references to `master/Qiskit.bib`

**Comment by divshacker** [comment]
Hey @horvatha  thanks for reporting this. I think changing reference to `master/Qiskit.bib` will solve this issue. May I work on this ?

**Comment by horvatha** [comment]
I just realized, that github (or git?) also moved to neutral words instead of master, slave... so the new projects have main as their base branch. I thought that there is a plan in this project too to follow the new convention.
I heard that some projects uses some git hooks to change those words in the projects.

**Comment by divshacker** [comment]
Don't know why is is closed automatically XD
