### ISSUE TITLE
WSL Python 3.9.5 support / documentation

### ISSUE THREAD

**Issue by 2phx** [Qiskit/qiskit-metapackage#1274]
Hello, installing qiskit on WSL win10 Ubuntu 20.04.2 LTS. 

Following this page https://qiskit.org/documentation/getting_started.html

`conda create -n ENV_NAME python=3`

creates 3.9.5 python env and qiskit won't install via: 

`pip install qiskit`
---

Solution: `conda create -n ENV_NAME python=3.8`

**Comment by shil-m** [comment]
HI @2phx, can I do this?

**Comment by 2phx** [comment]
> HI @2phx, can I do this?

Run qiskit on WSL? Yea of course. Works great.

**Comment by shil-m** [comment]
No as in can I update the documentation so that it supports installation on WSL win10 Ubuntu 20.04.2 LTS?

> > HI @2phx, can I do this?
> 
> Run qiskit on WSL? Yea of course. Works great.

**Comment by 2phx** [comment]
> No as in can I update the documentation so that it supports installation on WSL win10 Ubuntu 20.04.2 LTS?
> 
> > > HI @2phx, can I do this?
> > 
> > 
> > Run qiskit on WSL? Yea of course. Works great.

Sure go ahead if you want :)

**Comment by jakelishman** [comment]
I'll close this issue as stale now.  If there are further problems with installing Qiskit, please feel free to re-open an issue, ideally including the build log showing the failure.
