### ISSUE TITLE
CSwap gate documentation says it is a Controlled-X gate

### ISSUE THREAD

**Issue by epelaaez** [Qiskit/qiskit-metapackage#1278]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

In `qiskit.circuit.library.standard_gates.swap`, in the `CSwapGate` class. Which is also found on the documentation page [here](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CSwapGate.html#qiskit.circuit.library.CSwapGate).

- What is the current text that needs to be fixed or removed? (You can copy and paste)

The very first line of the docstring says:

> Controlled-X gate.

- What should the documentation say instead?

It should be 

> Controlled-SWAP gate.

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

None that I know of.

**Comment by divshacker** [comment]
May I work on this @epelaaez  ?

**Comment by epelaaez** [comment]
@divshacker sure, go ahead!

**Comment by epelaaez** [comment]
I just found out this was fixed with pull request [#6358](https://github.com/Qiskit/qiskit-terra/pull/6358) in `qiskit-terra`. Therefore, the only thing that needs an update is the documentation in the website.

**Comment by mtreinish** [comment]
The documentation will be updated automatically at release time. The hosted documentation is built from the latest release of the qiskit components when the metapackage is updated (see #1275 for the most recent example of this) so I'm going to close this as already fixed if the docstring has already been updated on terra's main branch pending a release. But, please feel free to reopen if there is more to discuss on this.
