### ISSUE TITLE
Is there a corresponding function that has the same function as function get_expectation_value() in Project Q?

### ISSUE THREAD

**Issue by ntyz** [Qiskit/qiskit-metapackage#1283]
### What is the expected behavior?
Get the expectation value of qubit_operator w.r.t. the current wave function represented by the supplied quantum register.
        Args:
            qubit_operator : Operator to measure.
            qureg (list[qubit],qreg): Quantum bits to measure.

        Returns:
            Expectation value

**Comment by taalexander** [comment]
In Qiskit this higher-level functionality is currently being handled by [opflow](https://qiskit.org/documentation/apidoc/opflow.html). For an example of expectation see the [tutorial](https://qiskit.org/documentation/tutorials/operators/01_operator_flow.html#Expectations).

Please let me know if this helps.

**Comment by ntyz** [comment]
Thank you for your answer！but there is a problem that when I use CircuitSampler to calculate the expectations, it's really slow, espacially when the target circuit include 5~10 qubits, it usually takes a few seconds to calculate. Is there any optimization tricks or other more direct way that I can use to accerlarate the process?

**Comment by taalexander** [comment]
I am rather unfamiliar with this module. @jlapeyre or @Cryoris may know better?

**Comment by Cryoris** [comment]
@ntyz Could you post the code snippet you are using? There are some features we can use to speed up the calculations.

**Comment by ntyz** [comment]
A small example is like this, although not all qubits of the register are used there, but my project will involve circuits of this scale
`
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, Aer
import numpy as np
from qiskit.aqua import QuantumInstance
from qiskit.aqua.operators import PauliExpectation, CircuitSampler, StateFn, CircuitOp, CircuitStateFn

qctl = QuantumRegister(10)
psi  = QuantumCircuit(qctl)
psi.h(0)
psi  = CircuitStateFn(psi)

qctl = QuantumRegister(10)
op   = QuantumCircuit(qctl)
op.z(0)
op.ry(np.pi/4,0)
op   = CircuitOp(op)

backend = Aer.get_backend('qasm_simulator')
q_instance = QuantumInstance(backend, shots=1024)
measurable_expression = StateFn(op, is_measurement=True).compose(psi)
expectation = PauliExpectation().convert(measurable_expression)
sampler = CircuitSampler(q_instance).convert(expectation)
print('Expectation Value = ', sampler.eval())
`

**Comment by Cryoris** [comment]
So to clarify, even though this example only uses only 1 of the 10 qubits you still want to compute the expected value over all 10? And you want shot-noise, not a statevector simulation?

I think one issue is that your operator is not given in terms of Paulis but as a circuit. If you could formulate it using Pauli operators only then the line 
```
expectation = PauliExpectation().convert(measurable_expression)
```
will likely be faster.

**Comment by ntyz** [comment]
Thank you for your answer！I found it really accelerated the calculation by alter the operator to the Paulis. And I find another function that seems more faster in the case of the operator is given as a circuit that is MatrixExpectation(), but it would be more slower when the  operator is given in  terms of Paulis. so I want to ask : what's the differences between the PauliExpectation() and MatrixExpectation()? from the perspective of input parameters, calculation principle and return value of two functions

**Comment by ntyz** [comment]
Thank you for your answer！I found it really accelerated the calculation by alter the operator to the Paulis. And I find another function that seems more faster in the case of the operator is given as a circuit that is MatrixExpectation(), but it would be more slower when the  operator is given in  terms of Paulis. so I want to ask : what's the differences between the PauliExpectation() and MatrixExpectation()? from the perspective of input parameters, calculation principle and return value of two functions

**Comment by Cryoris** [comment]
As both are used to calculate the expected value, the input and output is the same but they differ in how the expectation value is calculated. 

The `MatrixExpectation` converts the Hamiltonian to a matrix and the circuit into a vector and does plain matrix multiplication to obtain the result. So this works well if your Hamiltonian is already a matrix but it scales poorly with the number of qubits.

The `PauliExpectation` decomposes the Hamiltonian to a Pauli-strings and does basis transformations on the circuit to measure in the different basis before finally combining them into the result. This is efficient and scalable if your Hamiltonian is given as Paulis and the state as circuit.
