### ISSUE TITLE
Can I include figures generated using qiskit in research papers?

### ISSUE THREAD

**Issue by catproof** [Qiskit/qiskit-metapackage#1286]
I'm not sure where to ask this, but I can't seem to find the answer anywhere online.

Can I include figures generated using qiskit in research papers? Do I need to make any sort of reference in the research paper to allow me to use the figures? I really like the bloch sphere visual qiskit provides, and would like to use it for a research paper.

**Comment by divshacker** [comment]
I think citing qiskit would work in this case. https://github.com/Qiskit/qiskit/blob/master/Qiskit.bib
Also if you want to ask questions like these fell free to join slack https://ibm.co/joinqiskitslack

**Comment by nonhermitian** [comment]
Citing Qiskit would be nice, but not strictly required.
