### ISSUE TITLE
Image shows up in artifacts but not in online tutorials

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#1290]
A new tutorial for IPE was added in https://github.com/Qiskit/qiskit/pull/128.  The artifacts for this PR show that the included image `binary.png` displays fine.  However, when the docs are pushed to the server the image fails to show.

https://qiskit.org/documentation/tutorials/textbook/01_IQPE.html

**Comment by divshacker** [comment]
There is a bug. Images are shown buy they are  double in number
![Screenshot from 2021-07-21 13-12-04](https://user-images.githubusercontent.com/55018955/126450857-ff7552df-e781-474c-8071-7cac8e76ee05.png)

**Comment by jakelishman** [comment]
As of now, these images all appear.
