### ISSUE TITLE
Grammatical error in Quantum Neural Networks doc

### ISSUE THREAD

**Issue by dukenguyenxyz** [Qiskit/qiskit-metapackage#1291]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
1. https://github.com/qiskit-community/qiskit-translations/blob/a17debe9cd64f2177745ebc570db82648f51a687/machine-learning/docs/locale/en/LC_MESSAGES/tutorials.po#L39

2. https://github.com/qiskit-community/qiskit-translations/blob/a17debe9cd64f2177745ebc570db82648f51a687/machine-learning/docs/locale/en/LC_MESSAGES/tutorials.po#L76

3. https://github.com/qiskit-community/qiskit-translations/blob/a17debe9cd64f2177745ebc570db82648f51a687/machine-learning/docs/locale/en/LC_MESSAGES/tutorials.po#L82-L83

- What is the current text that needs to be fixed or removed? (You can copy and paste)
1. "Depending on the application, a particular type of network might more or less suitable and might require to be set up in a particular way."
2. "different implementations of this interfaces are introduced."
3. "Then, the ``nn.forward(input, weights)`` pass takes either flat inputs for the data and weights of size ``nn.num_inputs`` and ``nn.num_weights``, respectively. "

- What should the documentation say instead?

1. There should be a "be" between "might" and "more or less suitable"

"Depending on the application, a particular type of network might be more or less suitable and might require to be set up in a particular way."

2. "different implementations of this interface are introduced."

3. "Then, the ``nn.forward(input, weights)`` pass takes both flat inputs for the data and weights of size, ``nn.num_inputs`` and ``nn.num_weights``, respectively. "

- Are there other related issues or pull requests about this bug?

**Comment by woodsp-ibm** [comment]
The original text, the above is from, is the opening paragraph in this notebook https://github.com/Qiskit/qiskit-machine-learning/blob/main/docs/tutorials/01_neural_networks.ipynb

**Comment by dukenguyenxyz** [comment]
Should I open an issue & a PR there?

**Comment by jakelishman** [comment]
Fixed by Qiskit/qiskit-machine-learning#523.
