### ISSUE TITLE
`randomized_benchmarking` benchmarks are not representative

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-metapackage#1298]
### What is the current behavior?

The set of benchmarks in `randomized_benchmarking`:

- are not run with `optimization_level=0`
- are run on non-adjacent qubits (and so have a runtime dominated by the routing passes)

which lead to them being not representative of how RB would generally be run in practice, which is unfortunate because RB is a good use-case of large circuits requiring little to no optimization.

Since resolving this will invalidate existing data, this would also be a good opportunity to update the RB circuit generation code to use `qiskit-experiments`.

**Comment by jessica-angel7** [comment]
Can anyone please review my PR for this issue...?
