### ISSUE TITLE
Link to PyTorch guide uses Markdown syntax and is not interpreted by Sphinx

### ISSUE THREAD

**Issue by pybeaudouin** [Qiskit/qiskit-metapackage#1303]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

https://github.com/Qiskit/qiskit-machine-learning/blob/main/docs/getting_started.rst
https://qiskit.org/documentation/machine-learning/getting_started.html#installation

- What is the current text that needs to be fixed or removed? (You can copy and paste)
```
[getting started](https://pytorch.org/get-started/locally/)
```

- What should the documentation say instead?
```
`getting started <https://pytorch.org/get-started/locally/>`__
```

- Are there other related issues or pull requests about this bug?

Not that I am aware of.

**Comment by pybeaudouin** [comment]
Fixed, changes not published yet.

**Comment by woodsp-ibm** [comment]
> Fixed, changes not published yet.

The fix is published now

**Comment by pybeaudouin** [comment]
Thanks Steve!
