### ISSUE TITLE
Use CITATION.cff instead of Qiskit.bib

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-metapackage#1311]
### What is the expected behavior?

Recently, GitHub supports cff format for citation.
https://citation-file-format.github.io

How about using cff?

**Comment by nonhermitian** [comment]
Yeah but then I need yet another package to get the bib file that I actually need.  I also do not think that a single one of these would be enough.  More like one for the core of Qiskit and then another for individual applications.

Also, it does not really solve the Authorship issues https://github.com/Qiskit/qiskit/issues/1273 that popup in our current solution.

**Comment by kdk** [comment]
There was some discussion of how to add support for this in https://github.com/Qiskit/qiskit/pull/1322 . (.bib files are also apparently supported.)

**Comment by jakelishman** [comment]
I'll close this as stale now, since there never seemed to be a huge amount of support for using this CFF format.  We can re-open this on the relevant component repos, if people are more in favour of it again in the future.
