### ISSUE TITLE
CZ Gate in Composer is not displaying properly

### ISSUE THREAD

**Issue by praveentn** [Qiskit/qiskit-metapackage#1320]
### Informations
I'm using the IBM Quantum Experience Composer [portal](https://quantum-computing.ibm.com/composer). 

- **Qiskit version**: N/A
- **Python version**: N/A
- **Operating system**: N/A

### What is the current behavior?
![qiskit_composer_cz_1](https://user-images.githubusercontent.com/566274/129471040-6387c456-4fe2-4f64-912d-1e4c16a43d92.png)

### Steps to reproduce the problem
```
OPENQASM 2.0;
include "qelib1.inc";

qreg q[3];
creg c[3];

h q[0];
x q[1];
cz q[0],q[1];
```

### What is the expected behavior?
Display CZ gate correctly by showing the connection between the qubits!

**Comment by nonhermitian** [comment]
This is not a Qiskit issue per say as the composer is not part of Qiskit.  I have however notified the people in charge of the composer about this issue.

**Comment by francabrera** [comment]
thanks for reporting this, it should be fixed now (just refresh the browser)
