### ISSUE TITLE
Replace ipython3 code blocks with python

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-metapackage#133]
Currently there are a number of 
```
.. code:: ipython3
```
blocks which are not rendered in the final .html files as the `ipython3` highlighter is not provided by stock sphinx (they seem to be in the aer documentation - as in https://qiskit.org/documentation/aer/device_noise_simulation.html#device-noise-module). In #70 some of them were changed manually to:
```
.. code:: python
```
can we do a round of replacing them, probably also removing the dependency on `ipython`?

They are likely a byproduct of using `nbconvert` (and it seems to be configurable - if we foresee that more content is going to be started from `nbconvert`, it might be worth documenting somewhere the default options to be used, some of which have been hinted at 15717c3714527b915c1d7dfb0fb184c79fed4732 and e2077b3ef6bd8cb879bdf4dfb05a6d5c73f8f196).

**Comment by derivation** [comment]
You've definitely diagnosed this correctly. I used nbconvert in the Aer doc.
