### ISSUE TITLE
Installation tutorial correction

### ISSUE THREAD

**Issue by bicycle315** [Qiskit/qiskit-metapackage#1332]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

- What is the current text that needs to be fixed or removed? (You can copy and paste)

- What should the documentation say instead?
qiskit should be installed in python at least 3.6 or later
- Are there other related issues or pull requests about this bug?

## Does existing documentation need to be updated with new content?

- Which files need to be updated?
https://qiskit.org/documentation/getting_started.html
![image](https://user-images.githubusercontent.com/56623045/133531604-3556849e-df71-432c-9228-500456ba591b.png)
- What content needs to be updated or replaced? (You can copy and paste)
python=3 
- What new content needs to be added?
have to fix it -> qiskit should be installed in python at least 3.6 or later
i followed that instruction but it didn't work at all . 
I tried python=3.7 and it worked

**Comment by jakelishman** [comment]
Sorry this had no attention at the time.  The Getting Started guide has been updated to no longer reference `conda` at all, so I'll close this as stale, but please feel free to re-open if there's more to discuss.
