### ISSUE TITLE
A mistranslation in the Japanese Tutorial

### ISSUE THREAD

**Issue by massn** [Qiskit/qiskit-metapackage#1335]
Hi!
I found a mistranslation in https://qiskit.org/documentation/locale/ja_JP/tutorials/noise/8_tomography.html#%EF%BC%91%E9%87%8F%E5%AD%90%E3%83%93%E3%83%83%E3%83%88%E3%81%AE%E7%8A%B6%E6%85%8B%E3%83%88%E3%83%A2%E3%82%B0%E3%83%A9%E3%83%95%E3%82%A3%E3%83%BC%E3%81%AE%E4%BE%8B .
`１量子ビットの状態トモグラフィーの例` (= a translation of `1-qubit process tomography example`)  must be `１量子ビットのプロセストモグラフィーの例`.
How should I correct it?

**Comment by divshacker** [comment]
This is wrong place of opening this issue. The correct place is here -> [Qiskit/qiskit-tutorials](https://github.com/Qiskit/qiskit-tutorials).

**Comment by massn** [comment]
Thank you very much. I close this.
