### ISSUE TITLE
qiskit installation on Python 3.10 not working

### ISSUE THREAD

**Issue by louis-martin** [Qiskit/qiskit-metapackage#1343]
### Informations

- **Qiskit version**: 0.30.1
- **Python version**: 3.10.0
- **Operating system**: Mac OS X 11.6

### What is the current behavior?

After a very long delay multiple errors are output, installation is aborted

### Steps to reproduce the problem

pip install qiskit

### Suggested solutions

Whit python 3.9.7 no problem

**Comment by mtreinish** [comment]
Qiskit does not support python 3.10 yet. It was only released 4 days ago and many of the upstream dependencies of Qiskit do not fully support python 3.10 yet (or haven't published python 3.10 wheels on pypi yet). This is just a matter of time as we wait for those packages to release and add support for python 3.10. Once all of Qiskit's dependencies have versions that support python 3.10 we can push out a qiskit version that supports 3.10. The process for this has started here: https://github.com/Qiskit/qiskit-terra/pull/7102 (but as you can see we're blocked by every upstream dependency and our CI system having 3.10) Until Python 3.10 is supported in qiskit I'd recommend you stick with python <=3.9 where everything is supported already.

It is probably possible to build everything from source, but it would require having a C, C++, and Rust compiler installed along with many system libraries (like BLAS, GMP, etc) to be able to build all of Qiskit's dependencies from source (which is probably the long delay you experienced, pip building things from source). I'd probably not recommend going that route unless you absolutely need to run on Python 3.10.

**Comment by louis-martin** [comment]
Thank you very much for your fast feedback. Everything working well with Python 3.9.7

**Comment by mstechly** [comment]
Hi @mtreinish ! 
Any updates on the front of making qiskit work with 3.10 :) ?

**Comment by mtreinish** [comment]
Oh, sorry I forgot to close this issue. Qiskit has supported running with Python 3.10 from the 0.34.2 release in the beginning of February (it's documented in the release notes here: https://qiskit.org/documentation/release_notes.html#qiskit-0-34-2). FWIW you can always refer to the package metadata at https://pypi.org/project/qiskit/#data to see the list of supported versions.

**Comment by mstechly** [comment]
Oh, I had a constraint for `<0.34` in my setup file 😅 
Will try newer version, thanks!
