### ISSUE TITLE
c_if gate after Bell state does not work as expected

### ISSUE THREAD

**Issue by zhanjunpeng** [Qiskit/qiskit-metapackage#1347]
### Informations

- **Qiskit version**: 0.31.0
- **Python version**: 3.9.0
- **Operating system**: Windows
![image](https://user-images.githubusercontent.com/12178478/137778615-e6961e61-5c19-4ca2-98d4-e34458080045.png)

### What is the current behavior?
As given in Fig. 2 below, adding another H gate (the right most at q0) to the circuit in Fig. 1 should change the final states to only have ‘10’. But why both ‘10’ and ‘11’ states appear as shown below?  (The backend is ‘aer_simulator’; I tried other simulators but the results were the same.)

### Steps to reproduce the problem
See the circuits given below. Just several gates.  The c_if gate is given as follows.
qc.x(q[1]).c_if(c,1)

### What is the expected behavior?
Fig. 1 and Fig. 2 should have different results in terms of final states, but they seem to have the same results as shown in the bottom of both figures.

•	The circuit given in Fig. 1 works as expected and it is used to compare with circuit 2. The only difference between Figs. 1 and 2 is the right most H gate at q_0.
![image](https://user-images.githubusercontent.com/12178478/137777144-6a823d7b-9426-4bfb-ac0f-d569deb39d16.png)
Fig. 1: circuit 1

•	As shown in Fig. 2, adding another H gate (the right most at q0) should change the final states to only have ‘10’. But why both ‘10’ and ‘11’ states appear as shown below?  In other words, Fig.1 and Fig.2 should have different results in terms of final states, but they seem to have the same results as shown in the bottom of both figures. (The backend is ‘aer_simulator’; I tried other simulators, including aer_simulator_statevector, and qasm_simulator, but the results were the same.)
o	The c_if gate is given as follows
o	qc.x(q[1]).c_if(c,1)
![image](https://user-images.githubusercontent.com/12178478/137777173-b0ebda8b-9785-4a26-beb1-498d36278c3e.png)
Fig. 2: circuit 2. For counts resluts ’10 0’ and ’11 0’, the two bits before space is the result from c29 and the one bit after space is the result from c28.

•	I encountered a similar issue when using reset gate, i.e., when replacing the c_if gate in Fig. 2 by reset gate, the circuit results are not as expected. I feel they have the same behavior. So, if necessary, I will post details later, say, after I get feedback from this issue. 

### Suggested solutions
I am not sure whether I use  c_if gate  correctly or not.

**Comment by jakelishman** [comment]
After the first measurement, you no longer have an entangled Bell state, you have a mixed state.  There's a hint to that in the output of your first circuit; there's only one qubit state per classical bit state.  The reason you get four outputs at the end is that the state of your classical bit has an effect as well - in the second circuit, you've recreated the same Bell state by the time you measure things at the end, but there's also the classical bit state to consider.

The use of the function `c_if` looks correct, except I think you've possibly not quite made the circuit you meant to, because the first measurement breaks the entanglement.

**Comment by zhanjunpeng** [comment]
> After the first measurement, you no longer have an entangled Bell state, you have a mixed state. There's a hint to that in the output of your first circuit; there's only one qubit state per classical bit state. The reason you get four outputs at the end is that the state of your classical bit has an effect as well - in the second circuit, you've recreated the same Bell state by the time you measure things at the end, but there's also the classical bit state to consider.
> 
> The use of the function `c_if` looks correct, except I think you've possibly not quite made the circuit you meant to, because the first measurement breaks the entanglement.

Thank you for the quick comments. It was very helpful. I think I understand both circuits (work as expected) now.

**Comment by jakelishman** [comment]
I actually made a mistake, sorry - there's no Bell state at the end of the second circuit at all - but the principle was that it wasn't turning into what you expected because the measurement collapsed the state.

**Comment by zhanjunpeng** [comment]
Yes, I agree. Thank you so much!
