### ISSUE TITLE
Duplicate instructions for "installation from source" in `getting_started.rst` and `contributing_to_qiskit.rst`

### ISSUE THREAD

**Issue by jond01** [Qiskit/qiskit-metapackage#1352]
These referenced labels from the file `contributing_to_qiskit.rst` (L656-L660)
```rst
#. :ref:`qiskit-terra <install-qiskit-terra>`
#. :ref:`qiskit-aer <install-qiskit-aer>`
#. :ref:`qiskit-ignis <install-qiskit-ignis>`
#. :ref:`qiskit-aqua <install-qiskit-aqua>`
#. :ref:`qiskit-ibmq-provider <install-qiskit-ibmq-provider>`
```
are duplicated in `getting_started.rst` (L131-L135):
```rst
   #. :ref:`qiskit-terra <install-qiskit-terra>`
   #. :ref:`qiskit-aer <install-qiskit-aer>`
   #. :ref:`qiskit-ignis <install-qiskit-ignis>`
   #. :ref:`qiskit-aqua <install-qiskit-aqua>`
   #. :ref:`qiskit-ibmq-provider <install-qiskit-ibmq-provider>`
```

The "installation from source" instructions are duplicated in two places with the same labels,
so when clicking [link 1](https://qiskit.org/documentation/contributing_to_qiskit.html#:~:text=the%20source%20versions%3A-,qiskit-terra,-qiskit-aer) here:
https://qiskit.org/documentation/contributing_to_qiskit.html#installing-from-source
One is redirected to:
https://qiskit.org/documentation/getting_started.html#install-qiskit-terra
Instead of:
https://qiskit.org/documentation/contributing_to_qiskit.html#installing-terra-from-source

_Originally posted by @jond01 in https://github.com/Qiskit/qiskit/issues/1351#issuecomment-963281590_

**Comment by jakelishman** [comment]
This got fixed at some point in the past, but I guess we forgot to close the issue.  Any residual bits will be cleaned up by #1788.
