### ISSUE TITLE
Could not install `qiskit-terra` from source on macOS with `clang` according to the instructions

### ISSUE THREAD

**Issue by jond01** [Qiskit/qiskit-metapackage#1353]
I have followed the instructions for installation from source of `qiskit-terra` on macOS (with a standard chip),
but unfortunately, the compilation of the C files failed.

- clang version:
   ```
   Apple clang version 13.0.0 (clang-1300.0.29.3)
   Target: x86_64-apple-darwin20.6.0
   Thread model: posix
   InstalledDir: /Library/Developer/CommandLineTools/usr/bin
   ```
- Platform: 
  - From `sw_vers` (CLI): 
    ```
    ProductName:    macOS
    ProductVersion: 11.6
    BuildVersion:   20G165
    ```
   - From `platform.platform()` (python):
    `macOS-10.16-x86_64-i386-64bit`
- Python version: `3.8.5`
- `pip` version: `21.3.1`

The step that caused the failure is `pip install .` / `pip install -e .` (step 5).
The output with the error message from this command is attached:
[out.txt](https://github.com/Qiskit/qiskit/files/7506476/out.txt)
```
  running build_ext
  building 'qiskit.transpiler.passes.routing.cython.stochastic_swap.utils' extension
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Users/jonathandaniel/venvs/qiskitenv/include -I/Users/jonathandaniel/.pyenv/versions/3.8.5/include/python3.8 -c qiskit/transpiler/passes/routing/cython/stochastic_swap/utils.cpp -o build/temp.macosx-10.15-x86_64-3.8/qiskit/transpiler/passes/routing/cython/stochastic_swap/utils.o -O2 -funroll-loops -std=c++11 -mmacosx-version-min=10.9
  In file included from qiskit/transpiler/passes/routing/cython/stochastic_swap/utils.cpp:29:
  In file included from /Users/jonathandaniel/.pyenv/versions/3.8.5/include/python3.8/Python.h:25:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:

```
...
```
  202 warnings and 13 errors generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for qiskit-terra
ERROR: Could not build wheels for qiskit-terra, which is required to install pyproject.toml-based projects

```

I hope this is the right place to for this issue. It may be just a local issue.

## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
  - https://qiskit.org/documentation/contributing_to_qiskit.html#installing-terra-from-source

- What is the current text that needs to be fixed or removed? (You can copy and paste)
  - The instructions for macOS ("Compiler for macOS").

- What should the documentation say instead?
  - I'm not sure.

- Are there other related issues or pull requests about this bug?
  - The same instructions appear also in https://qiskit.org/documentation/getting_started.html#installation (see #1352)

## Does existing documentation need to be updated with new content?

- Which files need to be updated?
  - `contributing_to_qiskit.rst`, `getting_started.rst`

- What content needs to be updated or replaced? (You can copy and paste)
  - Installing Terra from Source - Compiler for macOS

- What new content needs to be added?
   - Compilation instructions for building the C files

**Comment by jakelishman** [comment]
Those error logs look like a problem with the setup of the C toolchain - the errors are all about bad definitions in standard-library header files, which we don't have any control over.  Apple's C toolchain is notoriously changeable with new releases, unfortunately.

Are you able to compile a simple hello world program with your system `clang` and have it run?  I'm also suspicious that something may be feeding your C compiler the wrong `-I` flags as well; it's getting extra macOS SDK paths added to its include search (rather than by modifying the `sysroot`), which may well be messing up the order it accesses things.  I don't think _we_ do that directly in either Terra or Aer, so if that is the cause (I'm not at all sure), it may be due to an old version of `setuptools` or `scikit-build` being installed, perhaps?

**Comment by jond01** [comment]
Hi, thanks a lot for the detailed response!
So I'm not sure how, but the issue was solved for me after an update of the macOS version from Big Sur (11.6) to Monterey (12.0.1). 
The other dependencies (`clang`, `pip`, and `setuptools` versions) did not change.
