### ISSUE TITLE
result.get_counts() for the post-processing

### ISSUE THREAD

**Issue by gliewmeden** [Qiskit/qiskit-metapackage#1360]
### Current behavior

result.get_counts() returns an unsorted dictionary of qubit states and corresponding counts. If the state has 0 counts, it is absent. For example if there are 2 qubits and 4 states, the output can be {'11': 542, '10': 458}.

### What is the expected behavior?

Expected behavior: {'00': None, '01': 458, '10': None, '11': 542}. Such construction would be convenient in cases, when the post-processing of the counts distribution is required. For example, when one needs to reconstruct a state vector or calculate an expectation value.

**Comment by nonhermitian** [comment]
There is an exponentially growing number of bitstrings with qubit count. Thus it is impossible to do what you suggest here in general.
