### ISSUE TITLE
Getting error : AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

### ISSUE THREAD

**Issue by kumarsat** [Qiskit/qiskit-metapackage#1366]
### Informations
My code is not getting executed
- **Qiskit version**:  0.18.3
- **Python version**: 3.7.0
- **Operating system**: Windows

### What is the current behavior?
I am running plot_state_qsphere() on my local machine through virtual environment  and it is throwing error like AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'. Same code I am running o the IBMQ clould tool and it is executing fine there.

### Steps to reproduce the problem
Installed Qiskit on my local machine through virtual environment.  Below is the code 👍 

import numpy as np
from qiskit import QuantumCircuit,execute,Aer,IBMQ
from qiskit.compiler import transpile,assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
from ibm_quantum_widgets import *
import matplotlib.pyplot as P
import matplotlib.pyplot as plt
%matplotlib inline

#Loading IBMMQ Account
#provider = IBMQ.load_account()

qc = QuantumCircuit(1)
statevector_simulator = Aer.get_backend('statevector_simulator')
result = execute(qc,statevector_simulator).result()
statevector_results = result.get_statevector(qc)
plot_bloch_multivector(statevector_results)

plot_state_qsphere(statevector_results)

qc.x(0)
statevector_simulator = Aer.get_backend('statevector_simulator')
result = execute(qc,statevector_simulator).result()
statevector_results = result.get_statevector(qc)
plot_bloch_multivector(statevector_results)

plot_state_qsphere(statevector_results)

qc.h(0)
statevector_simulator = Aer.get_backend('statevector_simulator')
result = execute(qc,statevector_simulator).result()
statevector_results = result.get_statevector(qc)
plot_bloch_multivector(statevector_results)

plot_state_qsphere(statevector_results)

### What is the expected behavior?
Code is not running
![Qiskit_Issue](https://user-images.githubusercontent.com/59330484/144009150-5d0ee48a-665a-4aa7-a0a4-8056cfcdf403.JPG)

**Comment by jakelishman** [comment]
This is an issue with Qiskit and Matplotlib 3.5. For now, you can install Matplotlib 3.4 and everything should work, and Qiskit Terra 0.19 (coming soon) will fix it with Matplotlib 3.5. The patch is already in in Qiskit/qiskit-terra#7301.

**Comment by kumarsat** [comment]
Yes that worked. Thank you.
