### ISSUE TITLE
API for provider

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#138]
@derivation and @diego-plan9 I see that you did a nice job in the docs for creating a provider. However, what I was thinking is something slightly different. I would like to better define our API. I was thinking we should have a section called the provider API. This would be defined what it is and what is required etc. Then i think in this we should link to the tutorial for creating the API. I dont know if we need the code to be a copy of what is in the qiskit-tutorial.

**Comment by derivation** [comment]
Ah, yes, I understand. I'll give this another try.

**Comment by jaygambetta** [comment]
cool.
