### ISSUE TITLE
ImportError: DLL load failed while importing _tweedledum: The specified module could not be found. 

### ISSUE THREAD

**Issue by lironmo** [Qiskit/qiskit-metapackage#1380]
the latest version failed on windows 10.

reproduce code: from qiskit import IBMQ

**Comment by lironmo** [comment]
It seems that there was a problem installing one of the dependencies of qiskit called Tweedledum.

Official Link: https://pypi.org/project/tweedledum/

**Comment by lironmo** [comment]
related - https://github.com/Qiskit/qiskit-tutorials/issues/1242

**Comment by jakelishman** [comment]
Please can you show the full output from the `pip` command you used to install/upgrade/modify the `qiskit` installation?

You might want to try `pip uninstall tweedledum` and re-running the installation command to retrigger an installation of it, but without the error, it's hard to offer much more (and at any rate, you might have more success raising this issue on [`tweedledum`'s issue tracker](https://github.com/boschmitt/tweedledum)).

**Comment by lironmo** [comment]
hey @jakelishman,
I was able to work around it with two options:
1. build from source 
2. a downgrade of Tweedledum package.

it's a simple import error (ImportError: DLL load failed while importing _tweedledum)

reinstall qiskit or tweedledum  did not works, also on clean virtual env
