### ISSUE TITLE
delete job from 	System: ibmq_qasm_simulator

### ISSUE THREAD

**Issue by lironmo** [Qiskit/qiskit-metapackage#1381]
Hi,
I did not find a way to delete jobs from python code.

from qiskit import IBMQ
provider = IBMQ.load_account()

jobs = provider.backend.jobs(limit=1000)
for job in jobs:
    id = job.job_id()
# how to delete by id????

i found something in the realtime library  - provider.runtime.delete_job(id) - but it;s only for runtime jobs (different URL)

please help.

**Comment by jakelishman** [comment]
This never got a response at the time, but I believe the solution being sought for was `job.cancel()`.  I'm closing this issue as part of the sunsetting of this repository - if there are still problems, please re-open them on the Qiskit/Terra repo.
