### ISSUE TITLE
how to run batch computation

### ISSUE THREAD

**Issue by lironmo** [Qiskit/qiskit-metapackage#1382]
Hey, 
I am running this demo https://pennylane.ai/qml/demos/tutorial_kernels_module.html 
with ibmq_qasm_simulator backend.

it seems that If any access to a quantum computer at IBM quantum experience (which is usually a short operation because it is not possible to make long circuits at the moment) is expensive, then the whole idea in these libraries is not perfect.

I think the should be a possibility that you may submit a batch of calculations, for example, the calculation of the kernel matrix is a group of executions that may be submitted at once and will be performed one after the other at the cloud.

currently, the demo creates hundreds if not thousands of jobs of the same circuit and fail to reach the optimization stage...

**Comment by jakelishman** [comment]
Apologies that this never got attention at the time.  Since then, however, IBM hardware now offers access via the [Qiskit Runtime](https://quantum-computing.ibm.com/lab/docs/iql/runtime/), in part to address some of your concerns.
