### ISSUE TITLE
The version on the titles doesn't match the version on the URL

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1388]
### Informations

It's a bug related with the documentation so the qiskit and python versions and the operating system are not relevant

### Steps to reproduce the problem

Go to https://qiskit.org/documentation/stable/0.33/index.html and compare the version on the URL with the version on the titles

### What is the current behavior?

Although we are on the 0.33 version page, all the titles has the 0.34 version
<img width="1153" alt="Captura de pantalla 2021-12-23 a las 13 40 45" src="https://user-images.githubusercontent.com/17231966/147242044-43eb5e17-dd61-4959-ac6b-24c9b301d87e.png">

### What is the expected behavior?

The version on the titles should match the version on the URL

**Comment by y4izus** [comment]
I've tried to add the `documentation` label too, but I don't have access for that

**Comment by jakelishman** [comment]
This is likely a failure in the script that deploys tags to the stable branch - it finds the tag using `git describe`, which sometimes seems to be slightly out of sync on GitHub Actions.  It'll be more robust if we just get the triggering tag information from the `github` object in the workflow and pass it in.

**Comment by y4izus** [comment]
I've checked if we are still having this bug, but it's fixed now!! I close the issue :)
