### ISSUE TITLE
Broken links for previous releases

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1389]
### Informations

It's a bug related with the documentation so the qiskit and python versions and the operating system are not relevant

### Steps to reproduce the problem

1. Go to https://qiskit.org/documentation/
2. Click on the dropdown on the left sidebar menu
<img width="285" alt="Captura de pantalla 2021-12-23 a las 14 10 13" src="https://user-images.githubusercontent.com/17231966/147245285-4ba74edb-37c5-4c54-84a6-6cc2de42bf6e.png">

3. Select one of theses previous releases: 0.29, 0.30, 0.31, 0.32, 0.34

### What is the current behavior?

These release links are broken, so all these following links ends in a 404 page:
- https://qiskit.org/documentation/stable/0.29/index.html
- https://qiskit.org/documentation/stable/0.30/index.html
- https://qiskit.org/documentation/stable/0.31/index.html
- https://qiskit.org/documentation/stable/0.32/index.html
- https://qiskit.org/documentation/stable/0.34/index.html

Related with this, the workflow that creates this content have been failing, see: https://github.com/Qiskit/qiskit/actions/workflows/docs_tag.yml

### What is the expected behavior?
We should have the documentation for the previous stable versions working

### Notes
This issue should be address after fixing and merging #1388

**Comment by jakelishman** [comment]
@mtreinish: once you're back from holiday, we can go through this and just re-deploy the old documentation versions.  Yaiza and I were going to try this week, but we don't have write access to the necessary machine.

**Comment by jakelishman** [comment]
Matthew re-ran all the old runs locally, so these are back online now.  I also have the power to push to prod if we need it in the future.
