### ISSUE TITLE
Qiskit 0.34.0 issue with `IBMQ.ibmq` being `None`

### ISSUE THREAD

**Issue by mahyarmirrashed** [Qiskit/qiskit-metapackage#1391]
### Informations

- **Qiskit version**: 0.34.0
- **Python version**: 3.8.12
- **Operating system**: WIndows 11

### What is the current behavior?

```py
from qiskit import IBMQ
ibmq = IBMQ.imbq
```

This code always results in `ibmq` staying `None`. Even when I run in Jupyter notebooks in separate blocks, I still get the same error that it is resulting in `None`.

### Steps to reproduce the problem

Just run the code above. Then, optionally add something like `print(ibmq` and you should see that `None` gets printed out.

### What is the expected behavior?

The expected behaviour is to have a non-`None` type so that I can use the `ibmq#save_account` and `ibmq#load_account` methods. I am unable to follow the Qiskit tutorials without this.

### Suggested solutions

I took a look and saw the lazy loading approach. Not sure if that might be the reason behind it all. I made sure that the imports it tried to look for were present (they were) and tried to debug but I could not figure it out.

**Comment by jakelishman** [comment]
You don't need to access `IBMQ.ibmq` (and really, it should probably be a private attribute).  Try just accessing the functions you want directly, and the loader should pull everything in correctly for you.  For example:
```python
from qiskit import IBMQ
IBMQ.load_account()
```

**Comment by jakelishman** [comment]
I'll close this issue as stale now, but please feel to re-open if the solution I provided didn't work for you.
