### ISSUE TITLE
RippleAdder benchmarks don't set `seed_transpiler`

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-metapackage#1404]
### What is the expected behavior?

The benchmarks that live in `test/benchmarks/ripple_adder.py` don't set a value for `seed_transpiler`, resulting in noisy outputs that can hide small but significant changes. e.g. in `track_depth_transpile_square_grid_ripple_adder`, only https://github.com/Qiskit/qiskit-terra/pull/7205 is visible. https://qiskit.github.io/qiskit/#ripple_adder.RippleAdderTranspile.track_depth_transpile_square_grid_ripple_adder?commits=2fe852fa

**Comment by jakelishman** [comment]
A few others too by the looks of things: #1405.
