### ISSUE TITLE
Classically-controlled gates available on current devices?

### ISSUE THREAD

**Issue by platodeliyannis** [Qiskit/qiskit-metapackage#1406]
From what I can find online, quantum gates controlled on classical bits -- as per 'qiskit.circuit.Instruction.c_if' in the software -- are NOT currently supported on any IBM devices. Is this correct?

**Comment by kdk** [comment]
This has changed within the past few months as more backends with dynamic circuits capability have come online. From 
https://quantum-computing.ibm.com/services/programs/docs/runtime/manage/systems/dynamic-circuits/faq#whom-is-
dynamic-circuit-support-available-to , these can be discovered via `provider.backends(dynamic_circuits=True)`.
