### ISSUE TITLE
Tutorials page should link to additional tutorials (e.g. application modules, experiments)

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit-metapackage#1407]
At the moment, it is pretty easy to overlook that the [Tutorials](https://qiskit.org/documentation/tutorials.html) page ([`tutorials.rst`](https://github.com/Qiskit/qiskit/blob/master/docs/tutorials.rst)) includes only a subset of the tutorials.  I believe that at the bottom of that page, it would be helpful to mention that each of the application modules also has its own set of tutorials.  (So do Experiments and Metal, too, actually.)  Having this mention contain *links* to these additional tutorials would be ideal.

**Comment by nrhawkins** [comment]
I would like to work on this.  Is that ok?

**Comment by garrison** [comment]
@nrhawkins has proposed #1440 but it did not link back here.

**Comment by nrhawkins** [comment]
I removed a couple of trailing white spaces from the tutorials.rst file and pushed it.  Do I need to do anything else now?  The workflow ran when I first made the pull request, but I see that it won't run now until someone approves it.  I don't know where the 1440 came from.

**Comment by 1ucian0** [comment]
In the same direction of https://github.com/Qiskit/qiskit-metapackage/pull/1759, I'm closing this issues as `not planned`. Applications are moved away from to be supported by the community.
