### ISSUE TITLE
Mega and procedure for update of patches

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#141]
### What is the expected behaviour?

I think that the mega patches need to link with an exact qiskit element version. For instance the line 

https://github.com/Qiskit/qiskit/blob/2fdba884b2decaa38fc38315e04c1500e54e6218/setup.py#L17

should be 

```
requirements = [
   qiskit-terra==0.7.0”,
   "qiskit-aer==0.1.1,"
]
```
This way for each patch version of qiskit we know what elements are in it and we say this in the release tag. Then our rule should be if we patch an element we need to also patch the mega. We can also patch the mega with no update to the element if the mega needs a patch.

For a minor update on any element, the mega minor should be updated. So if we go to qiskit_aer 0.2.0 then the mega updates even if Terra does not. This is also true if we add a new element. If we add ignis then the mega should increase. 

Obviously, we should try to coordinate and then we can release patches and updates at the same time.

**Comment by nonhermitian** [comment]
100% agree.

**Comment by mtreinish** [comment]
I'm definitely fine with hard pinning in the meta-repository. Just to outline what we're expecting here. The current versions are `qiskit==0.7.3`, `qiskit-aer==0.1.1`, and `qiskit-terra==0.7.0`.

Let's say we release a new minor version of terra to fix https://github.com/Qiskit/qiskit-terra/issues/1838 as a minor version `qiskit-terra==0.7.1` then to correspond with that release we bump that requirement in the qiskit meta package and release it as `qiskit==0.7.4`. 

In the future we release qiskit-aer `0.2.0` when that happens we bump the requirement in the meta and release it as  `qiskit==0.8.0`.

Now, after we're at `qiskit==0.8.0` we add qiskit-ignis to the meta-repository requirements then we bump the version to `qiskit==0.9.0`.

That all seems fine for me, I just want to make it clear. If so I'll also write up a doc on the versioning to outline this.

**Comment by jaygambetta** [comment]
This is good with me. I think we should have a procedure where all repos say a patch is coming or a minor is coming and a period for coordinationed releases as well

**Comment by delapuente** [comment]
I'm afraid I don't understand the point of pinning the "patch" numbers. What is the advantage? What are the issues that support changing this?
