### ISSUE TITLE
Conflicting 'operational' information in backend

### ISSUE THREAD

**Issue by knsmith** [Qiskit/qiskit-metapackage#1410]
### Information

- **Qiskit version**:

{'qiskit-terra': '0.17.1', 'qiskit-aer': '0.8.2', 'qiskit-ignis': '0.6.0', 'qiskit-ibmq-provider': '0.12.3', 'qiskit-aqua': '0.9.1', 'qiskit': '0.25.3', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}

- **Python version**:

Python 3.6.10

- **Operating system**:

MacOS Catalina 10.15.5

### What is the current behavior?

Santiago is currently offline/not operational due to maintenance. This is reported when you query the device with backend.status().operational and backend.status().status_msg. However, when backend.properties() is examined, is_qubit_operational() and is_gate_operational() returns True for all qubits/gates. 

As an additional note, some two-qubit gates are reporting error of 1, and that would seem to be an indication that is_gate_operational should be False.

### Steps to reproduce the problem
```
backend = provider.get_backend('ibmq_santiago')
print("santiago is operational: "+ str(backend.status().operational))
print("santiago has a message: "+ str(backend.status().status_msg))

props = backend.properties()
for i in range(backend.configuration().num_qubits):
    print(i)
    print('     '+str(props.is_qubit_operational(i)))
    print('     '+str(props.gate_error('x',i)))

for i in backend.configuration().coupling_map:
    print(i)
    print('     '+str(props.is_gate_operational('cx',i)))
    print('     '+str(props.gate_error('cx',i)))

```

The above prints the following:

santiago is operational: False
santiago has a message: maintenance
0
     True
     0.0001963277973551847
1
     True
     0.00018121802641178793
2
     True
     0.01865106109966443
3
     True
     0.00018170450018450463
4
     True
     0.0002431898323367661

[0, 1]
     True
     0.006192784540510532
[1, 0]
     True
     0.006192784540510532
[1, 2]
     True
     1
[2, 1]
     True
     1
[2, 3]
     True
     1
[3, 2]
     True
     1
[3, 4]
     True
     0.00547056474214716
[4, 3]
     True
     0.00547056474214716

### What is the expected behavior?

Information in properties should reflect the current status of the machine.

### Suggested solutions

Have fields populated with the same data.

**Comment by jakelishman** [comment]
Apologies that this didn't get a response at the time.  `is_qubit_operational` and `is_gate_operational` are kind of separate metadata to whether the machine is actually online or not; it's perfectly possible for the machine to be fully functional, just not available for job submission.  The faulty qubits/gates handling is for when the machine _is_ online, but part of it is out of commission; it causes Qiskit's transpiler to not use those qubits / links.

**Comment by knsmith** [comment]
Great! Thanks for clarifying :)
