### ISSUE TITLE
Categorize content on qiskit optimization documentation

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1426]
Classify the tutorials on the following links using the description table defined on [this structure](https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#:~:text=a%20summary%20with-,this%20structure). You can add your summary on a comment below

- [ ] Categorize [qiskit optimization getting started page](https://qiskit.org/documentation/optimization/getting_started.html)
- [ ] Categorize [qiskit optimization tutorials](https://qiskit.org/documentation/optimization/tutorials/index.html)

**Comment by 1ucian0** [comment]
As the content audit was deprioritized (see https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#issuecomment-1477909804), closing for now.
