### ISSUE TITLE
Categorize content on qiskit experiments documentation

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1427]
Classify the tutorials on the following links using the description table defined on [this structure](https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#:~:text=a%20summary%20with-,this%20structure). You can add your summary on a comment below

- [ ] Categorize [qiskit experiments tutorials](https://qiskit.org/documentation/experiments/tutorials/index.html)

**Note**: I didn't find a getting started tutorial

**Comment by 1ucian0** [comment]
As the content audit was deprioritized (see https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#issuecomment-1477909804), closing for now.
