### ISSUE TITLE
Categorize content on qiskit dynamics documentation

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1428]
Qiskit dynamics already use the [divio](https://documentation.divio.com/) structure dividing documentation into: API Reference, user guides, tutorials and discussions. It would be nice to have them also in a [summary table](https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#:~:text=a%20summary%20with-,this%20structure). You can add your summary on a comment below

**Comment by 1ucian0** [comment]
As the content audit was deprioritized (see https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#issuecomment-1477909804), closing for now.
