### ISSUE TITLE
Categorize content on qiskit metal documentation

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1429]
Classify the tutorials on the following links using the description table defined on [this structure](https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#:~:text=a%20summary%20with-,this%20structure). You can add your summary on a comment below

- [ ] Categorize [qiskit metal installation page](https://qiskit.org/documentation/metal/installation.html)
- [ ] Categorize [qiskit metal overview tutorials](https://qiskit.org/documentation/metal/tut/index.html#overview).
- [ ] Categorize [qiskit metal components tutorials](https://qiskit.org/documentation/metal/tut/index.html#components).
- [ ] Categorize [qiskit metal renderers tutorials](https://qiskit.org/documentation/metal/tut/index.html#renderers).
- [ ] Categorize [qiskit metal analysis tutorials](https://qiskit.org/documentation/metal/tut/index.html#analysis).
- [ ] Categorize [qiskit metal quick topics tutorials](https://qiskit.org/documentation/metal/tut/index.html#quick-topics).
- [ ] Categorize [qiskit metal qubits tutorials](https://qiskit.org/documentation/metal/circuit-examples/index.html#qubits).
- [ ] Categorize [qiskit metal resonators tutorials](https://qiskit.org/documentation/metal/circuit-examples/index.html#resonators).
- [ ] Categorize [qiskit metal composite bi-partite systems tutorials](https://qiskit.org/documentation/metal/circuit-examples/index.html#composite-bi-partite-systems).
- [ ] Categorize [qiskit metal qubits couplers tutorials](https://qiskit.org/documentation/metal/circuit-examples/index.html#qubit-couplers).
- [ ] Categorize [qiskit metal input-output coupling tutorials](https://qiskit.org/documentation/metal/circuit-examples/index.html#input-ouput-coupling).
- [ ] Categorize [qiskit metal small quantum chips tutorials](https://qiskit.org/documentation/metal/circuit-examples/index.html#small-quantum-chips).
- [ ] Categorize [qiskit metal design flow tutorials](https://qiskit.org/documentation/metal/circuit-examples/index.html#design-flow).
- [ ] Check the tutorials under the `tutorial` folder too. Notice that the tutorials shown on qiskit metal tutorials page are under the `tut` folder on the Github repo. On that repo, we have [another `tutorials` folder](https://github.com/Qiskit/qiskit-metal/tree/main/tutorials) with more tutorials, check if they are the same or not and try to figure out why are they on that folder instead of in the one that is built on the page

**Comment by 1ucian0** [comment]
As the content audit was deprioritized (see https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#issuecomment-1477909804), closing for now.
