### ISSUE TITLE
Categorize content on qiskit partners documentation

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1430]
Classify the tutorials on the following links using the description table defined on [this structure](https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#:~:text=a%20summary%20with-,this%20structure). You can add your summary on a comment below

- [ ] Categorize [qiskit partners ionq installation](https://qiskit.org/documentation/partners/ionq/guides/install.html)
- [ ] Categorize [qiskit partners iong usage](https://qiskit.org/documentation/partners/ionq/guides/usage.html)
- [ ] Categorize [qiskit partners runtime overview](https://qiskit.org/documentation/partners/qiskit_runtime/)
- [ ] Categorize [qiskit partners runtime getting started](https://qiskit.org/documentation/partners/qiskit_runtime/getting_started.html)
- [ ] Categorize [qiskit partners runtime circuit runner](https://qiskit.org/documentation/partners/qiskit_runtime/example_scripts/circuit_runner.html)
- [ ] Categorize [qiskit partners runtime Quantum Kernel Alignment](https://qiskit.org/documentation/partners/qiskit_runtime/example_scripts/qka.html)
- [ ] Categorize [qiskit partners runtime tutorials](https://qiskit.org/documentation/partners/qiskit_runtime/tutorials.html)
- [ ] Categorize [qiskit partners mthree installation](https://qiskit.org/documentation/partners/mthree/installation.html)
- [ ] Categorize qiskit partners mthree user guides. There isn't an index page, so I add here the links to the user guides:
  - [ ] [Basic usage ](https://qiskit.org/documentation/partners/mthree/basic.html)
  - [ ] [Transpiled circuits](https://qiskit.org/documentation/partners/mthree/transpiled.html)
  - [ ] [Expectation values](https://qiskit.org/documentation/partners/mthree/expvals.html)
  - [ ] [Using collections](https://qiskit.org/documentation/partners/mthree/collections.html)
  - [ ] [Error analysis](https://qiskit.org/documentation/partners/mthree/error.html)
  - [ ] [Obtaining probabilities](https://qiskit.org/documentation/partners/mthree/probs.html)
  - [ ] [Saving and loading calibrations](https://qiskit.org/documentation/partners/mthree/cal_io.html)
  - [ ] [Utility functions](https://qiskit.org/documentation/partners/mthree/utils.html)
  - [ ] [Advanced usage](https://qiskit.org/documentation/partners/mthree/advanced.html)
- [ ] Categorize qiskit partners mthree tutorials. There isn't an index page, so I add here the links to the tutorials:
  - [ ] [M3 paper example](https://qiskit.org/documentation/partners/mthree/tutorials/01_M3_ex1.html)
  - [ ] [Correcting probabilities](https://qiskit.org/documentation/partners/mthree/tutorials/02_correcting_probs.html)
  - [ ] [Quantum Volume](https://qiskit.org/documentation/partners/mthree/tutorials/03_qv_example.html)
  - [ ] [Basic mitigated VQE](https://qiskit.org/documentation/partners/mthree/tutorials/10_basic_vqe.html)

**Comment by 1ucian0** [comment]
As the content audit was deprioritized (see https://github.com/Qiskit/qiskit_sphinx_theme/issues/226#issuecomment-1477909804), closing for now.
