### ISSUE TITLE
Fix broken links and 404 pages

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1438]
As part of the audit done on #1418, I've discovered [some errors on the page](https://github.com/Qiskit/qiskit/issues/1418#issuecomment-1040541230). I've talked with the user research team and one of the main user pain points are broken links and 404 pages, so we should prioritize and fix them

**Comment by mar-galho** [comment]
I'd like to jump in and help with this. How should I proceed?

**Comment by agebbie** [comment]
@y4izus Am I good to close this issue?

**Comment by y4izus** [comment]
hey @agebbie , we should do another web audit and check if the broken links and the 404 pages are fixed. In that case, we could close the issue

**Comment by TKushT** [comment]
Yes. I'd like to know if the issues with broken links have been fixed. Else, I can jump on it

**Comment by y4izus** [comment]
@TKushT , the tool we were using for looking for broken links doesn't work for our project, so we can't give you an answer yet, sorry!

**Comment by 1ucian0** [comment]
I'm closing this issues for now so it probably needs more info on where are those 404s coming from.
