### ISSUE TITLE
Create an API Reference example [size: L]

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1445]
On Qiskit docs 2.0 we would like to divide documentation in different types using the divio framework. For that, we are working on a tutorials audit to see what kind of documentation we already have. It's not been easy because no file fits 100% the framework.

Following @HuangJunye suggestion, having an example of every type of documentation could help us with the categorization.

The idea is convert one of the tutorials we already have in an [API Reference that follows divio framework](https://documentation.divio.com/reference/). It would be nice to have both to compare the old and the new in order to understand what we need for that update. If we already have an example of API Reference, please, you could just add the link :)

**Comment by garrison** [comment]
I think the API reference can and should be built from the docstrings using Sphinx.  I'm not sure if there is any existing Qiskit module that is exemplary, but there might be.  In my opinion, this is the type of documentation that Qiskit is already pretty good at having and maintaining, as far as the Divio/Diataxis four categories go.

Are you envisioning something different than me for the API Reference documentation?

**Comment by HuangJunye** [comment]
@garrison I agree with you that the existing API reference is good enough. I think @yaiza created this issue just for completeness with other three types of documentation.

**Comment by garrison** [comment]
Related, I wish there were a style guide and/or additional guidelines for creating API docs, to be referenced especially when creating new docstrings.  For instance,

- [PEP 257](https://peps.python.org/pep-0257/) recommends
  > The docstring is a phrase ending in a period. It prescribes the function or method’s effect as a command (“Do this”, “Return that”), not as a description; e.g. don’t write “Returns the pathname …”.

  but this advice is followed inconsistently, only in some places.  Incidentally, [Google's Python style guide](https://google.github.io/styleguide/pyguide.html) actually provides the _opposite_ advice:

  > The docstring should be descriptive-style (`"""Fetches rows from a Bigtable."""`) rather than imperative-style (`"""Fetch rows from a Bigtable."""`).

  I prefer the PEP 257 style, as I seem to encounter that much more frequently.
- Google's Python style guide also contains the following advice:
  > The docstring for a `@property` data descriptor should use the same style as the docstring for an attribute or a [function argument](https://google.github.io/styleguide/pyguide.html#doc-function-args) (`"""The Bigtable path."""`, rather than `"""Returns the Bigtable path."""`).

  but I see the "Returns ..." wording used more frequently in Qiskit.
- Cross-references to other parts of the API docs (and the other documentation modes) are encouraged.

**Comment by HuangJunye** [comment]
While it was not intended for addressing this issue, I created module level API reference doc for this Terra issue which may serve as an example: https://github.com/Qiskit/qiskit-terra/pull/8121#issue-1253897989

If we stick with creating all examples in qiskit-ibm-runtime repo, I think these pretty good examples:

- Module level: https://qiskit.org/documentation/partners/qiskit_ibm_runtime/apidocs/ibm-runtime.html
- Class level:
  - https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.Estimator.html
  - https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.Sampler.html

If we think these examples are good enough. I can work on the guildlines and checklist and then improve these three examples.

**Comment by HuangJunye** [comment]
I think the main problem of using qiskit-ibm-runtime as examples are that the code can't be ran because a token is required to connect to the service and run. It was ok for tutorials because qiskit-ibm-runtime doesn't execute the notebooks in the build but instead take the results and images directly from the PR.

Perhaps we should use terra examples for API reference. 

- Module level: https://qiskit.org/documentation/apidoc/circuit.html
- Class level: https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html

**Comment by y4izus** [comment]
ok! let's continue with this API Reference as our example, thank you!!
