### ISSUE TITLE
Documentation link to experiments

### ISSUE THREAD

**Issue by coruscating** [Qiskit/qiskit-metapackage#1448]
### What is the expected enhancement?

The sidebar for [Qiskit docs](https://qiskit.org/documentation/) should have a link to Qiskit Experiments: https://qiskit.org/documentation/experiments/

**Comment by jakelishman** [comment]
I know @y4izus is driving a more major overhaul of how we present our documentation to the world, so she may well have plans.  As of right now, the sidebar links to the docs for the metapackage, which Experiments isn't a part of (other than as an extra).  Experiments has a big link in the top navigation, along with the applications-layer packages, though.

**Comment by coruscating** [comment]
I see your point, though former Ignis users are probably looking for a replacement, so it would be helpful to direct people to experiments, whether in the links or a note to send them to experiments when they click into the Ignis API reference.

**Comment by jakelishman** [comment]
This issue was obsoleted by the pivot towards the ecosystem approach.
