### ISSUE TITLE
Typo in Torch Runtime Tutorial

### ISSUE THREAD

**Issue by nataliaferrazzo** [Qiskit/qiskit-metapackage#1461]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
#: ../../tutorials/06_torch_runtime.ipynb:25

- What is the current text that needs to be fixed or removed? (You can copy and paste)

_"First, we show how to use Torch Runtime via ``TorchRuntimeClient`` using the simple regression example. In the example, we will perform a regression task on a randomly generated dataset following a **sin wave**."_

- What should the documentation say instead?

_"First, we show how to use Torch Runtime via ``TorchRuntimeClient`` using the simple regression example. In the example, we will perform a regression task on a randomly generated dataset following a **sine wave**."_

- Are there other related issues or pull requests about this bug?

No.

**Comment by Darshil9120** [comment]
I would like to work on this issue, so if this issue is unassigned I would like to take it up. Although I just have one question, for the broken links, should I replace them with same working links or should I erase the broken one and leave it as is?

**Comment by divshacker** [comment]
Hey @Darshil9120 you can work on this issue. You have to fix the broken links by replacing all broken links to working links. Do not leave it as it is. And make a PR after you fix all the things.

**Comment by Darshil9120** [comment]
Please assign this issue to me as I cannot find it in my assigned issues.

**Comment by HuangJunye** [comment]
@Darshil9120 Thank you but it turns out this issue has been fixed by https://github.com/Qiskit/qiskit-machine-learning/pull/366 If you are interested in making other contributions, please look for other issues in other qiskit repos such as [qiskit-terra good first issues](https://github.com/Qiskit/qiskit-terra/labels/good%20first%20issue).
