### ISSUE TITLE
Block sphere

### ISSUE THREAD

**Issue by Snuag** [Qiskit/qiskit-metapackage#1472]
If phi = 3π/2, and theta = π/2, then which basis state is represented on the Block sphere!?

**Comment by jakelishman** [comment]
Hello!  This isn't really the right place to ask questions - it's a bug tracker for Qiskit software.  You can join the public Qiskit Slack channels (https://ibm.co/joinqiskitslack) to ask general questions about quantum physics or how to use Qiskit, but people will usually be more inclined to help if you can show that you've tried to search and understand the problem yourself first.  For example, I just searched for "introduction to bloch sphere" and found [this page](https://you.stonybrook.edu/qcomputing/2018/07/06/bloch-sphere/) which might help you.

**Comment by Snuag** [comment]
Great thank you
