### ISSUE TITLE
Compare all runtime tutorials and create a checklist for good practices

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1475]

**Comment by HuangJunye** [comment]
A checklist is created based on https://diataxis.fr/ and adapted after using it to go through the [4 primitives qiskit-ibm-runtime tutorials](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials.html#primitives). @Guillermo-Mijares-Vilarino is reviewing the checklist and using it to review the qiskit-machine-learning tutorials (https://github.com/Qiskit/qiskit-machine-learning/issues/582)

**Comment by HuangJunye** [comment]
The draft is [here](https://ibm.ent.box.com/notes/967973419693) (requires access permission).

**Comment by HuangJunye** [comment]
The checklist has been reviewed and it can be considered be done.
