### ISSUE TITLE
Migriate ignis-based benchmarks to qiskit-experiments

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-metapackage#1485]
### What is the expected behavior?

The Qiskit benchmarks in `test/benchmarks` have several benchmarks which rely on code from Ignis to build, compile, and simulate circuits, and analyze results (e.g https://github.com/Qiskit/qiskit/blob/9d2359525d34e7ab67b1ac00dc5aa3cfedf4f2ff/test/benchmarks/state_tomography.py#L24 and https://github.com/Qiskit/qiskit/blob/684dfe5dbf25caff27081fe3d78331837d908f72/test/benchmarks/randomized_benchmarking.py#L63 ). With the release of qiskit-experiments, these should be updated to use the corresponding methods, and likely expanded to cover some use-cases from qiskit-experiments.

@gadial and @chriseclectic Any thoughts on what would pieces of experiments would be useful to benchmark here?

**Comment by chriseclectic** [comment]
RB and QST have direct replacements in qiskit-experiments.

Another thing that would be good to benchmark are ParallelExperiments of 1-qubit experiments across a larger number of qubits. We are thinking more about benchmarkings so maybe can add some more to here in the future
