### ISSUE TITLE
Rename `master` branch to `main` branch in this repo

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-metapackage#1493]
### What is the expected behavior?

Many (if not all) repos in qiskit github org has renamed `master` branch to `main` branch, we should do that in this repo as well. I am not sure about the implications and the steps to do that though.

**Comment by InfamousPlatypus** [comment]
Oh, it's easy. I just went and checked on one of the repos I started. I don't know how it works with different levels of contributors, or what permissions will be needed. It's just Settings>Branches (in the Code and Automation subdivision) and for the repo I tried it on (Which has only me and one branch, so it may be different) the first option is to edit the default branch. I don't know of any implications, and I think this was designed so there wouldn't be

**Comment by HuangJunye** [comment]
I am not sure if it is that simple. @mtreinish Can you shed some lights here? I did a quick search and found a few places with `master` https://github.com/Qiskit/qiskit/search?q=master

**Comment by jakelishman** [comment]
Yeah, actually swapping the "default" branch on GitHub is very easy, the extra bits are just making sure that all our hyperlinks point to the new default branch.  That's a bit harder, because there's probably quite a few places across a bunch of different Qiskit components, and possibly the textbook, that might need updating.

**Comment by jakelishman** [comment]
With this repo being sunset now, we won't be going ahead with a change.  Terra, which will for most purposes replace this repository, already uses `main` as its default branch.
