### ISSUE TITLE
As a user, I would like to have just one top menu across all the qiskit.org domain pages

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1510]
Right now, the top menu under qiskit.org change between the home page and the documentation page. In addition, inside the documentation page, the top menu changes 12 times. We need to have just one top menu in order to improve the UX and also the maintainability (just one place to update instead of 13).

Needed tasks:

- [x] [Design] Create a prototype for the top menu
- [ ] [Dev] Implement the top menu as web component and serve it on a cdn
- [ ] [Dev] Add the web component to the qiskit.org project
- [ ] [Dev] Add the web component to the qiskit sphinx theme
- [ ] [Dev] Remove top menu from the Qiskit/qiskit repo
- [ ] [Dev] Remove top menu from the Qiskit/qiskit-nature repo
- [ ] [Dev] Remove top menu from the Qiskit/qiskit-finance repo
- [ ] [Dev] Remove top menu from the Qiskit/qiskit-optimization repo
- [ ] [Dev] Remove top menu from the Qiskit/qiskit-machine-learning repo
- [ ] [Dev] Remove top menu from the Qiskit/qiskit-metal repo
- [ ] [Dev] Remove top menu from the Qiskit/qiskit-dynamics repo
- [ ] [Dev] Remove top menu from the Qiskit/qiskit-experiments repo
- [ ] [Dev] Remove top menu from the Qiskit/retworkx repo
- [ ] [Dev] Remove top menu from the Qiskit-Partners/mthree repo
- [ ] [Dev] Remove top menu from the Qiskit-Partners/qiskit-ionq repo

**Comment by 1ucian0** [comment]
The `[Dev] Remove top menu from the Qiskit* repo` bullets need a change in the sidebar to have the links as runtime https://qiskit.org/documentation/partners/qiskit_ibm_runtime/

```
Overview
Getting Started
Tutorials
How to
API Reference
FAQs
Release Notes
GitHub
```

**Comment by agebbie** [comment]
Transferring this issue [here](https://github.com/Qiskit/qiskit.org/issues/2702) to build it into the next sprint for the Digital Team so that it has more visibility.
