### ISSUE TITLE
documentation/apidoc/*.html -> documentation/apidocs/*.html

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1511]
It seems like all the modules use `apidocs/` (eg https://qiskit.org/documentation/nature/apidocs/qiskit_nature.html) while the metapackage refers to `apidoc/` (eg https://qiskit.org/documentation/apidoc/terra.html).
 It would be nice to unify the nomenclature there.

**Comment by jakelishman** [comment]
Closing as unimportant during the migration away from the metapackage, and we may actually do this as part of the merge through to Terra anyway.
