### ISSUE TITLE
As a user, I would like to see that the tutorials showed on the qiskit.org/learn page has good quality

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-metapackage#1517]
The [qiskit learn page](https://qiskit.org/learn) has changed and now we can see a section pointing to qiskit core tutorials. We already have [checklist](https://github.com/Qiskit/qiskit/issues/1475#issuecomment-1154962558) to be sure that all tutorials have the quality we want, so we should apply that checklist to the qiskit core tutorials:

- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1433
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1411
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1425
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1401
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1422
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1420

**Comment by HuangJunye** [comment]
Closing this issue because we are now using GitHub project to track milestone / epics.
