### ISSUE TITLE
qiskit ising matrix shape is very strange

### ISSUE THREAD

**Issue by astrung** [Qiskit/qiskit-metapackage#1563]
I have create a simple QUBO problem with 2 binary variables, but when I tried to get ISING matrix, it is very strange with shape (4,4), when I expect I will get a matrix Q with shape (2,2) due to this formula of ISING:
![ISING_formula](https://user-images.githubusercontent.com/9162294/177744665-19d13126-4f40-417f-843b-c1ad92d15576.png)

Why my ISING matrix dimension is increased ? Please help

This is my full code 

    from qiskit_finance.applications.optimization import PortfolioOptimization
    from qiskit_finance.data_providers import RandomDataProvider
    import datetime
    import dimod
    from qiskit_optimization.converters import QuadraticProgramToQubo

    num_assets = 2
    seed = 123

    stocks = [("TICKER%s" % i) for i in range(num_assets)]
    data = RandomDataProvider(
        tickers=stocks,
        start=datetime.datetime(2016, 1, 1),
        end=datetime.datetime(2016, 1, 30),
        seed=seed,
    )
    data.run()
    mu = data.get_period_return_mean_vector()
    sigma = data.get_period_return_covariance_matrix()

    q = 0.5
    budget = 1

    portfolio = PortfolioOptimization(
        expected_returns=mu, covariances=sigma, risk_factor=q, budget=budget
    )
    qp = portfolio.to_quadratic_program()
    print(qp)

    conv = QuadraticProgramToQubo()
    qubo_model = conv.convert(qp)
    ising = qubo_model.to_ising()
    ising_matrix = ising[0].to_matrix()
    print(ising)
    print(qubo_model)
    print(ising_matrix)

**Comment by woodsp-ibm** [comment]
The matrix is the matrix operator equivalent of the sum of paulis operator that comprises the ising operator. A pauli, I, X, Y, Z is represented as 2x2 matrix. For two qubits as single pauli string say "ZI" will be a tensor product of the two 2x2 matrices ( ie Z tensor I in this case ) and will be of size 4x4. The size in general will be 2^num_qubits.

**Comment by astrung** [comment]
thank you. I get the ideal that I want a optimization formula with ISING format, but qiskit `ising_matrix` will give me to `quantum ising matrix`, a different definition in quantum computing. So I decided to convert to ISING optimization formula by my hand. Thank you for your help.
