### ISSUE TITLE
IBM Quantum composure gives incorrect state-vector

### ISSUE THREAD

**Issue by vs9205** [Qiskit/qiskit-metapackage#1572]
### Informations
I'm using the IBM Quantum Experience Composer [portal](https://quantum-computing.ibm.com/composer).

- **Qiskit version: N/A**:
- **Python version: N/A**:
- **Operating system: N/A**:

### What is the current behavior?
![image](https://user-images.githubusercontent.com/42830600/180440130-d7f25a37-54a2-4556-b66c-dec9a613b5e3.png)

Applying H-gate and then apply Measurement give state-vector 
[ 0+0j, 1+0j ]

### Steps to reproduce the problem
Step1: Go to [portal](https://quantum-computing.ibm.com/composer).
Step2: Select 1 quantum and 1 classical bit
Step3: Apply H gate to 1st qubit
Step4: Set the number of shot to 1024 from 'setup and run'
Step5: Apply measurement to 1st qubit

 

### What is the expected behavior?
State-vector should be [ 0.707+0j, 0.707+0j ]

**Comment by prakharb10** [comment]
I believe your expected behaviour is incorrect. Since you're applying a measurement operation, the superposition will collapse and you'll get a deterministic result i. e. either |0⟩ or |1⟩.
If you remove the measurement operation, you should get the superposition state that you're expecting.

**Comment by 1ucian0** [comment]
I agree with @prakharb10 . @vs9205, fee free to reopen or comment further if you disagree.
