### ISSUE TITLE
As a Qiskit User I would like to be able to use the search bar on the docs site to search across all repos

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit-metapackage#1574]
Currently the search bar only returns results for the repo whose docs site you are currently viewing. It would be great if we could have a search bar that returns results for all repos, so that users don't need to know which specific package a feature belongs to if they are looking for documentation on it.

As an intermediate step it would be good to signpost more clearly in the search bar in the sidebar that using that search box will return results just for that specific package, not all qiskit packages. See Qiskit/qiskit_sphinx_theme#63

**Comment by woodsp-ibm** [comment]
FYI also Qiskit/qiskit#1223

**Comment by 1ucian0** [comment]
closing as dup, thanks @woodsp-ibm
