### ISSUE TITLE
How to highlight a gate in the image output of a circuit?

### ISSUE THREAD

**Issue by Co1lin** [Qiskit/qiskit-metapackage#1575]
### What is the expected behavior?

I want to highlight a gate or surround it with a box in the image output of a circuit, but I cannot find how to do it.

**Comment by Amana-L** [comment]
You can enclose a group of gates and represent as one on the quantum circuit by using the 'to_gate' method (with a label parameter) 
https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.to_gate.html

**Comment by jakelishman** [comment]
Sorry that this didn't get a maintainer response at the time.  Qiskit isn't really a general-purpose visualisation library; we have some minimal visualisations to assist with development, but for a fully featured graphics package for quantum-circuit visualisation, it's out of scope for us.  If there's more to be said, please open an issue on Qiskit/qiskit-terra, but for the most part, additional visualisation features will likely not be considered in scope for the library.
