### ISSUE TITLE
Add how-to guides section on the sidebar

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-metapackage#1590]
In order to [add how-to guide example to Terra](https://github.com/Qiskit/qiskit-terra/issues/7965), we need to add a new section on the documentation side bar so that users can discover it.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/7631333/185358694-990fc9e5-8bf4-4e1c-a602-518bbf29825c.png">

**Comment by alt-shreya** [comment]
are you looking for contributors for this issue? I'd like to help!

**Comment by javabster** [comment]
closing this as it is covered by work in https://github.com/Qiskit/qiskit_sphinx_theme/issues/70
