### ISSUE TITLE
Qiskit header image includes qiskit-dynamics but it is not in the docs structure

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#1600]
How does one find `qiskit-dynamics`that is shown in the header figure from within the docs?

**Comment by jakelishman** [comment]
It's technically here: https://qiskit.org/documentation/dynamics/, but the Sphinx theme released the new landing page before the PR that sorted out the top nav bar.  The tracking issue for fixing the top nav bar is Qiskit/qiskit_sphinx_theme#64.

Perhaps in the interim, the SVG image could grow some hyperlinks to the correct parts of the documentation?

cc: @javabster
