### ISSUE TITLE
Label Qiskit github issues by classical software or quantum software category

### ISSUE THREAD

**Issue by pemmaras** [Qiskit/qiskit-metapackage#1605]
### What is the expected behavior?
If an issue is a purely classical software or services level bug/feature that does not require any familiarity with quantum computing to address, it should be labelled as such.  This will help expert software developers who are not yet familiar with quantum computing to contribute to the code base at a level that is commensurate with their expertise on the classical computing side.  The "good-first-issue" label does not seem to cover such scenarios.

**Comment by jakelishman** [comment]
Is this something that you personally have struggled with?  I'm curious if there is a concrete user story behind the request, or if this is just prospective.  I'm not keen to add further processes for maintainers without solid data that it is necessary.

We already put a good amount of effort into classifying issues that we deem suitable for contributors with the "good first issue", "help wanted" and "short project" labels, the enhanced problem/solution descriptions that go along with those labels, and the maintainer burden of helping new external contributors handle the Qiskit review/standards processes.  I'm concerned (as one of the primary maintainers / contact points for external contributors) that adding more classification levels will add more burden on maintainers, and make them less likely to put in the effort to make an issue suitable for external contributors.

A contributor who wishes to get involved, especially the hypothetical (?) expert in this question, would be expected to do some amount of work to integrate with the development process.  This can mean that they evaluate issue suitabilities themselves - not everyone has the knowledge for everything.  There really aren't _that_ many open "help wanted" or "short project" issues even on Terra (which has by far the most).  I also imagine there will be only _very_ infrequent issues that we consider "good for external contributions" (not all issues are) and that can only be handled by this expert, which makes me question the usefulness of the label.

**Comment by pemmaras** [comment]
Hi @jakelishman, Yes, my organization is looking to divert developer resources to help close Qiskit issues and I have been informed it is a significant barrier right now for experienced classical developers to quickly start working on software/services issues that they are not marked as such. 

I have personally been putting together spreadsheets manually categorizing issues as quantum/non-quantum so that our developer teams can more quickly start work on them.  

Obviously lower level pulse/circuit libraries will have relatively few "non-quantum" issues but higher level UX, tooling, cloud services or application level modules might have plenty of such issues especially in the medium term if they are designed to abstract away circuit level details.

**Comment by jakelishman** [comment]
For others watching this: @1ucian0 is the lead for our general open-source policy decisions, which are happening internally.  There is a tension to resolve here around more people wanting to provide code than we have resources to support.  We are very thankful for external help, but we do not necessarily want it on issues that have not been tagged in some form as "the maintainers are happy to accept a PR on this subject", because this may overwhelm us.  In particular, the existence of an issue is not sufficient to say we would accept a PR on it.

While we are working out the full details of our policies, we do ask that any prospective contributors respect our processes, and do not begin significant work on issues that are not tagged with "good first issue", "help wanted" or "short project" without prior consent from a maintainer.

**Comment by pemmaras** [comment]
Thanks @jakelishman , this is really useful information to inform near term decision making! Appreciate this perspective from the maintainer side!

**Comment by 1ucian0** [comment]
After talking off-band with @pemmaras, we agreed this would transfer a significant amount of work to maintainer's shoulder in exchange of a negligible amount of benefit for the contributor.

Therefore, closing as wontfix.
