### ISSUE TITLE
Qiskit docs search is broken

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#1636]
The search feature of the Qiskit docs is broken.  From experience, this happens when modifying the theme files erroneously.

**Comment by 1ucian0** [comment]
Fixed by https://github.com/Qiskit/qiskit_sphinx_theme/pull/139 ( Thanks @HuangJunye !) in sphinx theme 1.10.1.

**Comment by 1ucian0** [comment]
Fixed by https://github.com/Qiskit/qiskit_sphinx_theme/pull/139 ( Thanks @HuangJunye !) in sphinx theme 1.10.1.
