### ISSUE TITLE
Remove Aer and IBMQ provider from the sidebar 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1643]
Currently, the side bar includes *Qiskit Aer* and *Qiskit IBM Quantum Provider* as part of the sidebar.

![sidebar](https://user-images.githubusercontent.com/766693/206705010-d9f30309-4ffb-4d26-a5b1-f2aafd88d492.png)

As the metapackage deprecated the inclusion of these modules (and will be removed mid-2023) I think is time to remove them from the sidebar.

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

`docs/index.rst`

- What content needs to be updated or replaced? (You can copy and paste)

```udiff
  API Reference <apidoc/terra>
  circuit_library
- aer
- ibmq-provider
  release_notes
  configuration
```

- What new content needs to be added?

None.

**Comment by jade-emperror** [comment]
giving it a shot. My first Contribution.

**Comment by jade-emperror** [comment]
@1ucian0 i can see AER and ibmq-provider is moved to Other Api Reference section recently. do we have to remove them from Other API Reference section ?

**Comment by HuangJunye** [comment]
@jade-emperror Thanks for proposing to help. We need to wait for qiskit-aer to [have its own documentation](https://github.com/Qiskit/qiskit-aer/pull/1589) (which should happen in Feb) and for qiskit-ibmq-provider we need to keep it on the sidebar until it’s archived (targeted in July). The PR itself is relatively simple but it requires coordination with other maintainers so I think it's not very suitable for external contributions. 

How would you feel about instead looking for some other issues to contribute? You can look for the good first issues label in qiskit repos, for example, qiskit-terra: https://github.com/Qiskit/qiskit-terra/contribute. We'd love help with any of those!

**Comment by jade-emperror** [comment]
@HuangJunye Thanks for your response. i will look on good first issues on other qiskit repos.

**Comment by Eric-Arellano** [comment]
@1ucian0 is this no longer on hold, now that both projects have their own docs?

**Comment by 1ucian0** [comment]
Both projects are still part of the current stable release (Qiskit 0.43). That is true until July. Let's remove them then.
