### ISSUE TITLE
Remove circuit library provider from the sidebar 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1644]
Currently, the side bar includes *Circuit Library* (in a singleton section called *Libraries*) as part of the sidebar.

![sidebar](https://user-images.githubusercontent.com/766693/206706530-a2a2359b-5e06-4e09-962f-604308f575f6.png)

The original goal was to highlight this feature. However, they link to the feature now is in the landing page, in much more prominent place:
![Circuit library link in the landing page](https://user-images.githubusercontent.com/766693/206706797-876cb31e-8b7c-4082-96ea-3977bbff497a.png)

This fulfils the original goal and the singleton section can be removed.

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

`docs/index.rst`

- What content needs to be updated or replaced? (You can copy and paste)

```udiff
  API Reference <apidoc/terra>
- circuit_library
  aer
  ibmq-provider
  release_notes
  configuration
```

- What new content needs to be added?

None.

**Comment by mtreinish** [comment]
To do this you will need to update terra, the circuit library is managed as a separate table of contents and source file in the apidocs pulled in from terra.

**Comment by HuangJunye** [comment]
This can be done after the next Terra release. See more details https://github.com/Qiskit/qiskit/pull/1638#issuecomment-1421070966
