### ISSUE TITLE
The documentation should be updated to reflect recent Qiskit package changes and the reasons behind

### ISSUE THREAD

**Issue by daka1510** [Qiskit/qiskit-metapackage#1647]
### Where is the problem?
In previous versions, there was a description that helped to quickly understand the different [elements](https://qiskit.org/documentation/stable/0.24/the_elements.html) (Terra, Aer, Ignis, Aqua). This made it clear how the APIs were split in Qiskit.

When I accessed the [documentation](https://qiskit.org/documentation/) today, I noticed this background information is no longer present and that two of the packages have been deprecated:
![image](https://user-images.githubusercontent.com/16404496/142440561-2de7068b-9dd9-4548-af9a-ff900c19bcc2.png)

### What is the problem?
While the individual packages include references to the newer APIs, it is not easy to understand the bigger picture from the high-level documentation. Some questions that I had today included
- **why** does Qiskit appear to be moving away from the current package structure? 
- **what** other changes can the community expect in this context (e.g. in https://github.com/Qiskit/qiskit-ibmq-provider)?

**Comment by IceKhan13** [comment]
@daka1510 Thanks for bringing it up! We are working on this moment! 
I will be posting updates here also

**Comment by jakelishman** [comment]
I'm closing this issue as obsolete now; the elements structure is long since dead.  Qiskit is actually currently re-focussing, but we're hopeful that our PR efforts through [our Medium blog feed](https://medium.com/@qiskit) and through IBM Quantum news feeds will be communicating this sort of thing more clearly.
