### ISSUE TITLE
Release notes take a long time to load

### ISSUE THREAD

**Issue by king-p3nguin** [Qiskit/qiskit-metapackage#1653]
Current documentation takes a long time to load release notes. Splitting the release notes into separate pages for each version might improve loading times.

**Comment by Eric-Arellano** [comment]
Relates to https://github.com/Qiskit/qiskit/issues/1504

**Comment by jakelishman** [comment]
This issue is becoming obsolete as the current "release notes" file will become "legacy release notes" on Terra.  We may consider splitting it there, but for now, I'll close this issue as this repository is being sunset.
