### ISSUE TITLE
Can't use qiskit on Spyder neither on Jupyter

### ISSUE THREAD

**Issue by edan0314** [Qiskit/qiskit-metapackage#1665]
Hello, I'm a new python user and usually I use spyder for scientific means.
For a while I've been using Anancoda's Spyder, and had no problem untill now to install and use libraries.
However inthe past two days I've tryed to learn more about Quantum Computation and can't use Qiskit in Spyder neither in Jupyter (where most recommend to use it).
I followed these instructions:

https://www.youtube.com/watch?v=1kRfHNUbkrg

Everything worked fine in tha installation but when I try to use it in the programs cited before  it shows:
On Spyder:

Traceback (most recent call last):

  File C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\user\desktop\lsst\python\untitled0.py:8
    from qiskit import *

ModuleNotFoundError: No module named 'qiskit'

On Jupyter:

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from qiskit import *

ModuleNotFoundError: No module named 'qiskit'
And I have o idea what is going on

**Comment by jakelishman** [comment]
Sorry that this never got responded to at the time.  This will have been a problem in your virtual environment setup; you may have not activated the virtual environment that had Qiskit installed, or maybe you installed Qiskit globally and then were working in a virtual environment.

At either rate, it's very unlikely that there was a bug in Qiskit.  I'm going to close this issue now as part of the work to sunset this now-superfluous repository, but if you're still struggling, consider asking tech-support questions on [the public Qiskit slack](https://qisk.it/join-slack/).
