### ISSUE TITLE
Simplify "Contributing to Qiskit" 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1667]
## Does existing documentation need to be updated with new content?

- Which files need to be updated?

https://qiskit.org/documentation/contributing_to_qiskit.html 

- What content needs to be updated or replaced? 

Currently, non-qiskit componentes are included in the guide. The references to [qiskit-aer](https://qisk.it/aer), [platypus](https://qisk.it/platypus), [qiskit-nature](https://qisk.it/nature), [qiskit-finance](https://qisk.it/python-finance), [qiskit-optimization](https://qisk.it/optimization), [qiskit-machine-learning](https://qisk.it/machine-learning), [qiskit-experiments](https://qisk.it/experiments), [qiskit-dynamics](https://qisk.it/Dynamics), and [qiskit-metal](https://qisk.it/qiskit-metal) can be removed.

That will significantly simplify the page.

**Comment by jakelishman** [comment]
I'm not really sure I agree with this - I get that we want to promote "Qiskit == Terra", but this page was written before then, and its intent was to help discoverability for first-time contributors who wanted to help with the greater Qiskit community (or whatever we call what _used_ to be Qiskit), but didn't even know what they could contribute to.  Even if we make the naming split, I think this page of "how can I find something to contribute to?" is valuable.  Even very long-term IBMers don't generally know every project in the flowchart, and it's segregated to help people with different skillsets find something.

People who already know enough to know the repository structure of Qiskit will (I'd think) still quickly find the `CONTRIBUTING.md` file in the repository they were interested in.  The people I've heard complaining about this page aren't its target audience (although admittedly, I have a large selection bias in that I'm only likely to hear from those people, and not the actual target audience).
