### ISSUE TITLE
Enable intersphinx extension

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1691]
From the conversation in https://github.com/Qiskit/qiskit-terra/pull/9771/files#r1132366803: 

> I believe that the `:class:` directive won't really create a link for `matplotlib.figure`, `PIL.Image` and `str`, because these are not classes documented in the scope of`qiskit-terra`. If I'm not misteken, It will just have the same effect as writing the text between backticks. Therefore... wouldn't it be clearer to use the backticks directly? (also, shouldn't `matplotlib.figure` be `matplotlib.figure.Figure` ?)
> 
> ```suggestion
>             :class:`.TextDrawing` or ``matplotlib.figure.Figure`` or ``PIL.Image`` or
>             ``str``:
> ```
> 
> FYI, you can add links to external documentation by:
> 
> 1. If they use sphinx to build their docs, you can use [intersphinx_mapping](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html)
> 2. Manually [adding a link](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#use-custom-link-text) to whatever URLs are of interest.
> 

_Originally posted by @ElePT in https://github.com/Qiskit/qiskit-terra/pull/9771#discussion_r1132366803_

**Comment by jakelishman** [comment]
Fixed by #1769.
