### ISSUE TITLE
Source text issue

### ISSUE THREAD

**Issue by owitczak** [Qiskit/qiskit-metapackage#1701]
In Crowdin string English source text https://crowdin.com/translate/qiskit-docs/9536/en-pl#278740 there is a missing ")" before full stop.
Here:

> Tier 1 platforms are currently:
> Linux x86_64 (distributions compatible with the [manylinux 2014](https://www.python.org/dev/peps/pep-0599/) packaging specification.

https://qiskit.org/documentation/stable/0.34/getting_started.html

I'm not sure if I added this PR correctly, please let me know if I should have submitted this somewhere else.

**Comment by jakelishman** [comment]
You've made an issue rather than a PR, but this is the correct place.  The relevant file that needs fixing is here, if you'd like to fix it? https://github.com/Qiskit/qiskit/blob/master/docs/getting_started.rst

**Comment by owitczak** [comment]
My apologies! I think I did it correctly now in the link above.

**Comment by Eric-Arellano** [comment]
Thanks for flagging this @owitczak! To clarify, you would want to make a pull request to this repository with a change to the `getting_started.rst` file: https://github.com/Qiskit/qiskit/blob/master/docs/getting_started.rst. Updating Crowdin will not fix the original English source.

https://opensource.guide/how-to-contribute/#opening-a-pull-request has a guide for how to open a pull request with open source projects.

**Comment by atharva-satpute** [comment]
I don't see a PR raised for this issue. Can I take this up?

**Comment by Eric-Arellano** [comment]
@atharva-satpute, that would be great!
