### ISSUE TITLE
qiskit does not install on the raspberry pi - stretch

### ISSUE THREAD

**Issue by dliloch** [Qiskit/qiskit-metapackage#171]
Get the following error when using pip3 install qiskit as instructed..
pip3 install qiskit
Gave me:
Could not find version that satisfies the requirement qiskit-aer==0.1.1 (from qiskit) (from version 0.1.0) No matching distribution found for qiskit-aer==0.1.1 (from qiskit)
Any guidance would be appreciated.. thanks.

**Comment by wpballa** [comment]
I hacked at this for a while on a model 3 B+. For the cryptography module you need libffi-dev
sudo apt-get install libffi-dev 
pip3 install -U qiskit qiskit-aer
but this fails with a  segmentation fault during the list of successfully installed modules. Apparently, the blas module is not getting fully installed as I get an error on libf77blas.so.3 when loading python modules in qrasp. It does appear that blas is where it ought to be in the linalg subdirectory of scipy.

**Comment by dliloch** [comment]
Bill,
Thanks for the reply.. I followed your instructions but I did sudo pip3 install -U qiskit qiskit-aer
I got to a point where it could not find opensslv.h .. so I installed libssl-dev
Got failed building wheel for qiskit
But then continued with running setup.py clean for qiskit
The “wheels” take forever!..
Failed to build qiskit .. but it keeps going ..with 
Installing collected packages:... and qiskit is one of them ..
Comes back around to 
Running setup.py for qiskit and it installs!
Then I tried python3 main_controller.py
And got libopenjp2.so.7 .. error so I installed libopenjp2-7
Then when I retry it comes up but I get 
The missing libatlas-base ... so I install libatlas-base-dev
It installed ok for me ...
Next when I moved the joystick to run the bell_calling_sense_func.py
I got errors for can’t import Aer ..
Looking on google:
https://stackoverflow.com/questions/12270954/difference-between-import-x-and-from-x-import
I found that I needed to change :
from qiskit import BasicAer as Aer
Then I can move through all 4 axis without errors and the graphs work..
Now comes the easy part .. understanding QM! (Never for me...)
-don
By the way I am running on raspbian stretch lite 4.14.98-V7+ #1200

**Comment by wpballa** [comment]
Don,
Thanks, that worked, but only on a clean install of the 11-18 stretch lite version. I had independently installed SciPy and NumPy on the system for an earlier project, and there must be some version conflict between Qiskit and the Raspian version. 
Bill

**Comment by ordmoj** [comment]
Thanks much @wpballa and @dliloch for this post. Got stuck on my qiskit 0.61 to 0.7 upgrade on the Qrasp (PI 2B). Per your tip above had to resort to `pip3 install -U qiskit qiskit-aer qiskit-ignis` to get it to power through. Also had issues with wheel, and not everything seems to have "taken". Enough there to run the Qrasp though. Qiskit 0.7 support now validated: https://github.com/ordmoj/qrasp/blob/master/README.md

**Comment by jaygambetta** [comment]
@nonhermitian I think this is really a issue for the future or on hold for a owner that wants to make sure qiskit works on raspberry pi.

**Comment by nonhermitian** [comment]
It works on my pi.  I used https://github.com/jjhelmus/berryconda.

**Comment by ordmoj** [comment]
Likewise, I got mine to work earlier this summer as well using berryconda!

**Comment by nonhermitian** [comment]
Ok closing then
