### ISSUE TITLE
Proposals/RFCs: Communicate and collaborate on broad design changes

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-metapackage#173]
Currently, there is no forum for proposing large scale Qiskit changes to our developers and community members. Github issues are better suited to smaller changes and do not easily serve as a wide-reaching, persistent and amendable document. Consider this recent [Terra issue](https://github.com/Qiskit/qiskit-terra/issues/1713) which is providing an overview of the proposed Pulse API. It was necessary to create this as a Github issue to expose it to the community. This is not the proper medium since it is difficult to track changes to the document and have community members review specific sections.

Other opensource projects have created different solutions for the above problem and have created a proposal document repositories with clear submission and acceptance guidelines:
- Python: [PEPs](https://www.python.org/dev/peps/)
- Tensorflow:  [TF-RFCs](https://github.com/tensorflow/community/blob/master/governance/TF-RFCs.md)

**Comment by dongreenberg** [comment]
+1, great idea

**Comment by derivation** [comment]
@lerongil is this something you'd like to take up?

**Comment by jaygambetta** [comment]
@nonhermitian can you think about this or close it if we dont have the time to make this possible. I think it is a good idea just we are too small to do it now.

**Comment by taalexander** [comment]
This is now closed with the creation of the [RFC repository](https://github.com/Qiskit/rfcs)
