### ISSUE TITLE
broken links in release notes

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1739]
This is a check of https://qiskit.org/documentation/release_notes.html on https://www.deadlinkchecker.com/ - May 12, 2023

<b style="color: rgb(0, 0, 0); font-family: Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><font color="green">100%</font><span> </span>scanned - 1530/1530 URLs checked, 1515 OK,<span> </span><font color="red">15 failed</font></b><br style="color: rgb(0, 0, 0); font-family: Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(0, 0, 0); font-family: Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> </span><br style="color: rgb(0, 0, 0); font-family: Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Error | URL | Anchor Text | Linked From
-- | -- | -- | --
404 Not Found | <https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html.> | scipy docs | https://qiskit.org/documentation/release_notes.html
403 Forbidden | https://dl.acm.org/doi/10.1145/3445814.3446706 | “Time-optimal qubit mapping” | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.org/documentation/retworkx/apiref/retworkx.spring_layout.html | function | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.github.io/openqasm/ | OpenQASM 3 specification | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.org/documentation/retworkx/stubs/retworkx.vf2_mapping.html | retworkx | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.github.io/openqasm/language/openpulse.html | OpenPulse | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://github.com/Qiskit/qiskit-aer/issue/1351 | Qiskit/qiskit-terra#1351 | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://github.com/Qiskit/qiskit-aer/issue/1347 | Qiskit/qiskit-terra#1347 | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://github.com/Qiskit/qiskit-aer/issue/1346 | Qiskit/qiskit-terra#1346 | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.org/documentation/_static/thebelab-helper.js | script/src | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.org/documentation/_static/js/vendor/popper.min.js | script/src | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.org/documentation/_static/js/vendor/bootstrap.min.js | script/src | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.org/documentation/_static/js/vendor/anchor.min.js | script/src | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://qiskit.org/documentation/_static/thebelab.css | link/href | https://qiskit.org/documentation/release_notes.html
404 Not Found | https://github.com/Qiskit/qiskit-aqua/blob/main/CHANGELOG.md | changelog [302 from https://github.com/Qiskit/qiskit-aqua/blob/master/CHANGELOG.md] | https://qiskit.org/documentation/release_notes.html

**Comment by shoaib6174** [comment]
Hello there,

I would like to work on this issue. Could I be assigned please?

**Comment by jakelishman** [comment]
This link checker appears to be inaccurate - several of these actually work.  Ones that have `retworkx` in them need to be updated to `rustworkx`, and the Aer issues are mostly just because in GH issues links, the correct URL has plural "issues" in the middle (as opposed to PRs, which just have the singular "pull").

The `script/src` links would be bugs to be filed against the Sphinx theme, if anything.  All the rest of these would need to be fixed on the metapackage, since that's where the `release_notes.rst` file lives.

**Comment by joeswashington** [comment]
I could also work on this issue @jakelishman. Not sure if multiple people can be assigned to one issue?

**Comment by shoaib6174** [comment]
> This link checker appears to be inaccurate - several of these actually work. Ones that have `retworkx` in them need to be updated to `rustworkx`, and the Aer issues are mostly just because in GH issues links, the correct URL has plural "issues" in the middle (as opposed to PRs, which just have the singular "pull").
> 
> The `script/src` links would be bugs to be filed against the Sphinx theme, if anything. All the rest of these would need to be fixed on the metapackage, since that's where the `release_notes.rst` file lives.


@jakelishman , I have updated all the links except `script/src`. I would need some more time to understand the Sphinx theme. Before creating the PR I would like to check the following with you to be sure- 

Among the updated links-
- I have replaced https://github.com/Qiskit/qiskit-aqua/blob/main/CHANGELOG.md with https://github.com/Qiskit/qiskit-aqua/#migration-guide as qiskit-aqua has been deprecated
- I have replaced https://qiskit.github.io/openqasm/ links with https://openqasm.com/
- I have followed your instruction for `retworkx` and gh issues 

I have made the changes in the `release_notes.rst` of qiskit-metapackage .  Is changing the links only in the `release_notes.rst` of qiskit-metapackage  sufficient as some of these broken links are present in the releasenotes of their own repo (such as: https://github.com/search?q=org%3AQiskit%20https%3A%2F%2Fqiskit.github.io%2Fopenqasm%2F&type=code)?

**Comment by 1ucian0** [comment]
Moving this issue to the meta-package (although, I think it would make sense to fix it them here too at some point, for consistency. But that's another issue).

Hi @shoaib6174, assigning you! Please PR your changes so we can talk on a case-by-case.

**Comment by Eric-Arellano** [comment]
A lot of these should be fixed by https://github.com/Qiskit/qiskit-metapackage/pull/1737.
