### ISSUE TITLE
Include hyperlinks to relevant sections and source

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-metapackage#175]
I was looking for information about the multi-controlled Toffoli gate in the documentation and found the oracles section. Which says

> More information on mct and its three modes can be found at mct.

https://qiskit.org/documentation/aqua/oracles.html
but it is not a hyperlink. So after some more searching I find the actual description of mct which says

> This technique relies on mcu1, see mcux for more information.

https://qiskit.org/documentation/aqua/algorithms.html
but again this is not a hyperlink. (Luckily it is the section right below mct) It would be great if these could be turned into hyperlinks (I think they are already marked with `:ref:`). There may be more cases that need to be checked too.

Since the documentation does not fully specify the actions of the gates, I think it would also be helpful to include a link to the source file.

**Comment by woodsp-ibm** [comment]
- The above links were fixed as part of PRs #360 and #362 
- As to linking to source from the documentation there is an issue #79 that addresses this more globally

Given the above I believe this issue can be closed.

**Comment by jaygambetta** [comment]
I am closing this as this is essentially #79. I know this is different files but as we move to an API we need someway to do this with the source code.
