### ISSUE TITLE
Aer roadmap

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#18]
@chriseclectic i put something in for Aer but i don't really like it could you update the Aer section of doc/roadmap.rst

**Comment by pistoia** [comment]
@chriseclectic please add a paragraph on the noise models.  @jaygambetta added a TODO embedded into the Aer roadmap.  I removed it from the text so the description is cleaner, so I am making this comment here in order for us not to forget the TODO entered by Jay.
