### ISSUE TITLE
There is no search in the documentation

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#180]
Usually there is a way to search through Sphinx docs.  For example:

https://docs.scipy.org/doc/numpy/index.html
https://matplotlib.org/contents.html
http://qutip.org/docs/latest/index.html

**Comment by derivation** [comment]
Relevant instructions for adding a search bar
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_sidebars

**Comment by derivation** [comment]
@carlosazaustre it looks like a search bar can be added by creating a stylized version of [this design](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/searchbox.html) and then adding the file to the relevant list in the Sphinx configuration file as per [these instructions]( https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_sidebars).

Would you be able to take this on?

**Comment by carlosazaustre** [comment]
I'll take a look and try it out to see if it works correctly.
@derivation, thanks a lot for providing the instructions :)
