### ISSUE TITLE
Unable to reinstall qiskit after a while

### ISSUE THREAD

**Issue by JoseManuelBerenguer** [Qiskit/qiskit-metapackage#198]
Hello, 

Some time ago, I installed qiskit and jupiter under anaconda and it worked quite well. Some examples did never work; nevertheless this was not a problem to learn some concepts about quantum computing.

After that, I have been working for a while in a lot of other things and now, beeing unable to run qiskit again, I decided uninstall ad reinstalling it. QISKitenv has also been removed from Anaconda and reactivated again. 

Reading some contributions I learned that perhaps  cmake was neded and so, I pipinstalled it 

After that, I wrote de command line : 

pip install qiskit

After some requirements satisfied, I got the following errors :

Building wheels for collected packages: qiskit
  Building wheel for qiskit (setup.py) ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4t/3k_h8js960x51wlvrmg1mtgh0000gn/T/pip-install-72gzaa9n/qiskit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/4t/3k_h8js960x51wlvrmg1mtgh0000gn/T/pip-wheel-qc_l9lsi --python-tag cp36:
running bdist_wheel
  
  ----------------------------------------
Failed building wheel for qiskit
Running setup.py clean for qiskit
Failed to build qiskit
Installing collected packages: requests, sympy, decorator, networkx, qiskit-terra, qiskit-aer, qiskit-ignis, qiskit
  Found existing installation: requests 2.18.4
    Uninstalling requests-2.18.4:
      Successfully uninstalled requests-2.18.4
  Found existing installation: sympy 1.1.1
Cannot uninstall 'sympy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Could you help me to get qiskit installed again? In the meanwhile, as I was running some HighSierra OS or so, now my OS is Mojave. Follows detains on my system 
MacBook Pro. MacBookPro11,5. Intel Core i7. 2,8 GHz
Nombre de processadors:	1
Nombre total de nuclis:	4
Memòria cau L2 (per nucli):	256 KB
Memòria cau L3:	6 MB
Memòria:	16 GB
Versió de la ROM d’arrencada: 187.0.0.0.0
Versió d’SMC (sistema):	2.30f2

Thank you for your help in advance

All the best

José Manuel

**Comment by lzdanski** [comment]
Hi Jose, I just updated some of the [installation docs](
https://qiskit.org/documentation/install.html#install), to address some similar feedback. 

Some of those error messages are expected, and it looks like someone else has hit a similar `sympy` problem (see this [Slack conversation](https://qiskit.slack.com/archives/C9YTUV077/p1553064741039600)) 

@maddy-tod recommended using `pip install qiskit --ignore-installed sympy` to address the sympy problem over Slack. Maybe that will help?

```
Failed building wheel for qiskit
...
Failed to build qiskit
```
Both are non-fatal error messages that print during installation. Your installation was probably successful, these two notes relate to a known problem.  See the [Release Notes](https://github.com/Qiskit/qiskit/releases/tag/0.7.3). 

You can see if the package installed correctly by using `conda list` to see all the installed packages in your conda virtual environment. If Qiskit installed successfully, you will see the Qiskit packages in the output list.

Also, you can find more help on [Stack Exchange](https://quantumcomputing.stackexchange.com/search?q=qiskit) and [Qiskit Slack](https://qiskit.slack.com/).

**Comment by ajavadia** [comment]
@JoseManuelBerenguer It is likely that your `sympy` is a conda installation, and pip cannot update it. So please try this and let us know if it solves your problem:
```
conda uninstall sympy
pip install qiskit
```

**Comment by JoseManuelBerenguer** [comment]
@ajavadia and @lzdanski

Thank you so much for your directions.  

I am so sorry for this big delay! I decided to use an old computer to run qiskit... and forgot this thread... 

I was retrying today in this computer, and after comand 

$conda uninstall sympy

I got : 

$ conda uninstall sympy
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - sympy

pip install qiskit and pip install qiskit --ignore-installed sympy run in the same errors I reported before...

also, command  I found in "installation docs" :

$source activate name_of_my_env

yelds the folloving :

"-bash: activate: No such file or directory"

Thank you so much for your patience

All the best

José Manuel
