### ISSUE TITLE
Provide conda package

### ISSUE THREAD

**Issue by we-taper** [Qiskit/qiskit-metapackage#218]
### What is the expected behavior?

Could you provide a conda or conda-forge source for `qiskit`.

**Comment by nonhermitian** [comment]
We have of course considered this. The main issue is that all of the dependencies must also be conda packages. Thus we would need to create and maintain those if the original authors cannot or are unwilling.

**Comment by we-taper** [comment]
Hi @nonhermitian , thanks for the reply.

I think then it helps if the install requirements are documented also in qiskit, and therefore people using conda could conveniently install the dependencies as suggested [here](https://www.anaconda.com/using-pip-in-a-conda-environment/).

From my experiments, I found that:

The following packages are inside conda:
> sympy jsonschema sympy jsonschema marshmallow  networkx  pillow ply psutil 

The following packages are inside conda-forge:
> ntlm-auth requests-ntlm

The only missing dependency is:
> marshmallow-polyfield

**Comment by nonhermitian** [comment]
Also pylatexenc is required for the latest version and is not in conda. 

To be clear, I am all in favor of a conda package, and am a conda forge member on github. However, the reality is that we would need to devote manpower to maintaining repos, and trying to make our somewhat convoluted packaging scheme work as a conda package.

It is on our list of things to do.

**Comment by jaygambetta** [comment]
labelling on hold as I agree with @nonhermitian we want this just have not had a chance to do it yet.

**Comment by nonhermitian** [comment]
Closing as this is not really an issue, but a request that is on the radar
