### ISSUE TITLE
update Release History

### ISSUE THREAD

**Issue by derivation** [Qiskit/qiskit-metapackage#220]
Update the [Release History](https://qiskit.org/documentation/release_history.html) doc page using the change logs of each Qiskit element and a synopsis.

- [Terra](https://github.com/Qiskit/qiskit-terra/blob/master/CHANGELOG.rst)
- [Aer](https://github.com/Qiskit/qiskit-aer/blob/master/CHANGELOG.rst)
- [Aqua](https://github.com/Qiskit/qiskit-aqua/blob/master/CHANGELOG.rst)
- [Ignis](https://github.com/Qiskit/qiskit-ignis/blob/master/CHANGELOG.md)

**Comment by mtreinish** [comment]
At least on the terra side I got this started with: #211 and the continuation of it is in progress on #213
