### ISSUE TITLE
Packages installed from source get overwritten if meta is installed, even if versions are higher

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#222]
### Informations

- **Qiskit version**: master
- **Python version**:
- **Operating system**: osx

### What is the current behavior?
If an user has the elements installed individually from source, for example, then if the user installs the meta-package, or another package depends on the meta-package, e.g. JKU provider, then the source installed versions get overwritten, even if their version numbers are higher than those in the latest meta-package from pip.

**Comment by mtreinish** [comment]
This is the tradeoff of having pinned 1:1 mappings between meta-package version. Installing `qiskit` is basically telling pip to install very specific versions of everything. `pip install -I` might workaround that but I'm not sure. That all being said the JKU provider requirements are wrong I pushed up https://github.com/Qiskit/qiskit-jku-provider/pull/65 to fix it

**Comment by nonhermitian** [comment]
Ok, that makes sense.  It is unfortunate that doing a canonical `setup.py install` runs into issues here, but I agree that pinning the versions in the meta is a higher priority.
