### ISSUE TITLE
Add mailmaps to element repos

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-metapackage#229]
### Informations

- **Qiskit version**: master
- **Python version**: n/a
- **Operating system**: n/a

### What is the current behavior?

Right now when you run the script used to generate the authors list (and then by extension the bibtex file)  it returns a lot of duplicate names or short names for people. This is because we're not so great about maintaining consistent on the author fields in git commits. Luckily git has a native solution for handling this exact problem, a mailmap file:

https://github.com/git/git/blob/master/Documentation/mailmap.txt

If we add a mailmap file to each repository tracked by the generate_authors script defining the overlap and the preferred output name (and email address) git will automatically return us a cleaner and consistent data set for all future runs of the script. 

We should have pushed for doing this as part of #15 and #59 but didn't think of it then. We can use the revision history from those PRs as a starting point.

### Steps to reproduce the problem

Run `tools/generate_authors.py`

### What is the expected behavior?

The same just with a better output that doesn't need as much hand tweaking

### Suggested solutions

Add mailmap files to all tracked elements.

- [x] Qiskit/qiskit (https://github.com/Qiskit/qiskit/pull/340)
- [x] Qiskit/qiskit-terra (https://github.com/Qiskit/qiskit-terra/pull/2666)
- [x] Qiskit/qiskit-aer (https://github.com/Qiskit/qiskit-aer/pull/283)
- [x] Qiskit/qiskit-ignis (https://github.com/Qiskit/qiskit-ignis/pull/223)
- [x] Qiskit/qiskit-aqua (https://github.com/Qiskit/qiskit-aqua/pull/604)
- [x] ~~Qiskit/qiskit-chemistry (https://github.com/Qiskit/qiskit-aqua/pull/592 )~~
- [x] Qiskit/qiskit-ibmq-provider (https://github.com/Qiskit/qiskit-ibmq-provider/pull/259)
- [x] Qiskit/qiskit-jku-provider (https://github.com/Qiskit/qiskit-jku-provider/pull/70)

**Comment by jaygambetta** [comment]
sounds good

**Comment by levbishop** [comment]
Sympy seems to have a well-tested workflow around this see https://github.com/sympy/sympy/wiki/Adding-Someone-to-AUTHORS and https://github.com/sympy/sympy/wiki/Using-.mailmap

**Comment by yehuda-naveh** [comment]
Added the .mailmaps for Ignis and JKU

**Comment by mtreinish** [comment]
@atilag @chriseclectic @pistoia @diego-plan9 can you take a look at this for aer, aqua, chemistry, and the ibmq provider. This is currently the only blocker for updating the authors list and bibtex file.

**Comment by chriseclectic** [comment]
@mtreinish Added in Aer PR #283

**Comment by jaygambetta** [comment]
is this still need to be open?

**Comment by mtreinish** [comment]
This is finished and mailmaps from all the repos are used by the generate_authors.py script. If there are weird names or inaccuracies in the authors list/bibtex we can address those by updating mailmaps in the element repos.
