### ISSUE TITLE
Aer section of release_history has links for PR numbers

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#234]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The Aer section of the `release_history.rst` has lnks that point no where for the PR numbers.  For example the first line in the Aer 0.2 section:
```
Added multiplexer gate :pull_aer:`192`
```
where ```:pull_aer:`192``` is highlighted as a link that just points to itself.

**Comment by derivation** [comment]
@nonhermitian that RST syntax is for a Sphinx extension called [extlinks](https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html) and creates the appropriate links in the [HTML doc](https://qiskit.org/documentation/release_history.html#aer-0-2) 

So, I'd say that this is not a bug.

**Comment by nonhermitian** [comment]
Huh, your right.  Those link texts that were in the html docs before are now replaced with the correct links
