### ISSUE TITLE
update Contributing for Qiskit 0.9

### ISSUE THREAD

**Issue by derivation** [Qiskit/qiskit-metapackage#238]
Needs link to Ignis repo.

Install Terra from source.  Step 4. Pip install . Means install qiskit-terra to the current working directory, so it’s not really installing. Should be `python setup.py install`.

**Comment by mtreinish** [comment]
Umm I'm not sure what you think is wrong with step 4 on the terra install, but `pip install .` means install the package located in the current working directory. Which at that point in the instructions is the terra repo root. It is essentially the same as calling `python setup.py install` see my comment in It doesn't mean install to the current working directory.

**Comment by mtreinish** [comment]
See my comment here for more details: https://github.com/Qiskit/qiskit/pull/207#discussion_r279474595

**Comment by nonhermitian** [comment]
Ok yes, this is my mistake in reading the pip docs.  However, I still think it should be replaced with `setup.py install` as that is the standard way to install Python packages, not via pip.

For example: https://docs.scipy.org/doc/numpy/user/building.html

**Comment by mtreinish** [comment]
That was definitely the case pre-python 3.4 (which we don't support anyway) but as things moved forward in the python community (especially after pip is bundled in cpython now) the recommend way to install local packages from source is pip: https://packaging.python.org/tutorials/installing-packages/#installing-from-a-local-src-tree

**Comment by nonhermitian** [comment]
Fair enough.  Let's stick with pip.
