### ISSUE TITLE
update Development Strategy for Qiskit 0.10 release

### ISSUE THREAD

**Issue by derivation** [Qiskit/qiskit-metapackage#266]
@lerongil please update [this file](https://github.com/Qiskit/qiskit/blob/master/docs/development_strategy.rst) to reflect the current dev strategy

**Comment by lerongil** [comment]
This development strategy is for 2019 and is still valid. We are missing the module status for basic aer, aer provider and Ignis. #297 and #296 will cover the missing sections. 

I updated to remove the dated sentence plus some minor typos here: #305 .
