### ISSUE TITLE
 Qiskit is failing when updating to 0.7 from previous versions

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-metapackage#27]
The root cause of https://github.com/Qiskit/qiskit-terra/issues/1599 is as follows:

When upgrading, `pip` resolves the dependency tree of a package so that dependencies are installed before dependants. Finally, it installs the target package. During any of these installations, if there is a previous version of the package, `pip` first uninstalls the previous version, then it installs the new one.

When uninstalling a package, `pip` reads a record file listing all the files belonging to that package. Previous `qiskit` included all Terra files (now belonging to the `qiskit-terra`) and those get removed from the file system. Indeed, `pip` does not check if the files being removed belong to other packages.

**Comment by t-imamichi** [comment]
The solution looks great. Do I still need to update the install.rst as requested in https://github.com/Qiskit/qiskit-terra/issues/1599#issuecomment-452061591?

**Comment by t-imamichi** [comment]
Did it ship with qiskit-0.7.1? I tried to upgrade qiskit-0.6.1 to 0.7.1 by `pip install -U qiskit`, but it failed. I attach the [log](https://gist.github.com/t-imamichi/cb7ab7c3294fa116e6cba53f8770026d).

**Comment by delapuente** [comment]
Thank you for the log: it's been very helpful. I'm describing what happens here:

After downloading any package and **before** installing it, if the `wheel` package is present, `pip` tries to create a [wheel distribution](https://pip.pypa.io/en/stable/reference/pip_wheel/#id4) of the package. While installing, if there is a wheel version, `pip` uses it instead and avoids running `setup.py`. Since `setup.py` is never run, `qiskit-terra` is never reinstalled.

The proposed solution is to intentionally fail the build of the wheel so this won't be present while installing the package.
