### ISSUE TITLE
Remove the workaround for upgrading from terra <0.7

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-metapackage#271]
### Informations

- **Qiskit version**: >=0.7
- **Python version**: Any
- **Operating system**: Any

### What is the current behavior?

When installing the qiskit meta-package we have a workaround that relies on pip internals to force alternate commands when upgrading from qiskit<0.7 to qiskit-terra>=0.7. This is because in the 0.7 release we switched to a namespace package and split terra and aer. The qiskit metapackage owns the qiskit package name, but terra still owns the python namespace. However these workarounds involve forcing the wheel build to fail which leads to confusing errors being printed:
```
Building wheels for collected packages: qiskit
  Building wheel for qiskit (setup.py) ... error
  ERROR: Complete output from command /tmp/fun/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-hn0ryofy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ba18zhoz --python-tag cp37:
  ERROR: running bdist_wheel
  ----------------------------------------
  ERROR: Failed building wheel for qiskit
  Running setup.py clean for qiskit
Failed to build qiskit
Installing collected packages: qiskit
  Running setup.py install for qiskit ... done
Successfully installed qiskit-0.10.0
```

The lines starting with error are also printed in red on color terminals. This is very confusing for users and we get at least 1 person per week trying to install qiskit who is concerned about this.

### Steps to reproduce the problem

`pip install qiskit`

### What is the expected behavior?

No error messages during that command

### Suggested solutions

It's more a discussion about when we can remove these workarounds. At some point we can just say we don't support pip upgrades from <0.7.0 to anything newer. If you're using an old version uninstall and reinstall manually with:

`pip uninstall qiskit`
`pip install -U qiskit`

**Comment by jaygambetta** [comment]
I am good with this -- lets do It and we can have in the faq that only updates form qiskit 0.8 wok

**Comment by wo3kie** [comment]
Hi,
Looks like this change will fix my issue with Qiskit installation on Windows WSL using bazel

```
$bazel run //... 
...
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/qiskit_terra-0.7.2.dist-info'
...
File "/tmp/pip-build-1kxgnhe4/qiskit/setup.py", line 25, in _reinstall_terra
    [sys.executable, "-m", "pip", "install", "--no-deps", "-I", qiskit_terra])
File "/usr/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.7', '-m', 'pip', 'install', '--no-deps', '-I', 'qiskit-terra>=0.7,<0.8']' returned non-zero exit status 2.
```

Using pip instead of bazel I am getting the same error

```
$ /usr/bin/python3.7 -m pip install --no-deps -I "qiskit-terra>=0.7,<0.8"
Collecting qiskit-terra<0.8,>=0.7
  Using cached https://files.pythonhosted.org/packages/2b/4e/9773bed15c2de457bb47b643eeeff24f7f0a7aa28c852d2a32292c694355/qiskit_terra-0.7.2-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: qiskit-terra
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/qiskit_terra-0.7.2.dist-info'
Consider using the `--user` option or check the permissions.
```

however this works

```
$ /usr/bin/python3.7 -m pip install --user --no-deps -I "qiskit-terra>=0.7,<0.8"
Collecting qiskit-terra<0.8,>=0.7
  Using cached https://files.pythonhosted.org/packages/2b/4e/9773bed15c2de457bb47b643eeeff24f7f0a7aa28c852d2a32292c694355/qiskit_terra-0.7.2-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: qiskit-terra
Successfully installed qiskit-terra-0.7.2
```

Can you merge it finally?

Regards,
Łukasz
