### ISSUE TITLE
Aqua doc link dead

### ISSUE THREAD

**Issue by nubbyOne** [Qiskit/qiskit-metapackage#280]
See this page:
https://qiskit.org/documentation/aqua/optimization/qiskit_optimization.html

Under "Examples", the link referenced by " Aqua Tutorials GitHub Repository " points to "https://github.com/Qiskit/aqua-tutorials" and that doesn't exist ...rather I think you want "https://github.com/Qiskit/qiskit-aqua".

I am pretty sure there is software that can be used to check whether page links are dead or up-to-date.

**Comment by nubbyOne** [comment]
Plus these:
1) Go here: https://qiskit.org/documentation/aqua/algorithms.html

Under VQE section click link " Aqua provides a tutorial detailing this use case."


2) Go here : https://qiskit.org/documentation/aqua/execution.html#aqua-input-file

The aqua tutorial link in these sentences: 
"A number of sample JSON input files for Aqua are available in the aqua/input_filessubfolder of the Aqua Tutorials GitHub repository."

"Experiments can be run programmatically too. Numerous examples on how to program an experiment in Aqua can be found in the aqua folder of the Aqua Tutorials GitHub repository."

"There is nothing preventing a user from accessing the Aqua APIs and programming an experiment step by step, but a more direct way to access Aqua programmatically is by obtaining a JSON algorithm input file, such as one of those available in the aqua/input_files subfolder of the Aqua Tutorials GitHub repository."

**Comment by derivation** [comment]
@pistoia is there someone from your team you'd like to have ownership+responsibility over general maintenance of Aqua docs?

**Comment by lerongil** [comment]
@derivation Can we add Marco Pistoia and Steve Wood as code owners for the Aqua documentation?
