### ISSUE TITLE
Document average performance of popular algorithms

### ISSUE THREAD

**Issue by LifeIsStrange** [Qiskit/qiskit-metapackage#282]
What are the Tflops of IBM Q System One?
How much order of magnitude slower is this computer vs an ordinary Intel cpu?
Are there one example with a proof of quantum speedup? Does it exist at all?

Those are the questions that everybody should be asking before getting into quantum programming.

**Comment by derivation** [comment]
Hi @LifeIsStrange. These are indeed all good questions. However, I'm not sure Qiskit documentation is the best place to expand on these. First and foremost, the documentation should help folks use Qiskit, which they'd presumably be doing after they've gotten answers to the questions you posed, especially the last two. 

IBM Q has material relevant to your questions in the following marketing pages:
- [technical specs of IBM Q's quantum computers, accessible via Qiskit](https://www.research.ibm.com/ibm-q/technology/devices/)
- [info on the companies and academies using Qiskit on IBM Q systems](https://www.research.ibm.com/ibm-q/network/overview/)
- [proof of quantum advantage](https://www.ibm.com/blogs/research/2018/10/quantum-advantage-2/)

Of course, the other players in quantum computing have their own real world use-cases, technical specs, and prognostications.

For these high-level questions, you're welcome to join in on the [Qiskit Slack channel](https://qiskit.slack.com/).
