### ISSUE TITLE
standard the docs for installing from source

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#299]
In the installing from source section can we make the elements all the same. Currently we tell the user how to install terra from source and then in the contributing file in the terra element we link to this documentation. In all the other elements in the documentation we link to the contributing file in element. 

I recommend that we make them all like terra.

**Comment by mtreinish** [comment]
This is fixed by: https://github.com/Qiskit/qiskit/pull/318 and https://github.com/Qiskit/qiskit/pull/317
