### ISSUE TITLE
Backend_monitoring_tools broken link 

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metapackage#310]
The link provide on the page 

> https://qiskit.org/documentation/terra/backend_monitoring_tools.html 

under the text

> There are also Jupyter magic equivalents that give more detailed information, as demonstrated here: Jupyter tools for Monitoring jobs and backends

leads to a 404 not found page.

**Comment by RohitMidha23** [comment]
@jaygambetta I guess you can close this issue now
