### ISSUE TITLE
Unknown Error !

### ISSUE THREAD

**Issue by matrixbot123** [Qiskit/qiskit-metapackage#313]
this below is me trying hard to install qiskit the copy of error

C:\Users\admin\PycharmProjects\untitled>pip install qiskit
Collecting qiskit
  Using cached https://files.pythonhosted.org/packages/49/db/79e953e4353a00a85b478dac37fe6b5523ecaf2cee5193dc9de4a0c767d2/qiskit-0.10.3.tar.gz
Requirement already satisfied: qiskit_terra==0.8.1 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit) (0.8.1)
Requirement already satisfied: qiskit-aer==0.2.1 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit) (0.2.1)
Requirement already satisfied: qiskit-ibmq-provider==0.2.2 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit) (0.2.2)
Requirement already satisfied: qiskit-ignis==0.1.1 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit) (0.1.1)
Collecting qiskit-aqua==0.5.1 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/3e/54/c24fafbce45a7fc3d018ada5c45a5b71f3760b5ee65029ab290f43aa2672/qiskit_aqua-0.5.1-py3-none-any
.whl
Collecting qiskit-chemistry==0.5.0 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/41/35/6b10aa3ea2fbe1b64cb0c3b2eaecb23cff044b574b151e8adc9ab9fbfe9a/qiskit_chemistry-0.5.0-py3-non
e-any.whl
Requirement already satisfied: marshmallow<3,>=2.17.0 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit)
 (2.19.2)
Requirement already satisfied: ply>=3.10 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (3.11)
Requirement already satisfied: marshmallow-polyfield<4,>=3.2 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->
qiskit) (3.2)
Requirement already satisfied: jsonschema<2.7,>=2.6 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (
2.6.0)
Requirement already satisfied: networkx>=2.2 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (2.3)
Requirement already satisfied: sympy>=1.3 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (1.4)
Requirement already satisfied: scipy>=1.0 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (1.3.0)
Requirement already satisfied: pylatexenc>=1.4 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (1.5)
Requirement already satisfied: pillow>=4.2.1 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (6.0.0)
Requirement already satisfied: numpy>=1.13 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (1.16.4)
Requirement already satisfied: psutil>=5 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit_terra==0.8.1->qiskit) (5.6.2)
Requirement already satisfied: requests>=2.19 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit-ibmq-provider==0.2.2->qiskit)
 (2.22.0)
Requirement already satisfied: requests-ntlm>=1.1.0 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit-ibmq-provider==0.2.2->q
iskit) (1.1.0)
Requirement already satisfied: websockets<8,>=7 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit-ibmq-provider==0.2.2->qiski
t) (7.0)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit-aqua==0.5.1->qiskit) (0
.21.2)
Collecting cvxopt (from qiskit-aqua==0.5.1->qiskit)
  Using cached https://files.pythonhosted.org/packages/00/02/13657bcd12d93f53b64a19b68d204f43d5f3247c29287c9eaeefcfa58fb9/cvxopt-1.2.3.tar.gz
Requirement already satisfied: fastdtw in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit-aqua==0.5.1->qiskit) (0.3.2)
Requirement already satisfied: setuptools>=40.1.0 in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages (from qiskit-aqua==0.5.1
->qiskit) (40.8.0)
Requirement already satisfied: quandl in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit-aqua==0.5.1->qiskit) (3.4.8)
Requirement already satisfied: dlx in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit-aqua==0.5.1->qiskit) (1.0.4)
Requirement already satisfied: docplex in c:\users\admin\appdata\roaming\python\python37\site-packages (from qiskit-aqua==0.5.1->qiskit) (2.9.141)
Collecting h5py (from qiskit-chemistry==0.5.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/e2/3e/76c3d0b25fee11ab73049475ca1833229fbf6e6a6bb56a8bab8f61e53df2/h5py-2.9.0-cp37-cp37m-win32.wh
l
Requirement already satisfied: decorator>=4.3.0 in c:\users\admin\appdata\roaming\python\python37\site-packages (from networkx>=2.2->qiskit_terra==0.8.1
->qiskit) (4.4.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\admin\appdata\roaming\python\python37\site-packages (from sympy>=1.3->qiskit_terra==0.8.1->qiski
t) (1.1.0)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\admin\appdata\roaming\python\python37\site-packages (from requests>=2.19->qiskit-ibmq-provider
==0.2.2->qiskit) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\admin\appdata\roaming\python\python37\site-packages (from requests>=2
.19->qiskit-ibmq-provider==0.2.2->qiskit) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\admin\appdata\roaming\python\python37\site-packages (from requests>=2.19->qiskit-ibmq-p
rovider==0.2.2->qiskit) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\roaming\python\python37\site-packages (from requests>=2.19->qiskit-ibmq-prov
ider==0.2.2->qiskit) (2019.3.9)
Requirement already satisfied: ntlm-auth>=1.0.2 in c:\users\admin\appdata\roaming\python\python37\site-packages (from requests-ntlm>=1.1.0->qiskit-ibmq-
provider==0.2.2->qiskit) (1.3.0)
Requirement already satisfied: cryptography>=1.3 in c:\users\admin\appdata\roaming\python\python37\site-packages (from requests-ntlm>=1.1.0->qiskit-ibmq
-provider==0.2.2->qiskit) (2.7)
Requirement already satisfied: joblib>=0.11 in c:\users\admin\appdata\roaming\python\python37\site-packages (from scikit-learn>=0.20.0->qiskit-aqua==0.5
.1->qiskit) (0.13.2)
Requirement already satisfied: six in c:\users\admin\appdata\roaming\python\python37\site-packages (from quandl->qiskit-aqua==0.5.1->qiskit) (1.12.0)
Requirement already satisfied: python-dateutil in c:\users\admin\appdata\roaming\python\python37\site-packages (from quandl->qiskit-aqua==0.5.1->qiskit)
 (2.8.0)
Requirement already satisfied: pyOpenSSL in c:\users\admin\appdata\roaming\python\python37\site-packages (from quandl->qiskit-aqua==0.5.1->qiskit) (19.0
.0)
Requirement already satisfied: pandas>=0.14 in c:\users\admin\appdata\roaming\python\python37\site-packages (from quandl->qiskit-aqua==0.5.1->qiskit) (0
.24.2)
Requirement already satisfied: inflection>=0.3.1 in c:\users\admin\appdata\roaming\python\python37\site-packages (from quandl->qiskit-aqua==0.5.1->qiski
t) (0.3.1)
Requirement already satisfied: more-itertools<=5.0.0 in c:\users\admin\appdata\roaming\python\python37\site-packages (from quandl->qiskit-aqua==0.5.1->q
iskit) (5.0.0)
Requirement already satisfied: ndg-httpsclient in c:\users\admin\appdata\roaming\python\python37\site-packages (from quandl->qiskit-aqua==0.5.1->qiskit)
 (0.5.1)
Requirement already satisfied: pyasn1 in c:\users\admin\appdata\roaming\python\python37\site-packages (from quandl->qiskit-aqua==0.5.1->qiskit) (0.4.5)
Requirement already satisfied: docloud>=1.0.315 in c:\users\admin\appdata\roaming\python\python37\site-packages (from docplex->qiskit-aqua==0.5.1->qiski
t) (1.0.375)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\users\admin\appdata\roaming\python\python37\site-packages (from cryptography>=1.3->requests-ntlm
>=1.1.0->qiskit-ibmq-provider==0.2.2->qiskit) (1.12.3)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\users\admin\appdata\roaming\python\python37\site-packages (from cryptography>=1.3->requests-ntlm
>=1.1.0->qiskit-ibmq-provider==0.2.2->qiskit) (0.24.0)
Requirement already satisfied: pytz>=2011k in c:\users\admin\appdata\roaming\python\python37\site-packages (from pandas>=0.14->quandl->qiskit-aqua==0.5.
1->qiskit) (2019.1)
Requirement already satisfied: pycparser in c:\users\admin\appdata\roaming\python\python37\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3->re
quests-ntlm>=1.1.0->qiskit-ibmq-provider==0.2.2->qiskit) (2.19)
Installing collected packages: cvxopt, qiskit-aqua, h5py, qiskit-chemistry, qiskit
  Running setup.py install for cvxopt ... error
    ERROR: Complete output from command 'c:\users\admin\appdata\local\programs\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file_
_='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-8ng8_fhi\\cvxopt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.re
ad().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\
pip-record-04l1qvdx\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\cvxopt
    copying src\python\coneprog.py -> build\lib.win32-3.7\cvxopt
    copying src\python\cvxprog.py -> build\lib.win32-3.7\cvxopt
    copying src\python\info.py -> build\lib.win32-3.7\cvxopt
    copying src\python\misc.py -> build\lib.win32-3.7\cvxopt
    copying src\python\modeling.py -> build\lib.win32-3.7\cvxopt
    copying src\python\msk.py -> build\lib.win32-3.7\cvxopt
    copying src\python\printing.py -> build\lib.win32-3.7\cvxopt
    copying src\python\solvers.py -> build\lib.win32-3.7\cvxopt
    copying src\python\_version.py -> build\lib.win32-3.7\cvxopt
    copying src\python\__init__.py -> build\lib.win32-3.7\cvxopt
    UPDATING build\lib.win32-3.7\cvxopt/_version.py
    set build\lib.win32-3.7\cvxopt/_version.py to '1.2.3'
    running build_ext
    building 'base' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "'c:\users\admin\appdata\local\programs\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\admin\
\AppData\\Local\\Temp\\pip-install-8ng8_fhi\\cvxopt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"
'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-04l1qvdx\inst
all-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-install-8ng8_fhi\cvxopt
\

**Comment by nonhermitian** [comment]
It is saying you need Visual C++ 14 installed to build cvxopt for aqua. This is similar to #311.

**Comment by woodsp-ibm** [comment]
What are you running that its trying to build out 32-bit versions? There are pre-built wheels for 64 bit Windows.

**Comment by matrixbot123** [comment]
So what should I do woodsp-ibm to run it on 32 bit os

**Comment by nonhermitian** [comment]
You need to install this

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

You will also need it to get around #311.

**Comment by woodsp-ibm** [comment]
This line, from your error log, looks you are running a 32-bit version of Python i.e. the `python37-32` part
> ERROR: Complete output from command 'c:\users\admin\appdata\local\programs\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;_file

As such it needs 32-bit versions of the dependencies which you can see it fetching and trying to build. If you can run a 64-bit python, not this 32-bit one, then qiskit should install correctly as there are pre-built wheels for cvxopt for 64 bit.

**Comment by matrixbot123** [comment]
I installed it shows another error

**Comment by nonhermitian** [comment]
Which is?

**Comment by matrixbot123** [comment]
see this image .now can't even understand what to do next

**Comment by mhsmith** [comment]
You can't attach images to GitHub issues via email: you'll have to do it on the GitHub website.

**Comment by nonhermitian** [comment]
Closing this as not heard back from submitter.  Can be re-opened if need be.
