### ISSUE TITLE
Installation fails on Pydroid 3

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-metapackage#341]
### Informations

- **Qiskit version**: Stable
- **Python version**: 3
- **Operating system**: Android
- **Pip version**: 18

### What is the current behavior?

![Screenshot_20190621-115958](https://user-images.githubusercontent.com/18051574/59915387-cb297e00-941c-11e9-85b7-a4355e73da3a.png)

### Steps to reproduce the problem

Use the pip tab to install pip==18, and then try Qiskit.

**Comment by jaygambetta** [comment]
I think it is saying you should just do qiskit terra as this seems to be a limitation of not having blas

**Comment by nonhermitian** [comment]
The fact that it made it this far into the install makes me think that there is a BLAS somewhere as it is needed by numpy and scipy.  It is likely that the pyscf just cannot find the location.  It would be interesting to see if Terra alone could be installed.

**Comment by nonhermitian** [comment]
Closing.  Reopen if need be

**Comment by Blank-c** [comment]
I am still waiting for pyinstaller to be added to pydroid3
