### ISSUE TITLE
Error: QASM no longer accepted

### ISSUE THREAD

**Issue by cruzar** [Qiskit/qiskit-metapackage#359]
When trying to run a compiled program on _ibmq_20_tokyo_ I'm now getting the following error:

`Got a 400 code response to https://q-console-api.mybluemix.net/api/Network/ibm-q-academic/Groups/***...***: {"error":{"status":400,"message":"QASM no longer accepted","code":"QASM_NO_LONGER_ACCEPTED","statusCode":400}}`

Can someone help me understand why? Could this be because the code is from some months ago, written in `Qiskit v0.5.7`?

**Comment by nonhermitian** [comment]
Yes, 0.5.7 is no longer supported.  Your jobs must be submitted using the Qobj format.

**Comment by cruzar** [comment]
Is there a way to change the qasm without having to re-write my whole program and without upgrading qiskit?

**Comment by mtreinish** [comment]
You'll have to use a newer qiskit. But, you can install that in a separate venv or something if you don't want to remove the old version. If you have a qasm file already with a newer qiskit you can run something like:

```
import qiskit as qk
qk.IBMQ.load_accounts()
backend = qk.IBMQ.get_backend('ibmq_20_tokyo')
qc = qk.QuantumCircuit.from_qasm_file(path)
# if not transpiled:
result = qk.execute(qc, backend).result()
# if qasm is already transpiled:
qobj = qk.compiler.assemble(qc, backend)
backend.run(qobj)
```

which will load the qasm and submit it to the backend.

**Comment by cruzar** [comment]
Alright. Btw, do you plan to provide backward compatibility for interfacing with the real devices in the future? That would help.....

**Comment by ajavadia** [comment]
They are usually backwards compatible. Qiskit 0.5.7 is one year old however. In Qiskit 0.6 Qobj was introduced which was a major upgrade to how qiskit communicates with devices.

**Comment by qruzar** [comment]
Quick follow-up: How can I force the transpiler not to exchange swap qubits and keep the initial layout I define? Sometimes, it may not be useful to simplify the circuits if, in the end, the readout qubit turns out to be a very noisy one.

**Comment by qruzar** [comment]
Quick follow-up: How can I force the transpiler not to swap qubits and keep the initial layout I define? Sometimes, it may not be useful to simplify the circuits if, in the end, the readout qubit turns out to be a very noisy one.
