### ISSUE TITLE
Jobs never stop running

### ISSUE THREAD

**Issue by cruzar** [Qiskit/qiskit-metapackage#363]
### Informations

- **Qiskit version**: 0.8.2
- **Python version**: 3.6.0
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

I'm submitting simple circuits to _ibmq_20_tokyo_ and the jobs get stuck in the running state forever.

### Steps to reproduce the problem

Example jobs ids:
`5d20bb14e5ac32007041e4be`
`5d20c0d820a135006fa8478b`

Backend status:
`BackendStatus(backend_name='ibmq_20_tokyo', backend_version='1.2.2', operational=True, pending_jobs=0, status_msg='active')`

**Comment by nonhermitian** [comment]
Running is the default mode on those devices for a variety of reasons. However it likely means that you are in queue waiting. This behavior will be changed in the near future.

**Comment by cruzar** [comment]
Thanks. It's good to know you'll change that, it's been almost a year that I see `pending_jobs=0` in tokyo. In any case, these jobs seem to be running longer than usual. For instance, `5d20c0d820a135006fa8478b` was created 2 hours ago already. Could I be in the queue for so long?

**Comment by nonhermitian** [comment]
Yes you can, depending on what others are running, and how much allocated time you have already used up.

**Comment by cruzar** [comment]
Finished after more than 8 hours. I used tokyo in the past and it never took so long. How can I control how much allocated time I have available?

**Comment by nonhermitian** [comment]
The allocation amounts are set by your hub admin.

**Comment by nonhermitian** [comment]
Tokyo is now offline. Is this reopened for a different device?

**Comment by cruzar** [comment]
I reopened it for Tokyo. This problem is happening again since yesterday. I'm not the only user having trouble getting results for jobs submitted more than 20 hours ago. Running status just now prints: `BackendStatus(backend_name='ibmq_20_tokyo', backend_version='1.3.1', operational=True, pending_jobs=0, status_msg='active')`. Will it be back online again soon? How can we check?

**Comment by nonhermitian** [comment]
Sorry, but Tokyo is retired, and will not be back online. It still exists as a backend solely for users to retrieve saved jobs. The August 29 sunset date was communicated to those with access over a month ago, and reiterated in the announcement of the Boeblingen device.

**Comment by cruzar** [comment]
You are correct. Thank you for the reminder.
