### ISSUE TITLE
community projects

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#37]
In documentation, I want to make a file that has a list of community projects using qiskit. 

The file should be
docs/community_qiskit.rst

and it would have a list of projects using qiskit to do cool things. 

This would have so far (thanks @akarazeev to maintaining this project as a community project)

https://github.com/akarazeev/qiskit-slack-bot

I am sure there are more projects that we should highlight.

**Comment by derivation** [comment]
I'm reaching out to Liz D, Sebastian H, and Katie P to pull together a healthy first draft akin to [this design](https://www.tensorflow.org/about/uses).

**Comment by jaygambetta** [comment]
This is good. Can we also add https://github.com/qutech-delft/quantuminspire. The more info would be the medium blog https://medium.com/qiskit/quantum-inspire-and-qiskit-f1be608f8955

**Comment by jaygambetta** [comment]
Added a skeleton in #115
