### ISSUE TITLE
Doc example does not run on windows 

### ISSUE THREAD

**Issue by HologramSam** [Qiskit/qiskit-metapackage#371]
Doc example in: https://qiskit.org/documentation/aqua/chemistry/qiskit_chemistry_execution.html
in the declarative programming interface section does not work in Windows as it uses pyscf. It may be a good idea to warn users of this fact.

**Comment by nonhermitian** [comment]
Those examples are being moved, and replaced with either inline code or tutorials.  However, @pistoia can we make sure to add notes in places where pyscf is used so that users are aware that those examples cannot be run on Windows?

**Comment by nonhermitian** [comment]
Closing as stale.
