### ISSUE TITLE
INSTALL.md IBMQ.save_account is now different

### ISSUE THREAD

**Issue by sznadas** [Qiskit/qiskit-metapackage#377]
See https://qiskit.org/documentation/install.html#install-access-ibm-q-devices-label

from qiskit import IBMQ
IBMQ.save_account('MY_API_TOKEN', 'MY_URL')

MY_URL is also required

**Comment by jaygambetta** [comment]
@nonhermitian did you fix this

**Comment by nonhermitian** [comment]
This looks to me fixed, so will close
