### ISSUE TITLE
Improve "Overview" and "Index" pages of documentation

### ISSUE THREAD

**Issue by lzdanski** [Qiskit/qiskit-metapackage#379]
**Observed State**: When you first navigate to https://qiskit.org/documentation/ it only displays the Qiskit Table of Contents. This isn't ideal because it means the first impression of the landing page doesn't provide any descriptive information about Qiskit. This is the same for each of the individual packages, Terra, Aer, and Ignis. 

Instead, descriptive information about the packages is on the *Overview.rst* pages. This means that the information which would be most useful to users (an introduction to the architecture and contents of the package) appears on a separate page from a useful, explicit list of the documentation table of contents.

**To-be**: Merge the `overview.rst` content into the `index.rst` files for Qiskit, Terra, Ignis, and Aer, to better match [Aqua](https://qiskit.org/documentation/aqua/index.html), which currently uses this structure for Index pages.

**Actions**: Consolidate the Overview and Index pages for to create a more user friendly introduction and navigation structure for:

- [x] Qiskit
- [x] Terra
- [x] Transpiler
- [x] Aer
- [x] Ignis

**Comment by derivation** [comment]
@lzdanski I'd just like to +1 this
