### ISSUE TITLE
Standardizing info achitecture across the landing pages (index.rst)

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit-metapackage#388]
Call for revisiting all the landing pages (index.rst) and edit the content if necessary.

**Comment by SooluThomas** [comment]
@derivation @lzdanski
Docs that we mainly need to focus on 

- [ ] [Rewiring Circuits](https://qiskit.org/documentation/terra/transpiler/index.html)
- [ ] [Terra Parallel tools](https://qiskit.org/documentation/terra/terra_parallel_tools.html)
- [ ] "This tutorial shows how to..." in Qiskit Aer
   - [ ] [Simulate an Experiment](https://qiskit.org/documentation/aer/simulate_experiments.html)
   - [ ] [Find the Final Statevector](https://qiskit.org/documentation/aer/simulate_statevectors.html)
   - [ ] [Find the Unitary Matrix](https://qiskit.org/documentation/aer/simulate_unitary_matrix.html)
   - [ ] [Use a Simple Noise Model](https://qiskit.org/documentation/aer/device_noise_simulation.html)

**Comment by jaygambetta** [comment]
closing as with the new organization this is not needed.
