### ISSUE TITLE
Automate pushing rendered documentation

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-metapackage#39]
In a similar way that `terra` documentation was handled, we should set up the CI and the project so documentation ends up being pushed to qiskit.org. Ideally:
* allow keeping both the "stable" documentation (the one relevant to published packages) and the "master" (the one for more bleeding edge users) available (and maybe older versions too?).
* for chapters where the main content is rendered from notebooks, automate their conversion.

**Comment by jaygambetta** [comment]
@diego-plan9 and @abdonrd I'm fine if we start doing this now. Each time this repo is updated the doc pushes from docs to qiskit.org/documentation

**Comment by diego-plan9** [comment]
Sounds good!

**Comment by diego-plan9** [comment]
After #72, the script for deploying and the travis integration is in place, albeit currently is set to push to a fake directory (and thus not reaching the landing site yet). Next steps are:
* final tests and deploying the first version of the new documentation
* add support for handling both `master` and `stable` documentation versions

**Comment by diego-plan9** [comment]
Closing for tracking the remaining issue at #80.
