### ISSUE TITLE
Documentation source code linebreaks

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-metapackage#394]
## Did you find a doc bug or broken link that needs to be fixed?
The current documentation is not wide enough to contain the full lines of source code. This causes many line breaks and makes reading the source code on the documentation website unworkable. Since the max line width in the linters is 100 characters, the source documentation should show at least 100 characters per line to prevent linebreaks.

See, for example, https://qiskit.org/documentation/_modules/qiskit/aqua/operator.html#Operator.construct_evaluation_circuit

**Comment by derivation** [comment]
@SooluThomas could you look into whether this can be addressed in a Sphinx configuration or a change in the style template? The example above is auto-doc generated.

**Comment by eddieschoute** [comment]
I don't think this is fixed yet, see my comment at https://github.com/Qiskit/qiskit/pull/397#issuecomment-520243158

**Comment by SooluThomas** [comment]
This issue has been resolved.
