### ISSUE TITLE
Error msg typo: NOT_CREDITS_AVALIABLES

### ISSUE THREAD

**Issue by nubbyOne** [Qiskit/qiskit-metapackage#395]
### Informations

- **Qiskit version**: 0.11
- **Python version**: 3.6
- **Operating system**: macOS

### What is the current behavior?

This was reported from a customer using qiskit so I don't have all the details but you can see from the screen snapshot the error message and the typo.
<img width="1060" alt="Screen Shot 2019-08-08 at 11 32 02 AM" src="https://user-images.githubusercontent.com/11412634/62720224-94f98b00-b9d7-11e9-9c0d-ce080187230f.png">

**Comment by nonhermitian** [comment]
Yes, this is a known error that is being worked on.

**Comment by nonhermitian** [comment]
Credits are no longer used so this can be closed.
