### ISSUE TITLE
Instructions on how to build rst from jupyter

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-metapackage#40]
Let's include these in the developer guide

**Comment by mtreinish** [comment]
Is this just for the tutorials or will there be other notebooks to include. I'm planning to port Qiskit/qiskit-terra#1268 to automate the process for tutorials so there isn't anything extra to do when you run a docs build it will pull and convert the tutorials.

**Comment by diego-plan9** [comment]
If using `nbconvert`, it would be worth spending some time reviewing https://nbconvert.readthedocs.io/en/latest/config_options.html to find out which options can be of use to fine-tune the results, and include them in the document (for example, `output_files_dir` and `default_language` would mimic some of the changes in #70, and there might be some other useful ones).

**Comment by jaygambetta** [comment]
Lets not use the convert the documentation will evolve differently. We should just encourage this to be the web version.
