### ISSUE TITLE
out of context or out of place part of the documentation 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#416]
This section feels out of place. I think it should go with the install by source of in the install section we could have a section called  install element one by one (for example) and then give this information after telling the user why they may want just qiskit terra 

<img width="831" alt="image" src="https://user-images.githubusercontent.com/15731369/63217745-bc5c0080-c119-11e9-8028-de8d70b7fc10.png">

**Comment by nonhermitian** [comment]
Yes, saw this as well. Should be removed or fixed in source

**Comment by jaygambetta** [comment]
look at the install from source there is a note that already says this. I think we should just remove this.

**Comment by jaygambetta** [comment]
removed in #439
