### ISSUE TITLE
Section change in the getting started section

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#417]
I think we should not have set output to mpl in the code (as it might break if they dont have the Matplotlib installed. 

<img width="842" alt="image" src="https://user-images.githubusercontent.com/15731369/63217781-705d8b80-c11a-11e9-9cbd-47fd29a51703.png">

Could we remove this but have a note after that if your draw is text based and you want a nicer one then set your user config.

**Comment by nonhermitian** [comment]
Could we have an user config setup for the build that sets mpl for the default, then the draw command would work in all cases and output still look good. We could still have a note of course

**Comment by jaygambetta** [comment]
have a look at the pr I just did which is just a note but I agree we could put the user config in the install (for example) and in the getting started just have a smaller note linking to the user config section and then saying draw using whatever option you want. I think this is better than my pr but I let you decided. If you want to accept mine and then change later happy with that or close and do how you want im good as well.

**Comment by yesodharan1892** [comment]
hi,
i believe your are looking for a better representation of mpl,
may i suggest using 
%matplotlib inline                 # just once in the project and then implement
circuit.draw(output='mpl')       # i am sure you will see a better representation of mpl, till the time the qiskit team updates the user specific option. 
hope you are okay with the resolution. if not please revert.
