### ISSUE TITLE
do we need this questions in the faq

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#420]
Do we need this in the faq. I know it was pre qiskit running versions but are we seeing this issues anymore?

I would remove this as I dont think this comes up much anymore. 

<img width="729" alt="image" src="https://user-images.githubusercontent.com/15731369/63218229-dd761e80-c124-11e9-8995-6ff7fe75d939.png">

**Comment by nonhermitian** [comment]
No, will remove
