### ISSUE TITLE
Getting started docs should be executed at build time

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#448]
The code example in `getting_started.rst` should be executed when the docs are built.

**Comment by derivation** [comment]
I think the code in the getting started material should be **unit tested**, but not run to dynamically generate output displayed in the document. If the code doesn't work as intended, a flag should be raised; error messages or unintended output shouldn't be displayed in the document.

**Comment by nonhermitian** [comment]
Then we need the code executed manually and the resulting figure added. If an exception or the like is raised, I think the ipython parser will throw it.
