### ISSUE TITLE
Need to document Aer API

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#459]
Aer API needs to be documented like Terra was in #447.

**Comment by jaygambetta** [comment]
why is aer not done?

**Comment by jaygambetta** [comment]
https://qiskit.org/documentation/apidoc/providers/aer/aer.html

**Comment by nonhermitian** [comment]
I was not sure if I got it all.  But it does look like I did (at least the most common stuff).  Will close.
