### ISSUE TITLE
Need to add Aqua API docs

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#461]
Need to add Aqua API docs as in #447.

**Comment by jaygambetta** [comment]
yeah lets have qiskit.chemistry and submodes and qiskit.aqua and submodes. @pistoia 
if you want to split the aqua. up into a qiskit.optimization and qiskit.ai and qiskit.finance where in each for now you just have an __init__ with a documentation you should be able to give the appearance of this modules and documentation until you organize by domains.

**Comment by nonhermitian** [comment]
done
