### ISSUE TITLE
links in https://github.com/Qiskit/qiskit/blob/master/docs/the_elements.rst are broken

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#464]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

- What is the current text that needs to be fixed or removed? (You can copy and paste)

- What should the documentation say instead?

- Are there other related issues or pull requests about this bug?

You can find information about formatting and style for Qiskit in the [Doc Formatting Cheat Sheet](https://github.com/Qiskit/qiskit/tree/master/.github/DOCS_TEMPLATES/doc_formatting_cheat_sheet.rst)

## Do we need to create new documentation?

- What kind of documentation article are you making?

Check out the [Docs Templates](https://github.com/Qiskit/qiskit/tree/master/.github/DOCS_TEMPLATES) to see which type of article you want to make:

- Help users [understand a concept](https://github.com/Qiskit/qiskit/tree/master/.github/DOCS_TEMPLATES/understand_a_concept.rst)
- Show how to [perform a task](https://github.com/Qiskit/qiskit/tree/master/.github/DOCS_TEMPLATES/perform_a_task.rst)
- Create a reference page for people to [find technical specifications](https://github.com/Qiskit/qiskit/tree/master/.github/DOCS_TEMPLATES/find_tech_specs.rst)

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

- What content needs to be updated or replaced? (You can copy and paste)

- What new content needs to be added?

**Comment by SooluThomas** [comment]
this will be done once all the apidocs structuring is done.

**Comment by jaygambetta** [comment]
Thanks.
