### ISSUE TITLE
master, and previous versions 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#466]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/15731369/63352148-8ba0e480-c32e-11e9-9d07-c67d1c428879.png">

I would like to have master and the previous version in the documentation. I think if we do something like this would be great. 

@SooluThomas could you look at this and make this a high priority as then as the team improves the documentation in the master and we set a build every day (?) then this would allow us to see how it changes.

**Comment by jaygambetta** [comment]
@mtreinish and @SooluThomas and @nonhermitian could we discuss this and how we can do it all.

**Comment by SooluThomas** [comment]
I think we need to have tagging system enabled to tag the commits to their respective versions, which I think we have. The only thing that we need now is a button or a means to display the latest version tag and toggle between the versions.

**Comment by nonhermitian** [comment]
We should investigate this: https://docs.readthedocs.io/en/stable/versions.html.  This would be a good choice for theme as well.  It is already used by everyone.

**Comment by SooluThomas** [comment]
Yes. Using RTD is one of the best options.

**Comment by jaygambetta** [comment]
Im good with that as well but lets start another issue for theme.

**Comment by nonhermitian** [comment]
Not sure if this is one the roadmap or not anymore.  Namely we host our docs at `qiskit.org/documentation/*` where as what we really need is `qiskit.org/documentation/latest/*` or `qiskit.org/documentation/0.25/`.  Closing now, can reopen if needed.

**Comment by mtreinish** [comment]
The previous releases half of this was just implemented in #1261 there should be a dropdown now and let you go to old versions. I went as far back as 0.24, but we can go even further back but it'll require someone to manually build and upload the old versions (and update the sphinx build conf accordingly). The builds from master/main already existed via CI (both here and for the project repos) where you can download the built documentation as artifacts from the CI build.
