### ISSUE TITLE
Enable Doc Translation

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit-metapackage#475]
- [x] Create a branch for pushing in .po (portable object) files.
- [x] Update .travis.yml and deploy_documentation.sh to configure the translation build process.
- [x] Update Qiskit styling for locale.
- [x] Add .po files/folder to new branch.
- [x] update .gitignore of master and poBranch
- [x] add a LOCALIZATION_CONTRIBUTORS file 
- [x] add info on how to contribute to localization in docs
- [x] connect Qiskit-Docs Crowdin project to poBranch

**Comment by derivation** [comment]
@lzdanski if you get me a bullet point version of the envisioned CLA workflow, I can make sound good.

**Comment by derivation** [comment]
So, barring something unexpected coming up with the last legal review, I'd say this is mission complete. Great job everyone! Next steps are to promote the translation workflow to community members. Yuri is working on a blog post to kick that off.
