### ISSUE TITLE
Add information about working with several repositories

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-metapackage#48]
Coming from https://github.com/Qiskit/qiskit-ibmq-provider/issues/24#issuecomment-456883485, now that we have several repositories and projects that have dependencies on each other, it would be beneficial to have a slightly more formal set of instructions _aimed for developers_ on how to work with several repositories at the same time, as it is relatively common that working on `qiskit-foo` `master` requires using `qiskit-bar` `master` and similar scenarios.

Some informal instructions are at https://github.com/Qiskit/qiskit-ibmq-provider/issues/24 and https://github.com/Qiskit/qiskit-terra/pull/1700, but it would be nice to have them in a single place (and also have the input of the other teams - the "oldest" project where such setup is needed is probably `aer`, so maybe @atilag or @chriseclectic have some documentation somewhere).

@jaygambetta , where do you think this information would be best placed? It should be only for developers - I was thinking that maybe `CONTRIBUTING` on this repo would make sense, but any other place sounds good too.

**Comment by jaygambetta** [comment]
It should be in this repo. I am also good if it is CONTRIBUTING but let also link to the doc for installing for developers or something.

**Comment by jlatone** [comment]
I'm going to build-and-install-all-of-qiskit-from-repos from scratch again, also following the guidance under "Setup with an Environment" here https://github.com/Qiskit/qiskit-aqua/blob/master/.github/CONTRIBUTING.rst, "To better contribute to Qiskit Aqua, we recommend..."

**Comment by jaygambetta** [comment]
After seeing the documentation coming together I think this should go in this section 

<img width="789" alt="image" src="https://user-images.githubusercontent.com/15731369/52912887-d198c500-3285-11e9-998f-81fa66f20578.png">

**Comment by derivation** [comment]
@diego-plan9 would the proposed instructions for working with multiple Qiskit repos be different than simply going through the instructions laid out in each repos' CONTRIBUTING guide one by one? I don't think I'm catching the subtleties of the conversation you had [here](https://github.com/Qiskit/qiskit-ibmq-provider/issues/24#issuecomment-456577073). In the context [Jay suggested above](https://qiskit.org/documentation/install.html#install-from-source), what additional instructions would be helpful to developers?

**Comment by atilag** [comment]
>... so maybe @atilag or @chriseclectic have some documentation somewhere

Actually we don't, but that would be great, for sure.
On `Aer` we are pointing towards `master` branch of qiskit-terra in Travis, and similar techniques are being used locally in our development workflow.
Maybe having a `nightly` package could help with making things easier for everybody, but there's a lot of burden/overhead on keeping a `nightly` package. We can discuss this later

**Comment by diego-plan9** [comment]
> @diego-plan9 would the proposed instructions for working with multiple Qiskit repos be different than simply going through the instructions laid out in each repos' CONTRIBUTING guide one by one? I don't think I'm catching the subtleties of the conversation you had [here](https://github.com/Qiskit/qiskit-ibmq-provider/issues/24#issuecomment-456577073). In the context [Jay suggested above](https://qiskit.org/documentation/install.html#install-from-source), what additional instructions would be helpful to developers?

I think what might be missing it is a bit that "glues" all the parts together, which I believe was what prompted @jlatone in the first place - as in, instructions on to interact with different packages at the same time. I'll try to draft something from the different sources, aiming for keeping it minimal, and see how it fits.
