### ISSUE TITLE
incorrect measurement 

### ISSUE THREAD

**Issue by JunChiehWang** [Qiskit/qiskit-metapackage#512]
<img width="933" alt="Screen Shot 2019-08-27 at 22 04 58" src="https://user-images.githubusercontent.com/29104344/63827897-9c96ba80-c919-11e9-85a9-44b16a1adf32.png">

### Informations

- **Qiskit version**:0.8.2
- **Python version**:3.6.4
- **Operating system**:Linux ip-172-31-30-115 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What is the current behavior?
print out wrong measurements:
{'01': 55, '00': 45}

### Steps to reproduce the problem
backend = Aer.get_backend('qasm_simulator')
c = ClassicalRegister(2)
circuit = QuantumCircuit(q, c)
circuit.h(q[0])
circuit.measure(q[0], c[0])
circuit.measure(q[0], c[1])
job = execute(circuit, backend, shots=100)
job.result().get_counts(circuit)

### What is the expected behavior?
there shouldn't be a 01 measurements, after the first measurement,
the wave-function collapse,  and we should get measurement of '00' or '11' state, 
instead of '01' and '00'

**Comment by ajavadia** [comment]
Please open this issue in Aer: https://github.com/Qiskit/qiskit-aer

**Comment by JunChiehWang** [comment]
> Please open this issue in Aer: https://github.com/Qiskit/qiskit-aer

done, thank you.
Should I delete this issue ?
