### ISSUE TITLE
Aqua documentation could be clearer in places

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#541]
For example ??? here:

<img width="784" alt="Screen Shot 2019-09-06 at 9 26 46 AM" src="https://user-images.githubusercontent.com/1249193/64431524-9e365000-d088-11e9-9620-dd257f8c2c5b.png">

https://qiskit.org/documentation/api/qiskit.aqua.operators.suzuki_expansion_slice_pauli_list.html#qiskit.aqua.operators.suzuki_expansion_slice_pauli_list

**Comment by woodsp-ibm** [comment]
The above now has an updated docstring and will be fixed when https://github.com/Qiskit/qiskit-aqua/pull/674 is merged

**Comment by pistoia** [comment]
Agree with @woodsp-ibm
