### ISSUE TITLE
Q awards page not accessible from community page

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#545]
https://ibmqawards.com/ is not accessible from community page.

**Comment by delapuente** [comment]
Where should it be advertised?

**Comment by nonhermitian** [comment]
It is a community event, so somewhere on the community page seems logical.

**Comment by delapuente** [comment]
Sure, I'll check with Liz (hopefully we had the event site online to advertise there but it's not). Thanks for the head up.

**Comment by KallieFerguson** [comment]
Meeting set up on Wednesday to address this. We also have Yuri's challenge out of Japan. @delapuente, are there other relevant parties I should loop into Wednesday meeting?
