### ISSUE TITLE
Stop using namespace packages

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-metapackage#559]
### Informations

- **Qiskit version**: >= 0.7
- **Python version**: All
- **Operating system**: All

### What is the current behavior?

Python namespace packaging is inherently unreliable and is a constant source of problems for users. What might work in a fresh python environment over time pip and python packaging almost surely mess things up so it will no longer see sub elements. This is an inherent issue with python packages which is most clearly demonstrated by: https://github.com/pypa/sample-namespace-packages/blob/master/table.md which shows all the possible ways that namespace packages can be installed when the system is working as expected (which it often doesn't).  This is the reason we've had bugs like Qiskit/qiskit-terra#2483 and we've had to land PRs like Qiskit/qiskit-terra#2842 and Qiskit/qiskit#374 to try and communicate that namespacing doesn't work in python packaging. At least for me personally it's one of the biggest issues I have to field from people trying to develop or use qiskit.

### Suggested solutions

Since we don't want to have a single repo for all the qiskit elements the best path forward would be to just abandon namespace packaging altogether. Having everything in the same namespace is not necessary for distinct elements to work together to work together. The pattern that all the elements used prior to the integrated names with using a separate package like `qiskit_aer`, `qiskit_ignis`, and `qiskit_aqua` worked fine and avoided all these packaging issues. If we moved back to this model each element was self contained and inherited from `qiskit` (from terra) would work perfectly well without ever having to worry about pip, setuptools, distutils, etc messing up the namespace and making things disappear.

**Comment by mtreinish** [comment]
@dongreenberg @ajavadia I think we should continue the discussion from https://github.com/Qiskit/qiskit-terra/issues/2483 here, since it effects the whole project not just terra.

**Comment by dongreenberg** [comment]
I am highly in favor of abandoning the namespace hacking, but by far more strongly in favor of moving to a core qiskit repo (with a small number of highly-detatched satellite repos for specific use cases) with thoughtful codeowners and dependencies. I think using the `from qiskit.<>` structure is coherent, familiar to users, and resistant to error if placed in a directory structure as "intended." The only philosophical argument I've heard for why we would not do this is that Aqua and Terra look different in code structure, but I would argue that 1) this can be adjusted and 2) every large codebase on the planet includes subelements which are diverse in purpose and style. Maintaining 8 different clones with different master branches and dependencies as a qiskit developer is a nightmare, and has been discussed ad nauseam.

Frankly, this is a user issue. We are very unlikely to receive strong open-source contributions, especially ones which span elements, when we make the packages so difficult to install, maintain, and debug for development. I am happy to provide more detail on how painful the user story is for moving from a pip meta-package user to contributor.

**Comment by mtreinish** [comment]
With the release of Qiskit 0.44.0 this can finally be closed. The qiskit namespace is now completely owned by the qiskit-terra package and no other official qiskit packages are adding on to the namespace anymore. The namespace hook points have been deprecated and will be removed in a future release. We finally no longer have to worry about the packaging nightmares associated with the use of namespace packages. It feels really good to be able to finally close this issue for good after almost 4 years.
