### ISSUE TITLE
Inconsistent docstrings in pulse module

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#569]
### What is the expected enhancement?
In order to have documentation that is uniform over all Qiskit elements, the type annotations used in the Pulse module, and related functions, need to be converted into the standard docstring type used in most other modules.

**Comment by ajavadia** [comment]
Ok I transferred this issue here. As discussed, seems there is agreement that this should be handled by the docs.

@SooluThomas is there any update?

**Comment by SooluThomas** [comment]
I don't have any positive update for this yet. The best way is to stick on to a standard (either with type hints or without). I talked to @lcapelluto about this and got an understanding that having type hints is a better option for the developers but, for a user perspective, its not an ideal thing.

**Comment by taalexander** [comment]
It would be helpful if you could explain a bit on why there is a problem pulling them into the documentation? It was my understanding that the [Sphinx, Napolean package supported type hints in google style docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). Its possible we are not using this package?
