### ISSUE TITLE
circuit.draw() does not plot anything

### ISSUE THREAD

**Issue by Europium-152** [Qiskit/qiskit-metapackage#579]
### Informations

- **Qiskit version**: 0.9.0
- **Python version**: 3.7.3
- **Operating system**: Win10
- **Matplotlib version**: 3.0.3

### What is the current behavior?

circuit.draw() returns a matplotlib Figure and executes successfully but no plot shows up.

### Steps to reproduce the problem

Matplotlib backend is TkAgg.
I'm using PyCharm as IDE.
Running in the Ipython console and in the command prompt both show the same behavior.

Im trying with this example code from the [documentation](https://qiskit.org/documentation/getting_started.html).

```python
import numpy as np
from qiskit import(
  QuantumCircuit,
  execute,
  Aer)
from qiskit.visualization import plot_histogram

# Use Aer's qasm_simulator
simulator = Aer.get_backend('qasm_simulator')

# Create a Quantum Circuit acting on the q register
circuit = QuantumCircuit(2, 2)

# Add a H gate on qubit 0
circuit.h(0)

# Add a CX (CNOT) gate on control qubit 0 and target qubit 1
circuit.cx(0, 1)

# Map the quantum measurement to the classical bits
circuit.measure([0,1], [0,1])

# Execute the circuit on the qasm simulator
job = execute(circuit, simulator, shots=1000)

# Grab results from the job
result = job.result()

# Returns counts
counts = result.get_counts(circuit)
print("\nTotal count for 00 and 11 are:",counts)

# Draw the circuit
circuit.draw()
```

### What is the expected behavior?

I would expect a figure to be shown, but I don't get anything.

**Comment by maddy-tod** [comment]
This has just [been fixed](https://github.com/Qiskit/qiskit-terra/pull/3051) and will be available in the next release of Qiskit Terra. In the meantime you can save the figure by doing `circuit.draw(output='mpl', filename='my_circuit.png')` or you can display the circuit in the terminal by doing `print(circuit)`.

**Comment by konchady** [comment]
Use it like this: 

circuit.draw(output='mpl')
plt.show()

I'm assuming you imported matplotlib.pyplot as plt

**Comment by nonhermitian** [comment]
This looks to be solved to me.  Please reopen if necessary.

**Comment by PaulRBerg** [comment]
@konchady's solution worked for me. The [intro tutorial](https://qiskit.org/documentation/intro_tutorial1.html) should be updated!!
