### ISSUE TITLE
Main action should link to IQX rather than qiskit install instructions

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#588]
### What is the expected behavior?
The main "Welcome to Quantum" action should link to the IQX rather than the Qiskit install instructions.

**Comment by SooluThomas** [comment]
The link to IQX exists in the 2nd section after the main header. Right?

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/11485594/65625149-414bfc80-df99-11e9-8d06-e3626dbf3682.png">

**Comment by nonhermitian** [comment]
Correct. But there is a logical disconnect here.  We state that the IQX is the place to get started, no installation required, and thus motivate the fact that it is easy to get setup and running, but then direct users to a page that starts talking about creating virtual envs and VC++ runtime components.  It does not make sense to direct new users there to begin with.

Ideally we would have two things, an action to go to IQX, and a little code snippet that is just `pip install qiskit`.
