### ISSUE TITLE
Tutorials menu bar item should be a drop down

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#589]
### What is the expected behavior?
Menu bar tutorials should be a drop down that includes both the IQX `Interactive tutorials` and the static github ones `Read-only tutorials`, in that order.

**Comment by a07r** [comment]
Hi @nonhermitian Do we still want to work on this issue? I was wondering if I can help with it but for that You may want to elaborate the requirement please!

**Comment by SooluThomas** [comment]
@a07r Thank you for your interest in helping out. Whole website restructuring will be happening soon. So, this tutorials dropdown would not be necessary. 

Closing this issue as it is no longer required.
