### ISSUE TITLE
Include qiskit aqua and qiskit-chemistry in mega

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#6]
We need to start making the plan to include qiskit aqua and qiskit chemistry into the default package.  

There are many things to discuss. 

- [x] Structure of package. I suggest it goes qiskit.aqua.blah and qiskit.aqua.chemistry.

- [x] the GUI and should not be part of the default so it needs to move to another repo 

- [ ] do we make an execution for aqua look and feel like qiskit terra

**Comment by pistoia** [comment]
@jaygambetta @mtreinish we have addressed the following two issues:
- Packages are now called `qiskit.aqua` and `qiskit.chemistry` as we discussed with Jay.  We preferred `qiskit.chemistry` over `qiskit.aqua.chemistry` for simplicity and also for consistency with the name of the corresponding element (Qiskit Aqua) and chemistry component (Qiskit Chemistry).
- Qiskit Aqua and Qiskit Chemistry included five user interfaces: a command-line tool for Aqua, a command line-tool for Chemistry, a graphical user interface wizard for Aqua, a graphical user interface wizard for Chemistry, and a graphical user interface API browser for all the components registered in Aqua.  All of these five user interfaces have been removed from Qiskit Aqua and Qiskit Chemistry and transferred to a different repository, called `qiskit-aqua-interfaces`, whose installation will be optional.

I think this addresses points 1 and 2 in Jay's comment above.

@jaygambetta  please clarify what you mean by *do we make an execution for aqua look and feel like qiskit terra* (point 3 in the comment above).

@mtreinish what else do we need to do to ensure that Qiskit Aqua and Qiskit Chemistry are included in the default package?
