### ISSUE TITLE
set up a DOI for qiskit?

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#60]
should we set up a DOI for qiskit --- https://academia.stackexchange.com/questions/81583/are-there-free-doi-generation-services

**Comment by cbjuan** [comment]
In this sense, I would like to recommend Zenodo https://zenodo.org/. We can generate a DOI for the main repo (or for each one) and, if needed, we can even have DOIs per released version. 

This is an example of a GitHub repository with a DOI using Zenodo. DOI: https://doi.org/10.5281/zenodo.1009617 and the correspondent GitHub repo: https://github.com/cbjuan/paper-ieeeAccess-2017

**Comment by jaygambetta** [comment]
I am good with this. Do you want to set it up

**Comment by cbjuan** [comment]
Sure, I can do that. Moving to a private channel to discuss some details about this.

**Comment by cbjuan** [comment]
May it is time to close this issue, @jaygambetta?
