### ISSUE TITLE
Increase width of source code text when viewed in the documentation

### ISSUE THREAD

**Issue by jenglick** [Qiskit/qiskit-metapackage#605]
### **What is the current behavior?**

When viewing source code in the documentation, the text displayed is fixed at a narrow width, irrespective of width of the browser window and so requires horizontal scrolling.

### **What is the expected behavior?**

I would expect width of displayed source code to increase and decrease with width of browser window.

**Comment by nonhermitian** [comment]
Yes.  This is fairly staright forward to do, but we need to switch the theme to `rtd` first #467.  After that it is simply a `css` change:
```
.wy-nav-content {
    max-width: 90% !important;
}
```
