### ISSUE TITLE
Usage of draw(output='latex_source')

### ISSUE THREAD

**Issue by imv7** [Qiskit/qiskit-metapackage#618]
### Informations

- **Qiskit version**:

![image](https://user-images.githubusercontent.com/13357603/66396683-a0a20780-e9b0-11e9-8150-18c641d45256.png)

- **Python version**:

Python 3.7.3

- **Operating system**:

Windows 10

### What is the current behavior?

Is that the expected behavior by using **draw(output='latex_source')** ?

`'% \\documentclass[preview]{standalone}\n% If the image is too large to fit on this documentclass use\n\\documentclass[draft]{beamer}\n% img_width = 6, img_depth = 8\n\\usepackage[size=custom,height=10,width=16,scale=0.7]{beamerposter}\n% instead and customize the height and width (in cm) to fit.\n% Large images may run out of memory quickly.\n% To fix this use the LuaLaTeX compiler, which dynamically\n% allocates memory.\n\\usepackage[braket, qm]{qcircuit}\n\\usepackage{amsmath}\n\\pdfmapfile{+sansmathaccent.map}\n% \\usepackage[landscape]{geometry}\n% Comment out the above line if using the beamer documentclass.\n\\begin{document}\n\\begin{equation*}\n    \\Qcircuit @C=1.0em @R=0.0em @!R {\n\t \t\\lstick{ q4_0 : \\ket{0} } & \\gate{H} & \\ctrl{1} & \\ctrl{2} & \\qw & \\meter & \\qw & \\qw & \\qw\\\\\n\t \t\\lstick{ q4_1 : \\ket{0} } & \\gate{H} & \\targ & \\qw & \\meter & \\qw & \\qw & \\qw & \\qw\\\\\n\t \t\\lstick{ q4_2 : \\ket{0} } & \\qw & \\qw & \\targ & \\qw & \\qw & \\qw & \\qw & \\qw\\\\\n\t \t\\lstick{c4_{0}: 0} & \\cw & \\cw & \\cw & \\cw & \\cw \\cwx[-3] & \\cw & \\cw & \\cw\\\\\n\t \t\\lstick{c4_{1}: 0} & \\cw & \\cw & \\cw & \\cw \\cwx[-3] & \\cw & \\cw & \\cw & \\cw\\\\\n\t \t\\lstick{c4_{2}: 0} & \\cw & \\cw & \\cw & \\cw & \\cw & \\cw & \\cw & \\cw\\\\\n\t }\n\\end{equation*}\n\n\\end{document}'`

### Steps to reproduce the problem
```
from qiskit import(IBMQ, QuantumRegister, ClassicalRegister, QuantumCircuit, execute, Aer)
from qiskit.visualization import plot_histogram
IBMQ.load_account()

q = QuantumRegister(3)
c = ClassicalRegister(3)
qc = QuantumCircuit(q,c)
qc.h(q[0])
qc.h(q[1])
qc.cx(q[0],q[1])
qc.cx(q[0],q[2])
qc.measure(q[0],c[0])
qc.measure(q[1],c[1])
qc.draw(output='latex_source')
```

### What is the expected behavior?

I expected to see a readable output.

### Suggested solutions

Please, would you guide me on fixing or understanding the feature "latex_source" of draw() ?

**Comment by mtreinish** [comment]
This is the correct behavior of the `latex_source` output. It is used to return the raw latex string used to generate the quantum circuit diagram. That string is valid latex and when run in your latex distribution will build a pdf with the circuit diagram (it's what is used by the `latex` output to generate the png). The general use case for `latex_source` output is to take the relevant sections from that string and add the circuit diagram to an existing latex document (for example when writing a paper). For example I have personally used this in presentations: https://github.com/mtreinish/open-source-quantum-computing/blob/oss-jp-2019/open-source-quantum-computing.tex#L474-L487

As this is working as designed, I'm going to close the issue. Please feel free to re-open it if I'm missing something.
