### ISSUE TITLE
Control Z gate displays incorrectly when the circuit is printed

### ISSUE THREAD

**Issue by ztjohnst** [Qiskit/qiskit-metapackage#622]
### Informations

- **Qiskit version**: 0.12.0
- **Python version**: 3.6.8
- **Operating system**: OSX

### What is the current behavior?
In any circuit, the control z gate seems to print wrong. It is very hard to tell which qubit is the control and which is the target.

### Steps to reproduce the problem
Add a control z gate to any circuit then print the circuit like so:
circ.cz(q[0],q[1])
print(circ)

### What is the expected behavior?
The target bit should be labeled correctly.

**Comment by ajavadia** [comment]
control-z is a symmetric gate. it doesn't matter which qubit is control and which is target. that's why it is drawn that way.
