### ISSUE TITLE
Borken ReadMe Links

### ISSUE THREAD

**Issue by mikeumus** [Qiskit/qiskit-metapackage#625]
The link to join the Slack on the ReadMe is broken:
https://qiskit.slack.com/join/shared_invite/enQtNjQ5OTc5ODM1ODYyLTBlMWY1ZGJiYmZkNjliZTY4MTViNTQ3NzI2ZmU2MzQxZjlhZDZlYTAzZTNlMDU0ZjVmNzEyMzY3OGE1Y2UyNjk

and the link on the footer of https://community.qiskit.org to join Slack is no good either. 

Also the IBMQ Provider link is 💔 
https://qiskit.org/qiskit-ibmq-provider

😞

**Comment by mikeumus** [comment]
@SooluThomas well it doesn't fix the broken Slack link   :/

**Comment by SooluThomas** [comment]
> @SooluThomas well it doesn't fix the broken Slack link :/

It has been resolved in PR #627
