### ISSUE TITLE
bibtex file has duplicate names

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#64]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Hitomi Takahashi and Hitomi Takahashi 
Ismael Faro and Ismael Faro Sertage
Peng Liu and Peng Liu
Stefan Woerner and Stefen Worner
Steve Wood and Steve Wood

**Comment by mtreinish** [comment]
The bibtex file is generated using: https://github.com/Qiskit/qiskit/blob/master/tools/generate_bibtex.py from the AUTHORS file (which is also machine generated, but then hand edited) which means we have duplicate entries in the AUTHORS file too. We should just delete the duplicate entries from the AUTHORS file and rerun the script.

**Comment by diego-plan9** [comment]
While we are at it, can we change also https://github.com/Qiskit/qiskit/blob/master/AUTHORS#L23
`Diego M. Rodriguez` to `Diego Moreda` in the same PR?

**Comment by ajavadia** [comment]
I think @pistoia wanted to do this in #59?
