### ISSUE TITLE
Link to main website from Documentation

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit-metapackage#664]
## What is the expected behavior 

After merging #662, add links to [qiskit.org](https://qiskit.org), [Terra](https://qiskit.org/terra), [Aqua](https://qiskit.org/aqua), [Aer](https://qiskit.org/aer), [Ignis](https://qiskit.org/ignis), [IBM Q Account](https://qiskit.org/ibmqaccount) from [Documentation](https://qiskit.org/documentation).

**Comment by delapuente** [comment]
Where do you want to include them? I would say this is part of the side bar, something like "Go to website" but, to be honest, those landing pages don't add real value to the users and they are intended to dissapear (probably). The point of the landing pages is to redirect the user to more meaningful content like the repos or the documentation so I don't see a way back as something critical. @nonhermitian what do you think?

**Comment by SooluThomas** [comment]
I was thinking of redirecting to qiskit.org when the logo on the top left (in the documentation) is clicked.

**Comment by abbycross** [comment]
I have always found it strange that clicking on the "home" icon goes to the home of the API docs (which is where you already are), and not to qiskit.org.  In fact, there is no link in the API docs to get back to qiskit.org!  I agree with @SooluThomas and was going to suggest the same thing -- that clicking on the home icon ([top left of this page](https://qiskit.org/documentation/)) should go to qiskit.org.

**Comment by nonhermitian** [comment]
This has been done for some time now.
