### ISSUE TITLE
Inline drawing via matplotlib can clip information.

### ISSUE THREAD

**Issue by stolk** [Qiskit/qiskit-metapackage#667]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: 3.7.4
- **Operating system**: Ubuntu 18.04.3
- **Browser**: Firefox 70.0.1 (64-bit)

### What is the current behavior?

When I draw a circuit, information can be lost due to clipping.
See image.

![image](https://user-images.githubusercontent.com/455280/68356957-afbbc880-00c8-11ea-84f5-862d0088e96a.png)

The few pixels on the right is supposed to be a superscript 3 character.

### Steps to reproduce the problem

```
from qiskit import *
c = QuantumCircuit(3,3)
%matplotlib inline
c.draw(output='mpl')
```

### What is the expected behavior?

A diagram that has the '3' visible.

### Suggested solutions

Better clipping of the matplot image.

**Comment by tobeyOguney** [comment]
Hi stolk!
I noticed this is due to the "scale" parameter of the QuantumCircuit object being set to a default of 0.7.
The image doesn't clip when "scale" is set to 1.
![image](https://user-images.githubusercontent.com/28822467/68359350-e3740e00-011b-11ea-9006-e7a7518a1bb6.png)

**Comment by nonhermitian** [comment]
This is due to the removal of `tight_layout` in Terra.  It will be solved soon.

**Comment by nonhermitian** [comment]
This has been fixed.
