### ISSUE TITLE
could we have a subscription API for task status changing?

### ISSUE THREAD

**Issue by yunfan** [Qiskit/qiskit-metapackage#678]
### What is the expected behavior?

i hope there could be a subscription API for task status changing since it already had websocket support. that would helpful for the hurry user

**Comment by kdk** [comment]
Hi @yunfan, can you add some detail on what kind of subscription API, and what it would be used for? Would its purpose be different than the `%qiskit_job_monitor` from https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/fundamentals/6_qiskit_jupyter_tools.ipynb ?

**Comment by yunfan** [comment]
@kdk the subscription api should let the server push notifications(like job status changing) to my connected client . in that case, i could easily implmenet a local hub for sharing the token i had without gave local user

**Comment by nonhermitian** [comment]
I believe that sharing the token via the mechanism you describe is against the terms of service of the IBM Quantum Experience: https://quantum-computing.ibm.com/terms

**Comment by yunfan** [comment]
though this is a general demands, i think i should close the issue since it againts the term

**Comment by nonhermitian** [comment]
Yes the feature itself would be nice.

**Comment by wildfire810** [comment]
Where is the text of The 'against the terms of service of the IBM Quantum Experience'? I mean 'Share'.
@nonhermitian

**Comment by nonhermitian** [comment]
@wildfire810 I believe it falls under the "non-transferable" part of the license in section 2(b). However, you need to contact IBM if you have official questions on the licensing agreement required to access the quantum devices.
