### ISSUE TITLE
Qiskit elements image not looking fancy enough on white background

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-metapackage#68]
![elements](https://user-images.githubusercontent.com/418311/52417929-3b2e0c00-2aed-11e9-9a82-52db98b5a642.png)

`docs/images/qiskit_elements` makes use of transparency, but assuming the background is black.

**Comment by jaygambetta** [comment]
yeah, it should be on a black background or something. This is a placeholder until we get it done better.
