### ISSUE TITLE
Module status is completely out of date / incorrect.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#682]
Needs to be cleaned up.

**Comment by melvin2016** [comment]
Can you elaborate on this?

**Comment by nonhermitian** [comment]
The content is old and incorrect, and thus needs to be updated

**Comment by Ritvik-Sapra** [comment]
Which module and file are you referring to here? @nonhermitian

**Comment by nonhermitian** [comment]
https://qiskit.org/documentation/development_strategy.html#modules

But this is something for the lead devs to sort out.

**Comment by nonhermitian** [comment]
I have killed this in the new docs for 0.25.  Someone can  make a new PR if so desired.
