### ISSUE TITLE
504 Server Error: Gateway Time-out for url

### ISSUE THREAD

**Issue by AdrianTanTeckKeng** [Qiskit/qiskit-metapackage#685]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: 3.7.1
- **Operating system**: MacOS

### What is the current behavior?
I am running a time evolution algorithm and am measuring an observable at each time step. The time step at jth+1 depends on the observables at jth. I have a while loop to check if the job for the current time step is completed before moving on to the next time step. This works for the first few time steps but eventually, I will get an error that says this:

Traceback (most recent call last):
  File "chiesa_corr_fnc.py", line 181, in <module>
    status = job_sim.status()
  File "/Users/atanteck/anaconda3/lib/python3.7/site-packages/qiskit/providers/ibmq/job/ibmqjob.py", line 305, in status
    raise JobError(str(self._future_captured_exception))
qiskit.providers.exceptions.JobError: '504 Server Error: Gateway Time-out for url: https://api.quantum-computing.ibm.com/api/Network/ibm-q/Groups/open/Projects/main/Jobs?access_token=...

I am unsure what is the problem.

### Steps to reproduce the problem

...time evolution code...

<pre>
status = job_sim.status()
while status.name != 'DONE':
    time.sleep(90)
    print(status.name,'Still running')
    status = job_sim.status()
result_sim = job_sim.result()
</pre>

...code to measure observables...

**Comment by nonhermitian** [comment]
This should not be an issue anymore.
