### ISSUE TITLE
Sphinx tabs not working

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit-metapackage#688]
Documentation for [Installing from source](https://qiskit.org/documentation/contributing_to_qiskit.html#installing-terra-from-source) used to have a tab structure which toggles between installation for different operating systems, which is not currently working in the desired way. 

- What is the file name(s) where you found the bug?

   [Contributing to Qiskit file](https://github.com/Qiskit/qiskit/blob/master/docs/contributing_to_qiskit.rst)

- What should the documentation say instead?

   Figure out a way to get the tabs working.

- Are there other related issues or pull requests about this bug?

   sphinx-tabs were added in PR https://github.com/Qiskit/qiskit/pull/346
   The sphinx extension used is ['sphinx_tabs.tabs'](https://github.com/djungelorm/sphinx-tabs).

### Screenshots:

![](https://user-images.githubusercontent.com/11485594/59948664-cd9ccf80-943e-11e9-8ef4-4a87ed597e7e.png)

**Comment by melvin2016** [comment]
I'm on this

**Comment by melvin2016** [comment]
i'm on this.

**Comment by indhra** [comment]
> i'm on this.

any update

**Comment by melvin2016** [comment]
Yeah trying

**Comment by melvin2016** [comment]
> > i'm on this.
> 
> any update

Did a PR #692.
