### ISSUE TITLE
Cannot pip install qiskit in empty conda env

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#696]
### Information

- **Qiskit version**: 0.13.0
- **Python version**: 3.7 
- **Operating system**: OSX

### What is the current behavior?
```
ModuleNotFoundError: No module named 'numpy'
    **************************************************
    * numpy was not installed in your system.  Please run
    *     pip install numpy
    * before installing pyscf.
    **************************************************
```
However this is exactly what we tell people to do in the install instructions: https://qiskit.org/documentation/install.html

**Comment by thetronjohnson** [comment]
I'm having the same issue too, I installed numpy separately, now it's showing a runtime error
```python 
 ERROR: Command errored out with exit status 1:
     command: /home/tron/anaconda3/envs/quantum/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4zrsxjjn/pyscf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4zrsxjjn/pyscf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4zrsxjjn/pyscf/pip-egg-info
         cwd: /tmp/pip-install-4zrsxjjn/pyscf/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4zrsxjjn/pyscf/setup.py", line 245, in <module>
        raise RuntimeError
    RuntimeError
    ****************************************************************
    *** WARNING: BLAS library not found.
    * You can include the BLAS library in the global environment LDFLAGS, eg
    *   export LDFLAGS='-L/path/to/blas/lib -lblas'
    * or specify the BLAS library path in  PYSCF_INC_DIR
    *   export PYSCF_INC_DIR=/path/to/blas/lib:/path/to/other/lib
    ****************************************************************
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by yesodharan1892** [comment]
hi,
can i look into this , if yes, kindly send a screenshot of the complete procedure(entered code) where the issue is getting created.

**Comment by d4rkc0nd0r** [comment]
It's better using IBMQ Notebooks instead of using Anaconda

**Comment by FerjaniMY** [comment]
Have you tried to install numpy before because it was not installed in your system.  
Try `pip install numpy` or `pip3 install numpy`.

**Comment by Ritvik-Sapra** [comment]
@nonhermitian Clearly Qiskit requires a few python packages to be installed in order to work. Maybe we should update the [documentation](https://qiskit.org/documentation/install.html) to include instructions for the prerequisites?

**Comment by nonhermitian** [comment]
Yes, I believe the documentation needs updating.

**Comment by mtreinish** [comment]
The real bug here is probably in aqua's requirements list: https://github.com/Qiskit/qiskit-aqua/blob/master/setup.py#L42 and https://github.com/Qiskit/qiskit-aqua/blob/master/requirements.txt#L14 there are no precompiled binaries published on windows in general https://pypi.org/project/pyscf/#files which includes win64 and not just win32. Pip is trying to build pyscf from source which it can't do because pyscf isn't setup to make that easy (it will also likely fail later in the installation on a binary lib dependency).

To fix this we probably should fix the marker exclusion or just remove pyscf from the requirements list in aqua and get that staged for the next aqua release.

**Comment by nonhermitian** [comment]
I think the pyscf as optional would be nice.
