### ISSUE TITLE
Cannot pip install qiskit in Google Colab

### ISSUE THREAD

**Issue by PabloAMC** [Qiskit/qiskit-metapackage#706]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: Python 3
- **Operating system**: Google Colab

### What is the current behavior?
Unable to install qiskit. After installing some dependencies it returns:
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.

### Steps to reproduce the problem
In Google Colab, run:
!pip install qiskit

### What is the expected behavior?
It gets installed

### Suggested solutions
Update qiskit's folium version?

**Comment by nonhermitian** [comment]
`datascience` appears to be "A Berkeley library for introductory data science."  I do not think that require that.  In addition, it appears that that library requires a old version of `folium`.

**Comment by PabloAMC** [comment]
Actually, someone already found out that problem before me: https://github.com/Qiskit/qiskit-iqx-tutorials/issues/359
