### ISSUE TITLE
Cannot pip install qiskit on MacOS 10.15.1

### ISSUE THREAD

**Issue by frederikwilde** [Qiskit/qiskit-metapackage#710]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: 3.7.2
- **Pip version**: 19.3.1
- **Operating system**: MacOS Catalina 10.15.1

### What is the current behavior?
When I try to ```pip install qiskit``` I get a lot of warnings and three errors, of which the last line is
```
ERROR: Command errored out with exit status 1: /Users/fwilde/my-project/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2w/jd_gyvxx0fd29h9z7xn4gv240000gn/T/pip-install-f5ymlks3/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/2w/jd_gyvxx0fd29h9z7xn4gv240000gn/T/pip-install-f5ymlks3/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2w/jd_gyvxx0fd29h9z7xn4gv240000gn/T/pip-record-oi3g38c4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/fwilde/my-project/venv/include/site/python3.7/psutil Check the logs for full command output.
```
Afterwards only numpy and scipy is installed. I use a clean virtual environment and pip 19.3.1
Full error output in the attached [txt file](https://github.com/Qiskit/qiskit/files/3911026/qiskit-install-error.txt).

### Steps to reproduce the problem
```pip install qiskit``` with the above system specs.

### What is the expected behavior?
Qiskit should be installed in the venv.

**Comment by kdk** [comment]
This might be an issue in psutil ( https://github.com/giampaolo/psutil/issues/1632 ). Were you previously able to `pip install qiskit` on this machine?

**Comment by frederikwilde** [comment]
Yes, thank you, this seems to be it. I get exactly the same error messages. Older versions of psutil fail to install as well. This is the first time I am trying to install Qiskit.

**Comment by neur0nic** [comment]
Solved this by running `pip install cmake` and afterwards `pip install qiskit`.

**Comment by atilag** [comment]
I can build Qiskit with Catalina without problems, just tested with different virtual envs (`venv` and `anaconda3`) from scratch.
Looking at the error log, seems like the build process of `psutil` is taking the wrong path to the standard library: `-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include` , when it should be something like: `-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include`
I remeber having to reinstall/upgrade XCode/CommandLineTools when upgraded to Catalina, did you do it?

**Comment by colinkcurtis** [comment]
Similar to @atilag , upgrading XCode was necessary for me to install qiskit on MacOS 10.15.2

**Comment by MIWdlB** [comment]
Seems to work for me (10.15.2) in a new env, as long as I specify python3. Did you get it working? Interested to know what's going on.

**Comment by frederikwilde** [comment]
XCode did not seem to be the problem. But there is a solution linked to the psutil issue by @murphd40 that worked for me. I followed the steps of [this reply](https://github.com/explosion/thinc/issues/219#issuecomment-574247098), except that `--no-cache` was not necessary.
