### ISSUE TITLE
Slack invite link is expired

### ISSUE THREAD

**Issue by peachnuts** [Qiskit/qiskit-metapackage#717]
I have tried the slack invite link from qiskit.org  and  from the ReadMe.
Both of them are no longer active.
Can anyone give me a link to join in the slack?
Thanks!!

**Comment by lerongil** [comment]
Thanks for opening an issue @peachnuts. Here is a new invite link to use: https://join.slack.com/t/qiskit/shared_invite/enQtODQ2NTIyOTgwMTQ3LTI0NzM2NzkzZjJhNDgzZjY5MTQzNDY3MGNiZGQzNTNkZTE4Nzg1MjMwMmFjY2UwZTgyNDlmYWQwYmZjMjE1ZTM. We will update this in the readme and qiskit.org.

**Comment by SooluThomas** [comment]
PR #718 and https://github.com/Qiskit/qiskit.org/pull/347 closes this issue.
