### ISSUE TITLE
Job Status stucked in "job is being validated"

### ISSUE THREAD

**Issue by yoshiorubio** [Qiskit/qiskit-metapackage#719]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: 3.6.8
- **Operating system**: Ubuntu 16.04

### What is the current behavior?
If I execute several jobs, independently and sequentially, sometimes it gets stucked in
"Job Status: job is being validated"
The only way to stop this behavior is to enter my IBM Q Experience account, delete the job that is stucked in "VALIDATING" , and then it cancels.  

### Steps to reproduce the problem
The
In Python I run:
`
 circ = QuantumCircuit(q)
for i in range (bits):
     circ.h(q[i])
circ_a=[]   
for i in range(size):
    circ_a.append(circ)

meas=QuantumCircuit(q,c)
meas.measure(q,c)
qc_a = []

for i in range(size):
   qc_a.append(circ_a[i] + meas)

for j in range(num_jobs):
        job=execute(qc_a[j], simulator_backend)
        my_jobs.append(job)
        job_monitor(my_jobs[j])`

After a while, the message in the terminal only indicates that the job is being validated. This behavior happens when using the IBM backends on the cloud, it doesn't matters if I use the simulator or the IBMQ_16. How many iterations or executions are needed, it varies. The problem does not appears in the local simulator "qasm_simulator" of qiskit. 

### What is the expected behavior?
I expect to get the results of every job.

**Comment by yesodharan1892** [comment]
hi,
can i look into this issue for you, 
if yes please assign me the task.

**Comment by nonhermitian** [comment]
This is not something that we can handle, so closing.
