### ISSUE TITLE
KeyError: 'scale'

### ISSUE THREAD

**Issue by michaelmin2025** [Qiskit/qiskit-metapackage#720]
### Informations

- **Qiskit version**:
Should be the latest version. 

import qiskit
qiskit.__version__

gets the same error. 

- **Python version**: 
3.7 
- **Operating system**:
Ubuntu 18.04

### What is the current behavior?
I am trying to run this script but am I getting an unusual error. 
KeyError: 'scale'

### Steps to reproduce the problem
Here is the script.

import qiskit as q
from qiskit.tools.visualization import plot_bloch_multivector
from qiskit.visualization import plot_histogram
from matplotlib import style
import math
#style.use("dark_background")

%matplotlib inline

statevec_simulator = q.Aer.get_backend("statevector_simulator")
qasm_sim = q.Aer.get_backend('qasm_simulator')

def do_job(circuit):
    result = q.execute(circuit, backend=statevec_simulator).result()
    statevac = result.get_statevector()
    
    n_qubits = circuit.n_qubits
    
    circuit.measure([i for i in range(n_qubits)], [i for i in range(len(circuit.clbits))])
    
    qasm_job = q.execute(circuit, backend=qasm_sim, shots=1024).result()
    counts = qasm_job.get_counts()
    return statevac, counts

Error outputed is:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-0cd3cf6362e3> in <module>
----> 1 import qiskit as q
      2 from qiskit.tools.visualization import plot_bloch_multivector
      3 from qiskit.visualization import plot_histogram
      4 from matplotlib import style
      5 import math

~/anaconda3/lib/python3.7/site-packages/qiskit/__init__.py in <module>
     31 from qiskit.circuit import QuantumRegister
     32 from qiskit.circuit import QuantumCircuit
---> 33 from qiskit.execute import execute
     34 from qiskit.compiler import transpile, assemble
     35 

~/anaconda3/lib/python3.7/site-packages/qiskit/execute.py in <module>
     19 running quickly we have provided this wrapper module.
     20 """
---> 21 from qiskit.compiler import transpile, assemble
     22 
     23 

~/anaconda3/lib/python3.7/site-packages/qiskit/compiler/__init__.py in <module>
     18 
     19 from .assemble import assemble
---> 20 from .transpile import transpile

~/anaconda3/lib/python3.7/site-packages/qiskit/compiler/transpile.py in <module>
     17 import warnings
     18 
---> 19 from qiskit.transpiler import Layout, CouplingMap
     20 from qiskit.tools.parallel import parallel_map
     21 from qiskit.transpiler.transpile_config import TranspileConfig

~/anaconda3/lib/python3.7/site-packages/qiskit/transpiler/__init__.py in <module>
     15 """Utils for transpiler."""
     16 
---> 17 from .passmanager import PassManager, FlowController
     18 from .propertyset import PropertySet
     19 from .exceptions import TranspilerError, TranspilerAccessError

~/anaconda3/lib/python3.7/site-packages/qiskit/transpiler/passmanager.py in <module>
     22 from qiskit.dagcircuit import DAGCircuit
     23 from qiskit.converters import circuit_to_dag, dag_to_circuit
---> 24 from qiskit.visualization import pass_manager_drawer
     25 from .propertyset import PropertySet
     26 from .basepasses import BasePass

~/anaconda3/lib/python3.7/site-packages/qiskit/visualization/__init__.py in <module>
     94 import sys
     95 from qiskit.util import _has_connection
---> 96 from qiskit.visualization.counts_visualization import plot_histogram
     97 from qiskit.visualization.state_visualization import (plot_state_hinton,
     98                                                       plot_bloch_vector,

~/anaconda3/lib/python3.7/site-packages/qiskit/visualization/counts_visualization.py in <module>
     22 import functools
     23 import numpy as np
---> 24 from .matplotlib import HAS_MATPLOTLIB
     25 from .exceptions import VisualizationError
     26 

~/anaconda3/lib/python3.7/site-packages/qiskit/visualization/matplotlib.py in <module>
     29     from matplotlib import get_backend
     30     from matplotlib import patches
---> 31     from matplotlib import pyplot as plt
     32     HAS_MATPLOTLIB = True
     33 except ImportError:

~/anaconda3/lib/python3.7/site-packages/matplotlib-3.1.1+2663.ge240493a8-py3.7-linux-x86_64.egg/matplotlib/pyplot.py in <module>
     38 from matplotlib import docstring
     39 from matplotlib.backend_bases import FigureCanvasBase
---> 40 from matplotlib.figure import Figure, figaspect
     41 from matplotlib.gridspec import GridSpec
     42 from matplotlib import rcParams, rcParamsDefault, get_backend, rcParamsOrig

~/anaconda3/lib/python3.7/site-packages/matplotlib-3.1.1+2663.ge240493a8-py3.7-linux-x86_64.egg/matplotlib/figure.py in <module>
     17 
     18 from matplotlib import rcParams
---> 19 from matplotlib import docstring, projections
     20 from matplotlib import __version__ as _mpl_version
     21 from matplotlib import get_backend

~/anaconda3/lib/python3.7/site-packages/matplotlib-3.1.1+2663.ge240493a8-py3.7-linux-x86_64.egg/matplotlib/projections/__init__.py in <module>
      2 from .geo import AitoffAxes, HammerAxes, LambertAxes, MollweideAxes
      3 from .polar import PolarAxes
----> 4 from mpl_toolkits.mplot3d import Axes3D
      5 
      6 

~/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/__init__.py in <module>
----> 1 from .axes3d import Axes3D

~/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py in <module>
     40 
     41 
---> 42 class Axes3D(Axes):
     43     """
     44     3D axes object.

~/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py in Axes3D()
    832             """
    833 
--> 834     @docstring.dedent_interpd
    835     def set_zscale(self, value, **kwargs):
    836         """

~/anaconda3/lib/python3.7/site-packages/matplotlib-3.1.1+2663.ge240493a8-py3.7-linux-x86_64.egg/matplotlib/docstring.py in dedent_interpd(func)
    114     """Dedent *func*'s docstring, then interpolate it with ``interpd``."""
    115     func.__doc__ = inspect.getdoc(func)
--> 116     return interpd(func)
    117 
    118 

~/anaconda3/lib/python3.7/site-packages/matplotlib-3.1.1+2663.ge240493a8-py3.7-linux-x86_64.egg/matplotlib/docstring.py in __call__(self, func)
     38     def __call__(self, func):
     39         if func.__doc__:
---> 40             func.__doc__ %= self.params
     41         return func
     42 

KeyError: 'scale'

### What is the expected behavior?
The code should run with no errors. It was running earlier today. I was trying to fix an issue with a different project, trying get matplotlib to show results in a graph. Uninstalled and reinstalled numpy and mathplotlib. A reboot fixed the issue, but now it persists.

**Comment by mtreinish** [comment]
Reading through that traceback it looks like a local install issue with matplotlib in your python env. It doesn't look like any qiskit code is actually causing this failure it errors trying to run `from matplotlib import pyplot`. I'd suggest you try to run that import by itself and debug your local python environment. 

Alternatively, if you do not require visualization you can just try uninstalling matplotlib from your environment and use qiskit without it, since visualization is optional dependency if matplotlib is not installed the rest of qiskit should still be usable.

I'm closing this because it does not appear to be anything in qiskit that is causing the issue. Please feel free to reopen if I'm missing something
