### ISSUE TITLE
File error after fresh install with pip (python 3.8.1)

### ISSUE THREAD

**Issue by dark-dryu** [Qiskit/qiskit-metapackage#760]
After installing qiskit I cannot import aer. Getting the following error:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/myuser/.local/lib/python3.8/site-packages/qiskit/providers/aer/VERSION.txt'`

How I should address this problem?

**Comment by kdk** [comment]
Hi @dark-dryu, were any errors raised when you ran `pip install qiskit`?  Are you able to run `import qiskit` from a python terminal? Can you include the full traceback?

**Comment by dark-dryu** [comment]
No errors came out of `pip install qiskit`. I cannot run `import qiskit` from a python terminal i get the following full traceback:
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/home/andreu/.local/lib/python3.8/site-packages/qiskit/__init__.py", line 50, in <module>`
   ` from qiskit.providers.aer import Aer`
`  File "/home/andreu/.local/lib/python3.8/site-packages/qiskit/providers/aer/__init__.py", line 63, in <module>`
    `from .aerprovider import AerProvider`
  `File "/home/andreu/.local/lib/python3.8/site-packages/qiskit/providers/aer/aerprovider.py", line 20, in <module>`
      `       from .backends.qasm_simulator import QasmSimulator`
  `File "/home/andreu/.local/lib/python3.8/site-packages/qiskit/providers/aer/backends/__init__.py", line 17, in <module>`
   ` from .qasm_simulator import QasmSimulator`
 ` File "/home/andreu/.local/lib/python3.8/site-packages/qiskit/providers/aer/backends/qasm_simulator.py", line 23, in <module>`
    `from ..version import __version__`
 ` File "/home/andreu/.local/lib/python3.8/site-packages/qiskit/providers/aer/version.py", line 20, in <module>`
    `with open(os.path.join(ROOT_DIR, "VERSION.txt"), "r") as version_file:`
`FileNotFoundError: [Errno 2] No such file or directory: '/home/andreu/.local/lib/python3.8/site-packages/qiskit/providers/aer/VERSION.txt'`

**Comment by kdk** [comment]
Interesting, what's the output of `pip freeze | grep qiskit`? Can you try `pip install --force-reinstall qiskit-aer`?

**Comment by dark-dryu** [comment]
This is the output
`qiskit==0.14.0`
`qiskit-aer==0.3.4`
`qiskit-aqua==0.6.1`
`qiskit-ibmq-provider==0.4.4`
`qiskit-ignis==0.2.0`
`qiskit-terra==0.11.0`
No change reinstalling qiskit-aer

**Comment by dark-dryu** [comment]
May that be related with the first note in this page?
[https://qiskit.org/documentation/install.html](url)
If so, were can I get the precompiled package? My dist repositories?

**Comment by cpphen** [comment]
Have you checked where your dependencies/packages are getting installed? It could be that when you run the program, the default location it looks for the code being imported is not being found in the expected location.

Also I think best practice with working with python and packages is to spin up a virtual instance and install packages.

**Comment by dark-dryu** [comment]
I checked the same procedure with python 3.7.4 and no such problem was present, probably there is an error with the latest version of python.

**Comment by cgorgulla** [comment]
Had the same problem with python 3.8, and as for @dark-dryu the problem was resolved by using python 3.7. 

Here they also note that only python 3.5, 3.6, and 3.7 are currently supported: 
https://pypi.org/project/qiskit/

**Comment by kdk** [comment]
FYI, the problem reported above by @dark-dryu will be fixed by https://github.com/Qiskit/qiskit-aer/pull/560 .
