### ISSUE TITLE
Wrong state vector simulator output

### ISSUE THREAD

**Issue by weiT1993** [Qiskit/qiskit-metapackage#780]
### Informations

- **Qiskit version**: 0.14.1
- **Python version**: 3.7
- **Operating system**: MacOS 10.15.2

### What is the current behavior?
State vector simulator outputs wrong result.

### Steps to reproduce the problem
Running the following codes:
```Python
from qiskit import QuantumRegister, QuantumCircuit, ClassicalRegister, Aer, execute
full_circ_size = 2
qr = QuantumRegister(full_circ_size)
circ = QuantumCircuit(qr)
circ.h(0)
circ.x(1)
circ.h(1)
circ.cx(0,1)
circ.h([0,1])
print('generated circuit:')
print(circ)
result = execute(circ, backend=Aer.get_backend('statevector_simulator'),optimization_level=0).result()
outputstate = result.get_statevector(circ)
print(outputstate)
```
prints out results:
```
generated circuit:
         ┌───┐          ┌───┐
q0_0: |0>┤ H ├───────■──┤ H ├
         ├───┤┌───┐┌─┴─┐├───┤
q0_1: |0>┤ X ├┤ H ├┤ X ├┤ H ├
         └───┘└───┘└───┘└───┘
[-7.85046229e-17+3.08148791e-32j  1.11022302e-16+6.12323400e-17j
  1.57009246e-16+6.12323400e-17j  1.00000000e+00-2.44929360e-16j]
```

### What is the expected behavior?
The output of this particular circuit should just be [0,0,0,1]. 

### Suggested solutions
Look into if the returned `backend.run(qobj)` under `execute` still does unintended optimization to the circuit even after setting `optimization_level=0`.

**Comment by yehuda-naveh** [comment]
Making sure - all values that should be zero are of order 10^{-16}. Are you concerned about the floating point numerical error? or just missed that?

**Comment by weiT1993** [comment]
I see, just want to make sure that is due to floating point numerical error rather than unintended behavior of `execute`.

**Comment by yehuda-naveh** [comment]
Yes it is
