### ISSUE TITLE
Decomposition 

### ISSUE THREAD

**Issue by monica1131** [Qiskit/qiskit-metapackage#795]
Can you please provide an example for N qubit Toffoli gate decomposition code

**Comment by ajavadia** [comment]
You might find this helpful: https://quantumcomputing.stackexchange.com/questions/2177/how-can-i-implement-an-n-bit-toffoli-gate/8273#8273

**Comment by monica1131** [comment]
Thank you, but it all talks about Toffoli gate implementation. What I want is how to implement decomposition for toffoli gate.
