### ISSUE TITLE
IBMQ backend service status filter does not work

### ISSUE THREAD

**Issue by weiT1993** [Qiskit/qiskit-metapackage#799]
### Informations

- **Qiskit version**: 0.14.1
- **Python version**: 3.7.5
- **Operating system**: MacOS 10.15.3

### What is the current behavior?
I just submitted a job to IBMQ_Boeblingen and did:
```
for job in x.jobs(limit=10,status='QUEUED'):
print(job)
```
But it does not show anything queued. However, doing:
```
for job in x.jobs(limit=10):
print(job.creation_date(),job.status(),job.queue_position(),job.job_id())
```
it does show that the queued jobs are there.

### What is the expected behavior?
```x.jobs(limit=10,status='QUEUED')``` should return the (at most) 10 most recently jobs queued.

**Comment by jyu00** [comment]
Thanks @weiT1993 for reporting this! This issue was also opened in `qiskit-ibmq-provider` ([issue 465](https://github.com/Qiskit/qiskit-ibmq-provider/issues/465)) and has since been fixed.
