### ISSUE TITLE
Publish both stable and development documentation

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-metapackage#80]
### What is the expected behavior?

From #39:

> allow keeping both the "stable" documentation (the one relevant to published packages) and the "master" (the one for more bleeding edge users) available (and maybe older versions too?).

**Comment by jaygambetta** [comment]
Are we going to do this with just a section for development documentation in each element? as a subsection or a new folder that is development form the top level.

**Comment by diego-plan9** [comment]
My thought was along the lines of having two separate URLs (for example, `/documentation` and `documentation/0.7/`), each one containing the fully rendered .html files. This way we can "tie" their deployment to meta-qiskit releases and treat each of the two as separate and isolated entities, moving them around as needed.

**Comment by jaygambetta** [comment]
Ok

**Comment by diego-plan9** [comment]
Labelling also as `theme`, as we need to find a UI-sensible way of linking to different versions or toggling between them.

**Comment by jaygambetta** [comment]
rather than doing it with a 0.7 can we have something like 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/15731369/52907747-b69e6480-3235-11e9-8850-c44c58ae3b28.png">

where you can toggle between the stable and master version of the doc. Or it could be dev/0.7/0.6/0.5 etc

**Comment by diego-plan9** [comment]
But would that imply that the only part of the documentation that has two versions is the "API references"?  It is likely to be the section that contains more changes, but I believe the rest of the documentation might change between versions as well - that is partly why I suggested just having each version self-contained in different URLs (ie. as two independent sets of .html files, etc).

**Comment by jaygambetta** [comment]
I am fine to have it at the top I just dont think the 5 files should not change that much. But I agree if contributing and installing changed it should go up that top like 

<img width="316" alt="image" src="https://user-images.githubusercontent.com/15731369/63217250-d04f3480-c110-11e9-8881-bebadbf7c798.png">

**Comment by jaygambetta** [comment]
closing and starting a new issue #466 as we have changed the docs
