### ISSUE TITLE
Documentation: where the qiskitrc is stored

### ISSUE THREAD

**Issue by ismaelfaro** [Qiskit/qiskit-metapackage#800]
This is a Documentation improvement:

In the documentation file:
https://github.com/Qiskit/qiskit/blob/master/docs/install.rst

Should be more specific and describe where Qiskit qiskitrc is stored. Example in Unix systems is under ~/qiskit/qiskitrc

**Comment by Ritvik-Sapra** [comment]
Hello. Which section are you referring to in the install.rst?

**Comment by nonhermitian** [comment]
I believe the requested info is now here: https://qiskit.org/documentation/configuration.html

**Comment by jakelishman** [comment]
Closing as fixed, since as Paul points out, the information is now present.
