### ISSUE TITLE
ImportError: cannot import name 'QuantumCircuit'

### ISSUE THREAD

**Issue by GideonWolfe** [Qiskit/qiskit-metapackage#811]
### Informations

- **Qiskit version**: 0.15.0
- **Python version**:Python 3.8.1
- **Operating system**: `Linux archlinux 5.4.14-arch1-1 #1 SMP PREEMPT Thu, 23 Jan 2020 10:07:05 +0000 x86_64 GNU/Linux`

### What is the current behavior?
Trying to run any qiskit code results in:
`
ImportError: cannot import name 'QuantumCircuit' from partially initialized module 'qiskit' (most likely due to a circular import)`

### Steps to reproduce the problem

`pip3 uninstall qiskit`
`sudo rm -r $HOME/.local/lib/python3.8/site-packages/qiskit*`
`pip3 install --user qiskit`
`python3`
`from qiskit import QuantumCircuit`

### What is the expected behavior?

The example code should run without error

### Suggested solutions

I'm not sure where this problem comes from. Googling the error message yielded no relevant results. I thought it was how I am installing the packages but I have done many fresh reinstalls.

**Comment by ryan-lam** [comment]
Go to terminal and run `pip install qiskit` then try running `from qiskit import QuantumCircuit` in your IDE

**Comment by GideonWolfe** [comment]
I'm not using an IDE, just vim and the command line. 

Unless I'm missing something I already did both the things you instructed in my "steps to reproduce".

Running `from qiskit import QuantumCircuit` from the interactive python console seems to execute without error. This is a bit strange since it seems to have thrown an error earlier.
 
Running the code [here ](https://qiskit.org/documentation/getting_started.html) throws the aforementioned error. 

I can even run a file with its only contents being `from qiskit import QuantumCircuit` and it will throw the error.

**Comment by GideonWolfe** [comment]
Error on my part. Named my test file `qiskit.py` like an idiot.
