### ISSUE TITLE
broken link https://qiskit.org/documentation/_autodoc/qiskit.mapper.html

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#82]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

**Comment by jaygambetta** [comment]
this is not working so there is a bug in the code.

**Comment by diego-plan9** [comment]
Actually seems a combination of two things:
* the actual URL may have changed slightly
* we are not rendering documentation for private modules (which is actually related to long-standing https://github.com/Qiskit/qiskit-terra/issues/1206) currently - that seems like the bug
