### ISSUE TITLE
Add transpiler to documentation. 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#83]
In qiskit terra, we need a section on the transpiler. 

I think this should go after visualizing a quantum circuit

**Comment by jaygambetta** [comment]
@ajavadia if you dont have time for this maybe you can put some points down here and @derivation you could try the first version.

**Comment by derivation** [comment]
@ajavadia if you share the material you presented about the transpiler at the 01/21/2019 Software Talk, I could write a draft of doc about it. I looked in the repo Leron made to store all the talks, but couldn't find it, under IBMQuantum/qiskit-planning

**Comment by 1ucian0** [comment]
There is some write down in `qiskit-terra/qiskit/transpiler/README.md` that needs some updating.

**Comment by derivation** [comment]
@ajavadia tells me the transpiler is going through some significant flux, so we'll wait til it settles down in a week or so before documenting it.

**Comment by derivation** [comment]
@ajavadia has the transpiler's design settled enough to revisit this issue?

**Comment by ajavadia** [comment]
@derivation almost, there's still one more change to the function signature that needs to be made, and then i will get back with some examples

**Comment by ajavadia** [comment]
Ok with the latest release, the transpiler API is mostly stable. There are two tutorials here:
https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/using_the_transpiler.ipynb
https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/writing_a_transpiler_pass.ipynb

@derivation can you please help ~~porting these to the docs~~ write the documentation? These would provide a reasonable entry point to see how it all works, and I can help with any questions.

**Comment by derivation** [comment]
@ajavadia will do
