### ISSUE TITLE
Add Hindi Language

### ISSUE THREAD

**Issue by techwithshadab** [Qiskit/qiskit-metapackage#833]
### What is the expected behavior?
Hindi is the national language for India. I would like to translate documentation to Hindi so that it can be easy for folks in India to understand and work on Qiskit.

**Comment by SooluThomas** [comment]
Hi @shadab-entrepreneur! Thanks for your interest in the localization effort. There is already an open issue for adding the Hindi language #734. We require more volunteers to open Hindi in Crowdin.

I'm closing this issue and you can follow up in #734.

**Comment by techwithshadab** [comment]
Sure thomas, thanks for informing me about the issue already being open, 
I will keep track on issue #734
