### ISSUE TITLE
Provider visualization and jupyter docs not being generated

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#834]
### Information
On qiskit.org:

<img width="1022" alt="Screen Shot 2020-02-29 at 7 39 30 AM" src="https://user-images.githubusercontent.com/1249193/75607581-a1a21580-5ac6-11ea-9913-af26f6b2503e.png">

When building provider docs locally:

<img width="1006" alt="Screen Shot 2020-02-29 at 7 38 33 AM" src="https://user-images.githubusercontent.com/1249193/75607584-aebf0480-5ac6-11ea-93c3-46faa1ebb907.png">

Also the Jupyter docs section is completely missing.  On qiskit.org:

<img width="688" alt="Screen Shot 2020-02-29 at 7 40 43 AM" src="https://user-images.githubusercontent.com/1249193/75607601-e62db100-5ac6-11ea-8030-db5af3aa7950.png">

locally:

<img width="738" alt="Screen Shot 2020-02-29 at 7 40 16 AM" src="https://user-images.githubusercontent.com/1249193/75607603-e9c13800-5ac6-11ea-8252-ea01d84aa716.png">

These should be a part of provider version 0.5+

**Comment by mtreinish** [comment]
Taking a quick look at the most recent docs build log:
https://travis-ci.com/Qiskit/qiskit/jobs/291851161#L393

For whatever reason on the combined docs build it couldn't import either module

**Comment by nonhermitian** [comment]
I am guessing the build is missing the optional installs in the provider. They are in the setup and dev requiremwnts

**Comment by nonhermitian** [comment]
Ok yeah, I think I need tonadd them to dev requirements here

**Comment by jakelishman** [comment]
If this wasn't fixed already, it will be obsolete now as IBMQ is no longer part of the metapackage.
