### ISSUE TITLE
Need way of loading IQX credentials in docs

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#836]
### What is the expected behavior?
I should be able to execute docs examples that require getting device information (but not execution) from the IQX. 

This is blocking #835.

**Comment by mtreinish** [comment]
Isn't this the same thing we fixed in terra with: https://github.com/Qiskit/qiskit-terra/pull/3438 ? Why can't you just use the hidden jupyter-execute cell like in there. That class is part of terra so the ibmq providers docs can use it the same exact way.

**Comment by nonhermitian** [comment]
I forgot all about this. Your right, this will do what I need. Thanks!

**Comment by nonhermitian** [comment]
Solved in https://github.com/Qiskit/qiskit-terra/pull/3911 and https://github.com/Qiskit/qiskit-ibmq-provider/pull/570
