### ISSUE TITLE
Ignis tutorials not showing up in docs

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#847]
### Informations

- **Qiskit version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Ignis tutorials not showing up in docs,

<img width="467" alt="Screen Shot 2020-03-16 at 12 13 46 PM" src="https://user-images.githubusercontent.com/1249193/76778132-b3024780-677f-11ea-8099-32cf9caba3e0.png">

but get added when building locally:

<img width="514" alt="Screen Shot 2020-03-16 at 12 15 02 PM" src="https://user-images.githubusercontent.com/1249193/76778187-c6151780-677f-11ea-908a-69fd5b6c1903.png">

There is nothing in the Travis docs build to indicate why this is the case.

**Comment by Ritvik-Sapra** [comment]
Could you please provide a link to the file you are referring to ?

**Comment by SooluThomas** [comment]
I think this issue was related the older tutorials (before the [reorganization](https://github.com/Qiskit/qiskit/pull/926)). So, are we good to close this issue @nonhermitian?

**Comment by nonhermitian** [comment]
Yep, can be closed.
