### ISSUE TITLE
Add French Language

### ISSUE THREAD

**Issue by robertxdw** [Qiskit/qiskit-metapackage#849]
I'm an IBM Quantum Ambassador and preparing Qiskit Advocate Certificat. there are eight of us, all IBMers and we would like to start translate Qiskit in French. I would like to be the translation lead and a translator at the same time. At least one of us will be proofreader. May you add French Language please ?
Thanks

**Comment by nonhermitian** [comment]
Can you please open this issue here: https://github.com/Qiskit/qiskit-translations
