### ISSUE TITLE
qiskit plots not showing up in spyder console

### ISSUE THREAD

**Issue by Trey-Jiron** [Qiskit/qiskit-metapackage#871]
### Informations

- **Qiskit version**: 0.17.0
- **Python version**: 3.7.7
- **Operating system**: Windows 10 home x64

### What is the current behavior?
I am using spyder 4.1.1 on Anaconda and any time I try to plot data it does not show up. The code runs with no errors but the plot it self does not appear anywhere. 

### Steps to reproduce the problem
Running the code listed below which is from the IBMQ website: 
```
import numpy 
import qiskit as qc 
from qiskit import QuantumCircuit, execute, Aer
import matplotlib
from qiskit.visualization import plot_state_city

circ = qc.QuantumCircuit(3)

circ.h(0)
circ.cx(0,1)
circ.cx(0,2)
print(circ.draw())
backend = Aer.get_backend('statevector_simulator')
job = execute(circ, backend)
result = job.result()
outputstate = result.get_statevector(circ, decimals=3)
print(outputstate)
plot_state_city(outputstate)
```

### What is the expected behavior?
for the plot state city plot to show up in the console or somewhere else

### Suggested solutions
I tried using both matplotlib.pylot.show() and matplotlib.pyplot.draw()

**Comment by Hirmay** [comment]
Have you tried updating qiskit or matplot lib as I don't face that problem.
![noerror](https://user-images.githubusercontent.com/56473003/89789572-65c3af80-db3e-11ea-823d-08dd28c9d220.PNG)

**Comment by Trey-Jiron** [comment]
> 
> 
> Have you tried updating qiskit or matplot lib as I don't face that problem.
> ![noerror](https://user-images.githubusercontent.com/56473003/89789572-65c3af80-db3e-11ea-823d-08dd28c9d220.PNG)

I will have to try updating it, it was up to date when I posted this but perhaps a new update changed it. Will check it out, thank you very much.

**Comment by Hirmay** [comment]
Yeah it has been a long time since so try giving it a shot and let me know what happens

**Comment by Rocketblaster247** [comment]
Same thing happens to me.

**Comment by Rocketblaster247** [comment]
Never mind, matplotlib.pyplot.show worked just fine.

**Comment by Trey-Jiron** [comment]
followed the top solution here and it fixed it, so thank you all.: 
https://stackoverflow.com/questions/61568297/qiskit-plots-not-showing-up-in-spyder-console/62319001#62319001
