### ISSUE TITLE
Tutorials do not show up in non-default languages

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#874]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Tutorials are not showing up in German or Japanese translation pages.

**Comment by SooluThomas** [comment]
https://github.com/Qiskit/qiskit/pull/875 and commit [8055901](https://github.com/Qiskit/qiskit/commit/80559010fbab7a0fed638a2c320bc173b159e50a) will fix this
