### ISSUE TITLE
An issue regarding the function and module 

### ISSUE THREAD

**Issue by Diyorazh** [Qiskit/qiskit-metapackage#876]
### Informations

- qiskit 0.12.0
- Python 3
- mac OS 10.14.4

### What is the current behavior?

Hello there,
I was trying to reproduce a circuit by using qiskit. The code I was using includes 
"from qiskit.mapper import two_qubit_kak
from qiskit.wrapper import register, execute, get_backend, compile"
however, the results shows that these modules have been removed. 

### Steps to reproduce the problem

(same as above)

### What is the expected behavior?

I want to know about where to find these functions/modules.

### Suggested solutions

(blank)

Thank you so much!

Diyora

**Comment by MIWdlB** [comment]
Search in the documentations changelog for the alterations:
https://qiskit.org/documentation/release_notes.html

`qiskit.mapper.compiling.two_qubit_kak(): qiskit.quantum_info.synthesis.two_qubit_cnot_decompose() should be used instead.`

As far as I can tell the other ones should still be supported!

**Comment by d4rkc0nd0r** [comment]
Qiskit needs to be updated to its latest version `qiskit==0.20.0`.

**Comment by jakelishman** [comment]
Closing now as answered.
