### ISSUE TITLE
Makefile pointing to wrong directories for aqua and chem autodoc?

### ISSUE THREAD

**Issue by derivation** [Qiskit/qiskit-metapackage#88]
@diego-plan9, can I get a sanity check from you? 

### Information

- **Qiskit version**: latest
- **Python version**: 3.7
- **Operating system**: macOS 14.6

### What is the current behavior?

`make doc` errors out while looking for Aqua and Chemistry directories

sphinx-apidoc --output docs/autodoc --separate --implicit-namespaces --module-first -d 16 \
		<PATH_QISKIT>/qiskit_aqua
~/.../qiskit-terra/qiskit_aqua is not a directory.
make: *** [autodoc_aqua] Error 1

### Steps to reproduce the problem

1. Clone all of the repos with Qiskit doc in them.
2. Run `make doc`

### What is the expected behavior?

The Makefile should be pointing to the correct directories using `pip show` and `grep`.

### Suggested solutions

I've edited the Makefile in a personal fork to make things work, but I'm wary that there's a reason why the Makefile is the way it is today that I'm not aware of, despite it not working for me locally.

**Comment by diego-plan9** [comment]
Good catch @derivation !

https://github.com/Qiskit/qiskit/blob/master/Makefile#L24
```
$(PATH_QISKIT)/qiskit_aqua
```
should indeed be
```
$(PATH_AQUA)/qiskit_aqua
```
