### ISSUE TITLE
Error due to pyscf in qiskit 0.18.0 installation

### ISSUE THREAD

**Issue by ghost** [Qiskit/qiskit-metapackage#884]
### Informations

- **Qiskit version**: 0.18.0
- **Python version**:3.6.10,3.7.8,3.8.2
- **Operating system**: Mac OS X 10.12.6 (Sierra)

### What is the current behavior?
I have tried to install qiskit in different versions of python [3.6,3.7,3.8] (all installed via macports). In all cases I find the following error with the following command to install (I am providing the directory of the BLAS files using LDFLAGS since not doing that also leads to an error of not being able to locate BLAS directory):

$LDFLAGS="-L/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Resources/ -lblas" pip install qiskit

Output:
ERROR: Command errored out with exit status 1:
     command: /opt/local/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6n/1_y2bxmd2yq9xfh_z3k58tf80000gp/T/pip-install-h5t9l46j/pyscf/setup.py'"'"'; __file__='"'"'/private/var/folders/6n/1_y2bxmd2yq9xfh_z3k58tf80000gp/T/pip-install-h5t9l46j/pyscf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6n/1_y2bxmd2yq9xfh_z3k58tf80000gp/T/pip-install-h5t9l46j/pyscf/pip-egg-info
         cwd: /private/var/folders/6n/1_y2bxmd2yq9xfh_z3k58tf80000gp/T/pip-install-h5t9l46j/pyscf/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6n/1_y2bxmd2yq9xfh_z3k58tf80000gp/T/pip-install-h5t9l46j/pyscf/setup.py", line 354, in <module>
        raise RuntimeError
    RuntimeError
    ****************************************************************
    *** WARNING: libcint library not found.
    * You can download libcint library from http://github.com/sunqm/libcint
    * May need to set PYSCF_INC_DIR if libcint library was not installed in the
    * system standard install path (/usr, /usr/local, etc). Eg
    *   export PYSCF_INC_DIR=/path/to/libcint:/path/to/other/lib
    ****************************************************************
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### Steps to reproduce the problem
Since the issue somehow seems to be the libcint library files, I tried to make static library of the same by directly downloading the source files from:
http://github.com/sunqm/libcint
The following files are present in the /usr/local/lib/ folder:
$mdfind libcint
/Users/x2241044/Library/Containers/com.apple.Notes/Data/Library/CoreData/ExternalRecords/NotesV4/668306BD-DBA9-4896-8EB8-01ACF603303F/ICNote/_records/3/0/p361.notesexternalrecord
/usr/local/lib/libcint.a
/usr/local/lib/libcint.3.0.19.dylib

### What is the expected behavior?
I understand the python 3.8 support is not yet available but I was hoping at least earlier versions would work.

### Suggested solutions
I am out of ideas now..any help is appreciated. I am not an expert in Linux/OS X by any stretch of imagination!

**Comment by nonhermitian** [comment]
Hello.  Not really sure if this is a bug on our end.  It looks like your environment is requesting you build `pyscf` from source but your path information is not set correctly.

**Comment by FerjaniMY** [comment]
Try to add libcint to `pyscf_inc_dir` . I hope that will help!

**Comment by nonhermitian** [comment]
Closing as stale.  Feel free to reopen if not.
