### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by rtmatphys** [Qiskit/qiskit-metapackage#889]
### Informations

- **Qiskit version**: qiskit-0.18.1
- **Python version**: Python 3.7.3
- **Operating system**: SUSE Linux Enterprise Server 11 SP4

### What is the current behavior?
I created a conda virtual environment and tried to install qiskit in the following way:
```
conda create -n qiskit_env python=3.7.3 pip=19.1.1
pip install qiskit
```
Then I got the following error. Does anyone have a good suggestion for the solution?

```
ERROR: Complete output from command /home/xxxx/yyyy/anaconda3/envs/qiskit_env/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-y82svlmd/qiskit-aer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xyu5f0k9 --python-tag cp37:
  ERROR:

  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-y82svlmd/qiskit-aer/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "Unix Makefiles" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 4.3.4
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 4.3.4
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ - works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-y82svlmd/qiskit-aer/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Unix Makefiles" generator - success
  --------------------------------------------------------------------------------

  -- The CXX compiler identification is GNU 5.4.0
  -- The C compiler identification is GNU 5.4.0
  -- Check for working CXX compiler: /home/app/gcc/5.4.0/bin/c++
  -- Check for working CXX compiler: /home/app/gcc/5.4.0/bin/c++ - works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Check for working C compiler: /home/app/gcc/5.4.0/bin/gcc
  -- Check for working C compiler: /home/app/gcc/5.4.0/bin/gcc - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Looking for OpenMP support...
  -- OpenMP found!
  -- OpenMP_CXX_FLAGS = -fopenmp
  -- OpenMP_EXE_LINKER_FLAGS =
  -- Looking for NLOHMANN Json library...
  -- nlohmann include dir: /tmp/pip-install-y82svlmd/qiskit-aer/src/third-party/headers
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Looking for OpenBLAS library...
  -- OpenBLAS not found. Looking for any other BLAS library...
  -- Looking for sgemm_
  -- Looking for sgemm_ - not found
  -- Looking for sgemm_
  -- Looking for sgemm_ - found
  -- Found BLAS: /home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_core.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64_lin/libiomp5.so;-lpthread;-lm;-ldl
  -- BLAS library found: /home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_core.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64_lin/libiomp5.so;-lpthread;-lm;-ldl
  -- Looking for spdlog library...
  -- spdlog not found.
  -- No Thrust supported backend
  -- No Thrust support enabled
  -- Looking for muparserx library...
  -- Muparserx library not found. Uncompressing muparserx static library...
  x libmuparserx.a
  -- Muparserx library found: /tmp/pip-install-y82svlmd/qiskit-aer/src/third-party/linux/lib/libmuparserx.a
  -- muparserx library source code already exists
  -- Found PythonInterp: /home/xxxx/yyyy/anaconda3/envs/qiskit_env/bin/python (found version "3.7.3")
  -- Found PythonLibs: /home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/libpython3.7m.so (found version "3.7.3")
  -c:42: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
  -- Found Cython: /home/xxxx/yyyy/anaconda3/bin/cython
  CMake Error at .eggs/cmake-3.17.1-py3.7-linux-x86_64.egg/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
    Could NOT find NumPy (missing: NumPy_INCLUDE_DIR) (found version "")
  Call Stack (most recent call first):
    .eggs/cmake-3.17.1-py3.7-linux-x86_64.egg/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
    /home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/python3.7/site-packages/skbuild/resources/cmake/FindNumPy.cmake:98 (find_package_handle_standard_args)
    cmake/cython_utils.cmake:4 (find_package)
    qiskit/providers/aer/pulse/cy/CMakeLists.txt:4 (include)


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-y82svlmd/qiskit-aer/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-y82svlmd/qiskit-aer/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "/home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 574, in setup
      languages=cmake_languages
    File "/home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/python3.7/site-packages/skbuild/cmaker.py", line 232, in configure
      os.path.abspath(CMAKE_BUILD_DIR())))

  An error occurred while configuring with CMake.
    Command:
      "/tmp/pip-install-y82svlmd/qiskit-aer/.eggs/cmake-3.17.1-py3.7-linux-x86_64.egg/cmake/data/bin/cmake" "/tmp/pip-install-y82svlmd/qiskit-aer" "-G" "Unix Makefiles" "-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-y82svlmd/qiskit-aer/_skbuild/linux-x86_64-3.7/cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=/home/xxxx/yyyy/anaconda3/envs/qiskit_env/bin/python" "-DPYTHON_VERSION_STRING:STRING=3.7.3" "-DPYTHON_INCLUDE_DIR:PATH=/home/xxxx/yyyy/anaconda3/envs/qiskit_env/include/python3.7m" "-DPYTHON_LIBRARY:FILEPATH=/home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/libpython3.7m.so" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/python3.7/site-packages/skbuild/resources/cmake" "-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9" "-DCMAKE_BUILD_TYPE:STRING=Release"
    Source directory:
      /tmp/pip-install-y82svlmd/qiskit-aer
    Working directory:
      /tmp/pip-install-y82svlmd/qiskit-aer/_skbuild/linux-x86_64-3.7/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for qiskit-aer

```

**Comment by mtreinish** [comment]
The issue here seems to be that pip is not selecting a precompiled binary for the qiskit-aer package for some reason. Are you running on an architecture besides `x86_64`? The only linux wheels published for the package are on x86_64: https://pypi.org/project/qiskit-aer/#files Running on i686 or another architecture is the typical cause of this. Although my other guess would be that it might be because of sles 11 which is pretty old, the system libraries might not be compatible with [manylinux2010](https://www.python.org/dev/peps/pep-0571/) which is why pip doesn't think there are available precompiled wheel files.

**Comment by rtmatphys** [comment]
I appreciate the quick response.
I am running on x86_64, so it doesn't seem like the architecture is the issue here. 
Maybe the error is caused by the old operating system, as you mentioned. Do you have any suggestion for how I could successfully install qiskit on SLES 11?

**Comment by t-imamichi** [comment]
Perhaps pip might be old. Can you show `pip --version`?

**Comment by rtmatphys** [comment]
The pip version is 19.1.1.

**Comment by t-imamichi** [comment]
How about upgrading pip to the latest one?

**Comment by rtmatphys** [comment]
I tried the latest version of pip (20.0.2), and yet got the same error...

**Comment by mtreinish** [comment]
I would try `pip install -v qiskit-aer` and paste the output here. That will show us why pip is skipping the aer wheels published on pypi in your environment. As a workaround while we figure out/debug why the wheels aren't working for you and if you don't need aer for your use case manually install terra, ignis, and ibmq provider (aqua also depends on aer so that can't be installed until we figure out the source of the error) with `pip install qiskit-terra qiskit-ignis qiskit-ibmq-provider`.

The thing I'm confused by is in that error message specifically, because even if the wheels work you should be able to install from sdist (which will compile aer from source). Numpy should be installed by pip prior to trying to build qiskit-aer. My only thought is it's a conflict in the conda env, where numpy is installed by conda and pip can't find it (or pip installs numpy and it conflicts with the conda installed version).

**Comment by rtmatphys** [comment]
Thank you for the advice. Well, I need to use Aer and Aqua. 

I tried  `pip install -v qiskit-aer` and got a similar error. Since the output is very long, I paste it on the following attached file.
[qiskit-aer_install_output.txt](https://github.com/Qiskit/qiskit/files/4526057/qiskit-aer_install_output.txt)

I hope this could help you to figure out the cause of the failure. I suppose this time numpy was successfully found out.

**Comment by t-imamichi** [comment]
I saw the log. It may be because SUSE 11 is older than CentOS 6, which is the base of [manylinux2010](https://www.python.org/dev/peps/pep-0571/#rationale). manylinux1 matches in the log, but the latest Aer is provided upon manylinux2010.

**Comment by rtmatphys** [comment]
Thank you for checking the log. So... does that mean there's no way installing qiskit-aer on SUSE 11?

**Comment by t-imamichi** [comment]
According to [Aer documantation](https://github.com/Qiskit/qiskit-aer/blob/master/CONTRIBUTING.md#linux), you need a C++14 compatible compiler to build Aer.

**Comment by mtreinish** [comment]
Yeah, it's what I thought was going to be the issue with sles 11 being too old for the precompiled binary. Your only recourse for installing aer will be to build it from it from source (either the source package, sdist, via pip, or from the source repo manually). You can refer to the link from @t-imamichi and https://qiskit.org/documentation/contributing_to_qiskit.html#installing-aer-from-source for the process for doing this. Although both assume a local git clone. You can replace that piece in both guides with `pip install qiskit` or `pip install qiskit-aer` as both with attempt to build the package from source on your system. My only concern is that something on sles 11 is going to be a blocker for the compilation, especially based on the log's failure section:

```
    [ 89%] Linking CXX shared module test_python_to_cpp.cpython-37m-x86_64-linux-gnu.so
    /usr/bin/ld: ../../../../../src/third-party/linux/lib/libmuparserx.a(mpParser.cpp.o): unrecognized relocation (0x2a) in section `.text'
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    gmake[2]: *** [src/open_pulse/test_python_to_cpp.cpython-37m-x86_64-linux-gnu.so] Error 1
    gmake[1]: *** [src/open_pulse/CMakeFiles/test_python_to_cpp.dir/all] Error 2
    gmake: *** [all] Error 2
```

which normally happens if the version of `ld` is older than what's needed. You might be able to workaround this (if upgrading ld isn't an option) by trying to manually recompile libmuparserx, but it could be tricky to integrate that into the aer builds because of how it tries to bundle everything for a self contained build. If you continue to have build problems I can transfer this issue to qiskit-aer and we can discussing how to improve/fix the aer build system for your use case.

As an aside I suspect the manylinux1 wheels for old versions of aer wouldn't work either, because they are not actually manylinux1 compliant, they were hand edited to say they were despite using a newer libc. (which is why it's been fixed to only say manylinux 2010 now)

**Comment by rtmatphys** [comment]
By using the latest version of the GNU compilers, I got around the issue probably.

Since the GNU compiler was old (4.3.4), I installed the latest version in my conda environment and created the symbolic links:
```
conda install gcc_linux-64
conda install gxx_linux-64
ln -s envs/qiskit_env/bin/x86_64-conda_cos6-linux-gnu-gcc envs/qiskit_env/bin/gcc
ln -s envs/qiskit_env/bin/x86_64-conda_cos6-linux-gnu-gxx envs/qiskit_env/bin/gxx
```
Then I installed qiskit via `pip install qiskit` and looks like it worked fine.
Thank you for your valuable comments.

**Comment by t-imamichi** [comment]
I think we can close this issue.

**Comment by rtmatphys** [comment]
We should. Thank you!

**Comment by MichaelSchroter** [comment]
> ### Informations
> * **Qiskit version**: qiskit-0.18.1
> * **Python version**: Python 3.7.3
> * **Operating system**: SUSE Linux Enterprise Server 11 SP4
> 
> ### What is the current behavior?
> I created a conda virtual environment and tried to install qiskit in the following way:
> 
> ```
> conda create -n qiskit_env python=3.7.3 pip=19.1.1
> pip install qiskit
> ```
> 
> Then I got the following error. Does anyone have a good suggestion for the solution?
> 
> ```
> ERROR: Complete output from command /home/xxxx/yyyy/anaconda3/envs/qiskit_env/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-y82svlmd/qiskit-aer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xyu5f0k9 --python-tag cp37:
>   ERROR:
> 
>   --------------------------------------------------------------------------------
>   -- Trying "Ninja" generator
>   --------------------------------
>   ---------------------------
>   ----------------------
>   -----------------
>   ------------
>   -------
>   --
>   Not searching for unused variables given on the command line.
>   CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
>   -- Configuring incomplete, errors occurred!
>   See also "/tmp/pip-install-y82svlmd/qiskit-aer/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
>   --
>   -------
>   ------------
>   -----------------
>   ----------------------
>   ---------------------------
>   --------------------------------
>   -- Trying "Ninja" generator - failure
>   --------------------------------------------------------------------------------
> 
> 
> 
>   --------------------------------------------------------------------------------
>   -- Trying "Unix Makefiles" generator
>   --------------------------------
>   ---------------------------
>   ----------------------
>   -----------------
>   ------------
>   -------
>   --
>   Not searching for unused variables given on the command line.
>   -- The C compiler identification is GNU 4.3.4
>   -- Check for working C compiler: /usr/bin/cc
>   -- Check for working C compiler: /usr/bin/cc - works
>   -- Detecting C compiler ABI info
>   -- Detecting C compiler ABI info - done
>   -- Detecting C compile features
>   -- Detecting C compile features - done
>   -- The CXX compiler identification is GNU 4.3.4
>   -- Check for working CXX compiler: /usr/bin/c++
>   -- Check for working CXX compiler: /usr/bin/c++ - works
>   -- Detecting CXX compiler ABI info
>   -- Detecting CXX compiler ABI info - done
>   -- Detecting CXX compile features
>   -- Detecting CXX compile features - done
>   -- Configuring done
>   -- Generating done
>   -- Build files have been written to: /tmp/pip-install-y82svlmd/qiskit-aer/_cmake_test_compile/build
>   --
>   -------
>   ------------
>   -----------------
>   ----------------------
>   ---------------------------
>   --------------------------------
>   -- Trying "Unix Makefiles" generator - success
>   --------------------------------------------------------------------------------
> 
>   -- The CXX compiler identification is GNU 5.4.0
>   -- The C compiler identification is GNU 5.4.0
>   -- Check for working CXX compiler: /home/app/gcc/5.4.0/bin/c++
>   -- Check for working CXX compiler: /home/app/gcc/5.4.0/bin/c++ - works
>   -- Detecting CXX compiler ABI info
>   -- Detecting CXX compiler ABI info - done
>   -- Detecting CXX compile features
>   -- Detecting CXX compile features - done
>   -- Check for working C compiler: /home/app/gcc/5.4.0/bin/gcc
>   -- Check for working C compiler: /home/app/gcc/5.4.0/bin/gcc - works
>   -- Detecting C compiler ABI info
>   -- Detecting C compiler ABI info - done
>   -- Detecting C compile features
>   -- Detecting C compile features - done
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Performing Test flag_supported
>   -- Performing Test flag_supported - Success
>   -- Looking for OpenMP support...
>   -- OpenMP found!
>   -- OpenMP_CXX_FLAGS = -fopenmp
>   -- OpenMP_EXE_LINKER_FLAGS =
>   -- Looking for NLOHMANN Json library...
>   -- nlohmann include dir: /tmp/pip-install-y82svlmd/qiskit-aer/src/third-party/headers
>   -- Looking for pthread.h
>   -- Looking for pthread.h - found
>   -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
>   -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
>   -- Looking for pthread_create in pthreads
>   -- Looking for pthread_create in pthreads - not found
>   -- Looking for pthread_create in pthread
>   -- Looking for pthread_create in pthread - found
>   -- Found Threads: TRUE
>   -- Looking for OpenBLAS library...
>   -- OpenBLAS not found. Looking for any other BLAS library...
>   -- Looking for sgemm_
>   -- Looking for sgemm_ - not found
>   -- Looking for sgemm_
>   -- Looking for sgemm_ - found
>   -- Found BLAS: /home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_core.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64_lin/libiomp5.so;-lpthread;-lm;-ldl
>   -- BLAS library found: /home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64_lin/libmkl_core.so;/home/app/intel/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64_lin/libiomp5.so;-lpthread;-lm;-ldl
>   -- Looking for spdlog library...
>   -- spdlog not found.
>   -- No Thrust supported backend
>   -- No Thrust support enabled
>   -- Looking for muparserx library...
>   -- Muparserx library not found. Uncompressing muparserx static library...
>   x libmuparserx.a
>   -- Muparserx library found: /tmp/pip-install-y82svlmd/qiskit-aer/src/third-party/linux/lib/libmuparserx.a
>   -- muparserx library source code already exists
>   -- Found PythonInterp: /home/xxxx/yyyy/anaconda3/envs/qiskit_env/bin/python (found version "3.7.3")
>   -- Found PythonLibs: /home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/libpython3.7m.so (found version "3.7.3")
>   -c:42: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
>   -- Found Cython: /home/xxxx/yyyy/anaconda3/bin/cython
>   CMake Error at .eggs/cmake-3.17.1-py3.7-linux-x86_64.egg/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
>     Could NOT find NumPy (missing: NumPy_INCLUDE_DIR) (found version "")
>   Call Stack (most recent call first):
>     .eggs/cmake-3.17.1-py3.7-linux-x86_64.egg/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
>     /home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/python3.7/site-packages/skbuild/resources/cmake/FindNumPy.cmake:98 (find_package_handle_standard_args)
>     cmake/cython_utils.cmake:4 (find_package)
>     qiskit/providers/aer/pulse/cy/CMakeLists.txt:4 (include)
> 
> 
>   -- Configuring incomplete, errors occurred!
>   See also "/tmp/pip-install-y82svlmd/qiskit-aer/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
>   See also "/tmp/pip-install-y82svlmd/qiskit-aer/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeError.log".
>   Traceback (most recent call last):
>     File "/home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 574, in setup
>       languages=cmake_languages
>     File "/home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/python3.7/site-packages/skbuild/cmaker.py", line 232, in configure
>       os.path.abspath(CMAKE_BUILD_DIR())))
> 
>   An error occurred while configuring with CMake.
>     Command:
>       "/tmp/pip-install-y82svlmd/qiskit-aer/.eggs/cmake-3.17.1-py3.7-linux-x86_64.egg/cmake/data/bin/cmake" "/tmp/pip-install-y82svlmd/qiskit-aer" "-G" "Unix Makefiles" "-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-y82svlmd/qiskit-aer/_skbuild/linux-x86_64-3.7/cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=/home/xxxx/yyyy/anaconda3/envs/qiskit_env/bin/python" "-DPYTHON_VERSION_STRING:STRING=3.7.3" "-DPYTHON_INCLUDE_DIR:PATH=/home/xxxx/yyyy/anaconda3/envs/qiskit_env/include/python3.7m" "-DPYTHON_LIBRARY:FILEPATH=/home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/libpython3.7m.so" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/home/xxxx/yyyy/anaconda3/envs/qiskit_env/lib/python3.7/site-packages/skbuild/resources/cmake" "-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9" "-DCMAKE_BUILD_TYPE:STRING=Release"
>     Source directory:
>       /tmp/pip-install-y82svlmd/qiskit-aer
>     Working directory:
>       /tmp/pip-install-y82svlmd/qiskit-aer/_skbuild/linux-x86_64-3.7/cmake-build
>   Please see CMake's output for more information.
>   ----------------------------------------
>   ERROR: Failed building wheel for qiskit-aer
> ```

This the exact result that I get when trying to install qiskit. Qistkit-aer installation error is also similar. I am using Debian 10. 
`python3.9` virtual environment.
I did;
```
pip install qiskit
pip install qiskit-aer

```
Would anyone know what is the solutions for this please?

Thanks & Best Regards

Michael

**Comment by t-imamichi** [comment]
As in the discussion, sles 11 is too old and qiskit does not support pre-compiled binary.
