### ISSUE TITLE
Conda environment management command

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-metapackage#894]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
https://github.com/Qiskit/qiskit/blob/master/docs/install.rst

- What is the current text that needs to be fixed or removed? (You can copy and paste)
The current text uses `source activate name_of_my_env` for linux and mac and `activate name_of_my_env` for windows to activate a conda environment.

- What should the documentation say instead?
Since conda 4.6, it seems to use `conda activate` to activate an environment.
https://docs.conda.io/projects/conda/en/latest/commands.html#conda-vs-pip-vs-virtualenv-commands
I'm afraid that I didn't test it because I'm a virtualenv user. 

- Are there other related issues or pull requests about this bug?
I have no idea.

## Does existing documentation need to be updated with new content?

- Which files need to be updated?
https://github.com/Qiskit/qiskit/blob/master/docs/install.rst

- What content needs to be updated or replaced? (You can copy and paste)
- What new content needs to be added?
If qiskit supports only conda 4.6 or later, it seems good to replace `source activate name_of_my_env` and `activate name_of_my_env` with `conda activate name_of_my_env`; but if qiskit supports 4.5 or before, it is necessary to keep the current text.

**Comment by Ritvik-Sapra** [comment]
It is right to do so. Conda gives warning that activate/deactivate is depreciated. We should use conda deactivate
