### ISSUE TITLE
qiskit documentation 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#9]
# Qiskit documentation

This document summarizes the flow for updating the documentation for Qiskit
that ends up being available at:

https://qiskit.org/documentation/

This is complicated as it needs to draw from multiple places. 

## https://qiskit.org/documentation/

This is made from the repo **Qiskit** using the files:
- /doc/index.rst 
- /doc/overview.rst 
- /doc/install.rst 
- ... rst converstions of the notebooks in **qiskit-tutorials**/qiskit/basic

Then it should have a link to the following 
/terra -> either folder of link to doc generated by terra
/aer -> either folder of link to doc generated by aer
/ignus -> not available yet. 
/aqua -> either folder of link to doc generated by aqua
/chemistry -> either folder of link to doc generated by chemistry

## https://qiskit.org/documentation/terra

This will be built from **Qiskit-terra**

- /doc/index.rst
- /doc/overview.rst
- ... rst converstions of the notebooks in **qiskit-tutorials**/qiskit/terra
- /doc/CONTRIBUTING
- /doc/release_history
-- then auto build of the Terra SDK reference _autodoc/qiskit

## https://qiskit.org/documentation/aer

This will be built from **Qiskit-aer**

- /doc/index.rst
- /doc/overview.rst
- ... rst converstions of the notebooks in **qiskit-tutorials**/qiskit/aer
- /doc/CONTRIBUTING
- /doc/release_history
-- then auto build of the Aer SDK reference _autodoc/qiskit

## https://qiskit.org/documentation/aqua

This will be built from **Qiskit-aqua**

- /doc/index.rst
- /doc/overview.rst
- /doc/install.rst (this we need until aqua is in qiskit)
- ... rst converstions of the notebooks in **qiskit-tutorials**/qiskit/aqua
- /doc/CONTRIBUTING
- /doc/release_history
-- then auto build of the Aqua SDK reference _autodoc/qiskit

## https://qiskit.org/documentation/chemistry

This will be built from **Qiskit-chemistry**

- /doc/index.rst
- /doc/overview.rst
- /doc/install.rst 
- ... rst converstions of the notebooks in **qiskit-tutorials**/qiskit/aqua/chemistry
- /doc/CONTRIBUTING
- /doc/release_history
-- then auto build of the Chemistry SDK reference _autodoc/qiskit

## Flow steps:

1. update the .rst files in the `doc/` folder (or `qiskit/` Python docstrings)
   at `foo` repository.
2. push to `foo` repository `stable` branch (via a PR).
3. when the CI (Travis) is completed for that merge, it will automatically
   push a commit to the `qiskit.org` repository with the HTML documentation.
4. in turn, the CI (Travis) for the `qiskit.org` repository starts a deploy
   into the server that hosts `qiskit.org`.
5. enjoy the new documentation at https://qiskit.org/documentation.

Questions.
@abdonrd and @diego-plan9 which option is best 
- [ ] is it better we push from qiskit-foo to this repo and then when this repo passes it pushes to qiskit.org so that the https://qiskit.org/documentation/foo is just a folder in here
- [ ] option 2  or to have multiple auto ci going to the qiskit.org repo from all the elements and here to make the documentation. 
- [ ] option 3 [i like this best] is to remove all documentation from the elements and add it here and then generate from this folder the documentation on the qiskit.org/documentation. In the elements, we just have a readme pointing to this repo.
- [ ] diego can you set up the documentation building and automation in this repo for an overview and install

**Comment by jaygambetta** [comment]
@atilag and @chriseclectic to get the docs for aer going you only really need an overview as you have the contributing and the release notes and two tutorials.

**Comment by jaygambetta** [comment]
@pistoia how does this simplifying of documentation process change your current docs in aqua and chemistry.

**Comment by pistoia** [comment]
@jaygambetta Right now the process of generating the documentation of Qiskit Aqua and Qiskit Chemistry is somewhat convoluted because we wanted to merge the two documentation trees into one in spite of them coming from two separate repositories (see https://github.com/Qiskit/qiskit-aqua/blob/master/docs/README.md).  I think this process is going to simplify and unify everything so it's good.

**Comment by diego-plan9** [comment]
> diego can you set up the documentation building and automation in this repo for an overview and install

I added the first bit (building locally via `make doc` at #16). For the automation, I think we need to refine the flow with the help of other people involved (basically decide how the different projects "plug" their documentation into the main one). Which brings me to ...

> @abdonrd and @diego-plan9 is it better we push from qiskit-foo to this repo and then when this repo passes it pushes to qiskit.org so that the https://qiskit.org/documentation/foo is just a folder in here or to have multiple ci going to the qiskit.org repo. I would prefer the push here so that we can do a make doc in this repo and check out the documentation before it is pushed to the qiskit.org site

I'd basically be happy with whichever @abdonrd finds more convenient, as it seems mostly a deployment question! I do like the idea of having all the updates to the "live" documentation centralized somewhere (as in, in this repo, for example) as you mention.

My main question is how do you see the flow for each project's documentation team: would they always work against this repository, making changes to the files here directly; or on the contrary keep working on the documentation on each individual repo and we come up with some means of "retrieving those changes automatically"? I can see arguments for both :grimacing:

**Comment by jaygambetta** [comment]
I don’t know why if we move it all here we even need it in the other repositories. Look at tensorflow 

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

We could do the same with a readme going here. 

The problem with that is how do we auto generate the sdk. 

I would like only one place and then auto updating  for the rest.

**Comment by jaygambetta** [comment]
I am closing this as we have the documentation in this repo now.
