### ISSUE TITLE
sphinx-autodoc-typehints causes a deprecation warning on each type hint

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-metapackage#911]
### Informations

- **Qiskit version**: All
- **Python version**: All
- **Operating system**: All

### What is the current behavior?

Since the sphinx 3.0.0 release the use of sphinx-autodoc-typehints has been leading to runaway deprecation warnings. Every time a type hint is encountered the plugin's use of a deprecated api
emits a deprecation warning like:
```
/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/sphinx/util/inspect.py:555: RemovedInSphinx40Warning: sphinx.util.inspect.Signature() is deprecated
  RemovedInSphinx40Warning)
```

Which took some digging to figure where it was coming from: https://github.com/agronholm/sphinx-autodoc-typehints/blob/a25fa05084b4cee7e9e733603b79e68986a0ffee/sphinx_autodoc_typehints.py#L161 every time that gets called

Sphinx is supposed to have native support for type annotations now s o we should be able 
to remove the plugin usage.

### Steps to reproduce the problem

Run a docs build

### What is the expected behavior?

No deprecation warnings about this

### Suggested solutions

Remove the plugin from the build

**Comment by mtreinish** [comment]
This will also need to be propagated to each element, but I started here because it's causing the string extraction travis job to fail (the job actually works but when `travis_wait` exits and dumps the output the number of log lines exceeds the maximum and the job is marked as failed)

**Comment by mtreinish** [comment]
I've pushed a pull request to the plugin to fix this here: https://github.com/agronholm/sphinx-autodoc-typehints/pull/138

**Comment by nonhermitian** [comment]
Closing as fixed upstream
