### ISSUE TITLE
gif movie in circuit supplimentary material does not show up in docs.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#915]
### Informations

- **Qiskit version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
<img width="775" alt="Screen Shot 2020-05-01 at 10 58 41" src="https://user-images.githubusercontent.com/1249193/80814967-d0a63780-8b9a-11ea-9e8e-97346dc459ab.png">

**Comment by mtreinish** [comment]
Can this be closed now that https://github.com/Qiskit/qiskit/pull/918 has merged? Although if you think there is going to be more static content in each elements' documentation we might want to update the plugin to sync the static resources too, (from a fixed predefined location in each element) right now it only syncs `apidocs`.

**Comment by nonhermitian** [comment]
Yep sorry. Not sure how much in future. But also since it mostly me I now remember to do this
