### ISSUE TITLE
can we drop the subpackages and submodule in the TOC. I dont think we need this indent. 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#92]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/15731369/52759017-6c6c7780-2fd8-11e9-978b-1016f23c4c54.png">

**Comment by diego-plan9** [comment]
Just to clarify - this is only aimed at the top-level "Qiskit Module reference" (API Reference) section, right? If so, I think we can attempt to hard-code things a bit (even if it technically seems a byproduct of #93).

**Comment by jaygambetta** [comment]
yeah from a user ability i find it hard to get to the circuit package etc.
