### ISSUE TITLE
how to install the qiskit_textbook?

### ISSUE THREAD

**Issue by ChainCoderX** [Qiskit/qiskit-metapackage#924]
how to install the qiskit_textbook ?
I have  try  the cmd: pip install qiskit_textbook ,but faild

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-31f94498a090> in <module>
----> 1 from qiskit_textbook.widgets import plot_bloch_vector_spherical
      2 coords = [pi/2,0,1] # [Theta, Phi, Radius]
      3 plot_bloch_vector_spherical(coords) #

ModuleNotFoundError: No module named 'qiskit_textbook'

**Comment by maddy-tod** [comment]
You should be able to do it by cloning the `qiskit-textbook` [repo](https://github.com/Qiskit/qiskit-textbook). Then you need to run the file `setup.py`, located [here](https://github.com/Qiskit/qiskit-textbook/blob/master/qiskit-textbook-src/setup.py). 

It is worth noting that all the textbook code can be run in browser, by clicking `try` then `run` on the corresponding cell.
