### ISSUE TITLE
May 4 Challenge Minicomposer module Integration into Qiskit.

### ISSUE THREAD

**Issue by abhik-99** [Qiskit/qiskit-metapackage#927]
During the IBM Quantum Challenge 2020, we were given to use a module named
>  minicomposer

 which we used to import by
`from may4_challenge.ex1 import minicomposer`
It was used in the visualization of state vectors on bloch sphere and also showed what code would generate the circuit. The feature was very useful for beginners and getting started. Could this feature be added to Qiskit and Qiskit Textbook?

**Comment by jaygambetta** [comment]
I think this would be a good Jupiter widget to add. @nonhermitian and @delapuente would be best to take this but i'm not sure if it is an extension to our jupiter widgets or if it is a standalone package.

**Comment by nonhermitian** [comment]
I think having the IQX composer moved to a Jupyter widget is the correct move here, for a variety of reasons.

**Comment by abhik-99** [comment]
@nonhermitian , that would be great! Thanks.

**Comment by Ritvik-Sapra** [comment]
@nonhermitian I have an idea. We can use the package [Qutip](http://qutip.org/) to do a demonstration of how qubits are present in the Bloch sphere. A Jupyter notebook demonstration about this will help a lot whoever is starting to read about quantum. Should I move ahead in developing such a demonstration?

**Comment by nonhermitian** [comment]
Since QuTiP is a different program and as such is a bit out of scope. Qiskit has its own Bloch sphere functionality, and there are demos in the tutorials.

**Comment by Ritvik-Sapra** [comment]
Oh ok. I didn't know that. However, if there are demos present already, can we do some other improvement, or we can close this issue?

**Comment by nonhermitian** [comment]
Yeah, let me close this one.  I think we have a plan forward on this, but it is just taking a bit.
