### ISSUE TITLE
can we drop the submodules under the circuit package (true for other ones as well)

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#93]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/15731369/52759180-eb61b000-2fd8-11e9-9ae6-3d29ed9eedf5.png">

**Comment by jaygambetta** [comment]
In general, the folder within the folders navigation of the autodoc is a bit confusing.

**Comment by diego-plan9** [comment]
To put things in context, that hierarchy:
```
X package
  Subpackages
    X.Y
  Submodules
    X.Z
```

is actually the default Sphinx (autodoc) one. In the pre-meta-qiskit documentation, we used a nifty [third party package](https://github.com/goerz/better-apidoc) for customizing the automatic documentation template (in this case, template means "how the elements are structured around", not CSS template) and the TOC - we could explore using it again, although it seems support for recent Sphinx versions and namespaces might be a bit lacking (and we would need to come up with a new template from scratch, as the format we used before was not compatible with the newest versions).

In the meantime, the TOC navigation might get a bit better by fixing #67, reducing the confusion a bit?

**Comment by jaygambetta** [comment]
sure but something like https://www.tensorflow.org/api_docs/python to me is simpler to see where we are in the API documentation or even https://pytorch.org/docs/stable/

**Comment by derivation** [comment]
@carlosazaustre I looked into this a bit. 

sphinx-contrib/apidoc has a stale enhancement [issue](https://github.com/sphinx-contrib/apidoc/issues/5) to support this use case.

[This forum discussion](https://stackoverflow.com/questions/21003122/sphinx-apidoc-section-titles-for-python-module-package-names) addresses the issue at the top level, but does not address the issue at the submodule level.

I haven't come up with a solution.
