### ISSUE TITLE
Short version of Qiskit's bibfile

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-metapackage#934]
### Summary

Provide two `.bib` files to be used in references, a short one
```
Qiskit Contributors, “Qiskit: An open-source framework for quantum
computing,” 2019.
```
_additionally_ to the gargantuan one we currently have.

### Reasoning

Including the bibfile of Qiskit in a paper easily takes up half a column and includes GitHub usernames. Practically, many papers just put the name of the first author to get
```
H. Abraham et al., “Qiskit: An open-source framework for quantum
computing,” 2019.
``` 
This could be improved, because 
1. It's an extra manual step to remove all the authors.
2. Putting `Qiskit Contributors` instead of a single name, at least in my opinion, reflects the community effort of Qiskit better.

**Comment by mtreinish** [comment]
I'm fine with doing this, the list of contributors will only get bigger as time goes on and having a concise version for the references makes sense to me. When we do add a short version we should update the READMEs to reflect this distinction though since it might be confusing otherwise

**Comment by nonhermitian** [comment]
So I would be a bit cautious about this. Namely because if not everyones name is there they may not get credit when the references are parsed for authors. It is usually up to the LaTeX style of the journal for as to where the references get cut, but the bib file always includes all.

**Comment by t-imamichi** [comment]
I have a concern about github usernames as Julien mentions. Some names in the list are not full names.

**Comment by mtreinish** [comment]
FWIW, we do have a mechanism to correct this, each element has a mailmap file in the repo and contributors should update that if they're not setting a real name as the author in the commit metadata. What it comes down to is a lot of people don't configure git correctly (or don't know how to)  and/or don't realize that they should update the mailmap file with their real name if they didn't set it in the commit metadata. There also seems to be some confusion by people on how a mailmap is used as I've see periodic updates to the mailmap adding every contributor to it, which is not it's purpose. There's only so much we can do if a contributor doesn't give us a real name. Maybe it's worth doing a mailmap update on each repo again finding the commit authors who don't have a real name set, see if they set one on their github account and use that. For those that don't have one set anywhere ping them in the PR asking them to push an update (for example what @levbishop did in: https://github.com/Qiskit/qiskit-terra/pull/2666 )

**Comment by chriseclectic** [comment]
Is it possible to filter the git commit log so that only properly configured usernames with a first and last name are added to the bib file? Currently it does not conform to any journal standards because of all the github usernames in it.

**Comment by mtreinish** [comment]
> Is it possible to filter the git commit log so that only properly configured usernames with a first and last name are added to the bib file? Currently it does not conform to any journal standards because of all the github usernames in it.

Well we could filter names that have no spaces in it, but the problem with that approach is that it would exclude people with only one name and not exclude usernames with spaces. I'm not sure there is a surefire way to filter just the usernames, although maybe that's not a problem. Quickly scanning the authors list https://github.com/Qiskit/qiskit/blob/master/AUTHORS that would probably remove most of the user names, although I can see some people you'd probably want to keep in the list like @merav-aharoni who's only in there as a username: https://github.com/Qiskit/qiskit/blob/master/AUTHORS#L313 but forcing a space in the name field will probably be good enough as a heuristic.

The bigger problem is that git log, which is the canonical source of contributions, has a full name field and github automatically sets that to the username for people if they don't have a full name set (or the contributor explicitly does it in their local git config). My assumption is that most of the usernames on that list probably don't know this is happening. I kinda wish people would use the mechanisms we built to handle this.

**Comment by mtreinish** [comment]
The other idea I've been thinking of if we want to use names instead of the Qiskit contributors is maybe sorting the list by the number of commits across all repos using the top 10-20 names from that and using those et al instead of the giant list of everyone

**Comment by Cryoris** [comment]
> So I would be a bit cautious about this. Namely because if not everyones name is there they may not get credit when the references are parsed for authors. It is usually up to the LaTeX style of the journal for as to where the references get cut, but the bib file always includes all.

That's a good point. Are the authors fetched via the bibfile, e.g. in Google Scholar? Or couldn't we also link the authors to the DOI? (I don't know how any of this works so maybe this is also completely wrong what I'm saying!)

**Comment by alex-ozdemir** [comment]
Just bumping this.

Recently, I wanted to cite Qiskit. However, the suggested bib file produces a *2 page* citation, which didn't seem reasonable. I'd love to follow the recommended citation, but not if it takes that much space.

**Comment by Cryoris** [comment]
I did a quick search and at least on Google scholar it seems the citations are found by the Zenodo author list and not the actual authors in the bibtex file. 

For example: In https://quantum-journal.org/papers/q-2022-12-07-870/, the bibtex file contains only 
```
@article{Qiskit,
  author = {H{\'e}ctor Abraham and \emph{et al.}},   # <-- not the full author list!
  title = {Qiskit: An Open-source Framework for Quantum Computing},
  year = {2021},
  doi = {10.5281/zenodo.2573505}
}
```
but it shows up on [Google scholar citations for Qiskit](https://scholar.google.com/scholar?hl=en&as_sdt=2005&sciodt=0%2C5&cites=8253388254707236679&scipsc=1&q=scaling+of+the&btnG=). That means that the citations are likely pulled from zenodo -- which they should as authors are often truncated. 

In that case wouldn't it be fine to cite as the following?
```
@article{Qiskit,
  author = {Qiskit contributors},  
  title = {Qiskit: An Open-source Framework for Quantum Computing},
  year = {2021},
  doi = {10.5281/zenodo.2573505}  # this link cites all Qiskit versions
}
```
The crucial thing would be to make sure the zenodo link appears in the publication.
