### ISSUE TITLE
roadmap in development_strategy seems outdated

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#935]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

https://github.com/Qiskit/qiskit/blob/master/docs/development_strategy.rst

- What is the current text that needs to be fixed or removed? (You can copy and paste)

> In 2019, we have many extensions planned. 

> In 2019, Aer will be extended in many ways:

> In 2019, Ignis will include tools for:

> Over the course of 2019, we are planning to enrich Aqua as follows:

- What should the documentation say instead?

2019 is not in the future anymore.

**Comment by nonhermitian** [comment]
All of the content in the meta package docs needs updates: @ajavadia, @jaygambetta

**Comment by 3yakuya** [comment]
Perhaps a better place would be a separate page just for the roadmap and the documentation should just contain static links to it?

It's great to know what's ahead and see a change log of the past, but I think the docs are not the best place for it.

**Comment by 3yakuya** [comment]
Perhaps a better place would be a separate page just for the roadmap and the documentation should just contain static links to it?

It's great to know what's ahead and see a change log of the past, but I think the docs are not the best place for it.

**Comment by 3yakuya** [comment]
Perhaps a better place would be a separate page just for the roadmap and the documentation should just contain static links to it?

It's great to know what's ahead and see a change log of the past, but I think the docs are not the best place for it.

**Comment by nonhermitian** [comment]
This is resolved as the whole roadmap is removed in #1200 because of lack of maintainers.  A new version can be made in a follow up PR.
