### ISSUE TITLE
statevector simulator triggered when shots=1

### ISSUE THREAD

**Issue by lucacrippa88** [Qiskit/qiskit-metapackage#936]
## Does existing documentation need to be updated with new content?

- Which files need to be updated? 
QuantumInstance: https://qiskit.org/documentation/stubs/qiskit.aqua.QuantumInstance.html

- What content needs to be updated or replaced? (You can copy and paste)
Parameters > shots
"shots (int, optional) – Number of repetitions of each circuit, for sampling"

- What new content needs to be added?
We noticed that setting shots to 1, the simulator becomes the Statevector Simulator, producing exact (noiseless) results (we tested it on VQE simulations). We think could be better to clarify this behaviour in the documentation.

This behaviour has been tested together with Antonello Aita and Michele Grossi.

**Comment by woodsp-ibm** [comment]
Setting shots=1 when using Aer backend in 0.6 Aqua was indeed the condition to trigger some internal logic that used the special snapshot instruction to speed things up.

In Aqua 0.7 the expectation behavior for VQE and backends has been made more explicit as a param on VQE. By default, again when using Aer it chooses the AerPauliExpecation object which uses that special instruction so the outcome is more performant but the final outcome does look more like using a statevector simulator. Now a PauliExpectation() instance can be passed to VQE to overide the default and the outcome will then have shot noise as you expect. The reason for the default was performance, but there is an argument for what users expect of the  behavior when selecting a qasm simulator. There is an issue in Aqua around this https://github.com/Qiskit/qiskit-aqua/issues/1013 - but as noted there, I agree the documentation around this expectation behavior needs to be better.

**Comment by jakelishman** [comment]
I'm going to close this as stale now, but also because the relevant code is in Qiskit Terra.  If there's more questions on this, please feel free to raise them on Qiskit Terra.
