### ISSUE TITLE
AttributeError: module `qiskit.pulse.commands` has no attribute `Command`

### ISSUE THREAD

**Issue by TanveshT** [Qiskit/qiskit-metapackage#937]
### Informations

- **Qiskit version**: 0.19.2
- **Python version**: 3.5.2
- **Operating system**: Linux Ubuntu 16.04

### What is the current behaviour?
Getting an Attribute Error saying that `qiskit.pulse.commands` has no attribute `Command`

### Steps to reproduce the problem
whenever I import anything from qiskit and even if I try to import the whole module it is throwing this error
`from qiskit import QuantumCircuit, execute, Aer, IBMQ`

### What is the expected behaviour?
As these are import statements there is nothing much to explain here.

**Comment by asakhnenko** [comment]
I had the same problem on a Windows machine, but reinstalling Qiskit somehow solved the problem. 

**My setup**
- Qiskit version: 0.19.0
- Python version: 3.7.8
- Operating system: Windows 10

Although on the [requirements page](https://qiskit.org/documentation/install.html#:~:text=Installing%20Qiskit-,Requirements,can%20be%20problems%20with%20compatibility.) it is said that Qiskit supports Python 3.5, it was [deprecated](https://github.com/Qiskit/qiskit-aer/pull/428). So upgrading your Python will probably solve your problem.  I wouldn't recommend getting Python 3.8 version though as I couldn't get it to work with Qiskit. So the safes bet is Python 3.7.

**Comment by TanveshT** [comment]
@asakhnenko  Thank you for reminding me for this issue I had forgot to close it. recently solved it.
