### ISSUE TITLE
 Unable to install qiskit on anaconda

### ISSUE THREAD

**Issue by mertall** [Qiskit/qiskit-metapackage#949]
### Informations

- **Qiskit version**: most updated
- **Python version**:3.7.6
- **Operating system**:Conda

### What is the current behavior?

(base) C:\Users\Mridul>python version
python: can't open file 'version': [Errno 2] No such file or directory

(base) C:\Users\Mridul>version python
'version' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\Mridul>python --version
Python 3.7.6

(base) C:\Users\Mridul>pip install qiskit
Processing c:\users\mridul\appdata\local\pip\cache\wheels\5f\86\38\bdae64afd8006f5276440be91781393aab0280ebd2160ffa76\qiskit-0.19.4-py3-none-any.whl
Collecting qiskit-terra==0.14.2
  Using cached qiskit_terra-0.14.2-cp37-cp37m-win_amd64.whl (6.0 MB)
Collecting qiskit-aqua==0.7.2
  Using cached qiskit_aqua-0.7.2-py3-none-any.whl (1.9 MB)
Collecting qiskit-ibmq-provider==0.7.2
  Using cached qiskit_ibmq_provider-0.7.2-py3-none-any.whl (155 kB)
Collecting qiskit-ignis==0.3.0
  Using cached qiskit_ignis-0.3.0-py3-none-any.whl (172 kB)
Collecting qiskit-aer==0.5.2
  Using cached qiskit_aer-0.5.2-cp37-cp37m-win_amd64.whl (14.4 MB)
Collecting retworkx>=0.3.2
  Using cached retworkx-0.3.4-cp37-cp37m-win_amd64.whl (179 kB)
296 kB)
.
.
.
\
       cwd: C:\Users\Mridul\AppData\Local\Temp\pip-install-2rlbolnu\scs\
  Complete output (89 lines):
  Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, scs=False)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\scs
  copying src\__init__.py -> build\lib.win-amd64-3.7\scs
  running build_ext
  blas_mkl_info:
      libraries = ['mkl_rt']
      library_dirs = ['C:/Users/Mridul/anaconda3\\Library\\lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Mridul/anaconda3\\Library\\include']
  blas_opt_info:
      libraries = ['mkl_rt']
      library_dirs = ['C:/Users/Mridul/anaconda3\\Library\\lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Mridul/anaconda3\\Library\\include']
  lapack_mkl_info:
      libraries = ['mkl_rt']
      library_dirs = ['C:/Users/Mridul/anaconda3\\Library\\lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Mridul/anaconda3\\Library\\include']
  lapack_opt_info:
      libraries = ['mkl_rt']
      library_dirs = ['C:/Users/Mridul/anaconda3\\Library\\lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Mridul/anaconda3\\Library\\include']
  Could not locate executable g77
  Could not locate executable f77
  Could not locate executable ifort
  Could not locate executable ifl
  Could not locate executable f90
  Could not locate executable efl
  Using built-in specs.
  COLLECT_GCC=/usr/bin/gfortran
  COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/lto-wrapper.exe
  Target: x86_64-pc-cygwin
  Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.x86_64/src/gcc-7.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.x86_64/src/gcc-7.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
  Thread model: posix
  gcc version 7.4.0 (GCC)
  C:\Users\Mridul\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  C:\Users\Mridul\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  C:\Users\Mridul\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
  Using built-in specs.
  COLLECT_GCC=/usr/bin/gfortran
  COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/lto-wrapper.exe
  Target: x86_64-pc-cygwin
  Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.x86_64/src/gcc-7.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.x86_64/src/gcc-7.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
  Thread model: posix
  gcc version 7.4.0 (GCC)
  Using built-in specs.
  COLLECT_GCC=/usr/bin/gfortran
  COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/lto-wrapper.exe
  Target: x86_64-pc-cygwin
  Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.x86_64/src/gcc-7.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.x86_64/src/gcc-7.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
  Thread model: posix
  gcc version 7.4.0 (GCC)
  C:\Users\Mridul\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1730: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  C:\Users\Mridul\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1730: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  {}
  {}
  ----------------------------------------
  ERROR: Failed building wheel for scs
  Running setup.py clean for scs
  Building wheel for ecos (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Mridul\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mridul\\AppData\\Local\\Temp\\pip-install-2rlbolnu\\ecos\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mridul\\AppData\\Local\\Temp\\pip-install-2rlbolnu\\ecos\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Mridul\AppData\Local\Temp\pip-wheel-nleplahy'
       cwd: C:\Users\Mridul\AppData\Local\Temp\pip-install-2rlbolnu\ecos\
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\ecos
  copying src\ecos\ecos.py -> build\lib.win-amd64-3.7\ecos
  copying src\ecos\version.py -> build\lib.win-amd64-3.7\ecos
  copying src\ecos\__init__.py -> build\lib.win-amd64-3.7\ecos
  running build_ext
  building '_ecos' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ecos
  Running setup.py clean for ecos
Failed to build cvxpy scs ecos
ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly

### Steps to reproduce the problem

pip install qiskit  on base of conda terminal

### What is the expected behavior?

qiskit should download

**Comment by mertall** [comment]
Could it be because my OS is 32 bit?

**Comment by mtreinish** [comment]
This was caused by a temporary condition in the 0.19.4 release which added `cvxpy` as a dependency. `cvxpy` (and its dependencies) require a c++ compiler to install, which when you ran pip install you did not have one installed. If you look at the `error` lines in your log output it is telling you that (and even gives a link on where to download it). However, the cvxpy requirement was made optional in 0.19.5 (which was released earlier this morning) because we don't want qiskit to require users to need a compiler to install from releases. So if you re-run today you'll no longer have that error.

That being said if you're running on 32bit Windows you will not be able to install qiskit-aer. qiskit-aer requires a 64bit operating system.You can still use qiskit, but you'll have to manually install all the components except for aer with `pip install qiskit-terra qiskit-ignis qiskit-aqua qiskit-ibmq-provider`. This will enable you to use all of qiskit except for the aer simulators.
