### ISSUE TITLE
visualizing quantum data

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#95]
I think we need to think about the visualization section. It is really a visualization of quantum data of something. I think this should also go into the qiskit terra section. 

What do you think @derivation?

**Comment by derivation** [comment]
I think the top level doc ToC should not include Visualizations, as it does now. Instead, a more logical break between overview material for all of Qiskit vs each element/component is

- Overview
- Installing Qiskit
- Getting Started
- Running on IBM Q Devices
- **BREAK**
- Each element/component
- Roadmap
- etc.

The current Visualization section could be moved as-is under Terra's section, renamed something like "Visualizing Quantum Data", coming after "Visualizing a Quantum Circuit".

The workflow step of visualizing quantum data should also be called out more prominently in the "Getting Started" section, where it's currently done in passing while simulating/experimenting. It should be noticeable in the global ToC. Perhaps a subsection can be appended to "Getting Started" where the prior results of simulating and experimenting is explored and discussed a bit further.

**Comment by jaygambetta** [comment]
I agree it should be after the quantum circuit.
