### ISSUE TITLE
ImportError: cannot import name 'cvxpy' from 'qiskit.ignis.verification.tomography.fitters.cvx_fit'

### ISSUE THREAD

**Issue by sassan72** [Qiskit/qiskit-metapackage#955]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

**Comment by mtreinish** [comment]
Thanks for reporting this, this was an issue introduced in qiskit 0.19.5 and was reported to ignis: https://github.com/Qiskit/qiskit-ignis/issues/429 and will be included in a pending 0.19.6 release shortly. While you wait for that release to go live you can workaround this by either downgrading to 0.19.3 by running `pip install qiskit==0.19.3` or by installing cvxpy with `pip install cvxpy`.

**Comment by nonhermitian** [comment]
Closing as solved.
