### ISSUE TITLE
Broken links in file docs/contributing_to_qiskit.rst

### ISSUE THREAD

**Issue by Ritvik-Sapra** [Qiskit/qiskit-metapackage#958]
## Did you find a doc bug or broken link that needs to be fixed?
Yes, the link "Build from source" in the file docs/contributing_to_qiskit.rst is broken, and all the links inside that section too. They are not able to refer to the sections in the file.
- What is the file name(s) where you found the bug?
The file name is [contributing_to_qiskit.rst](https://github.com/Qiskit/qiskit/blob/master/docs/contributing_to_qiskit.rst#id14)
- What is the current text that needs to be fixed or removed? (You can copy and paste)
**:ref:`Build Qiskit packages from source <install_install_from_source_label>`**
This should be a link to the following section in the file.
- What should the documentation say instead?
There should be a link guiding the user to the section **Installing from source** in the same file
- Are there other related issues or pull requests about this bug?
Yes, all the links under this section **Installing from source** are broken and doesn't lead to the corresponding sections.
## Does existing documentation need to be updated with new content?
No. Just the links have to be fixed.
- Which files need to be updated?

- What content needs to be updated or replaced? (You can copy and paste)

- What new content needs to be added?

**Comment by bytesalad** [comment]
Hi. I can solve this issue. May I proceed?

**Comment by Ritvik-Sapra** [comment]
Definitely! However, I tried to fix this and I found it can't be fixed because the text is not writen in markdown language. If you change here, it will not work properly on the website. If you see this part on website, it is working fine. But do have a look.

**Comment by bytesalad** [comment]
Ah I see. And that is a problem because the HTML is generated from the RST?

Also, have you tried the autosectionlabel extension for Sphinx?

**Comment by Ritvik-Sapra** [comment]
@bytesalad Yes and no. Yes that that is the problem that HTML is generated from RST. And no that I didn't try. I thought its fine the way it is, since 95% of the people will read from the website only. Reading such a massive documentation from GitHub is very rare unless someone is an experienced developer, in which case it won't be a problem for him to figure out. So I think we can close this issue, unless you wanna work on it?

**Comment by bytesalad** [comment]
Good point. You can or you can flag it as priority low if you want to.

**Comment by SooluThomas** [comment]
The link works in the website - https://qiskit.org/documentation/contributing_to_qiskit.html. The requested change need not be made to [contributing_to_qiskit.rst](https://github.com/Qiskit/qiskit/blob/master/docs/contributing_to_qiskit.rst#id14). That's because these .rst files are rendered to HTML for the documentation. I'm closing this issue.
