### ISSUE TITLE
quantum_info tools documenation. 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#96]
We should have a section on the quantum tools in terra

**Comment by derivation** [comment]
@1ucian0 @diego-plan9 besides [the code itself](https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/quantum_info), is there any explanatory material on this today?

**Comment by jaygambetta** [comment]
@chriseclectic could you help @derivation on this.

**Comment by derivation** [comment]
@chriseclectic What do you think of this structure? Each section would explain the tools in a context of their use, akin to [this example doc](https://www.mathworks.com/help/matlab/math/eigenvalues.html).

Terra
- Quantum Information
  - Measurement
    - [analyzation/average.py/](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/analyzation/average.py)average_data
  - Distance Metrics
    - [states/_measures.py/](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/states/_measures.py)state_fidelity
  - State Properties
    - [states/_state.py/](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/states/_states.py)purity
  - Specialized State Functions
    - [states/_states.py](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/states/_states.py)/basis_state
    - [states/_states.py](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/states/_states.py)/random_state
    - [states/_states.py](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/states/_states.py)/projector
    - [states/_measures.py/](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/states/_measures.py)_funm_svd
  - Channel Fidelity
    - [operators/_measures.py](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/operators/_measures.py)/process_fidelity
  - [Pauli Operators](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/operators/pauli.py)
  - [Quaternions](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/operators/quaternion.py)

**Comment by derivation** [comment]
I'm working on this now. Should be done in a day or two.
