### ISSUE TITLE
Trying to install but I get multiple errors errors and is unable to install on Raspberry Pi

### ISSUE THREAD

**Issue by NoozAbooz** [Qiskit/qiskit-metapackage#963]
### Informations

- **Qiskit version*N/A*:
- **Python version*3.6.1*:
- **Operating system*RPI OS*:

### What is the current behavior?
I get `Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cdq_skwc/retworkx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-nfjbma4r/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-cdq_skwc/retworkx/
` When I run sudo pip3 install qiskit-terra

### Steps to reproduce the problem
Run `sudo pip3 install qiskit-terra` on Raspberry Pi OS

### What is the expected behavior?
Qiskit installs successfully

### Suggested solutions
I saw in another error BerryConda worked, but I have no idea how to install qiskit on it and I couldn't find it on the rpi channel.

**Comment by d4rkc0nd0r** [comment]
Please do mention the version of qiskit-terra.

**Comment by NoozAbooz** [comment]
I can't understand code, but I got the following when installing.
`  Using cached https://www.piwheels.org/simple/qiskit-terra/qiskit_terra-0.14.2-cp37-cp37m-linux_armv7l.whl
Requirement already satisfied: psutil>=5 in /usr/lib/python3/dist-packages (from qiskit-terra) (5.5.1)
Collecting scipy>=1.4 (from qiskit-terra)
  Using cached https://www.piwheels.org/simple/scipy/scipy-1.5.1-cp37-cp37m-linux_armv7l.whl
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra) (3.2.0)
Requirement already satisfied: marshmallow-polyfield<6,>=5.7 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra) (5.9)
Collecting python-constraint>=1.4 (from qiskit-terra)
  Using cached https://www.piwheels.org/simple/python-constraint/python_constraint-1.4.0-py2.py3-none-any.whl
Requirement already satisfied: marshmallow<4,>=3 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra) (3.7.0)
Collecting dill>=0.3 (from qiskit-terra)
  Using cached https://www.piwheels.org/simple/dill/dill-0.3.2-py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra) (2.8.1)
`

**Comment by d4rkc0nd0r** [comment]
Instead of installing in Raspberry Pi, my suggestion is to use [Google Colab](https://colab.research.google.com/notebooks/intro.ipynb).
`!pip install qiskit`
[Here it is as follows.](https://colab.research.google.com/drive/1X9K571zEKdXfAmD287QkKNIgwSHIEfW-?usp=sharing)
I've seen many issues regarding this Qiskit installation. I always suggest to use Google Colab or Using [IBM Notebook](https://quantum-computing.ibm.com/) instead of Anaconda or any other IDE for Python inorder to minimize efforts in setting up manually.  It decreases numerous steps for installation and runs smoothly.

**Comment by NoozAbooz** [comment]
The problem with that is I'm using Qrasp, which needs access to a sense hat to work.

**Comment by d4rkc0nd0r** [comment]
Please refer this Python module to control [Sense HAT](https://pythonhosted.org/sense-hat/).

**Comment by mtreinish** [comment]
I believe you're missing the actual error in the section of pip output that you copied in the issue, I assume somewhere in the output it is saying `error: Can not find Rust compiler` when it's trying to install the [retworkx](https://github.com/Qiskit/retworkx) dependency. On raspberry pis running rasbian or other linux distros using `armv7l` there are no precompiled binaries available for  on [pypi](https://pypi.org/project/retworkx/#files). (this is because there is not a python packaging spec for armv7l, just aarch64: https://www.python.org/dev/peps/pep-0599/#the-manylinux2014-policy )

Anyway, that's a long winded way of saying just run:

``` bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh --default-toolchain nightly -y
```

before you run

```
pip install qiskit-terra
```

and it should work fine. 

That will install the rust compiler at the proper version so that `pip` can compile retworkx from source when installing it.
For future retworkx releases I hope to have a precompiled binary available through piwheels (see https://github.com/piwheels/packages/issues/99 for the details) to avoid the need to build from source for raspberry pi users and install a rust compiler locally.

**Comment by NoozAbooz** [comment]
I got `sh: 0: Illegal option --
curl: (23) Failed writing body (0 != 15948)
`

**Comment by mtreinish** [comment]
Probably an issue with whatever shell sh is set to to on your system and not liking script args for running via stdin. Just split it up into 2 commands then:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
sh rustup.sh --default-toolchain nightly -y
```

**Comment by NoozAbooz** [comment]
I got 
`    ERROR: Command errored out with exit status 1:
     command: /home/pi/berryconda3/bin/python /home/pi/berryconda3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpl69868wu
         cwd: /tmp/pip-install-z9qn4sin/scipy
    Complete output (153 lines):
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/home/pi/berryconda3/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/home/pi/berryconda3/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/home/pi/berryconda3/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /home/pi/berryconda3/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/berryconda3/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries satlas,satlas not found in /home/pi/berryconda3/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/berryconda3/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /home/pi/berryconda3/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/berryconda3/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /home/pi/berryconda3/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/berryconda3/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/home/pi/berryconda3/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    lapack_src_info:
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    setup.py:462: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-hj81bndm'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Running from SciPy source directory.
    /tmp/pip-build-env-yrgpe9on/overlay/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    /tmp/pip-build-env-yrgpe9on/overlay/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    /tmp/pip-build-env-yrgpe9on/overlay/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    Traceback (most recent call last):
      File "/home/pi/berryconda3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/pi/berryconda3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/pi/berryconda3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-yrgpe9on/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-yrgpe9on/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 249, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-yrgpe9on/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 583, in <module>
        setup_package()
      File "setup.py", line 579, in setup_package
        setup(**metadata)
      File "/tmp/pip-build-env-yrgpe9on/overlay/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 477, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/berryconda3/bin/python /home/pi/berryconda3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpl69868wu Check the logs for full command output.
`

**Comment by nonhermitian** [comment]
Perhaps this will help: https://link.medium.com/M9nebED2i8

**Comment by NoozAbooz** [comment]
Hello! I got the following error when running "pip install - prefer-binary qiskit-aer==0.5.*. "ERROR: Command errored out with exit status 1:
 command: /home/pi/rasqberry/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rflkpdg4/qiskit-aer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rflkpdg4/qiskit-aer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yk50fn1d
 cwd: /tmp/pip-install-rflkpdg4/qiskit-aer/
 Complete output (121 lines):
 
 
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
 - Trying "Ninja" generator
 - - - - - - - - - - - - - - - - 
 - - - - - - - - - - - - - -
 - - - - - - - - - - - 
 - - - - - - - - -
 - - - - - - 
 - - - -
 - 
 Not searching for unused variables given on the command line.
 - The C compiler identification is GNU 8.3.0
 - Detecting C compiler ABI info
 - Detecting C compiler ABI info - done
 - Check for working C compiler: /usr/bin/cc - skipped
 - Detecting C compile features
 - Detecting C compile features - done
 - The CXX compiler identification is GNU 8.3.0
 - Detecting CXX compiler ABI info
 - Detecting CXX compiler ABI info - done
 - Check for working CXX compiler: /usr/bin/c++ - skipped
 - Detecting CXX compile features
 - Detecting CXX compile features - done
 - Configuring done
 - Generating done
 - Build files have been written to: /tmp/pip-install-rflkpdg4/qiskit-aer/_cmake_test_compile/build
 - 
 - - - -
 - - - - - - 
 - - - - - - - - -
 - - - - - - - - - - - 
 - - - - - - - - - - - - - -
 - - - - - - - - - - - - - - - - 
 - Trying "Ninja" generator - success
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
 
 Configuring Project
 Working directory:
 /tmp/pip-install-rflkpdg4/qiskit-aer/_skbuild/linux-armv7l-3.7/cmake-build
 Command:
 /tmp/pip-install-rflkpdg4/qiskit-aer/.eggs/cmake-3.18.0-py3.7-linux-armv7l.egg/cmake/data/bin/cmake /tmp/pip-install-rflkpdg4/qiskit-aer -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-rflkpdg4/qiskit-aer/_skbuild/linux-armv7l-3.7/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/pi/rasqberry/bin/python -DPYTHON_VERSION_STRING:STRING=3.7.3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/pi/rasqberry/lib/python3.7/site-packages/skbuild/resources/cmake -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release
 
 - The CXX compiler identification is GNU 8.3.0
 - The C compiler identification is GNU 8.3.0
 - Detecting CXX compiler ABI info
 - Detecting CXX compiler ABI info - done
 - Check for working CXX compiler: /usr/bin/c++ - skipped
 - Detecting CXX compile features
 - Detecting CXX compile features - done
 - Detecting C compiler ABI info
 - Detecting C compiler ABI info - done
 - Check for working C compiler: /usr/bin/cc - skipped
 - Detecting C compile features
 - Detecting C compile features - done
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Performing Test flag_supported
 - Performing Test flag_supported - Success
 - Looking for OpenMP support…
 - OpenMP found!
 - OpenMP_CXX_FLAGS = -fopenmp
 - OpenMP_EXE_LINKER_FLAGS =
 - Looking for NLOHMANN Json library…
 - nlohmann include dir: /tmp/pip-install-rflkpdg4/qiskit-aer/src/third-party/headers
 - Looking for pthread.h
 - Looking for pthread.h - found
 - Performing Test CMAKE_HAVE_LIBC_PTHREAD
 - Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
 - Looking for pthread_create in pthreads
 - Looking for pthread_create in pthreads - not found
 - Looking for pthread_create in pthread
 - Looking for pthread_create in pthread - found
 - Found Threads: TRUE
 - Looking for OpenBLAS library…
 - OpenBLAS not found. Looking for any other BLAS library…
 - Looking for sgemm_
 - Looking for sgemm_ - not found
 CMake Error at .eggs/cmake-3.18.0-py3.7-linux-armv7l.egg/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
 Could NOT find BLAS (missing: BLAS_LIBRARIES)
 Call Stack (most recent call first):
 .eggs/cmake-3.18.0-py3.7-linux-armv7l.egg/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
 .eggs/cmake-3.18.0-py3.7-linux-armv7l.egg/cmake/data/share/cmake-3.18/Modules/FindBLAS.cmake:947 (find_package_handle_standard_args)
 CMakeLists.txt:190 (find_package)
 
 
 - Configuring incomplete, errors occurred!
 See also "/tmp/pip-install-rflkpdg4/qiskit-aer/_skbuild/linux-armv7l-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
 See also "/tmp/pip-install-rflkpdg4/qiskit-aer/_skbuild/linux-armv7l-3.7/cmake-build/CMakeFiles/CMakeError.log".
 Traceback (most recent call last):
 File "/home/pi/rasqberry/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 586, in setup
 languages=cmake_languages
 File "/home/pi/rasqberry/lib/python3.7/site-packages/skbuild/cmaker.py", line 240, in configure
 os.path.abspath(CMAKE_BUILD_DIR())))
 
 An error occurred while configuring with CMake.
 Command:
 /tmp/pip-install-rflkpdg4/qiskit-aer/.eggs/cmake-3.18.0-py3.7-linux-armv7l.egg/cmake/data/bin/cmake /tmp/pip-install-rflkpdg4/qiskit-aer -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-rflkpdg4/qiskit-aer/_skbuild/linux-armv7l-3.7/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/pi/rasqberry/bin/python -DPYTHON_VERSION_STRING:STRING=3.7.3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/pi/rasqberry/lib/python3.7/site-packages/skbuild/resources/cmake -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release
 Source directory:
 /tmp/pip-install-rflkpdg4/qiskit-aer
 Working directory:
 /tmp/pip-install-rflkpdg4/qiskit-aer/_skbuild/linux-armv7l-3.7/cmake-build
 Please see CMake's output for more information.
 - - - - - - - - - - - - - - - - - - - - 
 ERROR: Failed building wheel for qiskit-aer

**Comment by NoozAbooz** [comment]
So https://link.medium.com/M9nebED2i8 does work! Looks like some dependencies and other things were not installed so it couldn't install.
