### ISSUE TITLE
in the install qiskit do we need troubleshooting?

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#97]
<img width="691" alt="image" src="https://user-images.githubusercontent.com/15731369/52828121-8cae3c00-3095-11e9-88d2-bd1bbc1e6c90.png">

**Comment by derivation** [comment]
I had the same thought. No, the first paragraph isn't helpful, and the second one is an edge case not specific to Qiskit.

I'll remove it.

**Comment by jaygambetta** [comment]
i agree.
