### ISSUE TITLE
Mathematical error in U3 Documentation

### ISSUE THREAD

**Issue by a-kapila** [Qiskit/qiskit-metapackage#972]
## Does existing documentation need to be updated with new content?
Yes
- Which files need to be updated?
https://qiskit.org/documentation/stubs/qiskit.circuit.library.U3Gate.html

- What content needs to be updated or replaced? (You can copy and paste)
Assuming the given form of U3 is correct, we can clearly see it will NOT factorise to U3(\theta, \phi, \lambda) = RZ(\phi - \pi/2) RX(\pi/2) RZ(\pi - \theta) RX(\pi/2) RZ(\lambda - \pi/2) as claimed. We can easily see this by taking eg (\phi, \lambda) = (-\pi/2,\pi/2) and expanding this expression and noting it does not yield RX(\theta)$as claimed (and can easily be shown to be true). 

- What new content needs to be added?
One possible correct answer is RZ(\phi) RX(\pi/2)RZ(\pi - \theta) RX(\pi/2)RZ(\lambda+\pi).

**Comment by rochisha0** [comment]
Can I take up this issue? @a-kapila

**Comment by a-kapila** [comment]
@rochisha0  sure, I would have done it but couldn't find where the file was stored in the repo - they need to make this clearer in my opinion.

**Comment by juandaanieel** [comment]
@a-kapila, I would like to help solving this issue in the documentation of the U3 gate.

In fact, direct multiplication of U3(\theta, \phi, \lambda) = RZ(\phi - \pi/2) RX(\pi/2) RZ(\pi - \theta) RX(\pi/2) RZ(\lambda - \pi/2) does not yield the matrix representation shown in the U3 doc page.

To solve this issue, let us use the Z-Y single qubit decomposition (theorem 4.1 found in the Nielsen and Chuang Quantum Computation book) which states that any single qubit operation can be decomposed in the following way:

U = \exp(\alpha) R_z(\beta) R_y(\gamma) R_z(\delta)

If we want to find \alpha, \beta, \gamma and \delta, as in the matrix representation shown in the U3 doc page, we have to choose, \alpha = (\phi+\lambda)/2, \beta = -\lambda, \gamma = \theta, and \delta = -\phi, according to the notation used.

**Comment by rochisha0** [comment]
@a-kapila You would find it in qiskit-terra. There you can search for u3 gate.

**Comment by a-kapila** [comment]
@juandaanieel your reply is appreciated but I have already calculated an answer is 
RZ(\phi) RX(\pi/2)RZ(\pi - \theta) RX(\pi/2)RZ(\lambda+\pi)

[ there are more answers like RZ(\phi - \pi) RX(\pi/2)RZ(\pi + \theta) RX(\pi/2)RZ(\lambda) ]

**Comment by a-kapila** [comment]
Opened this in qiskit-terra, didn't realise that's where it really belongs.
