### ISSUE TITLE
slack invitation link is no longer active

### ISSUE THREAD

**Issue by utzb** [Qiskit/qiskit-metapackage#976]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
README.md and on web page qiskit.org

- What is the current text that needs to be fixed or removed? (You can copy and paste)
`To join our Slack community use the link`

- What should the documentation say instead?
provide a valid link

- Are there other related issues or pull requests about this bug?
None here; some related on qiskit-terra, but they're closed (resolved).

## Does existing documentation need to be updated with new content?

- Which files need to be updated?
README.md
qiskit.org
(maybe others)

- What content needs to be updated or replaced? (You can copy and paste)
`To join our Slack community use the link`

- What new content needs to be added?
new link to join slack

**Comment by Morcu** [comment]
I can update the README.MD not only for this repo, all the README must be updated (ignis, terra, aer, aqua).

**Comment by utzb** [comment]
I figured on the (great) youtube video series it should probably just be `http://ibm.co/joinqiskitslack` instead of a link with some tokens. If you confirm that is the case, I can submit PRs for qiskit and all the projects (ignis, terra, aer, aqua). (Or you simply commit)

**Comment by SooluThomas** [comment]
This issue was fixed
