### ISSUE TITLE
FileNotFoundError on building documentation from source and installing

### ISSUE THREAD

**Issue by gunchamalik** [Qiskit/qiskit-metapackage#979]
### Informations

- **Qiskit version**: 0.19.3
- **Python version**: 3.7.6
- **Operating system**: MacOS 10.15.5

### What is the current behavior?
FileNotFoundError is thrown during the installation of edocs when built from source as per the instructions listed at https://qiskit.org/documentation/contributing_to_qiskit.html#building-from-source

### Steps to reproduce the problem
1. Build from source as per instructions at https://qiskit.org/documentation/contributing_to_qiskit.html#building-from-source
2. Clone the Qiskit repository
    `git clone https://github.com/Qiskit/qiskit.git`
3. `cd qiskit`
4. Install tox if not installed already
    `pip install tox`
5. Build the documentation using below command
    `tox -edocs`
6. Error is thrown
`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/Documents/Guncha/Work/qiskit/qiskit/.tox/docs/lib/python3.7/site-packages/pydot.py in create(self, prog, format, encoding)
   1914                 arguments=arguments,
-> 1915                 working_dir=tmp_dir,
   1916             )

~/Documents/Guncha/Work/qiskit/qiskit/.tox/docs/lib/python3.7/site-packages/pydot.py in call_graphviz(program, arguments, working_dir, **kwargs)
    135         stdout=subprocess.PIPE,
--> 136         **kwargs
    137     )

~/opt/anaconda3/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:

~/opt/anaconda3/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1550                             err_msg += ': ' + repr(err_filename)
-> 1551                     raise child_exception_type(errno_num, err_msg, err_filename)
   1552                 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'neato': 'neato'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-17-fb582978e25d> in <module>
      3 coupling_map = CouplingMap(
      4     [[0, 1], [1, 0], [1, 2], [1, 3], [2, 1], [3, 1], [3, 4], [4, 3]])
----> 5 coupling_map.draw()

~/Documents/Guncha/Work/qiskit/qiskit/.tox/docs/lib/python3.7/site-packages/qiskit/transpiler/coupling.py in draw(self)
    341 
    342         dot = nx.drawing.nx_pydot.to_pydot(self.graph)
--> 343         png = dot.create_png(prog='neato')
    344 
    345         return Image.open(io.BytesIO(png))

~/Documents/Guncha/Work/qiskit/qiskit/.tox/docs/lib/python3.7/site-packages/pydot.py in new_method(f, prog, encoding)
   1721                 """Refer to docstring of method `create`."""
   1722                 return self.create(
-> 1723                     format=f, prog=prog, encoding=encoding)
   1724             name = 'create_{fmt}'.format(fmt=frmt)
   1725             self.__setattr__(name, new_method)

~/Documents/Guncha/Work/qiskit/qiskit/.tox/docs/lib/python3.7/site-packages/pydot.py in create(self, prog, format, encoding)
   1920                 args[1] = '"{prog}" not found in path.'.format(
   1921                     prog=prog)
-> 1922                 raise OSError(*args)
   1923             else:
   1924                 raise

FileNotFoundError: [Errno 2] "neato" not found in path.
ERROR: InvocationError for command /Users/gmalik/Documents/Guncha/Work/qiskit/qiskit/.tox/docs/bin/sphinx-build -b html docs docs/_build/html (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   docs: commands failed`

### What is the expected behavior?
Documentation should be built successfully without any errors.

### Suggested solutions
"neato" file or directory needs to be added.

**Comment by nonhermitian** [comment]
I believe that this is related to the graph visualization binaries that need to be installed from conda or here: https://www.graphviz.org/download/ as they are binaries.

**Comment by anupamaray** [comment]
I installed graphviz but still getting the same error. @gunchamalik were u able to resolve with just installing graphviz?
