### ISSUE TITLE
circuit drawing in documentation

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#98]
How should we be drawing the circuits in the documentation 

Currently it is from the text. 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/15731369/52830772-211d9c00-30a0-11e9-998c-b11af17a5efb.png">

@ajavadia do you want it latex or matplotlib?

**Comment by derivation** [comment]
Are there plans to have `QuantumCircuit.draw()` able to stylize circuits in the same way as the Quantum Composer? Might that roadmap inform this choice?

**Comment by ajavadia** [comment]
matplotlib might look better in the docs. it does have a style field as well that you can play with. i also like the professional look of the latex one, but it is currently buggy in some parts.

**Comment by jaygambetta** [comment]
I think so with matplotlib. @derivation we dont have an interactive on the roadmap yet but i agree it would be cool to have. There is an issue to build one in terra. For now i think we should use the matplotlib version.

**Comment by derivation** [comment]
I'm going through the doc, updating the circuit diagrams as necessary. I'm starting with the global Getting Started material.

**Comment by t-imamichi** [comment]
FYI. There is a tutorial of matplotlib circuit drawer. https://github.com/Qiskit/qiskit-tutorials/blob/master/to_sort/circuit_drawing.ipynb
