### ISSUE TITLE
Link broken as 3_the_ibmq_account.ipynb does not exist

### ISSUE THREAD

**Issue by Vismai-Khanderao** [Qiskit/qiskit-metapackage#980]
### Informations

- **Qiskit version**: 0.19.6
- **Python version**: N/A
- **Operating system**: N/A

### What is the current behavior?
Link for tutorial on managing multiple IBM Quantum account credentials is broken in install.rst
https://github.com/Qiskit/qiskit/blob/master/docs/install.rst

This is the current link in the file which redirects to a missing page:
https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/fundamentals/3_the_ibmq_account.ipynb

### Steps to reproduce the problem
Clicking on last link under https://qiskit.org/documentation/install.html#access-ibm-quantum-systems , just above **Checking Which Version is Installed**.

The file on github is install.rst linked above.

### What is the expected behavior?
I have noticed the tutorial was in the legacy_tutorials in the qiskit-tutorials repo (https://github.com/Qiskit/qiskit-tutorials/tree/master/legacy_tutorials/terra) but has been removed on July 16, 2020 with commit 
(https://github.com/Qiskit/qiskit-tutorials/commit/53a9fb168d9a4a85cc7c5265cdc6135da1eb184e)

The link should direct to the tutorial

### Suggested solutions
I have not been able to find this tutorial in the master branch of the repo, but ideally a new link to the tutorial can be made if the tutorial exists.

**Comment by gunchamalik** [comment]
IQE documentation also refers to "Updating from previous versions" section, but there is no such section available in the IQE documentation.
Link: https://quantum-computing.ibm.com/docs/cloud/account/ibmq_account

`Note: The use of provider instances is the default way of retrieving backends from Qiskit 0.11 onwards - if you have been using earlier versions of Qiskit, check the “Updating from previous versions” section for more detailed instructions on updating and using the different options.`

**Comment by y4izus** [comment]
Hi @Vismai-Khanderao and @gunchamalik !! I'm trying to reproduce the bugs you both found but I'm not able to do it. The content is constantly evolving and maybe these bugs disappeared from one version to another. Could you double check if we still have the bugs or if we could close the issue, please??

Thanks for your help!!

**Comment by y4izus** [comment]
Hi @Vismai-Khanderao and @gunchamalik !! I've tried to reproduce the bug again and the link https://qiskit.org/documentation/install.html doesn't exist anymore, we are redirecting to another page, so I'm gonna close this issue.

Thanks for your time!
