### ISSUE TITLE
plotting_data_in_qiskit bulleted list correction

### ISSUE THREAD

**Issue by eleonorapeck** [Qiskit/qiskit-metapackage#983]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
https://qiskit.org/documentation/tutorials/circuits/2_plotting_data_in_qiskit.html

- What is the current text that needs to be fixed or removed? (You can copy and paste)

> The visualizations generated by the functions are: - 'plot_state_city': The standard view for quantum states where the real and imaginary (imag) parts of the state matrix are plotted like a city.

- What should the documentation say instead?
The part about plot_state_city should be part of the bulleted list

- Are there other related issues or pull requests about this bug?
N/A

**Comment by Vismai-Khanderao** [comment]
This seems like an issue in the qiskit-tutorials repo (https://github.com/Qiskit/qiskit-tutorials) under tutorials/circuits/2_plotting_data_in_qiskit.ipynb
