### ISSUE TITLE
Qiskit Chemistry, Programmatic Approach bullet list correction

### ISSUE THREAD

**Issue by aserra88** [Qiskit/qiskit-metapackage#988]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
https://qiskit.org/documentation/tutorials/chemistry/1_programmatic_approach.html

- What is the current text that needs to be fixed or removed? (You can copy and paste)
To run VQE with the UCCSD variational form, we require - VQE algorithm - Classical Optimizer - UCCSD variational form - Prepare the initial state in the HartreeFock state

- What should the documentation say instead?
The requirement list should be a bullet list and not be visualized on a single row.

- Are there other related issues or pull requests about this bug?
N/A

**Comment by SooluThomas** [comment]
This should have been fixed by https://github.com/Qiskit/qiskit-tutorials/pull/980. Please reopen if this issue still exists.
