### ISSUE TITLE
interactive visualizations 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#99]
in the plotting section can we get the interactive visualization showing. 

https://qiskit.org/documentation/plotting_data_in_qiskit.html#interactive-histogram-plots-for-jupyter-notebooks

If we can it would be nice to do it for all plot state types.

**Comment by derivation** [comment]
@JavaFXpert any thoughts on how this might be done?

**Comment by JavaFXpert** [comment]
To get the interactive widgets working in the Qiskit documentation , this page would need to be connected to a Jupyter kernel. Perhaps it would be good to use the same Jupyter backend that IQS uses, so that it is always on. 

Regards,
James Weaver

**Comment by jaygambetta** [comment]
I don't think this is correct. If we say the data and since the interactive visualizations are in javascript I think this can be done. @ismaelfaro or what you do you think.

**Comment by nonhermitian** [comment]
In order for this to work there would have to be some png representation of the js object that can be stored. The ipywidgets have a store state option in the notebooks, but this only works in the notebooks as they are also JS.

**Comment by JavaFXpert** [comment]
I assumed that the goal was to make the widgets interactive in the Qiskit docs. Is the goal to just display static images of the interactive widgets in the Qiskit docs?

**Comment by nonhermitian** [comment]
Currently they show nothing. So anything is an improvement. The problem is that we need some way of storing the js state from a notebook, to rst text, and then revive it in html for interactive to work. And all automatically. I am unuse has how to do this

**Comment by jaygambetta** [comment]
@nonhermitian you are mixing two different things up. One is the addition to make it show in the qiskit tutorial and the other is to render on a webpage. Here let's focus on the webpage, not the qiskit tutorial.

**Comment by francabrera** [comment]
after talking with @diego-plan9, I took a look to the `.. raw:: html` tag in Sphinx, and it seems that we could include in the docs the JS file of the visualizations so you would be able to write code blocks in the docs calling the javascript functions passing the data to plot them on an interactive way @diego-plan9, @carlosazaustre and Borja are going to give this approach a chance and create an example to see if it works and come back with the results

**Comment by carlosazaustre** [comment]
This is still a WIP but I think we can achieve. I need to work with the styles a little bit.
I will keep you updated.
Thanks @francabrera for the examples an the `html` tag recomendation in Sphinx.

![image](https://user-images.githubusercontent.com/650752/53753152-d928b280-3eb0-11e9-84e8-ac105e4caa4b.png)
![image](https://user-images.githubusercontent.com/650752/53753160-db8b0c80-3eb0-11e9-8ae9-895a26554739.png)
![image](https://user-images.githubusercontent.com/650752/53753180-eba2ec00-3eb0-11e9-992a-8524992f6194.png)
