### ISSUE TITLE
Plot Hinton - ValueError: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (4)

### ISSUE THREAD

**Issue by praveentn** [Qiskit/qiskit-metapackage#990]
### Informations

- **Qiskit version**: 0.14.2
- **Matplotlib version**: 3.3.0
- **Python version**: Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
- **Operating system**: Windows 10

### Stack Trace
`
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-347f1def9cd2> in <module>
----> 1 plot_state_hinton(psi)

c:\python37\envs\qiskit\lib\site-packages\qiskit\visualization\state_visualization.py in plot_state_hinton(rho, title, figsize, ax_real, ax_imag)
    142         ax1.set_xticks(np.arange(0, lx+0.5, 1))
    143         ax1.set_yticks(np.arange(0, ly+0.5, 1))
--> 144         ax1.set_yticklabels(row_names, fontsize=14)
    145         ax1.set_xticklabels(column_names, fontsize=14, rotation=90)
    146         ax1.autoscale_view()

c:\python37\envs\qiskit\lib\site-packages\matplotlib\axes\_base.py in wrapper(self, *args, **kwargs)
     61 
     62         def wrapper(self, *args, **kwargs):
---> 63             return get_method(self)(*args, **kwargs)
     64 
     65         wrapper.__module__ = owner.__module__

c:\python37\envs\qiskit\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*args, **kwargs)
    449                 "parameter will become keyword-only %(removal)s.",
    450                 name=name, obj_type=f"parameter of {func.__name__}()")
--> 451         return func(*args, **kwargs)
    452 
    453     return wrapper

c:\python37\envs\qiskit\lib\site-packages\matplotlib\axis.py in _set_ticklabels(self, labels, fontdict, minor, **kwargs)
   1791         if fontdict is not None:
   1792             kwargs.update(fontdict)
-> 1793         return self.set_ticklabels(labels, minor=minor, **kwargs)
   1794 
   1795     @cbook._make_keyword_only("3.2", "minor")

c:\python37\envs\qiskit\lib\site-packages\matplotlib\axis.py in set_ticklabels(self, ticklabels, minor, **kwargs)
   1713             if len(locator.locs) != len(ticklabels) and len(ticklabels) != 0:
   1714                 raise ValueError(
-> 1715                     "The number of FixedLocator locations"
   1716                     f" ({len(locator.locs)}), usually from a call to"
   1717                     " set_ticks, does not match"

ValueError: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (4).

`
### What is the current behavior?

Unable to plot hinton

### Steps to reproduce the problem

Execute the following code:

`from qiskit import QuantumCircuit, QuantumRegister
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_state_qsphere, plot_histogram, plot_state_city
from qiskit.visualization import plot_state_hinton, plot_state_paulivec, plot_bloch_multivector
from qiskit_textbook.tools import array_to_latex
from qiskit import Aer, execute

qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])

''' execute the quantum circuit '''
backend = Aer.get_backend('statevector_simulator') # the device to run on
result = execute(qc, backend).result()
psi  = result.get_statevector(qc)

plot_state_hinton(psi)`

**Comment by Ananyapam7** [comment]
The error is due to matplotlib v3.3. Works perfectly fine with lower versions 
downgrading matplotlib with
`pip install 'matplotlib<3.3.0'` should solve this issue. 
These links talk about it
https://github.com/Qiskit/qiskit-terra/pull/4739 fixes the issue
https://github.com/Qiskit/qiskit-terra/issues/4815#issuecomment-665581394

**Comment by praveentn** [comment]
Working fine now after downgrading the `matplotlib` library! 

`pip install matplotlib==3.2.0`

**Comment by theDreamer911** [comment]
I just got the answer, actually in `matplotlib>3.3.0`, you should give the first and last index with same value. If you have category like this

categories = ['HP', 'MP', 'Attack', 'Defense', 'Speed']

To make it being plotted in radar chart, you need to make sure that the first index [0] comes again in last index, it can be done easily using numpy or you can did it manually

categories = np.concatenate((categories, [categories[0]]))

**Comment by Helala2030** [comment]
I face this problem:


ax=sns.countplot(df['Malware'])
ax.set_xticklabels(['Not Malware', 'Malware'])











------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-33-d38d73e4e7b4>](https://localhost:8080/#) in <cell line: 2>()
      1 ax=sns.countplot(df['Malware'])
----> 2 ax.set_xticklabels(['Not Malware', 'Malware'])

2 frames
[/usr/local/lib/python3.10/dist-packages/matplotlib/axis.py](https://localhost:8080/#) in set_ticklabels(self, labels, minor, fontdict, **kwargs)
   1967             # remove all tick labels, so only error for > 0 labels
   1968             if len(locator.locs) != len(labels) and len(labels) != 0:
-> 1969                 raise ValueError(
   1970                     "The number of FixedLocator locations"
   1971                     f" ({len(locator.locs)}), usually from a call to"

ValueError: The number of FixedLocator locations (1), usually from a call to set_ticks, does not match the number of labels (2).
