### ISSUE TITLE
Images not found in install.rst

### ISSUE THREAD

**Issue by prasad-kumkar** [Qiskit/qiskit-metapackage#993]
Browser:
Google Chrome, Safari

- Which files need to be updated?
https://github.com/Qiskit/qiskit/blob/master/docs/install.rst

- What content needs to be updated or replaced? 
The image needs to be updated under point 2 and 3 of Access IBM quantum systems:
https://github.com/Qiskit/qiskit/blob/master/docs/install.rst#access-ibm-quantum-systems
<img width="1198" alt="Screenshot 2020-08-05 at 10 37 20 AM" src="https://user-images.githubusercontent.com/43164022/89374764-eb43fb80-d709-11ea-8916-402d5a4d78ca.png">

- What new content needs to be added?
Image of where to find the section 'My accounts'
Image of where to get an API token.

**Comment by mtreinish** [comment]
These images are correct, the documentation is not designed for viewing via github's builtin rst viewer but instead for use with sphinx to build the documentation. We host the html compiled version of the documentation here:
https://qiskit.org/documentation/install.html#access-ibm-quantum-systems
which you can see has the images correctly.

**Comment by prasad-kumkar** [comment]
Oh okay. Thank you for sharing that @mtreinish, I didn't know about that. I will close this issue now.
