### ISSUE TITLE
Write reno sphinx plugin for all elements

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-metapackage#997]
### What is the expected behavior?

Reno includes a sphinx extension https://docs.openstack.org/reno/latest/user/sphinxext.html that enables including release notes natively in documentation. However, this extension is built on the assumption that there is only one repo with documentation in tree that needs release notes generated for it. For the qiskit documentation we have a bit of a special case because there are 5 repositories each using reno that are tied together for a single release.

Right now whenever we do a release of the metapackage we manually update the release notes rst file https://github.com/Qiskit/qiskit/blob/master/docs/release_notes.rst with the contents of running `reno report` on each element being bumped in that release. However, this should be automated. To do this we need to write a custom extension that adds a new sphinx directive to build the release notes for each version (like what we do for the version table already). It should take the element versions for a particular release generate the rst using reno for those versions, combine them in the proper formatting, and add that to the document dynamically.

**Comment by mtreinish** [comment]
The need for this has decreased a bit since we've been moving things out of the metapackage to make the qiskit package slimmer. However, as long as there is > 1 package in the metapackage having this would be nice (if the metapackage is ever reduced to a single package we can just use the built-in reno sphinx plugin). Right now our release notes rst file is gigantic because it copies and pastes all the reno contents from all the projects reducing that would be a big win with a custom plugin.

**Comment by Eric-Arellano** [comment]
Is this still relevant in 2023?

**Comment by mtreinish** [comment]
The plan as of now is after we reduce the metapackage to just be an alias for qiskit-terra the need for this goes away as we'll just have a single project's release notes published and we can use the built-in reno sphinx extension. So we can close this
